- __snapshots__/story-shots.test.js.snap
- packages/wonder-blocks-core/index.stories.js
- packages/wonder-blocks-core/package.json
- packages/wonder-blocks-core/src/text.js
This was a good idea but in practice it turns out that it prevents
colors from cascading, which is really annoying. This commit reverts
us back to the previous behavior, which was fine. Ideally we'll just
set the default text color in a css reset somewhere instead
Test Plan:
npm test
Reviewers: briangenisio
> Remove default text color from Text component

- __snapshots__/story-shots.test.js.snap
- packages/wonder-blocks-core/index.js
- packages/wonder-blocks-core/src/text.js
- packages/wonder-blocks-core/src/types.js
- packages/wonder-blocks-typography/index.stories.js
- packages/wonder-blocks-typography/src/types.js
- packages/wonder-blocks-typography/src/typography.js
This is necessary for a11y best practices: Headings on a page should
form a hierarchy.
Test Plan:
npm test
Reviewers: briangenisio
> Allow tag overrides for Title and Heading____ typography components

- CODEOWNERS
This in combination with enabling the "Require review from Code Owners" setting on the `master` protected branch is equivalent to Phabricator's "add required reviewer" herald system.
> add CODEOWNERS file and make myself a global owner

- packages/wonder-blocks-modal/components/modal-launcher.md
- packages/wonder-blocks-modal/components/standard-modal.js
- packages/wonder-blocks-modal/components/standard-modal.md
- styleguide.config.js
In this change, we implement the basics of the "standard overflow" modal layout, by creating the `StandardModal` component.
I also added a `position: relative` style to our Styleguidist preview areas, to enable the example container to take the full height of the preview area. This means that, when using the resize handle to increase the size of the preview area, the space available to the modal will now correctly increase. (It also introduces an awkward issue, in which decreasing the height of the preview area will add a scrollbar, to help you see the rest of the sizer element that I used to set the preview's initial height. Womp, womp! I think it's a net better experience, since you actually _can_ test height changes now, even though parts of the experience are clunky.)
Test Plan: …
> [modal] Create basic StandardModal component

- packages/wonder-blocks-modal/components/modal-launcher.js
- packages/wonder-blocks-modal/components/modal-launcher.test.js
In this change, we add keyboard listeners to `ModalLauncher` to close the modal when Escape is pressed.
Test Plan:
```npm test```
In Styleguidist, use the `ModalLauncher` example to launch a standard modal and a two-column modal. For each, confirm that pressing Escape closes the modal.
> [modal] Pressing Escape closes a launched modal

- packages/wonder-blocks-modal/components/modal-close-button.js
- packages/wonder-blocks-modal/components/modal-close-button.test.js
- packages/wonder-blocks-modal/components/modal-launcher.js
- packages/wonder-blocks-modal/components/standard-modal.js
- packages/wonder-blocks-modal/components/standard-modal.md
- packages/wonder-blocks-modal/components/standard-modal.test.js
- packages/wonder-blocks-modal/components/two-column-modal.js
- packages/wonder-blocks-modal/components/two-column-modal.md
- packages/wonder-blocks-modal/components/two-column-modal.test.js
- styleguide.config.js
In this change, we create a `ModalCloseButton` component, and add it to the modal layout components.
This close button doesn't control modal launcher state yet; it just triggers the public callback `onClickCloseButton` on the modal layout component. (We'll probably need to set up some wires via context, in order to control the modal launcher. Coming soon!)
Some modals will not want to provide default close behavior at all, but that's not part of the scope of this change. (See WB-134.)
Test Plan:
Open Styleguidist, and take a look at those cute close buttons!
Click them, and see an alert, because the Styleguidist examples have an alert handler hooked up to `onClickCloseButton`.
Additionally, use a ruler to confirm that the title and subtitle are indeed centered in the title bar, despite …
> [modal] Add close button to modal layouts

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/text.js
- packages/wonder-blocks-core/components/view.js
- packages/wonder-blocks-core/docs.md
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/util/types.js
- packages/wonder-blocks-grid/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-typography/__snapshots__/generated-snapshot.test.js.snap
In this change, we allow `View` and `Text` to accept arbitrary props to pass along to the wrapper HTML element. This enables event handlers like `onClick`, and accessibility features like `id` and `aria-hidden`.
In Styleguidist, look at the new example in the "Core" section.
Click the words "Click me!", and see an alert appear.
Use a screen reader (I used VoiceOver in Safari), and observe that the screen reader does not recognize the text "This text is hidden from screen readers.".
> Update View and Text to pass along unknown props

- packages/wonder-blocks-typography/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-typography/components/body-monospace.js
- packages/wonder-blocks-typography/components/body-serif-block.js
- packages/wonder-blocks-typography/components/body-serif.js
- packages/wonder-blocks-typography/components/body.js
- packages/wonder-blocks-typography/components/caption.js
- packages/wonder-blocks-typography/components/footnote.js
- packages/wonder-blocks-typography/components/heading-large.js
- packages/wonder-blocks-typography/components/heading-medium.js
- packages/wonder-blocks-typography/components/heading-small.js
- packages/wonder-blocks-typography/components/heading-xsmall.js
- packages/wonder-blocks-typography/components/label-large.js
- packages/wonder-blocks-typography/components/label-medium.js
- packages/wonder-blocks-typography/components/label-small.js
- packages/wonder-blocks-typography/components/label-xsmall.js
- packages/wonder-blocks-typography/components/tagline.js
- packages/wonder-blocks-typography/components/title.js
- packages/wonder-blocks-typography/docs.md
- packages/wonder-blocks-typography/generated-snapshot.test.js
- packages/wonder-blocks-typography/util/types.js
In this change, we add an `id` prop to typography components. This enables us to identify these nodes to screen readers, for cases like `aria-labelledby`.
Depends on #68, which enables `Text` to accept arbitrary props.
Open the typography section in styleguidist. Confirm that all typography tags in the first example have their `id` set correctly.
> [typography] Type components now accept an `id` prop

- packages/wonder-blocks-modal/components/modal-footer.js
- packages/wonder-blocks-modal/components/modal-launcher.md
- packages/wonder-blocks-modal/components/one-column-modal.js
- packages/wonder-blocks-modal/components/one-column-modal.md
- packages/wonder-blocks-modal/components/two-column-modal.js
- packages/wonder-blocks-modal/components/two-column-modal.md
- packages/wonder-blocks-modal/components/two-column-modal.test.js
- packages/wonder-blocks-modal/package-lock.json
- packages/wonder-blocks-modal/package.json
- styleguide.config.js
This diff adds in support for the one and two-column modal dialogs, using the new grid system. See #65 for the details of how the grid is ready.
A couple things that had fuzzy definitions in the design that I made a decision on:
* I added a 64px margin to the top and bottom of the modal, which seems to match the current design.
* I used a single 12-column grid for all two-column modals (which will be the same one I use for the standard modal, too).
* For the "11-column" modal the new design calls for a 128px space between the two pieces of text. I implemented that as: (in Sidebar: 32px space + 32px gutter + in Content: 64px space). This helps us to avoid having to implement a brand new type of grid just for this one modal.
* If the contents have a footer then I add a 48px padding to the …
> Use the Grid for the one and two-column modal dialogs.

- packages/wonder-blocks-modal/components/modal-backdrop.js
- packages/wonder-blocks-modal/components/modal-backdrop.test.js
- packages/wonder-blocks-modal/components/modal-launcher.md
- packages/wonder-blocks-modal/components/standard-modal.js
- packages/wonder-blocks-modal/components/two-column-modal.js
- packages/wonder-blocks-modal/util/util.js
In this change, we add basic screen reader support for our modal. In particular, we give it the "dialog" ARIA role, mark its title+subtitle nodes as a label and description respectively, and we add very basic focus management.
I only added an ARIA label and description in the `StandardModal`, since `title` and `subtitle` are its props. For the `TwoColumnModal`, I only applied `role="dialog"`, since identifying the appropriate label is trickier. (We just receive a monolith of content as our props.)
Depends on #69, which enables typography components to accept `id`.
https://khanacademy.atlassian.net/browse/WB-138
Using VoiceOver in Safari, open the standard modal in the `ModalLauncher` example. Confirm that focus shifts to its "Close modal" button, and that VoiceOver reports that the user …
> [modal] First draft of ARIA dialog behavior

- packages/wonder-blocks-modal/components/focus-trap.js
- packages/wonder-blocks-modal/components/modal-backdrop.js
- packages/wonder-blocks-modal/components/modal-backdrop.test.js
- packages/wonder-blocks-modal/components/modal-launcher.md
- styleguide.config.js
In this change, we ensure that tab focus stays within the modal. If the user attempts to tab beyond the modal's boundaries, their tab focus wraps back around.
The general approach was adapted from the WAI-ARIA dialog behavior example, in which they implemented similar behavior for their modal.
Unfortunately, I couldn't get an automated test working :( I left my WIP version of the test in the suite as a `test.skip`, and performed testing manually.
This new login-form example showcases that maybe we want cleverer auto-focus behavior than #70 gives us. (We auto-focus the "log in" button, but we should probably auto-focus the username field.) Will try something cleverer in a later change!
Depends on #70, which added basic auto-focus behavior for ARIA's sake. …
> [modal] Trap focus in the modal, and wrap tab button presses

- packages/wonder-blocks-modal/components/standard-modal.js
I mentioned this in code review for #64, but forgot to change it! In addition to resetting our `maxWidth` and `maxHeight` rules, we also need to reset our `minHeight`. Otherwise, the modal will overflow the screen when it's <200px tall.
Test Plan:
Launch a `StandardModal`, then manually resize the window to be quite narrow and quite short. Confirm that the modal continues to be full-screen, without overflowing.
> [modal] Whoops, override `minHeight` in mobile view

- .gitattributes
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/view.js
- packages/wonder-blocks-grid/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-grid/util/styles.js
- packages/wonder-blocks-modal/components/modal-backdrop.js
- packages/wonder-blocks-modal/components/standard-modal.js
- packages/wonder-blocks-modal/components/standard-modal.md
- packages/wonder-blocks-modal/components/two-column-modal.js
- packages/wonder-blocks-modal/components/two-column-modal.md
- packages/wonder-blocks-typography/__snapshots__/generated-snapshot.test.js.snap
The rationale for this change is:
- flex-box layouts can break when a <div> is inserted in the layout
without setting display: flex;
- by default flexDirection is "row" on the web, but this is quite
different from the default layout of children when display: flex
isn't set
- these are defaults for React Native's View component after which
our View component is modelled so it makes sense have similar
defaults
I've also re-enabled display of .snap files in github reviews.
Test Plan:
- npm test
- npm run styleguidist, look at all of the components to verify that
nothing's broken after this change
> Update View to have to have display: flex; flexDirection: column

- packages/wonder-blocks-modal/building-blocks.md
- packages/wonder-blocks-modal/components/modal-content-pane.js
- packages/wonder-blocks-modal/components/modal-content.js
- packages/wonder-blocks-modal/components/modal-dialog.js
- packages/wonder-blocks-modal/components/modal-footer.js
- packages/wonder-blocks-modal/components/modal-header.js
- packages/wonder-blocks-modal/components/modal-launcher.md
- packages/wonder-blocks-modal/components/modal-title-bar.js
- packages/wonder-blocks-modal/components/one-column-modal.js
- packages/wonder-blocks-modal/components/one-column-modal.md
- packages/wonder-blocks-modal/components/standard-modal.js
- packages/wonder-blocks-modal/components/standard-modal.md
- packages/wonder-blocks-modal/components/standard-modal.test.js
- packages/wonder-blocks-modal/components/two-column-modal.js
- packages/wonder-blocks-modal/components/two-column-modal.test.js
- styleguide.config.js
Now that we're free from our Grid restrictions it's really easy to build up a series of low-level building blocks to construct our modals! I built a collection of these components to build all of our modals, and to give users the power to construct their own and potentially override specific aspects of the layout, if need be.
Looking at an existing set of modals:
* ModalDialog (red): Holds the entire modal and all of the contents (a set of ModalContentPanes).
* ModalContentPane (orange): Holds a set of ModalTitleBar, ModalHeader, ModalContent, and ModalFooter and renders them all. Additionally is responsible for rendering the ModalCloseButton.
* ModalTitleBar (green): Renders the Title and Subtitle.
* ModalHeader (teal): Renders the section displayed beneath the titlebar and above the …
> Re-implement modals to use low-level building blocks.

- package.json
- packages/wonder-blocks-spacing/package.json
The addition of `prop-types` is b/c in a few places we were using it was being included in built files.  The webpack.config.js looks at package.json so if something's not explicitly listed but imported as a sub dependency of something else we don't mark it as external.  Adding an explicit dep for it to the root package.json avoid bundling prop-types in each of the packages.
> make wonder-blocks-core a dependency of wonder-blocks-spacing, add prop-types as a project-wide dep

- packages/wonder-blocks-core/components/media-layout.js
- packages/wonder-blocks-core/package.json
- packages/wonder-blocks-grid/package.json
- packages/wonder-blocks-progress-spinner/package.json
- packages/wonder-blocks-spacing/package.json
We had an issue where `yarn run watch:all` resulting in an ever growing dist/index.js for `wonder-blocks-core`.  This PR fixes that by ensuring that `wonder-blocks-core` has the prop dependencies specified and that internal dependencies are imported directly.  This fix will also require us to publish `wonder-blocks-spacing` which is a dependency of `wonder-blocks-core`.
> Avoid recursive imports

- package.json
I'm going to give this a try.  It should prevent situations where we bump the version of a package and then any other package using that gets auto-bumped.
> only publish packages with explicit updates

- packages/wonder-blocks-modal/components/modal-panel.js
Jira: [WB-194](https://khanacademy.atlassian.net/browse/WB-194)
This moves the close button to render above the title and content so that it is accessible via pointer devices.
This also refactors the close button into a method so that it's a little easier to read the code.
I checked the styleguidist examples in both local and master.
> WB-194: Make sure the close button is above the header and content

- .vscode/settings.json
If you add the coverage gutter extension, this means you can see our coverage results inside the code, and other useful things.
> Add path for coverage gutter to find coverage info

- lerna.json
Unfortunately, this change doesn't impact any of the packages that lerna wants to bump since it still checks to see if devDependencies have changed when decided whether or not to bump a package's version.
> ignore changes to tests and documentation when publishing

- packages/wonder-blocks-button/generated-snapshot.test.js
- packages/wonder-blocks-color/generated-snapshot.test.js
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-grid/generated-snapshot.test.js
- packages/wonder-blocks-icon-button/generated-snapshot.test.js
- packages/wonder-blocks-layout/generated-snapshot.test.js
- packages/wonder-blocks-link/generated-snapshot.test.js
- packages/wonder-blocks-modal/generated-snapshot.test.js
- packages/wonder-blocks-progress-spinner/generated-snapshot.test.js
- packages/wonder-blocks-spacing/generated-snapshot.test.js
- packages/wonder-blocks-typography/generated-snapshot.test.js
- utils/gen-snapshot-tests.js
This is needed for when we use things like `ReactDOM.findDOMNode` in our components, as they will cause jest to fail the test.
While no components do this yet, there are some coming (like the `Tooltip`: #140 ) that will require this change.
> Mock react-dom in snapshot tests

- .vscode/extensions.json
- .vscode/settings.json
- package.json
- packages/wonder-blocks-core/util/util.js
This is a tooling-only PR.
In this PR there are two main changes:
1. `jest` now uses `globals` in the jest configuration to control aphrodite style flattening, rather than an environment variable. This allows us to use idiomatic jest tooling like the VS Code jest extension.
1. Adds an `extensions.json` file to recommend a few extensions to use when developing for Wonder Blocks. This adds a "star" swatch to the extensions in the extensions explorer to indicate they are recommend; they can also be viewed by searching extensions for `@recommended` and expanding the "Workspace Recommendations" section.
> Make jest work idiomatically and add extensions.json

- .vscode/launch.json
- .vscode/tasks.json
This adds a few things to our VS Code setup:
1. Some tasks that wrap our common `package.json` tasks. This sets up a default build task, a default test task, and provides a combined task that will watch and start the dev server, allowing us to have live update of the dev server when package dependencies are changed
2. A new debug configuration specifically for debugging jest test files. The Jest extension provides some great support for jest, but even without it, this will allow us to set breakpoints in our tests and step through them.
> Debug your tests in VS Code and more

- packages/wonder-blocks-tooltip/components/tooltip-anchor.js
- packages/wonder-blocks-tooltip/components/tooltip-anchor.test.js
This extends #149 to add the `TooltipAnchor` component. This component is responsible for controlling the active state of the tooltip so that we know when to show or hide the tooltip bubble.
This is another piece of #140.
> Add TooltipAnchor component

- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-bubble.js
- packages/wonder-blocks-tooltip/components/tooltip-bubble.test.js
- packages/wonder-blocks-tooltip/components/tooltip-content.js
- packages/wonder-blocks-tooltip/components/tooltip-content.md
- packages/wonder-blocks-tooltip/components/tooltip-content.test.js
- packages/wonder-blocks-tooltip/components/tooltip-portal-mounter.test.js
- packages/wonder-blocks-tooltip/components/tooltip.js
- packages/wonder-blocks-tooltip/components/tooltip.md
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
- packages/wonder-blocks-tooltip/index.js
- packages/wonder-blocks-tooltip/package.json
- packages/wonder-blocks-typography/index.js
- styleguide.config.js
This PR implements the `TooltipContent` component that is used to render the content of the `TooltipBubble`. In this change, we add the new component and some test documentation for it, as well as update the other components to support it.
We also add some helper types to `wonder-blocks-typography` to simplify how we specify what elements are valid.
> Add TooltipContent component

- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-arrow.js
- packages/wonder-blocks-tooltip/components/tooltip-arrow.md
- packages/wonder-blocks-tooltip/components/tooltip-bubble.js
- packages/wonder-blocks-tooltip/components/tooltip.md
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
- packages/wonder-blocks-tooltip/package.json
- styleguide.config.js
- yarn.lock
This PR builds on #152 to add the `TooltipArrow` component.
In this work, we extend the `TooltipBubble` component to render the arrow, including style changes to ensure the arrow appears where we need it relative to the content.
Now that we know the overall structure, the next PR after this one will split the `TooltipBubble` into a rendering component and a positioning component. This should allow us to have some rendering docs for the entire bubble outside of the positioning code. This will also be when we add styling for the tooltip bubble.
The SVG code for drawing the arrow may need some tweaks to get the drop shadow radius looking like our designs. This can be done once the overall tooltip styling is done in the next PR.
Docs have been added for this internal component. These internal …
> Add TooltipArrow component

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/no-ssr.js
- packages/wonder-blocks-core/components/no-ssr.md
- packages/wonder-blocks-core/components/no-ssr.test.js
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/index.js
This adds the `NoSSR` component that @jnetterf created.
I have also added additional tests for the SSR-specific behaviour.
Having the ability to avoid rendering things on the server is valuable; especially when we need to have different behaviours between client and server, like when producing identifiers; initial renders much match on server and client, and so unique IDs have to be generated on the client AFTER intial render. This component can help with that. The next work will be to add support for unique identifiers and that will require this SSR/Client behaviour differentiation.
> Add NoSSR component

- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-bubble.js
- packages/wonder-blocks-tooltip/components/tooltip-bubble.md
- packages/wonder-blocks-tooltip/components/tooltip-bubble.test.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.test.js
- packages/wonder-blocks-tooltip/components/tooltip-portal-mounter.js
- packages/wonder-blocks-tooltip/components/tooltip-portal-mounter.test.js
- packages/wonder-blocks-tooltip/components/tooltip.js
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
- styleguide.config.js
This builds on #155 where we introduced the `TooltipArrow` component. The main purpose here is to separate the `TooltipBubble` component into a positioning component (`TooltipPopper`) and a rendering component (`TooltipBubble`).
This also adds some test examples for the bubble. The next task will be to style the bubble content.
> Split TooltipBubble into TooltipBubble and TooltipPopper

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/unique-id-provider.js
- packages/wonder-blocks-core/components/unique-id-provider.md
- packages/wonder-blocks-core/components/unique-id-provider.test.js
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/index.js
- packages/wonder-blocks-core/index.test.js
- packages/wonder-blocks-core/util/__snapshots__/unique-id-factory.test.js.snap
- packages/wonder-blocks-core/util/ssr-id-factory.js
- packages/wonder-blocks-core/util/ssr-id-factory.test.js
- packages/wonder-blocks-core/util/types.js
- packages/wonder-blocks-core/util/unique-id-factory.js
- packages/wonder-blocks-core/util/unique-id-factory.test.js
This PR adds the `UniqueIDProvider` component for the provision of unique identifiers in a server-side render-friendly manner (for those with access, this is detailed in [ADR #60](https://docs.google.com/document/d/1BYQtb6GLZpruWEoYYQ74_7H8qZ41UbFuVsQBVGFew3o/edit#)).
The component uses the `NoSSR` component to control behavior based on whether something is being rendered for the first time or not, allowing us to ensure that initial rendering on both client and server will match.
This also adds documentation and test coverage for the component and the utilities that it uses.
NOTE: This is part of the `Tooltip` work as we need unique identifiers for the a11y solution.
> Add UniqueIDProvider

- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-anchor.js
- packages/wonder-blocks-tooltip/components/tooltip-anchor.test.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.js
- packages/wonder-blocks-tooltip/components/tooltip.md
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
- packages/wonder-blocks-tooltip/util/__snapshots__/active-tracker.test.js.snap
- packages/wonder-blocks-tooltip/util/active-tracker.js
- packages/wonder-blocks-tooltip/util/active-tracker.test.js
- packages/wonder-blocks-tooltip/util/constants.js
This PR updates the `TooltipAnchor` to enforce tooltip behavior:
1. Only one tooltip visible at a time
2. Delay first tooltip appearance by 100ms
3. Delay last tooltip disappearance by 75ms
4. Switch tooltips instantly if going from one to another
> Tooltip behavior: one at a time and delays

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-layout/components/spring.js
- packages/wonder-blocks-layout/components/strut.js
- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-bubble.js
- packages/wonder-blocks-tooltip/components/tooltip-bubble.test.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.test.js
- packages/wonder-blocks-tooltip/components/tooltip-tail.js
- packages/wonder-blocks-tooltip/components/tooltip-tail.test.js
- packages/wonder-blocks-tooltip/components/tooltip.js
- packages/wonder-blocks-tooltip/components/tooltip.md
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
This PR adds our main accessibility feature to the tooltip. It is stacked on #190 so that the next PR can add testing for everything in the `Tooltip` component and make use of the testing utilities introduced in #188.
Here we add an identifier to the `TooltipBubble` and then force the anchor point to have `aria-describedby` that points to that identifier. This means when the anchor gets focused, assistive tech will give the tooltip content as additional information.
This also adds `aria-hidden` to `Spring` and `Strut`, as well as provide an escape hatch on the `Tooltip` for situations where a more complex or different accessibility solution is required.
NOTE: Additional test coverage to be added in separate PR.
> Implement a11y solution

- packages/wonder-blocks-core/components/no-ssr.test.js
- packages/wonder-blocks-core/components/unique-id-provider.test.js
- packages/wonder-blocks-core/util/enumerate-scroll-ancestors.test.js
- packages/wonder-blocks-core/util/get-element-intersection.test.js
- packages/wonder-blocks-tooltip/components/__snapshots__/tooltip.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-bubble.js
- packages/wonder-blocks-tooltip/components/tooltip-bubble.test.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.test.js
- packages/wonder-blocks-tooltip/components/tooltip.js
- packages/wonder-blocks-tooltip/components/tooltip.test.js
- packages/wonder-blocks-tooltip/util/is-obscured.test.js
- packages/wonder-blocks-tooltip/util/ref-tracker.test.js
- packages/wonder-blocks-tooltip/util/visibility-modifier.test.js
Here we add some final testing tweaks to the `Tooltip` component and related things, including validation of the a11y work in the previous PR on which this is stacked, #192.
In addition to the `Tooltip` coverage, this set of changes migrates all the tooltip fixtures to use the special version of `mount` that gives us an `unmountAll` method. This is important since tests share a DOM, and without unmounting all mounted things, side-effects can bleed across test boundaries (we should update all our testing to use this model).
Finally, we also rework many tests to use `async`/`await` for a much tidier set of tests.
> Add tests for tooltip.js and tidy up testing

- .eslintrc
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/multi-select-menu.js
- packages/wonder-blocks-modal/components/modal-backdrop.js
- packages/wonder-blocks-modal/components/modal-launcher.js
Uses [react/jsx-handler-names](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md) to check that our event handlers conform to our react style guide guidelines for [event handlers](https://github.com/Khan/style-guides/blob/master/style/react.md#name-handlers-handleeventname).
> add eslint rule for event handlers names

- packages/wonder-blocks-modal/components/modal-launcher-portal.test.js
- packages/wonder-blocks-tooltip/components/tooltip-bubble.test.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.test.js
Unfortunately I wasn't able to convert all async tests to use async/await.  In particular I couldn't get the tests in tooltip-portal-mounter.test.js to work b/c for some reason `node` wasn't actually mounted.  I do believe that using async/await results in more readable tests so it would be good to figure out why things weren't working in that particular situation.
> update some of tooltip tests to use async/await

- flow-typed/npm/react-router-dom_v4.x.x.js
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-core/util/get-clickable-behavior.test.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-link/components/link-core.js
This improves flow coverage in clickable-behaviour.js.  We still need to refactor the render method so that flow can better understand which props are going to which components that are being rendered.
> add flow types for react-router-dom

- package.json
- yarn.lock
eslint-scope 3.7.2 contains code to steal credentials.  We don't have any credentials in the project yet, but better to fix this now.
> Upgrade babel-eslint to avoid a bad version of eslint-scope

- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/components/tooltip-tail.js
- packages/wonder-blocks-tooltip/components/tooltip-tail.md
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
This updates the `TooltipTail` to match the latest design decisions so that in the rare circumstances that it will butt up against the bubble corners, it has an 8px margin.
See https://zpl.io/2j4zNjQ
> Make the distance from corners match latest spec

- .travis.yml
The command `yarn run build:coverage && codecov` started failing with message `codecov: command not found` in the travis builds. Build [#1663](https://travis-ci.org/Khan/wonder-blocks/builds/403894931) passed but build [#1666](https://travis-ci.org/Khan/wonder-blocks/builds/404475845) failed. We didn't change our config files between those builds, so perhaps something changed with travis or `yarn`.
This [issue](https://github.com/yarnpkg/yarn/issues/648) indicates that `global add` didn't put the binary in the expected location, so we append `yarn global bin` to `PATH`.
> Fix build to find codecov

- packages/wonder-blocks-button/package.json
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-grid/package.json
- packages/wonder-blocks-icon-button/package.json
- packages/wonder-blocks-icon/package.json
- packages/wonder-blocks-link/package.json
- packages/wonder-blocks-modal/package.json
- packages/wonder-blocks-progress-spinner/package.json
- packages/wonder-blocks-tooltip/package.json
I noticed that some of the packages that were published to npm are bigger than they should be.  This PR adds react, aphrodite, and react-router-dom as peer deps where need which will cause them to be excluded from the bundle b/c our build script marks anything that appears in `dependencies` or `peerDependencies` as external in the webpack settings for that package.
> add missing peerDependencies

- packages/wonder-blocks-modal/components/modal-backdrop.test.js
I think the tests were failing because they were doing a shallow render, causing `ReactDOM.findDOMNode(this)` in `ModalBackdrop.componentDidMount` to fail. If we do a full mount instead, the tests pass. Alternatively, we can disable the lifecycle methods, which don't appear to be relevant what these particular tests are testing for.
> Fix modal tests after update to react 16

- packages/wonder-blocks-icon/docs.md
- packages/wonder-blocks-icon/generated-snapshot.test.js
Removes the console warning about how iterated-over things need a distinct key
> Fix minor error in Icon docs

- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/components/modal-panel.js
The close button is `position: absolute`, so changing this doesn't change where the button renders. This creates a more natural order for tab navigation in the modal. Previously, the tab ordering went footer -> content -> close. Now it goes footer -> close -> content.
Go to https://deploy-preview-232--wonder-blocks.netlify.com/#modal and open the one-column modal, which has tab-active elements in the modal content.
> Create more natural tab order in modal

- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/dropdown-core.js
- packages/wonder-blocks-dropdown/components/multi-select-menu.js
- packages/wonder-blocks-dropdown/components/multi-select-menu.test.js
- packages/wonder-blocks-dropdown/components/single-select-menu.js
- packages/wonder-blocks-dropdown/components/single-select-menu.test.js
This pull request has the non-portal related changes from #199:
* changed `onClosed` prop to `onOpenChanged` for `DropdownCore`
* updated enzyme tests to use a better structure
* fixed minor typo in docs
> Change dropdown API, update comments and test structure

- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/multi-select-test.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-dropdown/components/separator-item.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.md
- packages/wonder-blocks-dropdown/components/single-select.test.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/index.js
- packages/wonder-blocks-dropdown/index.test.js
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-dropdown/util/types.js
- styleguide.config.js
I originally named the components closely to what they were called in the design. I realized that those names don't match the existing components or the basic HTML elements that the components correspond to, so I'm trying to improve that.
Test plan:
The snapshot of this package doesn't change with this diff. Searched through the codebase for all instances of the names I changed.
> Rename dropdown to more closely match existing and base elements

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/custom-snapshot.test.js
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-core/components/clickable-behavior.test.js
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-icon-button/custom-snapshot.test.js
- packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-link/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-link/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-link/components/link-core.js
- packages/wonder-blocks-link/custom-snapshot.test.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
`IconButton` had a `clientNav` prop, but its behaviour was never implemented.  This PR implements that prop bringing `IconButton` in line with `Button`.  I would like to add some automated test for `clientNav`, but I'll try to do this in a separate PR.  This PR also removes some `$FlowFixMe`s.
> WB-320: update IconButton to handle clientNav, fix FlowFixMes

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
Firefox adds an additional inner focus ring for buttons. Update `Button` and `IconButton` styles so that the inner focus ring is not shown.
Test plan:
Used keyboard navigation to navigate to `Button` and `IconButton` examples on styleguidist and confirm that the inner focus ring does not show up.
> Remove inner border from button elements for Firefox

- package.json
- packages/wonder-blocks-button/package.json
- packages/wonder-blocks-core/package.json
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-modal/package.json
- packages/wonder-blocks-tooltip/package.json
- webpack.config.js
- yarn.lock
This is still kind of error prone b/c I had to check things manually.  I would like to create a script to verify that all require/import state for an external dep appear in the modules "dependencies" or "peerDependencies".  That'll be a separate PR b/c I want to get some of these components published.  For now we can verify what's being bundled by looking at the output of webpack which we're now passing `--display-modules` to which will show all modules.  Ones that aren't bundled are marked as `external` and only occupy 42 bytes in the bundle.
> WB-338: exclude all external deps from built files

- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-icon-button/package.json
- packages/wonder-blocks-link/components/link.js
- packages/wonder-blocks-link/package.json
I noticed a couple issues with how we were using the router context.
1) Everywhere, except in the button module, we had forgotten to include the `contextTypes` (meaning that React would never give us access to the context, and thus we'd never get the router).
2) This introduced a dependency on prop-types for link, icon-button, and dropdown so I went to add it as a peerDependency and also realized it was missing for button, so I added it there too.
> Fix missing router context.

- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/components/modal-launcher.js
- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
Use `getDerivedStateFromProps` in `ClickableBehavior` instead of deprecated method.
- Verified by the existing test case in `clickable-behavior.test.js`
Change a `View` to `React.Fragment` in `ModalLauncher`.
- Manual verification of the modal examples.
> Address a few react 16 related TODOs

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-core/components/clickable-behavior.test.js
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/multi-select.test.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-dropdown/components/single-select.test.js
- packages/wonder-blocks-form/components/choice-internal.js
- packages/wonder-blocks-icon-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-link/components/link.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
After some invesigation and discussion, I wrote up [this document](https://docs.google.com/document/d/1DG5Rg2f0cawIL5R8UqnPQpd7pbdObk8OyjO5ryYQmBM/edit?usp=sharing) to describe the expected behavior of ClickableBehavior.
The main change here is to allow components that use ClickableBehavior to indicate whether they should be triggered on enter, or space, or both. This change also fixes a bug where a mouse click that directly followed a space click sometimes wasn't registered and attempts to normalize the ClickableBehavior across major browsers.
I added unit tests for the new cases, but since browsers have slightly different behavior in where event defaults happen, they're not perfect or fully comprehensive.
Test plan prereq:
* On Safari, may have to enable Preferences -> Advanced -> Check …
> Update ClickableBehavior behavior across browsers and components

- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-core/components/clickable-behavior.test.js
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/multi-select.test.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.md
- packages/wonder-blocks-dropdown/components/single-select.test.js
- packages/wonder-blocks-dropdown/docs.md
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/util/constants.js
- packages/wonder-blocks-dropdown/util/types.js
This change creates refs for each item in the Dropdown component, which handles focus navigation logic based on a keyboard event listener. Instead of the menu/select components cloning the user-supplied items, this now happens at the Dropdown component level so that the Dropdown component can also create the refs and manage indices without having to reclone each item.
Also now pre-binding callbacks.
Expected behavior:
* Opening the menu with mouse click doesn't automatically fous an item, but opening the menu with the keyboard does
* Action menus and MultiSelect start off with the first item focused, but SingleSelect starts off with the selected item focused
* Pressing space on an item no longer scrolls the page, and it selects the item as expected
* Both tab and escape keys should close …
> Add keyboard accessibility to dropdown menus

- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-modal/components/modal-launcher.test.js
Also changed the mock functions in`dropdown.test` to use `window` instead of `global`.
Run `yarn run jest`. Yay no more warnings about `scrollTo`.
> Remove warning messages about scrollTo not being implemented

- packages/wonder-blocks-form/components/checkbox-core.js
- packages/wonder-blocks-form/components/checkbox.js
- packages/wonder-blocks-form/components/choice-internal.js
- packages/wonder-blocks-form/components/radio-core.js
- packages/wonder-blocks-form/components/radio.js
- packages/wonder-blocks-form/util/types.js
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-icon-button/components/icon-button.test.js
- packages/wonder-blocks-icon-button/custom-snapshot.test.js
- packages/wonder-blocks-icon/components/icon.js
- packages/wonder-blocks-modal/components/modal-panel.js
I noticed that some checkboxes in `webapp` try to use `ariaLabel` to provide a label for checkboxes that don't have a clear label e.g.
However, the current `Checkbox` in `webapp` doesn't actually support an `ariaLabel` prop (which is how I missed this during the implementation spec phase). So all those checkboxes in `webapp` don't really have aria labels attached...oops.
> **Breaking change for Icon and IconButton** -- Add ariaLabel prop to checkbox / radio

- .eslintrc
- package.json
- yarn.lock
I just reviewed a PR in another project that fixed a misuse of promises that could've been caught with lint so figured we may as well lint our promises just in case.  Thankfully no lint, phew!  Descriptions of the rules can be found at https://github.com/xjamundx/eslint-plugin-promise#rules.  Warning: the docs are missing for some of the rules.  I also change our use of numbers in .eslintrc to strings.  The number `2` dead, long live `"error"`.
> lint our promises

- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-core/components/clickable-behavior.test.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-form/components/choice-internal.js
- packages/wonder-blocks-form/components/choice.js
- packages/wonder-blocks-form/components/radio.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-link/components/link.js
`role` prop is optional, and it defaults to both space and enter being triggers (this was the default behavior before as well).
> Replace ClickableBehavior's trigger props with role prop

- package.json
Either I just got it wrong or the API changed, I'm not sure! Either way these are the right options.
> Fix dry-run-publish command to use --skip-git/--skip-npm.

- packages/wonder-blocks-tooltip/components/tooltip-popper.js
When we upgraded our type checking for the style prop we missed copying the `transform` style prop which actually positions the tooltip on the page.
> Fix tooltip positioning

- package.json
- packages/wonder-blocks-core/util/get-element-intersection.js
The fix wasn't too bad, set the bounding rect's height to be the scrollHeight and add update its bottom to be consistent.  Unfortunately, this is hard to write a unit test for.  I'd rather spend time working on setting up image regression tests for this as those will be useful for other things that are hard (or impossible) to test as well.
I tested this by setting the `height: 100%` on `body, html` and `overflow-y: scroll` on `body`.  Then I navigated to http://localhost:6060/#tooltip-1 and hovered over items and saw their tooltips.
> fix element intersection func to work with overflow-y: scroll hack

- packages/wonder-blocks-toolbar/components/toolbar.js
I have a usecase for CS scratchpads where the toolbar editor variably shows different elements, ie. many of them are null at any given time. With the WB toolbar, it currently shows an empty View for each of those null elements, which is undesirable. This change filters out empty elements using Array.filter() before mapping them.
For testing, I manually edited the generated file in webapp/third_party/node_modules and verified it works for my use case. I did not see other obvious ways to test it, since the jest tests are auto-generated. I'm assuming those tests are run by a CI.
> Don't render empty elements inside toolbar components

- package.json
Before this change, the dist/es folders were appearing in the output for `yarn coverage`. We don't want that, so this ensures it doesn't happen.
> Ignore all the dist files

- package.json
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-icon-button/components/icon-button.test.js
- packages/wonder-blocks-modal/components/modal-backdrop.test.js
- packages/wonder-blocks-modal/components/modal-launcher.test.js
- test-setup.js
- utils/testing/expect-render-error.js
- yarn.lock
I was bothered by the console errors that were coming up during testing, I was worried that they might be obscuring real errors so I went and fixed them all.
- IconButton: This was fixed by creating an ErrorBoundary around the component that intentionally swallows the error. This was discussed in https://github.com/facebook/react/issues/11098 and required an upgrade to React 16.4.3 - which, in turn, required an upgrade of the Enzyme React Adapter. I pulled in the utility for testing these in the future into `utils/testing/expect-render-error.js`.
- Dropdown: We needed to not pre-mount the button before passing it in. The tests worked fine even without doing that!
- ModalBackdrop & ModalLauncher: Both needed to reference real Modals, not mock divs.
I also modified test-setup.js to throw an …
> Fix all console errors emitted during tests.

- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/dropdown.test.js
fixed a bug in #334. There was a test that should have caught this bug, but it is giving us a false-positive 😭 
Unfortunately the "modalHost" I was using was document.body, so checking
if the event was inside the modalHost always returned true! This uses a
ref on the actual popup element, so it works.
Test plan:
desktop & phone:
- open a SingleSelect
- select an item, it should work
- open it again
- tap/click outside of it, and it should dismiss
> Fix dropdown not dismissing on click

- packages/wonder-blocks-core/components/unique-id-provider.js
- packages/wonder-blocks-core/components/unique-id-provider.test.js
I ran into a situation where having a `NoSSR` wrapping a `UniqueIdProvider` resulted in `this._performRender(true)` not getting called which meant that `this._idFactory` never gets initialized.  This PR fixes that by always check if `this._idFactory` is initialized before calling it and initializing it if it hasn't already been done.
> fix issue with UniqueIdProvider inside NoSSR

- .browserslistrc
- babel.config.js
- packages/wonder-blocks-form/components/checkbox-group.test.js
- packages/wonder-blocks-form/components/radio-group.test.js
- packages/wonder-blocks-tooltip/components/__snapshots__/tooltip.test.js.snap
This will also avoid having to update UglifyJS which also can't handle ES6 code.  Upgrading both the phantomjs test runner and UglifyJS as part of the current build system aren't good uses of time given that we'll soon be replacing our current build system and test runner.
> output ES5 code so that we can run the phantomjs tests in webapp

- .circleci/config.yml
- package.json
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-form/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-form/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon/components/icon.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
This PR fixes a couple of issues with the ActionMenu opener:
- text wasn't being truncated
- icon was be squished
Icon is now fixed size.  It can't shrink or grow.
Before:
After:
Unfortunately we don't have an easy way to test changes in webapp.  We will once the webpack work is done, but I have high confidence that this will fix the issue.  In the before screenshot notice how the down caret is smaller than it should be.  I was able to reproduce this in one of the ActionMenu examples before fixing it with by setting `flexShrink: 0` on the Icon component.  I'll try copy/pasting the built component into webapp to verify things are working as expected.
> make Icon fixed size, fix truncation behavior in ActionMenu opener

- packages/wonder-blocks-typography/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-typography/components/body-monospace.md
- packages/wonder-blocks-typography/generated-snapshot.test.js
I had created a `Code` component for use in my React Sandbox work and thought it made a nice simple example. So I've added it to the docs.
> Add a simple example of using BodyMonospace

- lerna.json
In order to avoid bumping all modules all the time, I've added some more files to ignore to our lerna.json file.
Test Plan:
- run `node_modules/.bin/lerna updated`
- see the following output
```
lerna info version 2.11.0
lerna info versioning independent
lerna info ignore [ '*.test.js', '*.vite_test.js', '*.md', '*.js.snap' ]
lerna info Checking for updated packages...
lerna info Comparing with @khanacademy/wonder-blocks-button@2.2.5.
lerna info Checking for prereleased packages...
lerna info result 
- @khanacademy/wonder-blocks-dropdown
```
In this case `wonder-blocks-dropdown` has actually seen some code changes since the last publish.
> ignore more files to avoid unnecessary upgrades while publishing

- config/jest/test.config.js
- config/jest/vite.config.js
Since the addition of the vite test runner, the normal jest tests weren't excluding `.vite_test.js` files and the normal jest tests weren't excluding `.test.js` files.
> don't include test files in coverage reports

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.md
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
It seems that ActionMenu and SingleSelect already worked without any children.  This PR adds examples to show that they work and update MultiSelect to ensure that it works.  I've also updated the flow types for all of the dropdowns to allow code to type check when not passing children.
TODO: move the examples closer to the exiting disabled examples.
> WB-474: allow dropdowns to work without children

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-progress-spinner/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-progress-spinner/components/circular-spinner.js
This diff rotates the path inside the svg.  I removed the caching but I can put it back if necessary.
> WB-407: prevent spinner's bounding box from change as it rotates

- .flowconfig
- package.json
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-core/components/no-ssr.js
- packages/wonder-blocks-core/components/view.js
- packages/wonder-blocks-core/util/add-style.js
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-form/components/checkbox-group.js
- packages/wonder-blocks-form/components/radio-group.js
- packages/wonder-blocks-icon/components/icon.js
- packages/wonder-blocks-link/components/link-core.js
- packages/wonder-blocks-modal/components/modal-context.js
- packages/wonder-blocks-modal/components/modal-launcher.js
- yarn.lock
In version 0.85, you now have to specify the type parameter when using functions with parameterized types, see https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8 for details.  As a result, it turns out that our type declaration for the `addStyle` HOC is really awkward.  I'm going to try to simplify as part of this PR.
> upgrade Flow to version 0.85

- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.md
- packages/wonder-blocks-button/components/button.test.js
- packages/wonder-blocks-button/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-icon-button/components/icon-button.md
- packages/wonder-blocks-icon-button/components/icon-button.test.js
- packages/wonder-blocks-icon-button/generated-snapshot.test.js
The issue is that when using href we end up rendering either an `<a>` or a ` <Link>`.  With `<a>` you can disabled it not giving an `href`, but with `<Link>` its `to` prop is a required.  This PR instead renders a `<button>` whenever the Button, IconButton or ActionItem is disabled and sets `disabled={true}`.  This results in the component being un-clickable when disabled regardless of whether it uses `href` or not.
> WB-489: prevent navigation when using href and disabled props together

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.test.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.test.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
I'm not sure if I'm using the right roles for the right things.  The openers no-longer have any role.  They use a `<button>` under the hood whose role is `button` by default which I think is okay.  `Dropdown` is a pretty general component so in order to make people think about what role they want I've made `role` mandatory.
> WB-491: update dropdown components to have appropriate aria roles

- packages/wonder-blocks-modal/components/focus-trap.js
- packages/wonder-blocks-modal/components/modal-backdrop.js
- packages/wonder-blocks-modal/components/modal-backdrop.test.js
This diff solves two issues:
- we were focus the button inside the modal too soon and so it was actually at the bottom of the page since styles hadn't been applied yet
- the sentinel divs in `FocusTrap` were positioned at the bottom of the page
Now we wait a bit for styles to be applied before focusing the button.  We also set the style of the sentinel divs to be `position: fixed` so that they're always in view.
> WB-427: prevent page scrolling to bottom when opening modal

- packages/wonder-blocks-core/components/unique-id-provider.js
- packages/wonder-blocks-core/components/unique-id-provider.md
- packages/wonder-blocks-core/components/unique-id-provider.test.js
- packages/wonder-blocks-core/generated-snapshot.test.js
The (old) default behavior of UniqueIDProvider is that it would not
actually render its children during server-side rendering -- that is,
for the initial render.  That seems like a very surprising default to
me, and I think it would be for others as well.
I could change the default, but then you get a different non-obvious
behavior, that you get two different unique-id factories for the
initial render and subsequent renders.
So instead, I just make clients be explicit about which alternative
they prefer.  This helps ensure that they understand the consequences
of their choice.
Test Plan:
yarn test
> Breaking(core) - Make mockOnFirstRender required for UniqueIDProvider.

- package.json
We need to build all the packages before linting because we have a lint
check that verifies that all imports can be resolved.  The main entry
point for all of our packages is dist/index.js which is a built file.
Thus, in order to pass this check we must build the files before running
lint.  Reording the commands in the "test" script in package.json fixes
this.
Test Plan:
- yarn clean
- yarn install
- yarn test
> Build files before linting

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/unique-id-provider.js
- packages/wonder-blocks-core/components/unique-id-provider.test.js
- packages/wonder-blocks-core/components/with-ssr-placeholder.js
- packages/wonder-blocks-core/components/with-ssr-placeholder.md
- packages/wonder-blocks-core/components/with-ssr-placeholder.test.js
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/index.js
- packages/wonder-blocks-core/index.test.js
`NoSSR` is a misleading name, because with the `placeholder` param
it's not actually "no" ssr, it's "different" ssr.  (The name is doubly
misleading, since to me "No ssr" means that you can't render this
component during ssr -- it will raise an exception or some such --
when really what it means is that, by default, its children are
ignored when rendered via ssr.)
The new name, I think, makes the intent clearer.  I also made the
placeholder arg required, since I don't think it's right to privilege
"don't show anything" as the default behavior, since it's probably
not the right thing to do most of the time.  (If anything, I'd have
the default be "show a spinner".)
Test Plan:
yarn test
> Breaking(core) - Rename NoSSR to WithSSRPlaceholder

- styleguide.config.js
We were only downloading Lato at weight 400 (the default).  This PR updates the URL to grab 400, 700, and 900.
BEFORE:
AFTER:
> WB-401: Update styleguidist config to include Lato bold and black variants

- packages/wonder-blocks-core/components/with-ssr-placeholder.js
This makes the `default` case in context fall through to the `"root"` context rather than throwing an error. This should allow for the strange context bug seen in webapp.
I tried reproducing the issue in Wonderblocks (even downgrading) but it was not sufficient to reproduce at this time. For now, ensuring we cope gracefully seems fair.
> [WB-505] Deal with strange context issues for root SSR use

- .vimrc
To allow your vim to use project specific vimrcs put `set exrc` in your
`~/.vimrc` somewhere.  If you enable this, it’s also a good idea to add
`set secure` to the end of your ~/.vimrc to disable unsafe commands in
your project-specific .vimrc files.
Reference: https://andrew.stwrt.ca/posts/project-specific-vimrc/
Github link for ALE: https://github.com/w0rp/ale
> Add project-level .vimrc

- README.md
The "Contributing" section of the README pointed at our old and no-longer-used Zeplin comps. We've moved to Figma and this commit updates the README to reflect that.
> Update README to point to correct designs

- .codecov.yml
- package.json
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/text.js
- packages/wonder-blocks-core/components/text.md
- packages/wonder-blocks-core/components/view.js
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/index.js
- packages/wonder-blocks-core/util/types.js
- packages/wonder-blocks-dropdown/components/action-menu-opener.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-form/components/checkbox-group.js
- packages/wonder-blocks-form/components/checkbox.js
- packages/wonder-blocks-form/components/choice-internal.js
- packages/wonder-blocks-form/components/radio-group.js
- packages/wonder-blocks-form/components/radio.js
- packages/wonder-blocks-form/util/types.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-icon/components/icon.js
- packages/wonder-blocks-link/components/link.js
- packages/wonder-blocks-modal/components/one-column-modal.js
- packages/wonder-blocks-modal/components/standard-modal.js
- packages/wonder-blocks-modal/components/two-column-modal.js
- packages/wonder-blocks-progress-spinner/components/circular-spinner.js
- packages/wonder-blocks-toolbar/components/toolbar.js
- packages/wonder-blocks-tooltip/components/tooltip-anchor.test.js
- packages/wonder-blocks-tooltip/components/tooltip.js
- packages/wonder-blocks-typography/util/types.js
This PR does a little more work than is necessary, but I ran into some issues with the inexact types we were using for `View` and `Text` so I ended up making them exact including `AriaProps`.  Also, now that `AriaProps` is exact it was super easy to add it to all of our other components which had `aria-label?: string` as a prop.
This would be a breaking change if we were using flow typing.  I'm going to try to turn on flow typing for some packages (not typography).  There's another breaking change I'd like to make to switch to adopt ref forwarding on all of our components so that people can easily access the underlying DOM element.  I'd like to group multiple breaking changes together to avoid having more versions than is necessary of components in webapp.
> WB-504: BREAKING(core) - Add testId (and AriaProps) to all public components

- packages/wonder-blocks-layout/components/media-layout.js
- packages/wonder-blocks-modal/components/__snapshots__/standard-modal.test.js.snap
- packages/wonder-blocks-modal/package.json
This is in response to a bug I noticed yesterday when trying to update wonder-blocks in webapp.  From slack:
> The behavior I’m seeing is bizarre and I have yet to explain it, but when I click anywhere on the modal, it resizes the modal once, and if I click it again, it gets small, then if I click it stops and I can actually click the cancel button.  This only happens when in its mobile size.  I’m unable to reproduce this on wonder-blocks.netlify.com.  It feels like it has something to with MediaLayout re-rendering a child when it shouldn’t though I can’t say for sure and I don’t know how clicking would trigger this.
It turns out there were two copies of wonder-blocks-layout in code.  Adding `wonder-blocks-layout` as a dep of `wonder-blocks-modal` will remove the additional copy b/c our …
> add -layout as a dep of -modal, simplify creation of MediaQueryLists and addition/removal of listeners

- packages/wonder-blocks-core/components/text.md
I'm going to add something to Confluence too, but I thought I'd start here first.
> Add warning about using 'Text' component

- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/separator-item.js
- packages/wonder-blocks-grid/components/cell.js
- packages/wonder-blocks-grid/components/row.js
- packages/wonder-blocks-modal/components/modal-content.js
- packages/wonder-blocks-modal/components/modal-footer.js
- packages/wonder-blocks-modal/components/modal-header.js
- packages/wonder-blocks-modal/components/modal-panel.js
- packages/wonder-blocks-modal/components/one-column-modal/small-one-column-modal.js
- packages/wonder-blocks-modal/components/two-column-modal/small-two-column-modal.js
The issue is that react-hot-loader wraps components in ReactProxy classes which breaks direct component class checks.
Test Plan:
- use yarn link to test these components in webapp
- load demos.jsx.fixture.js in the react sandbox
- verify that all of the dropdowns and the modals work (the demos fixture doesn't have a grid example yet)
Aside: I really wanted to use `Symbol` so I could copy/paste the `isClassOf` snippet without having to modify it each time, but flow doesn't support computed static vars. 😞
> WB-554: update components for use with react-hot-loader

- packages/wonder-blocks-modal/components/modal-launcher.js
- packages/wonder-blocks-modal/components/modal-launcher.test.js
When a dialog closes, focus now returns to the element that invoked the dialog.
Test Plan:
1) `yarn start` and open http://localhost:6060/#!/ModalLauncher/1
2) Click on **OnePaneDialog** button
3) Close the modal
4) Check that the focus is returned to the **OnePaneDialog** button
> [fix: modal] WB-564 Modal returns to previous focused element

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-icon/components/icon.js
- Added `aria-hidden` as prop (`false` by default).
- Modified **<SelectOpener />** to pass `aria-hidden="true"` to its internal `Icon` instance.
1. Open https://deploy-preview-406--wonder-blocks.netlify.com/#!/SingleSelect/13
2. Inspect the `svg` icon element and make sure it includes `aria-hidden="true"`.
> WB-581 Add aria-hidden prop to Icon and SelectOpener

- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.md
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- packages/wonder-blocks-form/components/checkbox-core.js
- packages/wonder-blocks-form/components/checkbox-group.test.js
- packages/wonder-blocks-form/components/choice.js
- packages/wonder-blocks-form/components/radio-core.js
- packages/wonder-blocks-form/components/radio-group.test.js
- packages/wonder-blocks-icon/components/icon.js
- packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- Added `aria-*` support to buttons, icons, selects, checkboxes and radioboxes.
- Added unit tests to check this new behavior (`<Checkbox />`, `<Radiobox />`).
- Modified some documentation that included a couple of unused props. 
1. Open the following examples:
- Button: https://deploy-preview-411--wonder-blocks.netlify.com/#!/Button/1
- ActionMenu: https://deploy-preview-411--wonder-blocks.netlify.com/#!/ActionMenu/1
- SingleSelect: https://deploy-preview-411--wonder-blocks.netlify.com/#!/SingleSelect/13
- MultiSelect: https://deploy-preview-411--wonder-blocks.netlify.com/#!/MultiSelect/11
- Checkbox: https://deploy-preview-411--wonder-blocks.netlify.com/#!/CheckboxGroup/1
- Radiobutton: https://deploy-preview-411--wonder-blocks.netlify.com/#!/RadioGroup/1
- Icon: …
> [feat:button,dropdown,form,icon] WB-580 Components should pass through all aria-props to their foundational inputs

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/components/id-provider.js
- packages/wonder-blocks-core/components/id-provider.md
- packages/wonder-blocks-core/components/id-provider.test.js
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/index.js
- packages/wonder-blocks-core/index.test.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/components/one-pane-dialog/one-pane-dialog.js
- Moved `UniqueDialog` from `modal` to `core` and renamed it to `IDProvider`.
- Refactored `IDProvider` to be used by different components/packages.
- Added documentation example.
- Updated unit tests.
1. Run `yarn test`.
2. Open `http://localhost:6060/#!/IDProvider/1` and make sure the example works as expected.
> [feat:core,modal] WB-576: Create IDprovider component

- packages/wonder-blocks-timing/package.json
- utils/pre-publish-check.js
- Sets `wonder-blocks-timing` as private to avoid publishing this package.
- Adds an extra pre-publish check to avoid publishing private packages.
> [chore] Set wb-timing as private and modify pre-publish check

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-icon-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
- Fixed: Removed blue highlight style shown when the user focuses/clicks a button on mobile devices.
1. Open the following links on a mobile device:
- Button: https://deploy-preview-417--wonder-blocks.netlify.com/#!/Button/1
- ActionMenu: https://deploy-preview-417--wonder-blocks.netlify.com/#!/ActionMenu/1
- IconButton: https://deploy-preview-417--wonder-blocks.netlify.com/#!/IconButton/1
2. Click on any button on the examples.
3. Make sure the highlight don't appear anymore (this happens when the focus is activated for this clicked button).
> [fix:button,dropdown,icon-button] WB-478: Remove special highlight style on mobile

- packages/wonder-blocks-modal/components/modal-content.js
- packages/wonder-blocks-modal/components/modal-dialog.js
- packages/wonder-blocks-modal/components/modal-footer.js
- packages/wonder-blocks-modal/components/modal-header.js
- packages/wonder-blocks-modal/components/modal-panel.js
- packages/wonder-blocks-modal/generated-snapshot.test.js
- packages/wonder-blocks-modal/index.js
- packages/wonder-blocks-modal/index.test.js
- styleguide.config.js
- Added `ModalDialog, ModalHeader, ModalFooter, ModalPanel` to the public API.
- Included `Modals > Building blocks` section into the documentation website.
- Added descriptions to: `ModalDialog, ModalHeader, ModalFooter, ModalPanel`
- Open https://deploy-preview-413--wonder-blocks.netlify.com/#!/Building%20Blocks
> [feat:modal]WB-585: Add building blocks to public API

- packages/wonder-blocks-core/components/__snapshots__/view.test.js.snap
- packages/wonder-blocks-core/components/view.js
- packages/wonder-blocks-core/components/view.test.js
- packages/wonder-blocks-core/util/types.js
Added support for the 'tag' prop in view components to override the default div tag if needed. Changed StyledDiv declaration from const to let because I reassign it later if the tag prop is present. Pulled out tag prop from restProps for child safety once the StyledDiv is adjusted (although I don't know if this is necessary).
> WB-529: Add support for tag prop in View component

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-button/components/button.md
- packages/wonder-blocks-button/components/button.test.js
- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-dropdown/components/action-menu-opener.js
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-icon-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-icon-button/components/icon-button.test.js
Removed `aria-disabled` as prop when the `disabled` attribute is present.
`yarn test`
> [fix:button,dropdown,icon-button] WB-535: Remove aria-disabled when disabled is present

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
Jira: https://khanacademy.atlassian.net/browse/LP-5535
We were using the global `open` which is always truthy so `aria-expanded` was always being set to `"true"`.  This PR fixes this by using `props.open` instead.  The fixtures have been updated which should be sufficient to show that the issue has been fixed.
> [dropdown:fix] use props.open in action-menu-opener-core.js instead of global open

- packages/wonder-blocks-link/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-link/components/link.js
- packages/wonder-blocks-link/components/link.md
- packages/wonder-blocks-link/generated-snapshot.test.js
- Link's `children` prop is now able to accept all typography components.
1. Open https://deploy-preview-431--wonder-blocks.netlify.com/#!/Link/3
2. Check the Link example includes a Typography component.
> [feat:link] WB-582 Allow children to accept all typography components

- packages/wonder-blocks-breadcrumbs/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-breadcrumbs/components/breadcrumbs-item.js
- packages/wonder-blocks-breadcrumbs/components/breadcrumbs.js
- packages/wonder-blocks-breadcrumbs/components/breadcrumbs.test.js
- packages/wonder-blocks-breadcrumbs/docs.md
- packages/wonder-blocks-breadcrumbs/generated-snapshot.test.js
- packages/wonder-blocks-core/util/types.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- Changed `aria-current="page"` to be added automatically to the last breadcrumb item [WB-562]
- Added/fixed `testId` prop to work both Breadcrumb and BreadcrumbItem. [WB-600]
1. Open https://deploy-preview-441--wonder-blocks.netlify.com/#breadcrumbs
2. Make sure the example includes `aria-current="page"` automatically.
3. Add a `testId` in the source code example and check the HTML now includes `data-test-id="the-testId-value"`
> [fix:breadcrumbs] WB-562 WB-600: Breadcrumbs fixes > aria-current and testId

- packages/wonder-blocks-clickable/docs.md
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/dropdown.md
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
Added the ability to override the opened state of Dropdown and implemented a new prop to treat OptionItems as single selects (select only one & close dropdown when clicked)
> WB-623: Implement single select OptionItems in Dropdown 

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/dropdown.md
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
Fixes the `Dropdown` component to make it fully controllable.
- Added `getDerivedStateFromProps` to sync the `opened` prop with the parent's state.
- Added `onClose` prop to sync up the `opened` prop within the parent component (similar to `ModalLauncher` and `Popover`).
- Added `onClick` prop to the Dropdown anchor to keep it in sync with the parent state.
- Added an example explaining this behavior.
- Updated unit tests.
1. Open https://deploy-preview-456--wonder-blocks.netlify.com/#dropdown-1
2. Go to the example: **Opening a dropdown programmatically** and check that works as expected.
3. Also, check the explanation is clear enough.
> [feat:dropdown] WB-633: Fix controlled mode in Dropdown

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/dropdown.md
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/multi-select.test.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.md
- packages/wonder-blocks-dropdown/components/single-select.test.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
Adds a "controlled" mode to all the dropdown variants. To make this mode work, you need to add the `opened` and `onToggle` props to the component instance. The dropdown openers still work on this mode due to the dropdown/select nature.
- Changed `onClose` to `onToggle` for better understanding on the controlled mode. This means that `onToggle` will be triggered every time the menu is open or closed.
- Added `getDerivedStateFromProps` to sync the `opened` prop with the parent's state.
- Added `onToggle` prop to sync up the `opened` prop within the parent component.
- Updated unit tests.
- Added examples.
1. Open https://deploy-preview-457--wonder-blocks.netlify.com/#section-dropdown
2. Check the documentation is clear enough.
3. Go to the examples related to controlled components and check …
> [feature:dropdown] WB-632 - Add controlled mode to ActionMenu, SingleSelect and MultiSelect

- packages/wonder-blocks-timing/components/with-action-scheduler.md
- packages/wonder-blocks-timing/docs.md
- packages/wonder-blocks-timing/generated-snapshot.test.js
- packages/wonder-blocks-timing/package.json
- packages/wonder-blocks-timing/util/types.js
- utils/gen-snapshot-tests.js
Closes WB-591.
This makes the following changes:
1. Makes the Wonder Blocks Timing package public
2. Adds detailed documentation for the Timing API, including migration example
3. Updates the snapshot generation to cope with static code examples (so that they aren't compiled for snapshot testing)
> WB-591: Add detailed documentation for Timing package

- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/components/close-button.js
- packages/wonder-blocks-modal/components/close-button.test.js
- packages/wonder-blocks-modal/components/modal-backdrop.js
- packages/wonder-blocks-modal/components/modal-dialog.js
- packages/wonder-blocks-modal/components/modal-header.js
- packages/wonder-blocks-modal/components/modal-header.test.js
- packages/wonder-blocks-modal/components/modal-launcher.js
- packages/wonder-blocks-modal/components/modal-launcher.test.js
- packages/wonder-blocks-modal/components/modal-panel.js
- packages/wonder-blocks-modal/components/modal-panel.test.js
- packages/wonder-blocks-modal/components/one-pane-dialog/one-pane-dialog.js
- packages/wonder-blocks-modal/components/one-pane-dialog/one-pane-dialog.md
- packages/wonder-blocks-modal/components/one-pane-dialog/one-pane-dialog.test.js
- packages/wonder-blocks-modal/docs.md
- packages/wonder-blocks-modal/generated-snapshot.test.js
Adds the missing `testId` prop to the modal package.
- **ModalLauncher**: Added `testId` prop to be passed down to the `ModalBackdrop` component.
- **OnePaneDialog**: Added `testId` prop to be passed down to the `ModalDialog` component.
- **ModalHeader**: Added `testId` prop to be used inside the main wrapper. Also, used for both title and subtitle elements.
- **title**: For `<ModalHeader testId="some-id" />`, then title => e.g. `<h3 data-test-id="some-id-title" />`
- **subtitle**: For `<ModalHeader testId="some-id" />`, then subtitle => e.g. `<h4 data-test-id="some-id-subtitle" />`
- **ModalPanel**: Added `testId` prop to be used inside the main wrapper. e.g `<div class="modal-panel" data-test-id"some-id-ModalPanel" />`
- CloseButton: Added `testId` prop combining the `testId` defined in …
> [feature:modal] WB-636 Add testId prop to modal elements

- packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-core/generated-snapshot.test.js
- packages/wonder-blocks-core/util/add-style.md
- styleguide.config.js
- utils/gen-snapshot-tests.js
Adds documentation and examples to the `addStyle` util.
- Added docs and examples to `addStyle`.
- Fixed `gen-snapshot-tests.js` script to allow adding flow typed functions to the examples.
e.g. `export default function addStyle<T: React.AbstractComponent<*> | string>(`
1. Open https://deploy-preview-463--wonder-blocks.netlify.com/#!/AddStyle
2. Check the documentation and examples are clear and concise.
> [docs:core] WB-394: Add docs for addStyle

- .flowconfig
- packages/wonder-blocks-timing/components/with-action-scheduler.js
- packages/wonder-blocks-timing/util/types.flowtest.js
- packages/wonder-blocks-timing/util/types.js
This fixes an issue with the type expected by `withActionScheduler` and also adds some flow-only test cases that setup the expectations we have around how the types should work.
> Fix type issue with withActionScheduler

- packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
Currently, when using a small resolution (mobile) and the button is hovered/focused, the underline border is taking the whole container width, instead of just using the text width. This PR fixes that behavior.
1. Using a small resolution, open https://deploy-preview-465--wonder-blocks.netlify.com/#!/OnePaneDialog/3
2. Check the tertiary button looks as expected.
> [fix:button] WB-563 Fix tertiary button hover state

- packages/wonder-blocks-dropdown/components/dropdown.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/single-select.js
Added flow type support for falsy elements in Dropdowns, SingleSelects and MultiSelects. 
Flow will now recognize children such as `{false && <OptionItem />}`
> WB-641: Add flow type support for falsy elements in Dropdowns

- .flowconfig
- flow-typed/npm/enzyme_v3.x.x.js
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-core/util/add-style.js
- packages/wonder-blocks-core/util/types.js
- packages/wonder-blocks-dropdown/components/dropdown-core.js
- packages/wonder-blocks-dropdown/components/dropdown.test.js
- packages/wonder-blocks-modal/util/maybe-get-portal-mounted-modal-host-element.test.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.test.js
- packages/wonder-blocks-tooltip/util/ref-tracker.js
- packages/wonder-blocks-tooltip/util/types.js
- utils/testing/mount.js
I thought I'd try out some of the lint rules that flow has to offer.  This commit originally also included sketchy null checks as well but it turns out those are easier to fix if you have null coalescing which was easy to add but fixing them was still a bit of a pain so I scaled this back to just fix up deprecated types, namely `*`, `$Supertype`, and `$Subtype`.  I also decided to add flow types for enzyme which brought out batch coverage up from about 85% to 95%.
> lint against deprecated flow types

- README.md
Updated README.md to show a `getting started` section that includes short installation instructions and adds the URL to see the docs locally. Also, added a link to the confluence page for a more detailed explanation on the process.
Output: https://github.com/Khan/wonder-blocks/blob/internal/readme-docs/README.md
> WB-98: docs(): Update README.md

- .circleci/config.yml
- .flowconfig-ci
- .prettierignore
- package.json
Flow is slow running locally because it was only using a single worker.  This fixes that.
The reason why we only use one worker when running on CI to avoid situations where flow has trouble launching.  This can happen on CI because the free version of CircleCI using single core machines.  See https://circleci.com/gh/Khan/wonder-blocks/2076?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link for an example of the error.
> Create .flowconfig-ci with server.max_workers=1 for CI operation only

- packages/wonder-blocks-modal/components/modal-launcher.js
- packages/wonder-blocks-modal/components/modal-launcher.test.js
This change was motivated by https://phabricator.khanacademy.org/D57666.  We can use flow to enforce the prop constraints we were previously throw exceptions for.  This change though won't fix the issue fixed in D57666 so we should look at updating all uses of -v1 modals to -v2 modals.
While making this change I found myself a little confused about the various usages of ModalLauncher.  I think we should consider splitting ModalLauncher into two components:
- one that requires children and is always uncontrolled
- one that doesn't use children and is always controlled
I think that should cover all of our use cases and be less confusing both in terms of implementation but also in terms of use.
> Use flow to enforce invalid props in ModalLauncher

- packages/wonder-blocks-layout/docs.md
> General grammar and typo fixes in the layouts documentation

- .github/workflows/auto-approve.yml
I was reading about how people manage dependabot with a Code Owners file and it seems like some recommend auto-approving them with a Github Action, so I thought I'd give it a try! Let's see what happens.
> Github Action to Auto-approve Dependabot diffs

- CODEOWNERS
Hopefully this will make it so that the Gihub Actions bot can auto-approve the dependabot PRs now.
Test plan:
Will land and see if the dependabot PRs start getting auto-landed!
> Add github-actions to CODEOWNERS

- CODEOWNERS
Turns out bots have a hidden "[bot]" at the end of their name so the CODEOWNERS wasn't matching! I think this will work now?
> Change github-actions name to match actual name

- packages/wonder-blocks-dropdown/components/dropdown-core.js
- packages/wonder-blocks-popover/__mocks__/popper.js.js
- packages/wonder-blocks-tooltip/components/tooltip-popper.js
This PR adds a manual mock of Popper.js inside the `wonder-blocks-popover` package to avoid throwing the following message when adding tests on webapp:
```
(node:2048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'nodeName' of undefined
```
Also, we replaced `$FlowIgnoreMe` to `$FlowIgnore` to have consistent flow comments across the codebase.
`yarn test`
`yarn flow`
> patch(dropdown, popover, tooltip): WB-651 Add mocked version of Popper.js

- packages/wonder-blocks-tooltip/components/tooltip.md
The first example for Tooltip didn't have an import. It's maybe obvious for folks who've used WB for a while, but I had to hunt a bit for the right syntax.  So this PR adds the import.
*Before*
> Add import to Tooltip example

- packages/wonder-blocks-modal/components/modal-header.js
- packages/wonder-blocks-modal/components/one-pane-dialog/one-pane-dialog.js
- packages/wonder-blocks-popover/components/popover-content.js
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
Summary:
Flow gets confused when an optional prop exists in multiple variants of a
disjoint union.  This diff ensures that optional props only exist in a single
variant and that they are not optional in that variant.  To keep flow happy
we need to provide default values for these props when destructuring.
Test Plan:
- load localhost:6060
- see that OnePaneDialog is working correctly
I also, tested the theory behind this change in the flow playground to make sure it would fix the issue we're seeing in webapp.
https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDciiOAnukqgAwk1SwAdqAC8oAN4AfRIoC+PPoOEAxWLFkLloUADozY1BMkAaRMch6AXKBI4sySQHNbajQKGgAEJEWAZKdqbm4lK2xgBGIc6SAK6ocZRYPuq8-sIACozoZHIWVqCKoLr6FcFYGjTQpGRVtaCUAB44lJIAJmRUtDgmFpiS3TgAPAWwRQB8ChHsvRkAFACUC8bGN …
> Fix disjoint union prop types

- packages/wonder-blocks-button/.npmignore
- packages/wonder-blocks-core/.npmignore
- packages/wonder-blocks-icon-button/.npmignore
- packages/wonder-blocks-link/.npmignore
- packages/wonder-blocks-tooltip/.npmignore
- packages/wonder-blocks-tooltip/generated-snapshot.test.js
- packages/wonder-blocks-typography/.npmignore
They aren't useful anymore and `.npmignore` is generally a dangerous file to have around:
https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d
There's also a snapshot file change here. I think it's down to the lint rules ordering imports.
> Delete .npmignore files

- config/jest/test.config.js
While I wasn't able to reproduce the issue, I can definitely see why @jandrade was getting the following error:
```
Configuration error:
Could not locate module @khanacademy/eslint-config/.prettierrc.js mapped as:
/Users/juanandrade/khan/wonder-blocks/node_modules/@khanacademy/eslint-config/.prettierrc.js/index.js.
Please check your configuration for these entries:
{
"moduleNameMapper": {
"/^@khanacademy\/(.*)$/": "/Users/juanandrade/khan/wonder-blocks/node_modules/@khanacademy/$1/index.js"
},
"resolver": null
}
```
This diff restricts the modules affected by `moduleNameMapper` to `wonder-block-*` modules only.
Test Plan: `yarn test`
> fix issue with jest config and non-wonder-blocks @khanacademy modules

- .vscode/settings.json
- packages/wonder-blocks-data/components/data.js
- packages/wonder-blocks-data/components/data.md
- packages/wonder-blocks-data/components/data.test.js
- packages/wonder-blocks-data/generated-snapshot.test.js
- packages/wonder-blocks-data/index.js
- packages/wonder-blocks-data/index.test.js
- packages/wonder-blocks-data/util/request-fulfillment.test.js
- packages/wonder-blocks-data/util/request-handler.js
- packages/wonder-blocks-data/util/request-handler.test.js
- packages/wonder-blocks-data/util/request-tracking.js
- packages/wonder-blocks-data/util/request-tracking.test.js
- packages/wonder-blocks-data/util/response-cache.js
- packages/wonder-blocks-data/util/response-cache.test.js
- packages/wonder-blocks-data/util/types.js
- yarn.lock
Here we change `invalidateCache` to `refreshCache` and its default implementation. We also change how it is called.
1. We now pass the current `CachedEntry` so that refresh decisions can be made based on the current value in the cache.
2. The default implementation now returns that the cache should be refreshed if the cached entry is an error.
This has the effect of causing the client-side to re-request data that error'd when requested server-side. This is great in that we rehydrate with the error that the SSR rendered, but a new request to update the
data is made.
We also update the `clone` call on our `ResponseCache` class to be `cloneCachedData` to make it clearer what we're cloning, and the exports have been updated so that to the outside world, the cache object type is opaque.
> [WB-801] Make sure errors invalidate cache

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/dropdown-opener.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- Added a custom opener to the `ActionMenu` component.
- Created `DropdownOpener` to be reused across the multiple components.
- Added new example.
**Note:** This is the first part of this work:
1. Add custom opener to ActionMenu **[current]**.
2. Add custom opener to SingleSelect.
3. Add custom opener to MultiSelect.
> WB-660.1: Add custom opener to ActionMenu

- packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/action-menu.md
- packages/wonder-blocks-dropdown/components/action-menu.test.js
- packages/wonder-blocks-dropdown/components/dropdown-opener.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/multi-select.test.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-dropdown/components/single-select.md
- packages/wonder-blocks-dropdown/components/single-select.test.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- yarn.lock
- Fixed `testId` avoid using it from the parent component (`ActionMenu, SingleSelect and MultiSelect`).
- Added a new `text` argument as part of the `opener` prop (`ActionMenu, SingleSelect and MultiSelect`). This will allow people to optionally re-use the dropdown's current label in case they need it.
```
<MultiSelect
opener={(eventState) => (
<LabelLarge styles={[eventState.hovered && styles.customHoveredStyles]}>
Hard-coded label for opener
</LabelLarge>
)}
/>
```
```
<MultiSelect
opener={(eventState, text) => (
<LabelLarge styles={[eventState.hovered && styles.customHoveredStyles]}>
{text}
</LabelLarge>
)}
/>
```
> WB-660.4: Add text argument to the new opener prop

- packages/wonder-blocks-data/components/data.js
Before this change, if the props changed, it was properly detected but the state was updated from the incorrect props state and so things did not do the right thing; they were always a step behind and it caused some interesting issues.
Now, state is properly based off the props being used.
I haven't updated any tests for this yet as I am still thinking of the nicest way to cleanly test this. I may postpone that for a later diff while I mull it over.
> Make sure state is built from the right props

- config/jest/test.config.js
- packages/wonder-blocks-dropdown/components/dropdown-core-virtualized.js
- packages/wonder-blocks-dropdown/components/dropdown-core.js
- packages/wonder-blocks-timing/components/with-action-scheduler.js
- packages/wonder-blocks-timing/components/with-action-scheduler.md
- packages/wonder-blocks-timing/components/with-action-scheduler.test.js
- packages/wonder-blocks-timing/docs.md
- packages/wonder-blocks-timing/index.js
- packages/wonder-blocks-timing/util/types.flowtest.js
- packages/wonder-blocks-timing/util/types.js
Using this pattern adds support for default props and ref forwarding.  This will allow us to compose `withActionScheduler` with the HOCs defined in webapp.  It also means that all of our HOCs from wonder-blocks and webapp will have a consistent API as well as consistent behavior.
> WB-835: Update withActionScheduler to match webapp's HOC pattern

- package.json
- packages/wonder-blocks-button/components/button.js
We could make the check even faster if we skipped the build step, but then we'd have to modify the module mapper settings in the jest config.  TBH, I'm not sure how much value we get from testing the built versions of the packages.
Test Plan:
- `yarn test:fast`, see that only the commonjs modules are built and that only a subset of the tests run
- `git commit -a -m ...`, see that the same output as for `yarn test:fast`
> run only related tests in the pre-commit hook

- README.md
Some of our tooling now requires Node v10 as a minimum.
> Update prereqs to Node v10

- .github/workflows/node-ci.yml
I'm not sure why the previous check I had for `github.actor != 'dependabot-preview'` wasn't working.  It's possible that the actor is actually something different since `dependabot-preview` is an app not a user.
This solution instead checks the name of the PR and doesn't run the `chromatic` job if the ref for the PR contains `dependabot/`.
It took me a long time to figure out the syntax.  It turns out you have to wrap things in double quotes that have special characters like `!`.  I found the answer on https://github.community/t5/GitHub-Actions/Expression-syntax-for-not-startswith/td-p/39571. 
Test Plan: merge and wait for the next dependabot PR
> Try again to prevent dependabot PRs from running chromatic

- packages/wonder-blocks-data/docs.md
- packages/wonder-blocks-data/index.js
- packages/wonder-blocks-data/index.test.js
- packages/wonder-blocks-data/util/response-cache.js
- packages/wonder-blocks-data/util/response-cache.test.js
- packages/wonder-blocks-data/util/types.js
See WB-832 and WB-833
This is the main architectural change in how caching works. Here we weave the custom cache that can be optionally provided by handler into our `ResponseCache` behavior.
NOTE: This code and especially the tests will be nicer once the framework cache has a separate implementation.
There are four places:
1. `getEntry`
- If server-side, we ignore the custom cache
- If client-side,
- We defer to any value in the custom cache
- If custom cache is a miss, but framework cache is not, we add the framework cache entry to the custom cache, delete the framework cache version, and then return that value
2. `cacheError` and `cacheData`
- These both call the same function which, when client-side, will write to the custom cache rather than the framework cache
3. `remove`
- A new …
> Part 3: Implement deferring to custom cache

- packages/wonder-blocks-data/components/data.js
- packages/wonder-blocks-data/components/intercept-cache.js
- packages/wonder-blocks-data/components/intercept-data.js
- packages/wonder-blocks-data/components/internal-data.js
- packages/wonder-blocks-data/index.js
- packages/wonder-blocks-data/util/memory-cache.js
- packages/wonder-blocks-data/util/memory-cache.test.js
- packages/wonder-blocks-data/util/request-fulfillment.js
- packages/wonder-blocks-data/util/request-handler.js
- packages/wonder-blocks-data/util/response-cache.js
- packages/wonder-blocks-data/util/response-cache.test.js
- packages/wonder-blocks-data/util/types.js
For WB-833
This adds a new `MemoryCache` class that implements the `ICache` interface. This is not for use outside of Wonder Blocks Data. It implements the internal cache used for SSR and hydration. This simplifies the `ResponseCache` code a bit, identifies some improvements to flow types, and makes things overall easier to reason about.
The next diffs will add actual implementations for export that code can then use to modify caching for their data handlers.
> Part 4: Refactor internal cache to use new MemoryCache class

- packages/wonder-blocks-data/components/data.md
- packages/wonder-blocks-data/generated-snapshot.test.js
- packages/wonder-blocks-data/index.js
- packages/wonder-blocks-data/index.test.js
- packages/wonder-blocks-data/util/memory-cache.js
- packages/wonder-blocks-data/util/no-cache.js
- packages/wonder-blocks-data/util/no-cache.test.js
- packages/wonder-blocks-data/util/request-handler.md
- styleguide.config.js
For WB-833.
The first of our exported cache strategies; the `NoCache`. A simple example where we can configure a handler to never cache data. This allows us to use the framework cache to support SSR but then once hydrated, never cache, thus avoiding using up memory and just have the client always request new data after the initial hydration.
> Part 5: The NoCache cache

- netlify.toml
I found this recipe on https://community.netlify.com/t/common-issue-how-can-i-optimize-my-netlify-build-time/3907/10.
After this is landed we'll have to re-enable builds on PRs to check that it's working as expected.
> Configure netlify to ignore dependabot PRs

- netlify.toml
- netlify_check.sh
The `ignore` directive in netlify.toml files only needs the exit code.  If any text is returned it causes the github check to fail.  We'd like it not to build but the github check should still succeed.  Hopefully this will fix it.  
Netlify docs: https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds.
I tested this by changing the author name to my own and checking the exit code and then switch it back to dependabot and say that is was `1` when the author matched the author of the most recent commit and `0` when it did not.
> Fix netlify.toml

- netlify_check.sh
From the docs:
> An exit-code of 1 indicates the contents have changed, so if your command returns that code the build process will continue per usual. An exit-code of 0 indicates that the build should return early.
> Fix netlify_check.sh to do the right thing.

- config/jest/log-on-fail-reporter.js
- packages/wonder-blocks-clickable/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-clickable/components/clickable.md
- packages/wonder-blocks-clickable/components/clickable.stories.js
- packages/wonder-blocks-clickable/components/clickable.test.js
- packages/wonder-blocks-clickable/generated-snapshot.test.js
Fixed an issue that prevented `Clickable` to work with keyboard navigation.
The specific case happens when we set `href` and `skipClientNav` and try to open a link using the keyboard. The issue was that `href` wasn't passed down to `ClickableBehavior` and this caused the component to avoid navigating because `href` was undefined for that case.
To fix this, we are adding `href` to the internal `ClickableBehavior` instance.
1. Open https://5e1bf4b385e3fb0020b7073c-cwqfgsekob.chromatic.com/?path=/story/clickable--keyboard-navigation
2. Using the keyboard, hover on the clickable link, then press `Enter` and verify the browser opens the URL set in `href` (https://khanacademy.org in this case).
> fix(clickable) WB-860:  href prop not working with keyboard navigation

- packages/wonder-blocks-data/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/generated-snapshot.test.js
- packages/wonder-blocks-link/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-link/components/link.js
- packages/wonder-blocks-link/components/link.md
- packages/wonder-blocks-link/generated-snapshot.test.js
- Adds the `id` prop to the `<Link />` component.
- Fixes some remaining changes from the `prettier` upgrade.
Check that the `Link` snapshot includes the `id` when set in the example.
> feat(link) WB-859: Add id to Link

- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-button/components/button.test.js
Most of our components support an optional id, but it was missing on Button.  This diff fixes that.
Issue: none
Test plan: yarn test
> Add 'id' prop to Button

- .eslintrc.js
- packages/wonder-blocks-modal/components/scroll-disabler.js
When I was updating webapp to use 16.9, there was a warning about using `componentWillMount` that was causing a number of tests to fail.  This PR moves this logic into the `ScrollDisabler`'s constructor.  I've also added a new lint rule: `no-deprecated` which flags deprecated methods based on the current version of react we're using.
Test Plan: 
- yarn start
- open http://localhost:6060/#section-modal
- click on one of the buttons to open a modal
- try scroll with the modal open, see that the page doesn't scroll
- close the modal, see that the page doesn't jump
> Remove unsafe componentWillMount from ScrollDisabler

- packages/wonder-blocks-dropdown/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/action-menu.md
Unlike Button and Link it has href but not a target prop.
Adding target prop enables to open links in a separate tab.
Issue: https://khanacademy.atlassian.net/browse/WB-861
Test Plan:
- Run `yarn test`
> Add target to ActionItem

- packages/wonder-blocks-dropdown/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/components/dropdown-core-virtualized.js
- packages/wonder-blocks-dropdown/components/multi-select.md
- packages/wonder-blocks-dropdown/components/multi-select.stories.js
Fixes an issue introduced in `DropdownVirtualizedCore`. We have removed the maximum container width, allowing the dropdown container to take the width from its parent container.
1. Open https://5e1bf4b385e3fb0020b7073c-eneopdgtcf.chromatic.com/?path=/story/multiselect--custom-styles
2. Verify that when the dropdown is opened, the options container takes the parent's width.
> fix(dropdown) WB-858: Fix dropdown container width

- packages/wonder-blocks-modal/components/scroll-disabler.js
Adds a validation to verify that `window` exists and avoid any issues trying to run the `Modal` component on a SSR environment.
> WB-610: Wonder Blocks Modal package assumes a DOM

- packages/wonder-blocks-popover/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-popover/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-popover/components/close-button.js
- packages/wonder-blocks-popover/components/popover-content-core.js
- packages/wonder-blocks-popover/components/popover-content-core.md
The close button within the `PopoverContentCore` component accepts a `testId` property but did not propagate this to the close button for the popover. This fixes that and makes writing e2e tests easier where the popover needs to be dismissed and cannot click the action item available.
In scenarios where the `testId` is not provided, we can simply set the testId of the closeButton to "popover-close-btn" as a default value.
Issue: https://khanacademy.atlassian.net/browse/WB-975
- Add a testId to the `PopoverContentCore` component and ensure the `closeButtonVisible` prop is set to true.
- Inspect the close button and ensure that the `data-test-id` attribute of the close button is the provided id appended with "-close-btn".
> WB-975: Propagate testId to CloseButton within PopoverContentCore

- packages/wonder-blocks-core/util/add-style.js
- packages/wonder-blocks-core/util/add-styles.flowtest.js
If you're doing 'const StyledList = addStyle("ul", styles.list)' and there's
no custom style for an invidual 'StyledList' on the page then you shouldn't
be required to provide a 'style' prop to 'StyledList'.  This usage is more like
how the styled-components library functions.
Issue: none
- yarn test
> Make the 'style' prop that addStyle adds optional

- packages/wonder-blocks-breadcrumbs/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-link/__tests__/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-link/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-link/components/__tests__/link.flowtest.js
- packages/wonder-blocks-link/components/__tests__/link.test.js
- packages/wonder-blocks-link/components/link-core.js
- packages/wonder-blocks-link/components/link.js
- packages/wonder-blocks-toolbar/__tests__/__snapshots__/generated-snapshot.test.js.snap
This builds on the initial work from #1047 to add the same props to Link.  I didn't both creating navigation examples like I did for Button since the docs for Button are quite a bit more extensive than they are for Link.  The props show up in the docs and that should be sufficient.
Issue: WEB-2990
- yarn test
> WEB-2990.2: Add beforeNav and safeWithNav props to Link

- packages/wonder-blocks-button/components/__tests__/button.flowtest.js
- packages/wonder-blocks-button/components/__tests__/button.test.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-core/components/__tests__/clickable-behavior.test.js
- packages/wonder-blocks-core/components/clickable-behavior.js
I didn't put the 'waiting' logic for the server-side nav case in the right location.  This PR fixes that.
One of the things from the ADR was wanted to make sure people are using 'beforeNav' and 'safeWithNav' only when 'href' is set.  This PR also fixes that by changing the Button props to be a disjoint union.
Issue: WEB-2990
- yarn jest
> Fix issues from #1047

- packages/wonder-blocks-core/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-form/__tests__/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-form/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/components/checkbox-core.js
- packages/wonder-blocks-form/components/radio-core.js
- packages/wonder-blocks-icon-button/__tests__/__snapshots__/custom-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-modal/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-popover/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-toolbar/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/__tests__/__snapshots__/generated-snapshot.test.js.snap
React (dev-only build I believe) complains about setting boolean
attributes that don't exist on HTML elements.  This PR fixes the
issue.  While this should be an issue in prod, it will lead to
noisy console logs during dev so we should fix it.
Issue: none
- yarn start
- load localhost:6060
- see that there are no React errors complaining about non-existent boolean attributes
> Don't set boolean attributes that don't exist on HTML elements

- packages/wonder-blocks-core/components/clickable-behavior.js
- styleguide.config.js
- styleguide.setup.js
Even though we're using async/await in some places in webapp, the code we generator
here doesn't see webapp's version of regeneratorRuntime.  This PR changes the use
of async/await in clickable-behavior.js to Promises instead.
This PR also removes the changes I made to the styleguidist config to drop the import
of @babel/polyfill which was providing regeneratorRuntime locally.
Issue: WEB-2990
- yarn start
- load localhost:6060 and see that it loads fine without regeneratorRuntime errors
- yarn test
> WEB-2990.?: Use promises instead of async/await

- packages/wonder-blocks-button/components/__tests__/button.test.js
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.js
We were showing the spinner but not hiding the text or changing
the background color to grey.  This PR fixes that by setting the
'spinner' prop on ButtonCore to 'true' if 'waiting' is 'true'.
Issue: none
- yarn start
- load localhost:6060
- click on the "Aysnc action, client-side nav" button
- see that the button looks 'spinner={true}' is set
> Fix the waiting state

- packages/wonder-blocks-button/components/__tests__/button.flowtest.js
- packages/wonder-blocks-button/components/button.js
After deploying to webapp, a bunch of flow errors were triggered because the flow types for Button's props are ambiguous when only 'href' is being passed.
The error only triggers when passing the result of a function call instead of just passing a string.  I've added a flow test that reproduces the issue.
This PR fixes it by splitting up the possible cases to be more explicit to avoid ambiguous cases.
Issue: none
- yarn flow
> Avoid ambiguous cases in Button's prop types

- packages/wonder-blocks-clickable/components/__tests__/clickable.test.js
- packages/wonder-blocks-clickable/components/clickable.js
These were recently added to Button and Link.  This PR adds them to Clickable as well so that we can use them with bespoke buttons/links in webapp with their own custom styling.
Issue: None
- yarn jest packages/wonder-blocks-clickable/components/__tests__/clickable.test.js
> Add safeWithNav and beforeNav props to Clickable

- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-clickable/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-link/components/link.js
In some places we pass "rel" to links in webapp.  I've added this optional prop
to Button, Link, and Clickable as those are most likely to need that prop.  I've
also added "target", and all of our ARIA props to Clickable.
Issue: none
- yarn test
Reivewers: #fe-infra
> Add missing props to a few components

- packages/wonder-blocks-clickable/package.json
- packages/wonder-blocks-color/package.json
- packages/wonder-blocks-icon/package.json
- packages/wonder-blocks-layout/package.json
- packages/wonder-blocks-modal/package.json
- packages/wonder-blocks-spacing/package.json
- packages/wonder-blocks-typography/package.json
- yarn.lock
lerna looks at changes to local packages that appear in both dependencies and devDependencies when deciding which modules' versions to bump.  Because of how yarn workspaces works and how we've configured jest and flow all of our dev-tooling just works without listing local modules as devDependencies in local packages.  By removing them from devDependencies we avoid unnecessary version bumping from lerna.
Issue: none
- yarn test
- yarn start
- yarn start:storybook
> Remove unnecessary dev dependencies

- packages/wonder-blocks-button/components/__tests__/button.test.js
- packages/wonder-blocks-clickable/components/__tests__/clickable.test.js
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-link/components/__tests__/link.test.js
- wallaby.js
SearchBox in webapp uses onKeyDown to customize keyboard navigation of that component.  In order to switch from <a> to <Clickable> we need to handle these events.  In particular `handleKeyDown` is passed down to `SearchResultsPopup` which passes it down to other components which eventually pass it to `<a>`'s `onKeyDown` prop.
This PR also simplifies some of our existing tests for Link and Button.
Issue: none
- yarn test
> Add onKeyDown/onKeyUp to Clickable

- packages/wonder-blocks-link/components/__tests__/link.test.js
- packages/wonder-blocks-link/components/link.js
In #1069 I added these props to Clickable to handle some custom keyboard behavior in webapp's search box/page.  I thought Clickable would be enough, but there are some <a> tags where we want the thing to look like an actual link.
Issue: none
- yarn test
> Add onKeyDown/onKeyUp to Link as well

- packages/wonder-blocks-core/util/__tests__/add-style.test.js
- packages/wonder-blocks-core/util/add-style.js
I'm doing some work on the Google search results component in webapp and we're doing some pretty hacky stuff (replacing Google <a> tags with our <Link> component).  This is so that we can track conversions without having to use /bigbingo_redirect.  In order to do this properly though Link needs to support the "className" prop.  This PR updates 'addStyle' to handle className properly and since the underlying components Link renders are wrapped in 'addStyle' it too will handle className properly.
Issue: none
- yarn test
> Add support for className to addStyle

- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-dropdown/components/action-menu.js
- packages/wonder-blocks-dropdown/components/dropdown-core.js
- packages/wonder-blocks-dropdown/components/multi-select.js
- packages/wonder-blocks-dropdown/components/single-select.js
- packages/wonder-blocks-form/components/checkbox.js
- packages/wonder-blocks-form/components/choice-internal.js
- packages/wonder-blocks-form/components/radio.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-icon/components/icon.js
- packages/wonder-blocks-link/components/link.js
In #1072 I added support for 'className' to 'addStyle', but in order to use 'className' on components without flow complaining we also have to add it to the prop types.  For some of the components, the new prop needed to be piped through manually to a child component.  This PR doesn't add 'className' to all components though.  I've filed a followup task to complete this work: https://khanacademy.atlassian.net/browse/WB-1002.
Issue: none
- yarn start
- in one of the examples for Link, give one of the Links a className, see that it shows up in the inspector
- yarn flow
> Add 'className' prop type to commonly used components

- packages/wonder-blocks-button/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-button/components/__tests__/button.flowtest.js
- packages/wonder-blocks-button/components/__tests__/button.test.js
- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-button/components/button.md
- packages/wonder-blocks-core/components/clickable-behavior.js
In the process of adding beforeNav and safeWithNav props, I added a call to e.preventDefault() in response to click, keyboard, and touch events. This unfortunately cause forms with submit buttons to stop working.
To fix the issue, if we're handling an event from a `Button` with `type="submit"` we'll look for ancestor element that's a `<form>` and if we find one we'll dispatch a `submit` event to it.
Issue: WB-1004
- yarn test
- in styleguidist scroll to the "submit" button example
- click on "submit", see the alert message
- use the keyboard to nav to the "submit" button and press "enter", see the alert message, press "spacebar" and see the alert message
> WB-1004: Update Button to work with <form>s

- consistency-tests/__tests__/clickables.test.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-core/components/__tests__/clickable-behavior.test.js
- packages/wonder-blocks-core/components/clickable-behavior.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-link/components/link.js
- wallaby.js
clickable-behavior.js does a lot of custom handling when a user activates a link.  When implementing this custom handling we forgot to re-implement the default browser behavior of opening links with target="_blank" in a new tab.  This PR re-implements that browser behavior.
Issue: WB-1012
- yarn test
- edit one of the button examples in styleguidist to use target="_blank"
- click on it, see the link open in a new tab
> WB-1012: Open links in a new tab if target="_blank" is set

- .eslintrc.js
- package.json
- packages/wonder-blocks-button/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-button/components/button.md
- packages/wonder-blocks-clickable/components/__tests__/clickable-behavior.test.js
- packages/wonder-blocks-clickable/components/clickable-behavior.js
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-link/components/link.js
- yarn.lock
We were deferring the opening of a new URL in a new tab and this was trigger the action to be block by popup blockers built into some browsers (Safari and Firefox).  Deferring navigation is necessary if the navigation is happening in the same tab, but in this case it isn't.  The originating tab is staying around so it can do whatever it needs to do in 'safeWithNav' **while** the other tab opens.
NOTE: using "target='_blank'" with 'beforeNav' won't work and should be disallowed.
Issue: WB-1031
- run unit tests
- yarn start, open localhost:6060 in Safari or Firefox
- click on the new "Async action, open URL in new tab" button, see that it opens Google in a new tab
> WB-1031: don't defer opening of a URL in a new tab

- packages/wonder-blocks-button/components/button-core.js
- packages/wonder-blocks-button/components/button.js
- packages/wonder-blocks-clickable/components/clickable.js
- packages/wonder-blocks-clickable/util/get-clickable-behavior.js
- packages/wonder-blocks-dropdown/components/action-item.js
- packages/wonder-blocks-dropdown/components/action-menu-opener-core.js
- packages/wonder-blocks-dropdown/components/option-item.js
- packages/wonder-blocks-dropdown/components/select-opener.js
- packages/wonder-blocks-form/components/choice-internal.js
- packages/wonder-blocks-form/components/choice.js
- packages/wonder-blocks-icon-button/components/icon-button-core.js
- packages/wonder-blocks-icon-button/components/icon-button.js
- packages/wonder-blocks-link/components/link-core.js
- packages/wonder-blocks-link/components/link.js
So even though flow passed for Wonder Blocks, it didn't for webapp
consuming Wonder Blocks. These changes address the problematic types
I was able to identify.
Issue: FEI-3308
`yarn flow`
Update webapp and see where we're at.
> [FEI-3308].2 Tidy up some things that didn't work

- packages/wonder-blocks-button/components/button.stories.js
- packages/wonder-blocks-clickable/components/clickable-behavior.js
This was causing login forms to redirect to the LOHP without logging users in when using Firefox.  This issue arose because of a recent change in webapp to use forms properly.
In wonder-blocks we do a bunch of custom handling of events which involves calling 'preventDefault' on the user generated events.  Normally the browser would generate 'submit' events for us, but we have to do it ourselves in wonder-blocks because of this custom handling.
In webapp we need to call 'preventDefault' on the generate 'submit' event as part of the login flow.  Firefox does not support calling 'preventDefault' on non-cancelable events (which is what we were generating).  Safari and Chrome allow this but this may change in the future.
This PR fixes the issue by making the 'submit' event we generate …
> FEI-3316: Make dispatched 'submit' events cancelable

- packages/wonder-blocks-button/package.json
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-form/package.json
- packages/wonder-blocks-icon-button/package.json
- packages/wonder-blocks-link/package.json
A while back I extracted clickable related things from wonder-blocks-core into wonder-blocks-clickable but I forgot to update the package.json files for all of the other packages that were using those clickable related things.  This PR fixes that oversight.
Issue: none
- yarn run publish, see that it asks to bump the versions of all things using wonder-blocks-clickable
> Add missing deps to package.jsons

- packages/wonder-blocks-clickable/util/get-clickable-behavior.js
- packages/wonder-blocks-dropdown/components/dropdown-core.js
There were a couple of flow errors that appear in webapp in the node_modules after upgrading the wonder-blocks deps there.  I made the changes in this PR directly within node_modules are restarted to flow to make sure things were working as expected before backporting them here.
Issue: none
- yarn flow
> Fix flow errors that only manifest in webapp

- packages/wonder-blocks-data/components/data.js
Having this wrapper component was causing the children of InternalData to render
more than we wanted. I was unable to easily prevent it from doing so. So, instead
I removed the extra component and addressed the flow error with a suppression.
Issue: FEI-3327
1. `yarn build:all`
2. copy contents of packages/wonder-blocks-data to webapp's node_modules
3. Exit `javascript/data-access/with-content-data_test.js` in webapp to remove `forceStatic:true`
4. Run `yarn test javascript/data-access/with-content-data_test.js`
> Roll back flow-related change and comment why

- packages/wonder-blocks-button/src/components/button-core.js
- packages/wonder-blocks-button/src/components/button.js
- packages/wonder-blocks-clickable/src/components/clickable.js
- packages/wonder-blocks-dropdown/src/components/action-item.js
- packages/wonder-blocks-dropdown/src/components/action-menu-opener-core.js
- packages/wonder-blocks-dropdown/src/components/option-item.js
- packages/wonder-blocks-dropdown/src/components/select-opener.js
- packages/wonder-blocks-icon-button/src/components/icon-button-core.js
- packages/wonder-blocks-icon-button/src/components/icon-button.js
- packages/wonder-blocks-link/src/components/link-core.js
- packages/wonder-blocks-link/src/components/link.js
'prop-types' doesn't actually have a default export even though we're doing a default import.  webpack/babel make this work at run time.  TypeScript complains about this.  We could use TS' "allowSyntheticDefaultImports" setting to have it paper of this as well, but changing it a namespace import is easy and better reflect the true nature of this module.
Issue: none
- yarn flow
- yarn test
> Use namesapce imports for 'prop-types'

- packages/wonder-blocks-clickable/src/util/__tests__/is-client-side-url.js.test.js
- packages/wonder-blocks-clickable/src/util/is-client-side-url.js
In #1107 I updated the logic to decide when to render a <a> vs a <Link>.  I didn't realize we used mailto: and tel: in webapp.  This PR handles those cases in a more general way which should hopefully be more future proof.
Issue: none
- yarn jest packages/wonder-blocks-clickable/src/util/__tests__/is-client-side-url.js.test.js
> Handle mailto:, tel:, etc. hrefs in isClientSideUrl

- packages/wonder-blocks-clickable/src/util/__tests__/is-client-side-url.js.test.js
- packages/wonder-blocks-clickable/src/util/is-client-side-url.js
It's hard to guarantee that we're always passing an 'href' to 'Link' since Perseus is consuming Link in webapp in a way that isn't type safe.  Link will throw if it doesn't get a value for its 'to' property.  This diff avoids the situation by rendering an 'a' tag if 'href' is 'undefined' or 'null'.
Issue: none
- yarn jest packages/wonder-blocks-clickable/src/util/__tests__/is-client-side-url.js.test.js
> Don't render react-router Link if href is not a string

- packages/wonder-blocks-clickable/src/util/__tests__/is-client-side-url.js.test.js
- packages/wonder-blocks-clickable/src/util/is-client-side-url.js
React-router's Link component doesn't handle URLs with hashes correctly.  It will navigate to the correct pathname, but it doesn't scroll the page to the anchor with the given hash.  This PR makes all URLs with hashes use <a> tags.  If the URL is the same, it shouldn't trigger a full page reload.  In the future we can explore using react-router-hash-link, but it's not an official react-router component and it does some shenanigans with tabindex and focus which makes me cautious about adopting it because we don't want to introduce any new a11y issues.
Issue: none
- yarn jest packages/wonder-blocks-clickable/src/util/__tests__/is-client-side-url.js.test.js
> Make all URLs with an anchor non-client-side

- packages/wonder-blocks-dropdown/src/components/dropdown-core-virtualized.js
- packages/wonder-blocks-dropdown/src/components/single-select.js
Fixed a wrong width calculation with the `wonder-blocks-dropdown` list
which was causing a padding issue with the scrollbar (when the list was
large enough for the scrollbar to show).
Also fixed an issue with the single-select dropdown highlighting the incorrect
selected item when the dropdown was re-opened.
Issue: https://khanacademy.atlassian.net/browse/WB-1043
1. Open Styleguidist in browser (or React Storybook)
2. Go to: http://localhost:6060/#!/SingleSelect/17 (Storybook: http://localhost:59197/?path=/story/dropdown-multiselect--custom-styles-opened)
3. See that the dropdown scrollbar is perfectly aligned to the right edge (and also the selected item is correctly highlighted when dropdown is re-opened)
> WB-1043 - Fix Dropdown list scrollbar padding

- packages/wonder-blocks-clickable/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-clickable/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-clickable/src/components/clickable.js
- packages/wonder-blocks-clickable/src/components/clickable.md
- packages/wonder-blocks-clickable/src/components/clickable.stories.js
Added the `light` prop to the `Clickable` component in
`wonder-blocks-clickable` which will cause the default focus ring to be
white instead of blue when the `light` prop is set to true.
Issue: https://khanacademy.atlassian.net/browse/WB-1032
1. Open Styleguidist in browser
2. Go to: http://localhost:6060/#!/Clickable/3
3. Press 'tab' and see that the default focus ring is white when the
`light` prop is set to true.
> WB-1032 - Add `light` prop to `Clickable`

- packages/wonder-blocks-core/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/components/choice-internal.js
The Choice component already takes an optional `description` prop. When
provided, this renders as some smaller additional text below the main
label for the Choice. However, when using tab navigation and a screen
reader, only the main label was being read; the description was being
ignored.
This change wires up the inner `input` and the `description` elements so
that when a `description` is provided, the wrapping element gets an
auto-generated `id`, and the neighboring `input` gets
`aria-describedby=${descriptionId}`.
The result is something like this (in VoiceOver):
"Selected. Squirtle. Radio button (3 of 5). This is the description. You
are currently on a radio button..."
Whereas before this change, it would only read:
"Selected. Squirtle. Radio button (3 of 5). You are currently on a …
> Add `aria-describedby` to Choice inputs when a description is provided

- config/jest/test.config.js
- flow-typed/popper.js
- packages/wonder-blocks-core/src/util/get-element-intersection.js
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.js
- shared-unpackaged/__tests__/is-obscured.test.js
- shared-unpackaged/__tests__/visibility-modifier.test.js
- shared-unpackaged/get-axis-intersection.js
- shared-unpackaged/get-bounds.js
- shared-unpackaged/get-edges.js
- shared-unpackaged/get-intersection.js
- shared-unpackaged/is-obscured.js
- shared-unpackaged/types.js
- shared-unpackaged/visibility-modifier.js
Firstly, this adds flow types to popper.js. From that, I fixed an edge case
where the anchor element passed to `isObscured` could be just a reference
object - I don't know under what circumstances that occurs, though I had seen
an error along those lines in the past, so that should be fixed if it happens
anywhere.
Finally, and most importantly, I have fixed the issue that would cause the
popper (whether a tooltip, menu, dropdown, or popover) to flicker or not appear
when being scrolled near the top of the screen. It turns out this was because
the popper portion was coming back as something covering the anchor element.
To work around this, the popper (or child of a popper, as was the case with
the action menu) is set to not receive pointer events while the obscurity check
is completed. …
> [WB-498] Fix obscurity check for when popper can obscure the anchor

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/__tests__/index.test.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
- packages/wonder-blocks-form/src/index.js
- styleguide.config.js
Adding TextField to `wonder-blocks-form`. Implemented the basic look and
styles of the TextField from the [Figma](https://www.figma.com/file/VbVu3h2BpBhH80niq101MHHE/Wonder-Blocks-(Web)?node-id=495%3A2) concept. No props or any other
abilities have been implemented. Only its styles.
Issue: https://khanacademy.atlassian.net/browse/WB-1048
1. You can view the `TextField` section on Styleguidist, but since no error
and disabled props have been implemented yet, it is stuck on its default state.
2. I attached screenshots of the different styles above. Those screenshots are
the result of directly changing the style of the TextField using the 'default', 'disabled', and 'error' style.
> WB-1048 - Add TextField and the basic styles.

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
Integrated the States that TextField will use. This includes `enabled`,
`disabled`, `error`, and `focused`. Included the `focused` style for
when the user is focused on (editing) the TextField. I attached images
below of this new style.
Issue: https://khanacademy.atlassian.net/browse/WB-1051
1. View the generated Storybook link. Check the "Form / TextField" section.
2. You can also view Styleguidist under the "Form" section.
> WB-1051 - Add States to TextField

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
* Added the Props `id`, `type`, `value`, and `onChange` to the TextField.
* Included unit tests for all of these new props (Coverage displays 100% for the TextField component after the new unit tests).
* Added more examples to Styleguidist and React Storybook.
Issue: WB-1049
1. Open Styleguidist in the browser
2. Check the new examples under Form -> TextField
3. You can also view the new examples on React Storybook under Form -> Textfield
> WB-1049 - Add `id`, `type`, `value`, and `onChange` Props to TextField

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
Adding the `validation` and `onError` Props to TextField.
The `validation` prop will be called after every value change.
The `onError` prop will be called after every failed `validation`.
Added unit tests to test both new props.
Included examples on Styleguidist and React Storybook of `validation`
and `onError` working with the `password`, `email`, and `telephone`
type TextFields.
Issue: https://khanacademy.atlassian.net/browse/WB-1052
1. Open Styleguidist (or React Storybook)
2. Go to the TextField (under Form -> TextField)
3. See the given examples, specially the `password`, `email`, and
`telephone` TextField examples where `validation` and `onError` are at work.
---
> WB-1052 - Add `validation` and `onError` Props to TextField

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
Adding `onKeyDown`, `onFocus`, and `onBlur` props to TextField. Also
adding the ability to validate the initial value of TextField on
component mount and call `onValidation` as necessary.
Issue: https://khanacademy.atlassian.net/browse/WB-1053
1. Open Styleguidist (or React Storybook).
2. Go to the TextField under Form -> TextField.
3. Notice how pressing "Enter" while the TextField is focused will blur the TextField.
4. Also notice how the error message (on invalid input) will only show when the TextField is not focused (aka blurred).
---
> WB-1053 - Add `onKeyDown`, `onFocus`, and `onBlur` Props to TextField

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
Adding the `placeholder`, `required`, `light`, and `style` props to TextField.
When it comes to the `light` prop, I referenced off of the TextFields in Khan Academy's ["Donate"](https://www.khanacademy.org/donate) page (see images below). This was because the Figma did not specify any specific look for the `light` version of the TextField. Please let me know if there is another `light` style that is preferred.
Issue: https://khanacademy.atlassian.net/browse/WB-1056
1. Open Styleguidist (or React Storybook)
2. View TextField under Form -> TextField
3. See how all example TextFields have a unique placeholder text.
4. See the "Light" TextField example and how the "default" and "error" states fit the dark background.
5. See the "Custom Style" TextField and view the ease of passing custom …
> WB-1056 - Add `placeholder`, `required`, `light`, and `style` Props to TextField

- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/text-field.js
Adding `testId` and all ARIA related props (from `AriaProps` in `wonder-blocks-core`) to TextField.
Issue: https://khanacademy.atlassian.net/browse/WB-1057
1. Unit tests were added to test the addition of the `testId` and the `AriaProps`
> WB-1057 - Add `testId` and all ARIA Props to TextField

- packages/wonder-blocks-modal/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/src/components/modal-header.js
Fix the `ModalHeader`'s subtitle label that had the Typography style of
`LabelMedium` while the [design spec](https://www.figma.com/file/CRryTHqyr1l6aOOltD32KMh5/Modal-v2?node-id=412%3A195) requested `LabelSmall`.
Issue: https://khanacademy.atlassian.net/browse/WB-792
1. Open Styleguidist on the browser.
2. Go to the Modal section, under "Modals".
3. See the "OnePaneDialog with above container" example.
4. (Optional) You can also inspect-element and view that `LabelSmall` is used
---
> WB-792 - Fix Modal header subtitle out of sync with spec

- packages/wonder-blocks-modal/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/src/components/one-pane-dialog.js
Fixed `ModalHeader` not being passed a testId when used inside
`OnePaneDialog`. It was previously working in the case that `ModalHeader`
had a subtitle, but not in other cases. That was fixed.
Issue: https://khanacademy.atlassian.net/browse/WB-1070
1. You can view the code and see that testId is now being passed in all cases.
2. You can also open Styleguidist and check that testId is being passed
on all cases of `ModalHeader` when used in a `OnePaneDialog`. This
can be see through "inspect element".
---
> WB-1070 - Fix ModalHeader not setting testId properly (OnePanelDialog)

- packages/wonder-blocks-modal/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-modal/src/components/modal-header.js
Added right padding to the `title` of `ModalHeader` due to it
overlapping with the close button of the `OnePaneDialog`.
The Jira ticket specifically mentioned that the "Change Email Modal"
would show this issue on a mobile phone. The "Change Email Modal" it was
referring to was involving the `ModalHeader`. The screenshots below show
the before and after with the best attempt at recreating the issue in
Styleguidist.
Issue: https://khanacademy.atlassian.net/browse/WB-808
1. Open Styleguidist.
2. Go to the "Modal" section and choose any modal with a close button.
3. Edit the example and add a long title.
4. You can play around with the screen size and see how the title now
wraps before hitting the boundaries of the close button.
---
---
> WB-808 - Add right padding to ModalHeader title

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/checkbox-group.js
- packages/wonder-blocks-form/src/components/checkbox-group.md
Added the type `React.Element<Typography>` to `CheckboxGroup`'s `label` and
`description` props. This gives the user the option to pass in custom typography
components over a simple string.
Issue: https://khanacademy.atlassian.net/browse/WB-472
1. Open Styleguidist in Browser (view generated link)
2. Go to Form / CheckboxGroup
3. View the "Select all prime numbers" example. I added custom typography to the `label` and `description` props.
---
**\* The `label` and `description` are using custom typography elements**
\
> WB-472 - Add more flexibility to CheckboxGroup's label and description

- packages/wonder-blocks-form/src/components/__tests__/field-heading.test.js
- packages/wonder-blocks-form/src/components/field-heading.js
- packages/wonder-blocks-form/src/components/field-heading.stories.js
Added the `FieldHeading` private component under `wonder-blocks-form`.
This component is intended to provide a reusable handy label, description, and error element.
In the current situation, it is mainly intended to be used for `LabeledTextField`,
but later it may be easily used by other form fields.
Issue: https://khanacademy.atlassian.net/browse/WB-1063
I added a temporary example to React Storybook (see generated link below).
You can view it under Form / FieldHeading.
---
> WB-1063 - Implement FieldHeading Component

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/labeled-text-field.md
- packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
Added the `error` and `focused` state to the `LabeledTextField`. The `enabled` state was added in the form of a `disabled` prop where it is set to `false` by default.
Included unit tests to cover these new states and prop (except the `error` state because it will be covered once validation is added).
Issue: https://khanacademy.atlassian.net/browse/WB-1065
1. View the code to see the new states and prop
2. View Styleguidist and / or React Storybook examples under Form / LabeledTextField (see generated links)
---
> WB-1065 - Add States to LabeledTextField

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/labeled-text-field.md
- packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
- packages/wonder-blocks-form/src/components/text-field.js
Adding the first set of props to `LabeledTextField`.
This includes:
* id
* type
* label
* description
* initialValue
I added unit tests to cover these new props (current Coverage is 100%).
Issue: https://khanacademy.atlassian.net/browse/WB-1066
1. Open Styleguidist or React Storybook in browser (see generated links).
2. View the new props in action.
Note: I will be adding examples that use different TextField `type`s when I add validation
> WB-1066 - Add the first set of Props to LabeledTextField

- packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/labeled-text-field.md
- packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
Adding the final set of props to `LabeledTextField`.
This includes:
* placeholder
* light
* style
* testId
Included unit tests to verify these props work as expected (Coverage is 100%).
Issue: https://khanacademy.atlassian.net/browse/WB-1069
1. Open Styleguidist or React Storybook (See generated links).
2. View the new examples under Form / LabeledTextField.
---
> WB-1069 - Add the Final Set of Props to LabeledTextField

- packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
While building `LabeledTextField`, a few better-practice approaches came
up and were implemented into `LabeledTextField`'s code. These new
changes bring those approaches to `TextField`.
Three major changes occurred:
1. Updated the name of "handle" functions to follow the naming convention of
"handleEvent" instead of "handleOnEvent".
2. Updated the use of `setState(...)`'s callback to invoke prop methods
once the state has truly changed.
3. Renamed the `validation` and `onValidation` props to `validate` and
`onValidate`, respectively. This brings better clarity to the purpose
of the props.
Issue: https://khanacademy.atlassian.net/browse/WB-1071
1. You can view the code changes to see all the refactoring that was done.
2. You can check the Styleguidist and React Storybook examples to ensure …
> WB-1071 - Refactor TextField to Match New Changes in LabeledTextField

- packages/wonder-blocks-data/src/util/__tests__/request-fulfillment.test.js
- packages/wonder-blocks-data/src/util/__tests__/response-cache.test.js
- packages/wonder-blocks-data/src/util/request-handler.md
- packages/wonder-blocks-data/src/util/request-tracking.js
- packages/wonder-blocks-data/src/util/response-cache.js
- packages/wonder-blocks-data/src/util/types.js
This fixes our SSR support for non-hydrateable handlers to still support
request fulfillment during SSR.
Issue: FEI-3597
`yarn test`
I'll also be incorporating this version of WB Data into webapp to verify it
all works with the intended use-case; the new GqlQuery component.
> Properly support SSR request fulfillment without hydration support

- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/labeled-text-field.md
- packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
Changed `LabeledTextField` to behave as a controlled component. Now, the `value` and `onChange` props are **required**.
The `LabeledTextField` no longer has its `initialValue` prop, so the `npm` upgrade should be a major change.
**Note:** See issue for details on why `LabeledTextField` was changed to a controlled component.
Issue: https://khanacademy.atlassian.net/browse/WB-1083
1. View the examples on Styleguidist and React Storybook for `LabeledTextField` under "Form / LabeledTextField"
2. View the code examples to see the new API for the `LabeledTextField`.
> WB-1083 - Make LabeledTextField be a Controlled Component

- packages/wonder-blocks-form/src/components/__tests__/field-heading.test.js
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/field-heading.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/labeled-text-field.md
- packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
Currently, the style prop on `LabeledTextField` applies to the internal `TextField` element.
Due to problems with trying to set width, margin, padding, etc., to the entire `FieldHeading` container,
we would like to instead have the style prop apply to the FieldHeading container.
Issue: https://khanacademy.atlassian.net/browse/WB-1086
- Added unit tests to ensure `LabeledTextField`'s style is passed to FieldHeading
- Tested examples where setting flexGrow applies to the entire FieldHeading container
> WB-1086 - Make LabeledTextField's `style` prop Apply to FieldHeading

- packages/wonder-blocks-data/src/util/__tests__/response-cache.test.js
- packages/wonder-blocks-data/src/util/response-cache.js
Before this change, rendering data repeatedly in SSR with WB Data and a handler with a custom client-side cache would cause data to be erased from the hydration cache. This was not what we wanted. This simple bug fix addresses that bug.
Issue: FEI-3701
`yarn test`
I'll be putting this into webapp and it will be clear real quick from content and test prep pages if this is working or not.
> Fix SSR bug that would clear hydration cache incorrectly

- packages/wonder-blocks-data/src/__tests__/index.test.js
- packages/wonder-blocks-data/src/components/internal-data.js
- packages/wonder-blocks-data/src/index.js
- packages/wonder-blocks-data/src/util/__tests__/request-tracking.test.js
- packages/wonder-blocks-data/src/util/request-tracking.js
Now that WonderBlocks is responsible for cached queries, it is important that we support repeated render loops to get all the data requests. React Apollo's getDataFromTree handled this with its own render loop. Since we already have a
render loop in WebApp, we need to know when to stop looping in order to recreate similar behavior. We already do this for PageSettings by checking if anymore changes got made in the previous render and for loadables by checking for pending loadables. This adds the ability to check if we have pending tracked data requests.
Once this is in webapp, we can update the render loop to incorporate WB Data fulfillment rather that it only occurring once after a single tracking cycle.
Issue: FEI-3701
`yarn test`
Incorporate into webapp, modify rendering to include WB …
> Add ability to query if there are unfulfilled requests

- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/labeled-text-field.md
- packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
- packages/wonder-blocks-form/src/components/text-field.js
- packages/wonder-blocks-form/src/components/text-field.md
- packages/wonder-blocks-form/src/components/text-field.stories.js
Adding `autoComplete` and `readOnly` props to the `TextField` and
`LabeledTextField` components. These two props appear to be useful in
new scenarios that we are running into in Webapp in the `TextField` and
`LabeledTextField` migration.
Issue: https://khanacademy.atlassian.net/browse/WB-1088
- Added unit tests to ensure the new props are in `<input/>`.
- Added examples to React Storybook and Styleguidist.
> WB-1088 - Add `autocomplete` and `readonly` Props to TextField and LabeledTextField

- packages/wonder-blocks-modal/src/components/__tests__/one-pane-dialog.test.js
- packages/wonder-blocks-modal/src/components/modal-dialog.js
- packages/wonder-blocks-modal/src/components/one-pane-dialog.js
Alert dialog is similar to dialog, but it cues the screen reader techologoy to announce the alert message when the modal is opened
For more context: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role
Issue: WB-1089
`yarn test`
> Allow setting a role of alertdialog for ModalDialog and OnePaneDialog

- jest.config.js
- wallaby.js
We'd like to use the new "exclusive test run" feature.  The new version of wallaby didn't understand our current config.  I've updated it to auto-detect the config, but to do that jest.config.js needs to live in the root of the repo.  I've added a jest.config.js which re-exports config/jest/test.config.js.
> Fix wallaby config

- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
- packages/wonder-blocks-dropdown/src/components/action-menu.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/multi-select.js
- packages/wonder-blocks-dropdown/src/components/select-opener.js
- packages/wonder-blocks-dropdown/src/components/single-select.js
The focus events that we have for keyboard users are also important for screen readers - but screen readers generate click events that cannot be differentiated from regular click events. For that reason I removed all of the keyboard specific code and merged the click interface with the keyboard interface to the bet of my ability.
This is so that mobile screen readers can access the dropdowns. Without this change, focus is not shifted into the menu when it is opened with a screen reader, and screen reader users cannot interact with the menu.
It also greatly improves screen reader access on web. Currently dropdowns can be only accessed if the user knows to switch to the keyboard controls (enter/arrow) instead of using the screen reader controls (ie VO + enter / VO + arrow keys) which isn't …
> Remove keyboard tracking from dropdown-core so that menus can be accessed with a screen reader

- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core-virtualized.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/single-select.js
If you have a select list with more than 9 items, they won't
all fit in view.  If you have the 10th or later item selected,
upon open that item should not only be selected, but visible
too.  To accomidate this, I updated the code so that
initialFocusedIndex not only focuses the item, but scrolls
it into view.  This brought to light a few bugs that were
fixed along the way.
Issue: https://khanacademy.atlassian.net/browse/WB-1091
https://khanacademy.atlassian.net/browse/CLASS-7007
Verify that all unit tests work correctly.
In the Wonder Blocks documentation,
"Single select with search filter and custom styles"
example:
* Open the drop down
* Select an item that is initially out of view
* Re-open drop down
* Verify that the item visible
Change the example so no filter is available and
rerun …
> Changed initialFocusedIndex on drop downs to scroll into view

- .flowconfig
Without this people would have build packages first.  Also, the build packages could be out of sync with other local changes which is confusing.  This avoids the issue, but have 'yarn flow' work out of the box (well after running 'yarn install').
Issue: None
- yarn clean followed by yarn flow
> Add module.name_mapper entry in .flowconfig

- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
Here, we allow the user to pass in aria-describedby as a prop,
but default to the UniqueIdProvider error otherwise.
Issue: https://khanacademy.atlassian.net/browse/WB-1115
`yarn flow`
`yarn jest packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js`
> LabeledTextField: Allow passing `aria-describedby` as a prop.

- packages/wonder-blocks-button/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-button/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-button/src/components/__docs__/button.argtypes.js
- packages/wonder-blocks-button/src/components/__docs__/navigation-callbacks.stories.mdx
- packages/wonder-blocks-button/src/components/button.js
- packages/wonder-blocks-button/src/components/button.md
- packages/wonder-blocks-button/src/components/button.stories.js
- packages/wonder-blocks-clickable/src/components/clickable.md
- packages/wonder-blocks-link/src/components/link.md
This commit adds additional documentation describing the `onClick`,
`beforeNav`, and `safeWithNav` props. These props have been available in
Wonder Blocks for a while, but there has been some confusion about when to
use each one. This commit attempts to add enough detail about these
props to make it clear what the use case is for each prop.
Additionally, this commit changes the section headings in button.md from
h4 to h3 elements. This avoids a gap in heading levels and also brings the
section in line with other sections on the page.
Issue: none
- Load the documentation and read the Button, Clickable, and Link
sections.
Button
Clickable
Link
Storybook Documentation Page
Storybook Examples
> Improve navigation callback documentation

- .github/workflows/node-ci.yml
Removed dependabot check in node-ci.yml to run tests, linter, etc. on dependabot
Pull Requests.
By doing this change, now dependabot will be able to run lint and test checks so
we avoid introducing any regressions when upgrading third-party dependencies.
Issue: WB-1120
- Merge this PR.
- Comment `@dependabot recreate` on one of the dependabot-generated PRs.
- Verify that the Node CI worflow is triggered.
> WB-1120: Remove dependabot check in node-ci.yml

- .github/workflows/chromatic.yml
There was an issue with the Chromatic action (CLI) that didn't allow
skipping tests using the --skip flag (or `skip` env var in this case).
This now can be added back because the fix was applied on the Chromatic CLI repo.
Issue: WB-1121
- Merge this PR.
- Comment `@dependabot recreate` on one of the dependabot-generated PRs.
- Verify that the Chromatic tests are skipped and the PR can be landed automatically.
> WB-1121: Add chromatic GH action back on dependabot PRs

- .changeset/no-nested-render-state-roots.md
- packages/wonder-blocks-core/src/components/__tests__/render-state-root.test.js
- packages/wonder-blocks-core/src/components/render-state-root.js
- packages/wonder-blocks-core/src/hooks/use-unique-id.stories.mdx
Nesting of RenderStateRoots will result in unnecessary renders at best and incorrect behavior at worst.  This PR updates the component to throw if it detects that its a descendant of another RenderStateRoot.
Issue: none
- yarn test
> Prevent nesting of RenderStateRoots

- packages/wonder-blocks-popover/src/components/popover.stories.js
- packages/wonder-blocks-tooltip/src/components/tooltip.stories.js
Initial work for investigating on Chromatic about some flaky tests with PopperJS.
This first step is ~just to disable~ add a delay to the Popover and Tooltip
snapshots until we get a better sense of how (and if we can) remove the
flakyness.
Issue: WB-1170
Verify that the chromatic build doesn't report any changes on the Tooltip and
Popover stories.
> Chromatic: Add delay to Tooltip and Popover snapshots

- packages/wonder-blocks-core/src/components/__tests__/unique-id-provider.test.js
- packages/wonder-blocks-core/src/components/__tests__/with-ssr-placeholder.test.js
I added a few tests that verify that `WithSSRPlaceholder` and `UniqueIDProvider` can operate as descendants of `RenderStateRoot` without blowing up.
Issue: none
- yarn jest unique-id-provider.test.js with-ssr-placeholder.test.js
> Add some tests that test the interaction of RenderStateRoot with other components

- .changeset/fei-4212.1.md
- packages/wonder-blocks-timing/src/hooks/__tests__/use-scheduled-interval.test.js
- packages/wonder-blocks-timing/src/hooks/__tests__/use-scheduled-timeout.test.js
- packages/wonder-blocks-timing/src/hooks/internal/use-interval.js
- packages/wonder-blocks-timing/src/hooks/use-scheduled-interval.js
- packages/wonder-blocks-timing/src/hooks/use-scheduled-interval.stories.mdx
- packages/wonder-blocks-timing/src/hooks/use-scheduled-timeout.js
- packages/wonder-blocks-timing/src/hooks/use-scheduled-timeout.stories.mdx
- packages/wonder-blocks-timing/src/index.js
I thought initial that the more complicated hooks might be the default but after auditing our current use of 'withActionScheduler', it turned out that the majority of existing use cases can be met with the simpler API so that will become the default.  In the next PR, I'll export add a 'useTimeout' that mimics the current 'useInterval'.
Issue: FEI-4212
- yarn jest
> FEI-4212.1: rename timing hooks based on API design spec

- flow-typed/npm/@testing-library/jest-dom_v5.5.x.js
- flow-typed/npm/@testing-library/react_v11.x.x.js
This PR adds flow types for:
- @testing-library/react
- @testing-library/jest-dom
Issue: none
- yarn flow
> Add flow types for testing-library modules

- flow-typed/@testing-library/react-hooks.flow.js
- packages/wonder-blocks-timing/src/hooks/__tests__/use-scheduled-timeout.test.js
This should hopefully make writing tests using @testing-library/react-hooks a bit easier.
Issue: FEI-4165
- yarn flow
> FEI-4165: Add flow types for testing-library/react-hooks

- .github/workflows/release.yml
This tweaks our release Slack messaging to include the updated packages and fix other things.
Output of the jq filter is as follows:
- given input like changesets.publishedPackages,
```
[
{
"name": "foo-package",
"version": 1.0.0,
},
{
"name": "bar-package",
"version": 1.0.0,
},
{
"name": "baz-package",
"version": 1.0.0,
}
]
```
- the `jq -r '[group_by(.name) | .[] | " - "+.[].name+"@"+.[].version] | join("\n")'` command will give:
```
- bar-package@1.0.0
- baz-package@1.0.0
- foo-package@1.0.0
```
- which we should then combine into the Slack message to get something like...
> A new version of wonder-blocks was published! 🎉
> \- bar-package@1.0.0
> \- baz-package@1.0.0
> \- foo-package@1.0.0
>
> Release notes → https://github.com/Khan/wonder-blocks/releases/
We will need …
> Add updated package versions to slack output for release

- .github/workflows/release.yml
It's quite hard to get good answers about how to do this in GitHub Actions with their substitution syntax, but I tried this locally and it works, so hopefully it works there too.
Given an environment variable created using the `jq` command that we now know works, I ran this locally...
```
printf "A new version of wb was published! 🎉 \n$UPDATED_PACKAGES\nRelease notes → https://github.com/Khan/wb/releases/"
```
And I was able to see the output:
```
A new version of wb was published! 🎉
- @khanacademy/wonder-blocks-data@3.1.0
Release notes → https://github.com/Khan/wb/releases/
```
> [🔥AUDIT🔥] [fixescaping] Preserve multiline environment variable

- .changeset/good-months-tickle.md
- packages/wonder-blocks-modal/src/components/__tests__/modal-backdrop.test.js
- packages/wonder-blocks-modal/src/components/modal-backdrop.js
Right now, if you click in the modal backround and release in the panel, the modal closes even though it should not.
Also in Chrome, if you click in a modal panel and release in the backdrop, the modal closes even though it should not.
- Instead of handling `click`, handle `mouseup` and `mouedown` and keep track of whether both happened in the backdrop.
Only close if the user pressed AND released in the backdrop.
Issue: https://khanacademy.atlassian.net/browse/WB-602
Not sure how to show where my presses and releases are, but this video contains a variety of presses
and releases on Google Chrome.
https://user-images.githubusercontent.com/13231763/150456137-778f6880-bbb1-473a-9310-d34c8b475eac.mov
`yarn test packages/wonder-blocks-modal/src/components/__tests__/modal-backdrop.test.js` …
> Stop modals from closing when user releases click in the backdrop

- .github/workflows/release.yml
This utilizes a "here" document to properly construct a multiline environment variable.
This follows the option 2 guidance found here: [LIVE](https://trstringer.com/github-actions-multiline-strings/)|[ARCHIVE](https://web.archive.org/web/20211017170102/https://trstringer.com/github-actions-multiline-strings/)
The reason this broken was that we added the `-r` to `jq` to get a raw output instead of one that quoted the output and escaped control characters.
We want the raw string because otherwise, we'll output the surrounding quotes and such.
However, the raw output means it writes the newlines to the environment file (`$GITHUB_ENV`) and that file is interpreted line by line. So the first line sets a valid env variable, but subsequent lines are an invalid syntax. …
> [🔥AUDIT🔥] [finallyfixupslackmessageforreleases] Output a valid multiline environment variable

- .changeset/spotty-birds-collect.md
- build-settings/rollup.config.js
- build-settings/webpack.config.js
When things are modified between checkouts, package folders aren't deleted, so we can't use them as an indicator of a package to be built. Instead, check that there is a package.json.
This should fix [things like this](https://github.com/Khan/wonder-blocks/runs/4969439614?check_suite_focus=true) that occur when adding a new package.
The linked failure happens because the build first builds the current code with the new package, then it switches to the base branch and builds that, but the switch doesn't delete the new package folder, and so it tries to build that and fails.
With my change, it should ignore that new package folder in the second case because it will no longer have a package.json file.
`yarn build:all`
> [onlybuildactualpackages] Only build actual packages

- packages/wonder-blocks-popover/src/components/popover.stories.js
- packages/wonder-blocks-tooltip/src/components/tooltip.stories.js
Temporary fix that disables these snapshots so Chromatic stops reporting flaky
visual regressions.
Issue: WB-1170
Verify in Chromatic that these stories are no longer reported.
> [🔥AUDIT🔥] Disable Tooltip and Popover snapshots

- .github/workflows/release.yml
I think this is easier to grasp and hopefully, easier to verify. I have some thoughts on how we could "dry run" these actions more easily when we're trying to review such changes, but that will need a separate PR and some deeper thinking on action triggers and the like.
Do a release and ...fingers crossed?
> [🔥AUDIT🔥] [useoutputforreleasemessage] Use an output and bash substitution for slack message

- .storybook/main.js
Overriding the Storybook's webpack config so we can work with custom WB aliases
to be able to run Storybook inside our monorepo.
Issue: https://khanacademy.atlassian.net/browse/WB-1227
```
yarn start:storybook
```
1. Verify that storybook starts locally.
2. Verify that the Storybook chromatic build works fine.
> WB-1227: Storybook - Fix WB aliases on the webpack config file

- .changeset/early-cobras-care.md
I forgot to add the changeset after adding the `required` prop  in https://github.com/Khan/wonder-blocks/pull/1295
I included the changeset here
Issue: none
N/A I think
> Add changeset file for wonder blocks form

- packages/wonder-blocks-birthday-picker/src/components/__docs__/birthday-picker.argtypes.js
- packages/wonder-blocks-birthday-picker/src/components/__docs__/birthday-picker.stories.js
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.js
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.js
- Added the `disabled` prop.
- Added docs and tests covering this case.
- Added documentation to the existing stories.
- Removed some Storybook `argTypes` not needed anymore. SB is taking correctly the info from the `Props` type.
Issue: WB-1181
```
yarn jest packages/wonder-blocks-birthday-picker/
yarn start:storybook
```
Navigate to http://localhost:6061/?path=/story/birthdaypicker--disabled-birthday-picker
Verify that the birthday picker is disabled and cannot be interacted with.
https://user-images.githubusercontent.com/843075/152061785-6f30f361-1b06-40dd-b9f4-87af39d27fe0.mov
> WB-1181: Allow birthday component to be disabled

- .changeset/dull-rules-enjoy.md
- packages/wonder-blocks-cell/src/components/detail-cell.js
- packages/wonder-blocks-cell/src/components/internal/cell-core.js
- packages/wonder-blocks-cell/src/components/internal/common.js
Applying some changes on the `DetailCell` to match the latest design specs:
- Changed `title` from `bold` to `regular`.
- Changed the vertical padding from `12px` to `16px` (Note: `CompactCell` will remain using `12px`).
- Moved the `style` prop to the `innerWrapper` to be able to display the horizontal rule correctly in case there are layout changes (e.g. overriding padding).
Issue: WB-1222
Navigate to http://localhost:6061/?path=/story/cell-detailcell--default-detail-cell
Verify that the styles match the design specs:
Figma: https://www.figma.com/file/VbVu3h2BpBhH80niq101MHHE/branch/pQxVhYukfdxJSAXIaSjZvg/Main-Components?node-id=4337%3A2033
BEFORE:
AFTER:
> WB-1222: DetailCell style tweaks

- .changeset/thick-cobras-deny.md
- packages/wonder-blocks-data/src/hooks/__tests__/use-gql.test.js
- packages/wonder-blocks-data/src/hooks/use-gql.js
I was using the API and found it frustrating that `undefined` values explicitly included would override the defaults. I don't think this is what folks would expect and it certainly makes things harder in our case since we have to do some wrappers around the Wonder Blocks API in webapp.
So, this merges with an algorithm that ignores values explicitly set to undefined.
Also tidied up some typing.
Issue: FEI-4261
`yarn test`
`yarn flow`
> [fei4261.contextmerge] Only merge properties with non-undefined values

- .changeset/beige-rings-dream.md
- packages/wonder-blocks-cell/src/components/internal/__tests__/cell-core.test.js
- packages/wonder-blocks-cell/src/components/internal/cell-core.js
- packages/wonder-blocks-clickable/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-clickable/src/components/__tests__/clickable-behavior.test.js
- packages/wonder-blocks-clickable/src/components/__tests__/clickable.test.js
- packages/wonder-blocks-clickable/src/components/clickable-behavior.js
- packages/wonder-blocks-clickable/src/components/clickable.js
- Clickable: Replaced `disabled` attribute with `aria-disabled` to make Clickable
components keyboard focusable.  
- Cell: Changed styles to include the `not-allowed` cursor when the user hovers
on a disabled `cell`.  
- Fixed unit tests to account for this change.
Issue: WB-1213
Navigate to http://localhost:6061/?path=/story/cell-compactcell--compact-cell-disabled
Verify that the cell is disabled and it can be navigated using the keyboard.
Also verify that the `not-allowed` cursor is displayed when the user hovers on the cell.
Screenshot:
Video
https://user-images.githubusercontent.com/843075/153028015-fe0eb112-83cb-4a7c-9d97-04004174dca7.mov
> Clickable: Allow disabled state to be focusable

- .changeset/little-numbers-join.md
- packages/wonder-blocks-birthday-picker/src/components/__docs__/birthday-picker.stories.js
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.js
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.js
- Added `monthYearOnly` prop to hide the day field from the UI.
- Modified the logic to set the FIRST day of the SELECTED month when setting this new prop.
- Modified the `minWidth` of the components to account for this scenario.
- Added unit tests to cover this prop.
Issue: WB-1182
Navigate to: http://localhost:6061/?path=/story/birthdaypicker--birthday-picker-with-year-and-month-only
Verify that the UI hides the day field.
Chromatic: https://5e1bf4b385e3fb0020b7073c-yrgchxqdjx.chromatic.com/?path=/story/birthdaypicker--birthday-picker-with-year-and-month-only
Extra: Inspect the component using React DevTools and verify that the state is setting `day=1`.
> WB-1182: Remove `day` field from the `BirthdayPicker`

- .changeset/stale-feet-hang.md
- packages/wonder-blocks-core/src/hooks/__tests__/use-force-update.test.js
- packages/wonder-blocks-core/src/hooks/use-force-update.js
- packages/wonder-blocks-core/src/index.js
This adds a simple utility hook to allow components and hooks to trigger a re-render without requiring their own state to be updated.
This is useful when, for example, the state of the component comes from some shared cache or other location that doesn't warrant also sharing it in component state.
`yarn test`
`yarn flow`
> [fei4327.1.useForceUpdate] Add useForceUpdate hook

- .changeset/small-rockets-repeat.md
- packages/wonder-blocks-data/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-data/src/components/__tests__/data.test.js
- packages/wonder-blocks-data/src/components/data.js
- packages/wonder-blocks-data/src/components/data.md
- packages/wonder-blocks-data/src/util/__tests__/result-from-cache-response.test.js
- packages/wonder-blocks-data/src/util/gql-error.js
- packages/wonder-blocks-data/src/util/result-from-cache-response.js
- packages/wonder-blocks-data/src/util/types.js
Having access to the error, where possible, is incredibly useful. This is the first step to supporting that.
The `Data` component doesn't have it all correct yet because the client-side fetch is doing the same as the server-side fetch and as such, is using a "hydrated" error. Changes coming for that.
`yarn test`
> Change Result type to include the error object instead of string

- .changeset/chilled-students-poke.md
- packages/wonder-blocks-data/src/components/__tests__/data.test.js
- packages/wonder-blocks-data/src/components/data.js
- packages/wonder-blocks-data/src/components/intercept-requests.js
- packages/wonder-blocks-data/src/components/intercept-requests.md
- packages/wonder-blocks-data/src/hooks/__tests__/use-gql-router-context.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-gql.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-server-effect.test.js
- packages/wonder-blocks-data/src/hooks/use-gql-router-context.js
- packages/wonder-blocks-data/src/hooks/use-gql.js
- packages/wonder-blocks-data/src/hooks/use-request-interception.js
- packages/wonder-blocks-data/src/hooks/use-server-effect.js
- packages/wonder-blocks-data/src/index.js
- packages/wonder-blocks-data/src/util/__tests__/merge-gql-context.test.js
- packages/wonder-blocks-data/src/util/__tests__/request-fulfillment.test.js
- packages/wonder-blocks-data/src/util/__tests__/request-tracking.test.js
- packages/wonder-blocks-data/src/util/__tests__/result-from-cache-response.test.js
- packages/wonder-blocks-data/src/util/merge-gql-context.js
- packages/wonder-blocks-data/src/util/request-fulfillment.js
- packages/wonder-blocks-data/src/util/request-tracking.js
- packages/wonder-blocks-data/src/util/result-from-cache-response.js
- packages/wonder-blocks-testing/src/gql/__tests__/mock-gql-fetch.test.js
- packages/wonder-blocks-testing/src/gql/__tests__/wb-data-integration.test.js
In this PR:
1. `useGql` delegates some responsibility to `useGqlRouterContext` and the new `mergeGqlContext` function
2. `useGql` can now take context adjustments directly so that the returned fetch can have them applied to all calls
3. `Result<TData` is now the default return of our data architecture, which partly paves the way for a universal "opinion" on how aborts will be done (that is currently unprioritized work), but also simplifies integration to webapp
`yarn test`
`yarn flow`
> [fei4327.4.firstclassresult] Result<TData> as first class citizen in external API

- .changeset/curly-parents-allow.md
- packages/wonder-blocks-data/src/hooks/__tests__/use-cached-effect.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-hydratable-effect.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-server-effect.test.js
- packages/wonder-blocks-data/src/hooks/use-cached-effect.js
- packages/wonder-blocks-data/src/hooks/use-hydratable-effect.js
- packages/wonder-blocks-data/src/hooks/use-server-effect.js
- packages/wonder-blocks-data/src/hooks/use-shared-cache.js
- packages/wonder-blocks-data/src/index.js
This is the last of the main Wonder Blocks Data updates.
This splits out the client-side work into its own effect hook, and updates our `useHydrateableEffect` (introduced in the last PR) to use this new hook.
`yarn test`
`yarn flow`
> [fei4327.6.useCachedEffect] Implement useCachedEffect

- package.json
- utils/test-file-for.js
I find myself wanting this often to check that the tests for a given file actually cover that file.
It can be a lot to type out by hand, so now, instead of:
`yarn jest --coverage --collectCoverageFrom=packages/wonder-blocks-data/src/components/data.js packages/wonder-blocks-data/src/components/__tests__/data.test.js`
I can just do:
`yarn coveragefor packages/wonder-blocks-data/src/components/data.js`
No version bumps required. This is entirely repo tooling and does not affect package tooling.
Try it out :)
Example:
```bash
(khan27) ✔ ~/khan/wonder-blocks [fei4327.4.firstclassresult L|✔] 
12:08 $ yarn coveragefor packages/wonder-blocks-data/src/components/data.js
yarn run v1.22.17
$ bash -c 'yarn --silent jest --coverage --collectCoverageFrom=$0 $(node …
```
> [coverageforhelper] Add a little helper for just getting coverage of a single file, based on its own tests

- .changeset/red-beers-mate.md
- packages/wonder-blocks-data/src/hooks/__tests__/__snapshots__/use-shared-cache.test.js.snap
- packages/wonder-blocks-data/src/hooks/__tests__/use-gql-router-context.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-gql.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-server-effect.test.js
- packages/wonder-blocks-data/src/hooks/use-shared-cache.js
- packages/wonder-blocks-data/src/index.js
- packages/wonder-blocks-data/src/util/__tests__/request-fulfillment.test.js
- packages/wonder-blocks-data/src/util/__tests__/result-from-cache-response.test.js
- packages/wonder-blocks-data/src/util/data-error.js
- packages/wonder-blocks-data/src/util/get-gql-data-from-response.js
- packages/wonder-blocks-data/src/util/gql-error.js
- packages/wonder-blocks-data/src/util/request-fulfillment.js
- packages/wonder-blocks-data/src/util/result-from-cache-response.js
- packages/wonder-blocks-data/src/util/scoped-in-memory-cache.js
- packages/wonder-blocks-data/src/util/serializable-in-memory-cache.js
- packages/wonder-blocks-data/src/util/types.js
During my writing of the docs I found that I had not properly dealt with the error types (returning Gql errors for things that were not Gql specific), so this tidies that up and splits it out from the docs changes I was making (hence the `0` in the branch name).
`yarn test`
`yarn flow`
> [fei4191.0.errors] Fix up types of errors thrown

- packages/wonder-blocks-data/src/__docs__/_overview_.stories.mdx
- packages/wonder-blocks-data/src/__docs__/_overview_graphql.stories.mdx
- packages/wonder-blocks-data/src/__docs__/_overview_testing_.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.clear-shared-cache.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.data-error.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.data-errors.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.data.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.gql-error.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.gql-errors.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.gql-router.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.intercept-requests.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.request-fulfillment.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.scoped-in-memory-cache.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.serializable-in-memory-cache.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.status.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.track-data.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.use-cached-effect.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.use-gql.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.use-hydratable-effect.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.use-server-effect.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.use-shared-cache.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.when-client-side.stories.mdx
- packages/wonder-blocks-data/src/__docs__/types.error-options.stories.mdx
- packages/wonder-blocks-data/src/__docs__/types.valid-cache-data.stories.mdx
- packages/wonder-blocks-data/src/hooks/use-hydratable-effect.js
- packages/wonder-blocks-testing/src/__docs__/_overview_.stories.mdx
- packages/wonder-blocks-testing/src/__docs__/exports.mock-gql-fetch.stories.mdx
- packages/wonder-blocks-testing/src/__docs__/exports.respond-with.stories.mdx
This adds remaining docs for Wonder Blocks Data and Testing.
The only bit left is to resurrect the live examples for some of our components, where we can, at least - though this isn't a high priority right now, so I think I'll raise a separate task for that for now.
- Also, export `ValidCacheData` type and remove `useRequestInterception` from exports
Issue: FEI-4191
`yarn start:storybook` and have a little click around :)
https://user-images.githubusercontent.com/1266297/155818861-fcc93aa2-6063-4d3e-ba0c-4b00b6b0be2e.mov
> [fei4191.2.hooksdocs] Adding more docs!

- .changeset/funny-deers-grab.md
- packages/wonder-blocks-data/src/hooks/__tests__/use-hydratable-effect.test.js
- packages/wonder-blocks-data/src/hooks/use-hydratable-effect.js
In investigating an SSR issue I saw, I found this client-side bug. It doesn't explain why the SSR was not working in the case I saw, but it is definitely a bug. I've added a test case to cover this issue which failed before I implemented the fix.
Issue: FEI-4322
`yarn test`
Tried this out in dev server for webapp to verify it fixed the client-side bug I saw. Interestingly, SSR and hydration is working in dev which makes me think the SSR issue I saw in staging was down to something else entirely.
> [fei4322.fix] Fix bug where changing requestId after hydrating result would actually update

- .changeset/config.json
- .github/workflows/chromatic.yml
- .github/workflows/node-ci-push.yml
- .github/workflows/release.yml
- .storybook/components/component-info.js
- README.md
- packages/wonder-blocks-core/src/util/add-style.md
- packages/wonder-blocks-data/legacy-docs.md
Just renamed any reference to Wonder Blocks `master` branch to be `main`.
Issue: FEI-4353
We'll set this to the default branch and update codecov.io, and any other remaining PRs to be based off `main` as needed then see if things just work :)
> [🔥AUDIT🔥] Rename references to `master` to `main`

- .github/workflows/chromatic.yml
Adding `turbosnap` to optimize visual testing with Chromatic. Adding this change
means that Chromatic will only generate visual snapshots for the stories that
are really affected (instead of generating snapshots for ALL stories).
See https://www.chromatic.com/docs/turbosnap#configure
Verify the chromatic action and see if the Chromatic build changes.
For reference: https://www.chromatic.com/docs/turbosnap#how-can-i-tell-if-turbosnap-is-working
> [🔥AUDIT🔥] Add turbosnap to only run affected stories on Chromatic

- .github/workflows/release.yml
Adds a new step as part of the Release job to build the Storybook static version
and push those generated files to the `gh-pages` branch.
Verify that https://khan.github.io/wonder-blocks works a couple of minutes after
landing this PR.
> [🔥AUDIT🔥] Add GitHub pages action to publish storybook in gh-pages branch

- .storybook/manager-head.html
- .storybook/preview-head.html
- .storybook/wonder-blocks-theme.js
- packages/wonder-blocks-cell/src/components/__docs__/compact-cell.argtypes.js
- packages/wonder-blocks-modal/src/components/one-pane-dialog.stories.js
Fixed all the absolute paths in Storybook. This prevented us from displaying
some images and loading correctly the Lato font in the Storybook static version.
1. Run `yarn build-storybook`
2. Verify that the WB logo is displayed on the top left.
> [🔥AUDIT🔥] Storybook: Use relative paths on images

- .changeset/quick-snails-fail.md
- packages/wonder-blocks-cell/src/components/__docs__/compact-cell.argtypes.js
- packages/wonder-blocks-cell/src/components/__docs__/detail-cell.stories.js
- packages/wonder-blocks-cell/src/components/internal/__tests__/cell-core.test.js
- packages/wonder-blocks-cell/src/components/internal/cell-core.js
- packages/wonder-blocks-cell/src/util/types.js
Added `href` to both `CompactCell` and `DetailCell`.
Issue: WB-1257
- Navigate to /?path=/story/cell-detailcell--detail-cell-navigation  
- Verify that the "See navigation changes here" text changes after clicking on any of the
cells.
> WB-1257: Add href to Cell

- consistency-tests/__tests__/clickables.test.js
- packages/wonder-blocks-button/src/components/button.js
- packages/wonder-blocks-cell/src/components/internal/cell-core.js
- packages/wonder-blocks-cell/src/util/types.js
- packages/wonder-blocks-clickable/src/components/clickable-behavior.js
- packages/wonder-blocks-clickable/src/components/clickable.js
- packages/wonder-blocks-dropdown/src/components/action-item.js
- packages/wonder-blocks-icon-button/src/components/icon-button.js
- packages/wonder-blocks-link/src/components/link.js
The consistency tests found that the 'target' prop was missing.  We may also want to expand this test suite to also include 'tabIndex' in the future since that's another common prop that people may want to use on clickables.  I'll leave that for another day.
Issue: None
- yarn jest clickables.test.js
> Add cell components to our clickable consistency test suite

- packages/wonder-blocks-dropdown/src/components/__tests__/action-menu.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core-virtualized.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
Pre-work to migrate most of the existing enzyme test in `wb-dropdown` to RTL.
This is done so we can modify the `react-window` logic in the next PR and we can
see what tests need to be updated using RTL as source of truth.
Issue: WB-1258
```
yarn test
```
> WB-1258.0: Migrate Dropdown tests to RTL

- .changeset/bright-ears-watch.md
- packages/wonder-blocks-dropdown/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/src/__tests__/generated-snapshot.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/action-menu.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-popper.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/dropdown-popper.js
- packages/wonder-blocks-dropdown/src/components/single-select.md
- packages/wonder-blocks-dropdown/src/components/single-select.stories.js
- Modified `DropdownCore` to only use `react-window` if there are more than 80
options in the menu.
- Improved the performance a bit by avoiding to recalculate rendering the options list on every re-render.
- Created `DropdownPopper` to abstract out the `PopperJS` functionality into a
separate component. This will help us to make improvements in the future (e.g.
porting to hooks, using PopperV3/floating-ui).
- Modified unit tests inside `wb-dropdown` to avoid relying on timers to test the dropdowns.
Current benchmarks for showing the dropdown menu without `react-window`:
BEFORE IMPROVING PERFORMANCE: 173ms for 70 items.
AFTER IMPROVING PERFORMANCE: ~90ms for 70 items (average).
Issue: WB-1258
Navigate to the Stories related to Dropdown components and verify that everything continues …
> WB-1258: Use react-window only for long lists

- .changeset/seven-pots-think.md
- packages/wonder-blocks-i18n/src/functions/i18n.js
- packages/wonder-blocks-i18n/src/index.js
I started extracting the handlebars specific functions from shared-package/i18n.js in webapp and noticed that I needed ngetpos() for that change.
Issue: None
- n/a
> Export ngetpos so that it can be use by handlebars i18n functions in webapp

- .changeset/curly-doors-draw.md
- packages/wonder-blocks-cell/src/components/__docs__/detail-cell.stories.js
- packages/wonder-blocks-cell/src/components/internal/cell-core.js
- packages/wonder-blocks-cell/src/components/internal/common.js
There’s an extra spacing on the content container that doesn’t work well when we try to align the accessory to the top. We need to fix the layout to align both the accessories and the content using the same padding (applies for both Compact and Detail cells).
Issue: https://khanacademy.atlassian.net/browse/WB-1267
Navigate to the Storybook instance and verify that the
?path=/story/cell-detailcell--detail-cell-with-custom-styles example is now
vertically aligned to the top.
BEFORE
AFTER
> WB-1267: Fix top alignment between accessory and content

- .changeset/poor-keys-ring.md
- packages/wonder-blocks-i18n/package.json
This will save some bytes and hopefully also fix some errors I was seeing in webapp tests around "key" prop missing when using some of the i18n functions.
Issue: none
- yarn build:all
- check the dist bundles for wonder-blocks-i18n, grep for "Facebook", see no hits
> Don't bundle 'react' in dist bundle for wonder-blocks-i18n

- .changeset/friendly-boats-argue.md
- packages/wonder-blocks-testing/src/fixtures/__tests__/fixtures.test.js
- packages/wonder-blocks-testing/src/fixtures/adapters/__tests__/adapter-group.test.js
- packages/wonder-blocks-testing/src/fixtures/adapters/__tests__/adapter.test.js
- packages/wonder-blocks-testing/src/fixtures/adapters/storybook.js
- packages/wonder-blocks-testing/src/fixtures/fixtures.basic.stories.js
- packages/wonder-blocks-testing/src/fixtures/fixtures.defaultwrapper.stories.js
- packages/wonder-blocks-testing/src/fixtures/fixtures.js
- packages/wonder-blocks-testing/src/fixtures/types.js
This makes the `title` field optional/nullable and adds a `getDefaultTitle` function so that adapters that cope with nullish titles can do their own thing, but those that can't (like if we had a React Sandbox adapter) can just use the default title as needed.
Issue: FEI-4127
`yarn test`
`yarn flow`
> [fei4127.allowstorybookautogentitles] Allow auto-gen titles in storybook

- .changeset/red-zoos-matter.md
- packages/wonder-blocks-testing/src/fixtures/__tests__/fixtures.test.js
- packages/wonder-blocks-testing/src/fixtures/fixtures.js
This creates a simpler call signature for the common use of `fixtures`.
Issue: FEI-4127
`yarn flow`
`yarn test`
> [fei4127.simples] Simplify fixtures call for common case

- .changeset/few-kangaroos-battle.md
- packages/wonder-blocks-testing/src/fixtures/__tests__/fixtures.test.js
- packages/wonder-blocks-testing/src/fixtures/fixtures.js
Turns out that what React.forwardRef returns does not look like a component at all, so I expanded the heuristic check accordingly.
Issue: FEI-4127
`yarn test`
> [fei4127.3.forwardrefs] Cope with React.forwardRef

- .changeset/tall-snails-pretend.md
- package.json
- packages/wonder-blocks-testing/package.json
- packages/wonder-blocks-testing/src/__tests__/make-mock-response.test.js
- packages/wonder-blocks-testing/src/__tests__/mock-requester.test.js
- packages/wonder-blocks-testing/src/__tests__/response-impl.test.js
- packages/wonder-blocks-testing/src/fetch/__tests__/__snapshots__/mock-fetch.test.js.snap
- packages/wonder-blocks-testing/src/fetch/__tests__/fetch-request-matches-mock.test.js
- packages/wonder-blocks-testing/src/fetch/__tests__/mock-fetch.test.js
- packages/wonder-blocks-testing/src/fetch/fetch-request-matches-mock.js
- packages/wonder-blocks-testing/src/fetch/mock-fetch.js
- packages/wonder-blocks-testing/src/fetch/types.js
- packages/wonder-blocks-testing/src/gql/__tests__/mock-gql-fetch.test.js
- packages/wonder-blocks-testing/src/gql/__tests__/wb-data-integration.test.js
- packages/wonder-blocks-testing/src/gql/mock-gql-fetch.js
- packages/wonder-blocks-testing/src/gql/types.js
- packages/wonder-blocks-testing/src/index.js
- packages/wonder-blocks-testing/src/make-mock-response.js
- packages/wonder-blocks-testing/src/mock-requester.js
- packages/wonder-blocks-testing/src/response-impl.js
- packages/wonder-blocks-testing/src/types.js
- yarn.lock
This takes the implementation of `mockGqlFetch` and creates a generic approach that is then reused with the new `mockFetch`. This also adds some more things to `RespondWith` to cater to `mockFetch` scenarios and generally refactors things.
The idea is that in webapp stories we can now use `mockFetch` to create a mock of `fetch` for the given story, as well as reset the `fetch` function between stories to prevent overlap.
Issue: FEI-4429
`yarn test`
`yarn flow`
> [fei4429.1] Implement mockFetch

- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.js
Adds `waitFor` to a couple of Dropdown virtualized tests in `DropdownCore` so we safely assert when the right component receives focus.
We have to use async here due to the virtualized version having to use timeouts/requestAnimationFrame.
Verify that unit tests pass fine.
> [🔥AUDIT🔥] Fix flaky Dropdown tests

- .changeset/neat-cobras-sing.md
- packages/wonder-blocks-cell/src/components/__docs__/detail-cell.stories.js
- packages/wonder-blocks-cell/src/components/internal/cell-core.js
Fixes `CellCore` to set the styles properly on the `rightAccessory` element. The previous styles where applied incorrectly.
With this fix, now we are applying the remaining space available to the content, so the accessories are correctly aligned to each side.
Navigate to http://localhost:6061/?path=/story/cell-detailcell--default-detail-cell&globals=outline:true
https://5e1bf4b385e3fb0020b7073c-nkzomwxcrj.chromatic.com/?path=/story/cell-detailcell--default-detail-cell
Verify that the cells render as expected.
BEFORE:
AFTER:
> Cell: Fix rightAccessory style

- .changeset/orange-baboons-decide.md
- packages/wonder-blocks-i18n/src/components/__tests__/parse-simple-html.test.js
- packages/wonder-blocks-i18n/src/components/parse-simple-html.js
The translation isn't correct, but it's better to show the translation than to throw an exception which results in us showing an error screen.
Issue: None
- yarn jest parse-simple-html
> Update parseSimpleHTML to warn instead of throw when the use of I18nInlineMarkup isn't necessary

- .changeset/tame-ghosts-poke.md
- build-settings/rollup.config.js
Strip comments out from ES bundles (rollup).
Issue: WB-1299
Verify that the bundle sizes check shows some improvements on each bundled package.
> WB-1299: Strip comments out from ES bundles

- .storybook/manager.js
- packages/wonder-blocks-clickable/src/components/__docs__/clickable-behavior.argtypes.js
- packages/wonder-blocks-clickable/src/components/__docs__/clickable-behavior.stories.js
- packages/wonder-blocks-clickable/src/components/clickable-behavior.js
- Add stories for the `ClickableBehavior` component.
- Reuse from of the argtypes defined for `Clickable`.
- Modify JSDocs to improve the way the comments are displayed in Storybook docs.
NOTE: This component doesn't include any accessibility notes as the recommended
approach is to use `Clickable` for an improved and more robust experience.
Issue: WB-1131
1. Navigate to the newly created `ClickableBehavior` section in storybook.
2. Verify that there's a new story explaining how to use that component.
3. Verify that the props table is displayed correctly.
https://5e1bf4b385e3fb0020b7073c-wjhmfkabvs.chromatic.com/?path=/story/clickable-clickablebehavior--default
> WB-1131.2: Migrate `wonder-blocks-clickable` to Storybook - ClickableBehavior

- .changeset/tame-owls-draw.md
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core-virtualized.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/single-select.stories.js
- packages/wonder-blocks-dropdown/src/util/__tests__/dropdown-menu-styles.test.js
- packages/wonder-blocks-dropdown/src/util/constants.js
- packages/wonder-blocks-dropdown/src/util/dropdown-menu-styles.js
- Add `maxHeight` to the dropdown menu container (listbox) to avoid overflow
issues when the options list is longer than the screen height.
- Created a new helper to abstract out calculating the dropdown menu height, so it can be used by `DropdownCore` and the virtualized version.
- Added unit tests to verify that the styles are applied correctly.
Issue: WB-1301
Navigate to any of the Dropdown stories and verify that after opening the
dropdown, you can see a maximum of 9 items in the screen.
Navigate to the `BirthdayPicker` stories and verify that all the dropdowns are
now correctly displayed.
BEFORE
AFTER
> WB-1301: Restrict the dropdown menu height

- .changeset/clever-poems-dream.md
- package.json
- packages/wonder-blocks-data/src/util/request-tracking.js
- yarn.lock
Simple update. Even cause an unnecessary `new` use.
Issue: FEI-4424
`yarn flow`
`yarn test`
> [fei4424.1.updateflow] Update flow to 0.176.2

- packages/wonder-blocks-data/src/__docs__/types.fetch-policy.stories.mdx
- packages/wonder-blocks-data/src/index.js
- packages/wonder-blocks-data/src/util/types.js
This adds a `FetchPolicy` enum to Wonder Blocks Data along with docs.
Nothing uses it yet.
Issue: FEI-4413
`yarn storybook` and check the docs are there.
> [fei4413.1.addfetchpolicy] Add FetchPolicy enum

- .changeset/perfect-spies-help.md
- packages/wonder-blocks-data/src/__docs__/exports.request-fulfillment.stories.mdx
- packages/wonder-blocks-data/src/__docs__/exports.use-cached-effect.stories.mdx
- packages/wonder-blocks-data/src/components/__tests__/data.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-cached-effect.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-hydratable-effect.test.js
- packages/wonder-blocks-data/src/hooks/use-cached-effect.js
- packages/wonder-blocks-data/src/hooks/use-hydratable-effect.js
- packages/wonder-blocks-data/src/util/data-error.js
- packages/wonder-blocks-data/src/util/request-fulfillment.js
This reworks `useCachedEffect` to add fetch policy and refetch support.
This was a heavier lift than I originally hoped for, however, it works. I think things will get a little nicer when the RequestFulfillment properly supports aborting requests, but that's a while away (see FEI-4276) as we need to determine how to exactly do that. For now, I've added basic "aborting" to the RequestFulfillment that we'll have to expand later.
Issue: FEI-4413
`yarn test`
> [fei4413.2.usingfetchpolicies] Implement fetch policy in useCachedEffect

- packages/wonder-blocks-data/src/index.js
- packages/wonder-blocks-data/src/util/__tests__/graphql-document-node-parser.test.js
- packages/wonder-blocks-data/src/util/__tests__/to-gql-operation.test.js
- packages/wonder-blocks-data/src/util/graphql-document-node-parser.js
- packages/wonder-blocks-data/src/util/graphql-types.js
- packages/wonder-blocks-data/src/util/to-gql-operation.js
This pulls the `DocumentNode` parsing from webapp (which was from Apollo) into Wonder Blocks Data, with some tweaks around error cases and typing (to avoid taking a dependency on an old `graphql` just for types).
This also adds tests.
Issue: FEI-4357
`yarn test`
> [fei4357.1.documentparsing] Add document parsing to Wonder Blocks Data

- .changeset/tough-geckos-boil.md
- packages/wonder-blocks-data/src/__docs__/exports.abort-inflight-requests.stories.mdx
- packages/wonder-blocks-data/src/util/__tests__/request-api.test.js
- packages/wonder-blocks-data/src/util/request-api.js
This adds a handy `abortInflightRequests` export.
Issue: FEI-4454
`yarn test`
> [fei4454.2] Add abortInflightRequests export

- .changeset/cold-falcons-invent.md
- packages/wonder-blocks-data/src/util/__tests__/ssr-cache.test.js
- packages/wonder-blocks-data/src/util/ssr-cache.js
This fixes a bug in the `purgeHydrationCache` call and similar where if it were called before `Server.setServerSide()` or a something that affected the return value of `Server.isServerSide()` (such as a mock), then the internal SSR-only cache wouldn't get initialized and then any future setup that needed it wouldn't work right.
This fixes things by initializing that cache when in the test NODE_ENV. This creates behavior of least surprise for devs in testing, while retaining the existing client-side behavior when in the browser.
Issue: FEI-4371
`yarn test`
> [🔥AUDIT🔥] [fixssrcacheintests] Ensure purgeCaches and purgeHydrationCache will work as devs would expect in tests

- .changeset/good-frogs-allow.md
- packages/wonder-blocks-data/src/util/__tests__/ssr-cache.test.js
- packages/wonder-blocks-data/src/util/ssr-cache.js
I had the expectation that the NODE_ENV things weren't applied when wonder blocks was built but instead would be applied when webapp was built; this was incorrect and so my last fix for this problem did not work
Issue: FEI-4371
`yarn test`
Include in webapp and check that the route tests now work again.
> [🔥AUDIT🔥] [fixssrcacheagain] Always init SSR only cache

- .github/actions/shared-node-cache/action.yml
- .github/workflows/node-ci-pr.yml
- yarn.lock
The two parallel jobs were missing node-version from their matrices and as such, they were looking at the wrong cache keys. This should now properly share the same keys and speed things up considerably.
Issue: FEI-4370
See the jobs run on GitHub. Run jobs, run. 🐇
> [fei4370.2.fixcaching] Fix shared cache usage

- .github/workflows/node-ci-push.yml
I forgot to update the two jobs in node ci push workflow.
Merge into `main` and check that it now runs the shared action for these two jobs.
> [🔥AUDIT🔥] [howdidImissthis] Use the shared action for all cache references

- .changeset/giant-otters-judge.md
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/search-text-input.js
- packages/wonder-blocks-dropdown/src/components/single-select.stories.js
- packages/wonder-blocks-dropdown/src/util/constants.js
Currently, if a dropdown switches between a virtualized list (125+ results) and
a non-virtualized list (< 125 results), then the search field rerenders and
loses focus. This means that a user is typing in the search field and the filter
results change mid-typing, the focus leaves the text field and the user will have
to click back in to keep typing.
As a temporary fix, here we force focus on the field on mount if the focus was already
previously on the field.
The issue should go away with WB-1310, but we are adding this quick fix as a bandaid for now.
Issue: https://khanacademy.atlassian.net/browse/WB-1281
https://user-images.githubusercontent.com/13231763/166083939-c26ea043-c6d0-43b0-98b4-10c765965d21.mov
https://user-images.githubusercontent.com/13231763/166083866-5b3a9284-1444-49e1-8440 …
> Fix focus issue with filterable dropdowns

- .changeset/olive-weeks-knock.md
- packages/wonder-blocks-testing/src/harness/__tests__/types.flowtest.js
- packages/wonder-blocks-testing/src/harness/types.js
I had played around with variance markers and trusted flow to tell me if things stopped working, but instead, of adding an unused suppression warning, it did nothing. Without one of the suppressions in the test file, no error; with the suppression, no unused suppression warning.
I only discovered this while integrating the changes into webapp because I had forgotten to carry over the flowtest file. This audit includes that file and reverts the variance changes. I am pretty sure it was just the `TestHarnessAdapter<>` one that was the issue, but decided not to risk it on the other cases for now.
You can see this for yourself by visiting [this example](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDciiw++RAVABBYgBMi6HJSygcsUACNKoGk0wl …
> [🔥AUDIT🔥] [fei4370.typesexportfix] Fix test harness types

- .changeset/plenty-peas-battle.md
- package.json
- packages/wonder-blocks-core/package.json
- packages/wonder-blocks-data/package.json
The reason for making this change is to avoid having to install this dependency multiple times.
Issue: None
- let GitHub Actions run all the checks
> Make flow-enums-runtime a peer dependency

- .changeset/curvy-snakes-flow.md
- packages/wonder-blocks-dropdown/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/multi-select.js
- packages/wonder-blocks-modal/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-typography/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
Fixes an issue with iOS that was not announncing properly the total of options.
- Created new wrapper for announcing the options count when the dropdown menu
(`listbox`) is opened.
- Added unit tests.
NOTE: There's a known issue with the `SingleSelect` not being able to use the correct text when there's a single item in the list. This should be fixed after we allow passing translated strings to this component.
Issue: WB-646
Using an iPad or iPhone:
1. Activate `Voice Over`.
2. Navigate to any of the dropdown stories.
3. Click on the dropdown opener.
4. Verify that VO announces the # of options (e.g. `9 items`).
5. Focus on the search field and filter some elements by typing in `o`.
6. Verify that VO also announces the filtered # of options (e.g. `4 items`). …
> WB-646: Add Live region to announce available options

- package.json
- yarn.lock
Removed lint-staged, pretty-quick and husky as we don't rely on these pre-commit
hooks anymore and use GH actions instead.
https://khanacademy.slack.com/archives/C4PE1QM5Y/p1651091304777409
https://khanacademy.slack.com/archives/C4PE1QM5Y/p1639511766076800?thread_ts=1639511103.074300&cid=C4PE1QM5Y
Issue: "none"
N/A
> Remove lint-staged, pretty-quick and husky

- packages/wonder-blocks-modal/src/components/modal-dialog.js
Doing some accessibility testing on webapp with jest-axe I found a component that uses this dialog and has no way to pass the test if a label cannot be set (a good labelledby attribute isn't available)
Issue: wb-1324
Set an aria-label attribute
Verify the dialog has the aria-label
> Set an aria-label on ModalDialog if one is passed in

- .changeset/nasty-keys-admire.md
- packages/wonder-blocks-icon/src/components/icon.js
- packages/wonder-blocks-progress-spinner/src/components/circular-spinner.js
These components currently accept a `testId` prop but they don't hook it up to `data-test-id`, which is what we need to look up elements by test id in React testing library.
Testing in deploy preview, `data-test-id` appears for both components:
> Hook up data-test-id for CircularSpinner and Icon

- .github/workflows/node-ci-pr.yml
Experiment to try out the new Jest 28 feature: Sharding.
Also, splited the `lint_and_test` workflow step into `lint` and `test` to be
able to run the tests in two different workers.
The idea is to be able to split tests and run each test running instance in
parallel.
Verify that there are new checks.
TODO
> [Experiment] Add jest --shard flag to the PR workflow

- packages/wonder-blocks-button/src/components/__docs__/accessibility.stories.mdx
- packages/wonder-blocks-button/src/components/__docs__/best-practices.stories.mdx
- packages/wonder-blocks-button/src/components/__docs__/button.stories.js
- packages/wonder-blocks-button/src/components/__docs__/navigation-callbacks.stories.mdx
- Moving `button.stories.js` to the `__docs__` folder.
- Changing the navigation to remove one `Button` level in the side nav.
- Renaming some examples to make them more concise and similar to the other Storybook stories.
- Moving some stories to the `navigation callbacks` section.
Navigate to the `Button` section in SB and verify that all the examples work fine.
> [🔥AUDIT🔥] Reorganize button docs (Storybook)

- .storybook/preview-head.html
- packages/wonder-blocks-dropdown/src/components/__docs__/action-menu.argtypes.js
- packages/wonder-blocks-dropdown/src/components/__docs__/action-menu.stories.js
- packages/wonder-blocks-dropdown/src/components/action-menu.js
First part of the wb-dropdown migration to storybook:
- Adding stories for ActionMenu.
- Adding props table for both `ActionMenu` and `ActionItem`.
Issue: WB-1134
Open storybook and navigate to `Dropdown > ActionMenu`.
Verify that all the examples are similar from the ones in the StyleGuidist site:
https://wonder-blocks.netlify.app/#actionmenu
> WB-1134.1: Add stories for ActionMenu

- packages/wonder-blocks-breadcrumbs/src/components/__docs__/accessibility.stories.mdx
- packages/wonder-blocks-breadcrumbs/src/components/__docs__/breadcrumbs.stories.js
- packages/wonder-blocks-breadcrumbs/src/components/breadcrumbs.js
- Fixed breadcrumbs example to remove the link from the last item.
- Removed one `Breadcrumbs` item from the side nav.
- Updated usage guide to reflect this change.
Issue: "none"
Verify that the `Breadcrumbs` example looks as expected (no link in the last item).
> [🔥AUDIT🔥] Fix Breadcrumb stories to match StyleGuidist

- packages/wonder-blocks-form/src/components/__docs__/radio.stories.js
Add Radio to storybook. The stories are very similar to
those of Checkbox. A separate ArgTypes file was not needed
because storybook was able to extrapolate all the info
from the comments and props in radio.js.
It's fairly short and simple because most of the
functionality for radio buttons comes in radio groups,
which is a different component altogether.
Issue: https://khanacademy.atlassian.net/browse/WB-1290
- Go to http://localhost:6061/?path=/docs/form-radio--default
- Confirm that interacting with the controls affects the
default radio button as expected.
- Confirm that the descriptions for the stories sound right.
> Add Radio to Storybook

- .alexrc
- .changeset/ninety-tomatoes-wait.md
- .github/workflows/node-ci-pr.yml
- packages/wonder-blocks-core/src/components/with-ssr-placeholder.js
- packages/wonder-blocks-i18n/CHANGELOG.md
- packages/wonder-blocks-testing/src/__docs__/types.get-props-options.stories.mdx
- packages/wonder-blocks-testing/src/fixtures/adapters/__tests__/storybook.test.js
- packages/wonder-blocks-testing/src/fixtures/adapters/storybook.js
- packages/wonder-blocks-testing/src/fixtures/types.js
- packages/wonder-blocks-timing/CHANGELOG.md
I was finding that the dominant use-case for logging in props is to log event handlers and the same boilerplate cropped up. This reduces that boilerplate a little. See the updated docs for an example.
Issue: FEI-4131
`yarn storybook`
`yarn test`
> [fei4131.reduceboilerplate] Add logHandler to API to simplify event logging in fixture stories

- .changeset/seven-guests-cry.md
- packages/wonder-blocks-testing/src/__docs__/exports.fixtures.stories.mdx
- packages/wonder-blocks-testing/src/__docs__/types.fixture-fn.stories.mdx
- packages/wonder-blocks-testing/src/__docs__/types.fixture-props.stories.mdx
- packages/wonder-blocks-testing/src/fixtures/fixtures.js
- packages/wonder-blocks-testing/src/fixtures/types.js
- packages/wonder-blocks-testing/src/index.js
This will allow us to change:
```js
const fixture = fixtures<typeof Component, Props>(...);
```
into:
```js
const fixture: FixtureFn<Props> = fixtures(...);
```
`yarn flow`
`yarn start:storybook`
> [testingtweaks] This exports more types from the fixtures framework so that we can type things better in our fixtures files

- .changeset/gorgeous-sloths-juggle.md
- packages/wonder-blocks-testing/src/fixtures/__tests__/fixtures.test.js
- packages/wonder-blocks-testing/src/fixtures/fixtures.js
When I reworked the framework, I somehow dropped the ability to render the wrapper. This brings that back and adds a test case to cover it.
Issue: FEI-4603
`yarn test`
> [fixfixturesbug] Make sure wrapper component is used if provided

- .changeset/fuzzy-boats-boil.md
- .changeset/khaki-swans-add.md
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.js
- packages/wonder-blocks-clickable/src/components/clickable-behavior.js
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.js
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/multi-select.js
- packages/wonder-blocks-dropdown/src/components/single-select.js
- packages/wonder-blocks-dropdown/src/util/__tests__/helpers.test.js
- packages/wonder-blocks-dropdown/src/util/helpers.js
Added keyboard support to `DropdownCore` so we can try to match a given option
from the listbox.
This is done replicating the behavior from the `<select>` element:
- If the user focuses on the dropdown opener (but dropdown menu is CLOSED),
typing in will automatically SELECT the first occurrence.
- If the user focuses on the dropdown opener (and the dropdown menu is OPEN),
typing in will FOCUS on the first occurrence, but won’t select it unless the
user press space.
Issue: WB-1264
Navigate to any SingleSelect example and verify that keyboard search is enabled
when you focus on the dropdown.
Navigate to the BirthdayPicker examples and try out the different fields (day,
month, year).
https://user-images.githubusercontent.com/843075/179804174-dbb16c45-257c-4398-8b77-de6d0c990628.mov …
> WB-1264: Add keyboard support for searching options

- .changeset/new-boats-hunt.md
- packages/wonder-blocks-data/src/index.js
This just exports an existing method so that we can use it in our non-React implementation of gqlFetch in webapp.
Issue: FEI-4517
`yarn test`
`yarn flow`
> [fei4517.1] Export getGqlDataFromResponse

- .changeset/strong-penguins-kneel.md
- packages/wonder-blocks-testing/src/__docs__/exports.respond-with.stories.mdx
- packages/wonder-blocks-testing/src/__docs__/exports.settle-controller.stories.mdx
- packages/wonder-blocks-testing/src/__tests__/make-mock-response.test.js
- packages/wonder-blocks-testing/src/__tests__/settle-controller.test.js
- packages/wonder-blocks-testing/src/__tests__/settle-signal.test.js
- packages/wonder-blocks-testing/src/index.js
- packages/wonder-blocks-testing/src/make-mock-response.js
- packages/wonder-blocks-testing/src/settle-controller.js
- packages/wonder-blocks-testing/src/settle-signal.js
This introduces a pattern similar to `AbortController` and `AbortSignal` (but with a little less implementation - adding a `onsettled` event listener property seemed overkill, for example), but for settling a promise.
I chose this pattern so that it was familiar with existing APIs/solutions.
Now folks can create a `SettleController`, then pass it's `signal` property to the various `RespondWith` methods to create a pending outcome that can be settled (rejected or resolved) by calling `settle()` on the `SettleController`.
This means we can support more complex test scenarios where the order of operations is important. Previously, folks would need to create their own promises and responses in order to create this kind of behavior.
In the next PR, I'll be exposing a first class way to turn a …
> [fei4681.1] Introduce response settling

- .changeset/brown-elephants-boil.md
- packages/wonder-blocks-data/src/util/__tests__/get-gql-request-id.test.js
- packages/wonder-blocks-data/src/util/get-gql-request-id.js
This modifies the `getGqlRequestId` method to handle variables that are arrays or objects in a way that is idempotent and readable. Before this change, the nested fields were unsorted which could lead to the same query not sharing cache because of the field orders being different. Of course, we don't sort arrays as array order can have meaning, but this does change how they are encoded in the generated identifier so that they are more readable (i.e. not peppered with %-encodings).
So, now, we turn nested elements and fields into sub-variable keys that are sorted the same way as top-level variables.
For example, an array variable named `x` with the value `[1, 2, 3]`, is now encoded as `x.0=1&x.1=2&x.2=3`, and similarly, an object variable named `y` with the value `{a: 1, b: 2, c: 3}` is …
> [fei4736.1] Handle array and object variables so that requestIDs are idempotent and readable

- .changeset/sour-otters-poke.md
- packages/wonder-blocks-tooltip/src/__tests__/__snapshots__/generated-snapshot.test.js.snap
- packages/wonder-blocks-tooltip/src/components/tooltip-tail.js
Slack convo: https://khanacademy.slack.com/archives/C8Z9DSKC7/p1662657335181759
The tooltip-tail is an SVG which the OSX VoiceOver was seeing as an image. The image is decorative and isn't super useful for users using screen readers, so I'm hiding it from screen readers with [aria-hidden](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden).
I can write a unit test if that's helpful, but I figured it'd be more noise than anything. I manually tested with Storybook and the results of using aria-hidden were what I was hoping for.
> add aria-hidden to tooltip-tail

- .changeset/breezy-wasps-allow.md
- packages/wonder-blocks-data/src/util/__tests__/get-gql-request-id.test.js
- packages/wonder-blocks-data/src/util/get-gql-request-id.js
Although I think we really should only use primitive types within variables, there are currently some cases where we pass `Date` objects (and maybe other non-primitive object types).
Previously, the request ID generation ignored these because they went down a path that only converted them if `Object.entries` returned any entries.
Now, we do a little more effort to ensure that even if there are no results from `Object.entries`, we still get that object value represented in the ID somehow.
Issue: FEI-4762
`yarn test`
> [fei4762.1.betterrequestids] Handle non-standard objects better

- .changeset/cold-items-fix.md
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-dropdown/src/components/__docs__/single-select.stories.js
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/multi-select.js
- packages/wonder-blocks-dropdown/src/components/single-select.js
- packages/wonder-blocks-dropdown/src/index.js
We previously created a new functionality to be able to pass translated
strings to `MultiSelect` using a `labels prop` that is used by the consumers
passing `i18n.()...` strings.
This PR is responsible for adding a similar functionality to
`SingleSelect`, but with some minor differences from `MultiSelect` (we
don't need to support all the texts multiselect does).
Also removed some WB interdependencies that are not really used by the
Dropdown package.
JIRA: https://khanacademy.atlassian.net/browse/WB-1318
Verify that the `Custom Labels` story allows passing different labels.
> WB-1318: Add `labels` prop to `SingleSelect` to pass translated strings

- .changeset/shaggy-ladybugs-count.md
- packages/wonder-blocks-form/src/components/__docs__/radio.stories.js
- packages/wonder-blocks-form/src/index.js
It doesn't really make sense to use Radio on its own.  RadioGroup + Choice provides standard formatting as well as better accessibility (since it renders as `<fieldset>`).
This was discussed on Slack in this thread: https://khanacademy.slack.com/archives/C4PE1QM5Y/p1666365101733479
Issue: None
- yarn start:storybook, see that the Radio stories are still accessible for dev work
- yarn jest
> Make Radio private to encourage use of RadioGroup

- .changeset/flat-snails-tease.md
- packages/wonder-blocks-clickable/src/components/__tests__/clickable-behavior.test.js
- packages/wonder-blocks-clickable/src/components/__tests__/clickable.test.js
I'd like to add a `useClickable` hook and update `ClickableBehavior` to use it.  This will allow use to get rid of `getClickable` since we'll be able to determine if there's a router or not by simply using `useHistory`.  Before we can do any of that though, we need to convert all of our enzyme tests to testing library because enzyme (our at least the version we're on) doesn't support testing components using hooks.
The reason why I want to create a `useClickable` hook is that I was going through the "Advanced React Patterns" workshop that's part of Epic React and learned about hooks that return a props object.  That seemed pretty similar to what `ClickableBehavior` does expect it's a full blown component that provides props for its children to spread into some other component.
Updating …
> Update wonder-blocks-clickable tests to use @testing-library

- .changeset/pink-plums-cross.md
- packages/wonder-blocks-form/src/components/__docs__/checkbox-group.stories.js
- packages/wonder-blocks-form/src/components/__docs__/labeled-text-field.argtypes.js
- packages/wonder-blocks-form/src/components/__docs__/labeled-text-field.stories.js
- packages/wonder-blocks-form/src/components/__tests__/checkbox-group.test.js
- packages/wonder-blocks-form/src/components/__tests__/field-heading.test.js
- packages/wonder-blocks-form/src/components/__tests__/radio-group.test.js
- packages/wonder-blocks-form/src/components/checkbox-group.js
- packages/wonder-blocks-form/src/components/checkbox.js
- packages/wonder-blocks-form/src/components/choice-internal.js
- packages/wonder-blocks-form/src/components/choice.js
- packages/wonder-blocks-form/src/components/field-heading.js
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/radio-group.js
- packages/wonder-blocks-form/src/components/radio.js
label, description, and error props on components in wonder-blocks-form are too restrictive (sometimes accepting just strings).  Sometimes designs call for markup in these props such as links or bolded words.  This PR makes these props accept any React.Node so that developers can implement designs without having to use workarounds.
- yarn jest
- yarn flow
> WB-1430: Update form component types to accept React.Node

- .changeset/stupid-starfishes-heal.md
- packages/wonder-blocks-form/src/components/__docs__/checkbox-group.stories.js
- packages/wonder-blocks-form/src/components/__docs__/radio-group.stories.js
- packages/wonder-blocks-form/src/components/__tests__/checkbox-group.test.js
- packages/wonder-blocks-form/src/components/__tests__/radio-group.test.js
- packages/wonder-blocks-form/src/components/checkbox-group.js
- packages/wonder-blocks-form/src/components/radio-group.js
As I was upgrading components in webapp to use v3 of wonder-blocks-form (which removes Radio and requires RadioGroup), I noticed that in some places we provide conditional children.  Neither RadioGroup or CheckboxGroup handle this case, but our dropdown components do.  This PR updates RadioGroup and CheckboxGroup to allow falsy children (and filter them out) when rendering.  This makes them consistent with the dropdown components in terms of how we deal with children.
Issue: WB-1430
- yarn jest wonder-blocks-form
- yarn start:storybook
- check that the new stories I added render without their last child
> WB-1430.1: Allow falsy children in CheckboxGroup and RadioGroup

- .changeset/clean-cameras-admire.md
- packages/wonder-blocks-form/src/components/checkbox-group.js
- packages/wonder-blocks-form/src/components/radio-group.js
Converting children to an array in #1631 cause issues in webapp with React complaining about children not having a 'key' prop.  We do set the 'key' prop on the Choice, but React doesn't see this because the Choice is wrapped in a Fragment.  The wrapper isn't necessary and removing it should fix the issue in webapp.
Issue: WB-1430
- let CI run the tests
> WB-1430.2: Don't wrap cloned Choices in fragments

- .changeset/real-rocks-attack.md
- packages/wonder-blocks-clickable/src/components/__tests__/clickable.test.js
- packages/wonder-blocks-clickable/src/components/clickable.js
Currently, if no aria label is provided, Clickable components
have `aria-label=""`. Instead of having an empty aria label,
it should just not have the aria label attribute.
- Remove the default value of aria-label in Wonder Blocks Clickable
- Add tests for aria label values
Issue: https://khanacademy.atlassian.net/browse/WB-1429
`yarn jest packages/wonder-blocks-clickable/src/components/__tests__/clickable.test.js`
Storybook
- Go to https://khan.github.io/wonder-blocks/?path=/story/clickable-clickable--basic
- Inspect the <a> element.
- Observe that it has an empty aria-label attribute.
- Now go to http://localhost:6061/?path=/story/clickable-clickable--basic
- Confirm there is no aria-label by default when inspecting the element
Before (prod storybook):
After (local storybook):
> Remove default aria-label from WB Clickable

- .changeset/stupid-chefs-speak.md
- packages/wonder-blocks-core/src/__docs__/exports.use-render-state.stories.mdx
- packages/wonder-blocks-core/src/components/render-state-root.js
- packages/wonder-blocks-core/src/hooks/__tests__/use-render-state.test.js
- packages/wonder-blocks-core/src/hooks/use-render-state.js
- packages/wonder-blocks-core/src/hooks/use-unique-id.js
- packages/wonder-blocks-core/src/index.js
This hook provides access to the value of RenderStateContext which differentiates between initial renders (server and rehydration) to standard renders (on the client after rehydration).  This information can be useful in helping the client avoid rehydration errors.
This work was motivated by https://github.com/Khan/webapp/pull/9508.
- let CI run its checks
- yarn start:storybook, check that the docs are appearing as intended
> Add 'useRenderState' hook to wonder-blocks-core

- .changeset/few-eggs-dress.md
- .changeset/sharp-otters-sleep.md
- .storybook/preview.js
- packages/wonder-blocks-modal/package.json
- packages/wonder-blocks-toolbar/package.json
- packages/wonder-blocks-toolbar/src/components/__docs__/toolbar.argtypes.js
- packages/wonder-blocks-toolbar/src/components/__docs__/toolbar.stories.js
- packages/wonder-blocks-toolbar/src/components/toolbar.js
We noticed that the current `Toolbar` layout doesn't allow for any of
the content nodes to use all the available space.
This PR modifies the `Toolbar` layout to allow doing this.
See Slack thread: https://khanacademy.slack.com/archives/C8Z9DSKC7/p1667842562518939
While I was at that, I also did a bit of refactoring to reduce the
number of elements rendered and also updated the styles to use WB tokens
(e.g. Spacing and Color).
Issue: WB-1145
Test Plan:
Navigate to the `Toolbar > Responsive` story and resize the window to
verify that the content flows as expected.
https://5e1bf4b385e3fb0020b7073c-wtvdnqhlph.chromatic.com/?path=/story/toolbar-toolbar--responsive
1. In `small` screens, the main button uses all the available space and
the secondary button is hidden.
2. In `large` screens, the …
> WB-1145.2: Allow more flexibility in Toolbar component

- .changeset/odd-paws-hang.md
- .changeset/seven-bikes-sing.md
- packages/wonder-blocks-modal/src/components/__docs__/modal-launcher.stories.js
- packages/wonder-blocks-modal/src/components/__docs__/one-pane-dialog.argtypes.js
- packages/wonder-blocks-modal/src/components/__tests__/one-pane-dialog.test.js
- packages/wonder-blocks-modal/src/components/modal-dialog.js
- packages/wonder-blocks-modal/src/components/one-pane-dialog.js
This allows us to add attributes like `aria-describedby` to the modal. Note that these props were already in the types, but did nothing.
Issue: TP-7580
Open `ModalLauncher`'s "navigation with focus trap" story in Safari with VoiceOver enabled and verify that it reads the body text
> Handle `aria-describedby` in `OnePaneDialog` and `ModalDialog`, and remove unused aria props from Flow types

- .changeset/gentle-pianos-travel.md
- packages/wonder-blocks-banner/src/components/__docs__/banner.stories.js
- packages/wonder-blocks-banner/src/components/__tests__/banner.test.js
- packages/wonder-blocks-banner/src/components/banner.js
Sometimes the actions need more stuff than the current
implementation allows them to do (for example: button
with spinner, button with beforeNav).
Here, Banner actions can now have custom actions using
the "custom" type with a node passed in.
Issue: none
http://localhost:6061/?path=/docs/banner--with-mixed-actions
yarn jest packages/wonder-blocks-banner/src/components/__tests__/banner.test.js
> Add support for custom actions to Banner

- .changeset/chilled-pens-fetch.md
- packages/wonder-blocks-popover/src/components/__docs__/popover.stories.js
Previously, the button that opens the popover in the "Popover With
initialFocusId" story referenced a "Next" button in the popover, which
doesn't exist. This commit changes the button text to reference the "It
is focused!" button, which does exist.
Issue: none
- Run `npm run start:storybook`.
- View the Popover > Popover > With initialFocusId story.
- Verify that the button says: Open with initial focus on the "It is
focused!" button.
- Click the button.
- Verify that the "It is focused!" button in the popover has focus.
Before change:
After change:
> Fix the text of a popover story button

- .changeset/selfish-gifts-destroy.md
- packages/wonder-blocks-form/src/components/checkbox-group.js
Just a simple typing change that aligns the types with the commented usage and makes using this component a little easier.
Issue: WB-1472
`yarn flow`
> [🔥AUDIT🔥] Allow maybe values on CheckboxGroup errorMessage prop

- .changeset/cold-dingos-smash.md
- packages/wonder-blocks-dropdown/src/components/__docs__/single-select.stories.js
- packages/wonder-blocks-dropdown/src/components/dropdown-core.js
- packages/wonder-blocks-dropdown/src/components/select-opener.js
A bug was discovered where the dropdown box alignment shifts when the selected option changes from a blank option to an option with text. This PR adds a story to test the behavior of the dropdown box when nested in text as an inline-block, plus adds CSS for inline-block dislay and middle vertical alignment to styles.menuWrapper. As a result, the alignment no longer shifts when an option with text replaces an empty option.
With inline-block setting, before vertical alignment
With inline-block setting, after vertical alignment
Issue: LP-13114
- confirm all checks pass
- confirm story works as expected
- confirm other stories work as expected
-> Should there be a changeset for this? If so, is the summary I added to the changeset acceptable?
-> Will changing the display to inline-block for …
> Stop dropdown box from shifting position on change from empty to filled state

- .changeset/green-chicken-rush.md
- packages/wonder-blocks-form/src/components/labeled-text-field.js
- packages/wonder-blocks-form/src/components/text-field.js
We had to use "internal" class names for the components used in
`TextField` and `LabeledTextField` because Styleguidist was not able to
resolve the names properly (this was an issue with `Styleguidist` +
`forwardRef`).
Now that Styleguidist is gone, we can replace the "internal" class names
with the intended ones, as this no longer causes any issues with
Storybook.
NOTE: This is a super small change that will help us with better
readability when using React DevTools.
Issue: WB-1081
Test Plan:
Verify that all the checks pass (specially unit tests) and that the
`TextField` and `LabeledTextField` stories work fine.
> WB-1081: TextField - Replace all "internal" Class Names to intended Names

- .changeset/rude-spies-enjoy.md
- packages/wonder-blocks-tooltip/src/components/__tests__/__snapshots__/tooltip-tail.test.js.snap
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-anchor.test.js
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-bubble.test.js
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-popper.test.js
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-tail.test.js
- packages/wonder-blocks-tooltip/src/components/tooltip-tail.js
- packages/wonder-blocks-tooltip/src/util/__tests__/ref-tracker.test.js
Summary:
Final part of the porting of `wonder-blocks` from Enzyme to RTL.
This ports the `wonder-blocks-tooltip` package.
Test Plan:
```
yarn test
```
> hack-enzyme.8: Port `wonder-blocks-tooltip` to RTL

- .changeset/great-readers-jam.md
- .github/workflows/node-ci-pr.yml
- package.json
We recenty removed webpack from our build process (#1720) and in the
process I accidentally removed the flow exports that were being done at
the end of the webpack build script. This PR adds them back in.
Verify that the build works fine (this can be verified with the check build
sizes workflow step).
https://github.com/Khan/wonder-blocks/actions/runs/4144792470/jobs/7168301496#step:5:218
> [🔥AUDIT🔥] Fix flow exports

- .changeset/bright-rocks-run.md
- build-settings/rollup.config.js
We recently removed Webpack from the build process, but we still need to
export the CJS build as the main entry point.
This is because the CJS build is the only one that works for some
particular cases such as when we use the `flow-enums-runtime` package.
In this Flow enums case, this happens because FlowJS needs to convert
the enums to code that can be executed at runtime. This is done by the
`babel-plugin-transform-flow-enums` plugin, which is configured to
transform enums from:
```
enum Foo {
Bar,
Baz,
};
```
to:
```
const Foo = require("flow-enums-runtime").Mirrored(["Bar", "Baz"]);
```
The problem with this is that the `flow-enums-runtime` package expects
us to import the CJS build, so it can import the module via `require`.
I attempted to fix this by changing the …
> Export the CJS build as the main entry point

- .changeset/curly-meals-sing.md
- package.json
- packages/wonder-blocks-data/package.json
- packages/wonder-blocks-icon/package.json
- packages/wonder-blocks-icon/src/components/__docs__/icon.stories.js
- packages/wonder-blocks-icon/src/index.js
- packages/wonder-blocks-testing/package.json
- yarn.lock
This PR also fixes a Flow error with one of the uses of 'entries()' and tweaks out we export icons to use 'export * from'.  We use this pattern in wonder-stuff as well.
Issue: FEI-4957
- yarn flow
- yarn lint
- yarn start
- verify that http://localhost:6061/?path=/story/icon-icon--variants loads without any issues
- let CI run the remainder of the checks
> FEI-4957: Update to use migrated wonder-stuff packages

- .changeset/stale-rivers-bow.md
- packages/wonder-blocks-core/src/components/__tests__/render-state-root.test.js
- packages/wonder-blocks-core/src/components/render-state-context.js
- packages/wonder-blocks-core/src/components/render-state-root.js
- packages/wonder-blocks-core/src/components/with-ssr-placeholder.js
- packages/wonder-blocks-core/src/hooks/__tests__/use-render-state.test.js
- packages/wonder-blocks-core/src/hooks/use-render-state.js
- packages/wonder-blocks-core/src/hooks/use-unique-id.js
- packages/wonder-blocks-core/src/index.js
- packages/wonder-blocks-data/src/components/__tests__/data.test.js
- packages/wonder-blocks-data/src/components/data.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-cached-effect.test.js
- packages/wonder-blocks-data/src/hooks/__tests__/use-hydratable-effect.test.js
- packages/wonder-blocks-data/src/hooks/use-cached-effect.js
- packages/wonder-blocks-data/src/hooks/use-hydratable-effect.js
- packages/wonder-blocks-data/src/index.js
- packages/wonder-blocks-data/src/util/types.js
The codemod we're using can't deal with Flow enums so we're temporarily converting them to POJOs.
- let CI do its thing
> FEI-4966.2: Convert Flow enums to POJOs

- .changeset/seven-mangos-leave.md
- packages/wonder-blocks-banner/src/components/banner.js
TypeScript doesn't like this pattern.  Instead, we provide defaults when destructuring props inside the component.
- yarn flow
> FEI-4966.2a: Replace .defaultProps on functional components

- .changeset/slimy-shirts-juggle.md
- packages/wonder-blocks-clickable/src/components/clickable-behavior.js
- packages/wonder-blocks-clickable/src/components/clickable.js
- packages/wonder-blocks-link/src/components/__tests__/link.flowtest.js
- packages/wonder-blocks-link/src/components/link.js
- packages/wonder-blocks-modal/src/components/modal-launcher.js
- packages/wonder-blocks-popover/src/components/popover-content.js
TypeScript's pattern for conditional props is different from Flow's pattern for disjoint props and the codemod doesn't know how to do the conversion properly.  Also, there's the issue of having to publishing Flow types until the migration is complete.  This PR addresses the issue by temporarily removing the use of disjoint props.
- yarn flow
> FEI-4966.2b: Remove uses of disjoint props

- .changeset/afraid-lamps-begin.md
- .changeset/quiet-pets-yell.md
- .changeset/thirty-paws-admire.md
- packages/wonder-blocks-core/src/util/add-style.tsx
- packages/wonder-blocks-core/src/util/util.ts
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-popover/src/components/popover-dialog.tsx
- packages/wonder-blocks-progress-spinner/src/components/circular-spinner.tsx
- packages/wonder-blocks-testing/src/harness/adapters/css.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.tsx
- packages/wonder-blocks-tooltip/src/util/types.ts
- types/aphrodite.d.ts
This PR updates the aphrodite lib def to use the 'CSSProperties' from "react".  This should keep the types more up-to-date.  'CSSProperties' is extended with pseudo-selectors, media queries, and a few browser specific properties.
- yarn typecheck
- let CI run
> FEI-4966.12: Improve aphrodite lib def

- .changeset/kind-terms-melt.md
- package.json
- packages/wonder-blocks-data/package.json
- packages/wonder-blocks-icon/package.json
- packages/wonder-blocks-testing/package.json
- yarn.lock
The wonder-stuff packages now include the 'types' field in their package.json files.  This PR updates the wonder-stuff deps that wonder-blocks is using so that we can lock step all uses of wonder-stuff, all the way up to and including webapp.
Issue: None
- let CI run
> Update wonder-stuff dependencies

- .changeset/olive-spiders-eat.md
- __docs__/wonder-blocks-banner/banner.stories.tsx
- __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
- __docs__/wonder-blocks-link/link.stories.tsx
- packages/wonder-blocks-link/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-link/src/components/link-core.tsx
While the new dashed link is available, we are updating it to the old underline
style to match the non-wonder blocks links across webapp. An audit is currently
being run so we can update all these to wonder blocks link.
Once all the legacy links have been updated to use Wonder Blocks Link, we can
finally use the dashed link style.
- Update styles so that the links use solid 1px underlines.
- Comment out the old styles and add a TODO comment above them so we can easily go back.
- The TODOs should reference WB-1521.
Issue: https://khanacademy.atlassian.net/browse/WB-1520
- Go to http://localhost:53078/?path=/story/link--variants
- Confirm all the chromatic interaction tests are passing
- Confirm all the links have 1px solid underlines with no offset.
> Use solid underline for links (until audit can be completed)

- .changeset/fluffy-humans-kiss.md
- build-settings/gen-flow-types.ts
flowgen hasn't been updated in a while and the TS lib def for React keeps getting updated.  As a result there are some new types that the tool doesn't know about.  This PR adds some more post-processing logic to gen-flow-types.ts to rewrite "JSX.LibraryManagedAttributes<>" as "React.ElementConfig<>".
Issue: None
- test the regex replacement code manually on a test string
- see that it's doing the expected replacement in the logging
```
✅ wrote: packages/wonder-blocks-clickable/dist/util/get-clickable-behavior.js.flow
replacing 'JSX.LibraryManagedAttributes<
typeof ClickableBehavior,
React.ComponentProps<typeof ClickableBehavior>
>' with 'React.ElementConfig<typeof ClickableBehavior>'
```
> Replace new TS React types

- .changeset/fluffy-geckos-switch.md
- __docs__/wonder-blocks-core/with-ssr-placeholder.stories.tsx
- build-settings/gen-flow-types.ts
- package.json
- packages/wonder-blocks-core/src/components/__tests__/unique-id-provider.test.tsx
- packages/wonder-blocks-core/src/components/__tests__/with-ssr-placeholder.test.tsx
- packages/wonder-blocks-core/src/components/unique-id-provider.tsx
- packages/wonder-blocks-core/src/components/with-ssr-placeholder.tsx
- packages/wonder-blocks-core/src/util/aria-types.ts
- yarn.lock
- View and Text's props are now inexact since in the generated types to support random props being added to them in webapp
- AriaAttributes is a type now so that it can be spread in the generate flow types of various components
- ChangeEvent will now be converted to SyntheticInputEvent [flowgen#6f8276dcf4ac9d8324d66c99589e3fb9e1cc8125]
- ComponentType will not longer be changed [flowgen#6f8276dcf4ac9d8324d66c99589e3fb9e1cc8125]
See https://github.com/Khan/flowgen/pull/4 for flowgen changes.
Issue: FEI-5042
- run flowgen manually on text.d.ts and view.d.ts without the '--no-inexact' flag, see that the generate .js.flow file uses inexact types for their props
> FEI-5042.1: Fix issues with Flow types in wonder-blocks-core

- .changeset/six-kiwis-divide.md
- packages/wonder-blocks-data/src/components/__tests__/data.test.tsx
- packages/wonder-blocks-data/src/components/data.ts
Callbacks should always allow React.ReactNodes to be returned.  I missed updating this one in wonder-blocks-data.  I'm updating wonder-blocks-data at the same time as wonder-blocks-core.  I tested this change in webapp by editing node_modules directly.
Issue: None
- see that the 'children' prop in data.js.flow now allows a 'React.Node' to be returned.
> Update <Data>'s 'children' prop to allow a ReactNode to be returned

- .changeset/metal-games-compete.md
- build-settings/gen-flow-types.ts
Some uses of JSX.LibraryManagedAttributes<> use React.ComponentProps and other use React.ElementProps.  This PR updates gen-flow-types.ts to handle both cases.
Issue: None
- change the glob in gen-flow-types.ts to wonder-blocks-typography
- see the following in the console log
replacing 'JSX.LibraryManagedAttributes<
typeof Text,
React.ElementProps<typeof Text>
>' with 'React.ElementConfig<typeof Text>'
> Update gen-flow-types.ts to better handle JSX.LibraryManagedAttributes

- .changeset/good-lemons-stare.md
- packages/wonder-blocks-data/src/util/graphql-types.js.flow
- packages/wonder-blocks-data/src/util/graphql-types.ts
Fixing #1803 revealed other issues in the Flow type definitions for wonder-blocks-data.  I'm not sure why these didn't show up when I was testing the changes from #1803 in webapp.
Issue: None
- apply the changes manually in webapp, restart flow, see all of the DocumentNode errors go away
> [🔥AUDIT🔥] Fix DocumentNode Flow type

- __docs__/wonder-blocks-link/link.argtypes.ts
- __docs__/wonder-blocks-link/link.stories.tsx
- packages/wonder-blocks-link/src/components/__tests__/link.test.tsx
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-link/src/components/link.tsx
- Adds optional `startIcon` and `endIcon` props to `Link`
- `endIcon` overrides the default external icon when `target="_blank"`, so if `endIcon` is passed in, it will show `endIcon` after the link label instead of `externalIcon`.
- Adds story for links with start and end icons, as well as an external link using `endIcon` in place of `externalIcon` (screenshot)
Issue: WB-1085
- Ran yarn test and yarn typecheck
- Set start and end icons in control panel and inspected change in the DOM
- Set `endIcon` and `target` to `"_blank"`, confirmed that `endIcon` renders instead of `externalIcon`, and inspected in the DOM 
- <img width="123" alt="Screenshot 2023-03-16 at 1 59 59 PM" src="https://user-images.githubusercontent.com/100858764/225711278-19fd1037-9076-4a53-b2e2-508ab8ebe33c.png">
- <img …
> Add startIcon and endIcon props to Link

- .changeset/poor-trainers-join.md
- .changeset/soft-cherries-boil.md
- build-settings/gen-flow-types.ts
- packages/wonder-blocks-i18n/src/components/i18n-inline-markup.tsx
Many of our components use 'children: React.Element<typeof Component>' (Flow) to restrict which components can be used as children.  In TypeScript the pattern is 'React.ReactElement<React.ComponentProps<typeof Component>>' which flowgen was converting to 'React.ReactElement<React.ComponentProps<typeof Component>>' which is wrong for Flow.
This PR updates gen-flow-types.ts to fix this using a regex to post process the incorrect type.  We'll want to port this to flowgen for use with converting perseus and webapp.
Issue: FEI-5042
- change the glob in gen-flow-types.ts to wonder-blocks-breadcrumbs
- check that the generate .js.flow files for wonder-blocks-breadcrumbs are correct
> Fix issue with some React.Element<> Flow types and more

- .changeset/famous-donuts-tan.md
- build-settings/gen-flow-types.ts
It turns out that some of these types span multiple lines so we need to handle that.
Issue: None
- Test the new regex out on regex101.com against single line and multi-line cases
- Temporarily change glob to `wonder-blocks-dropdown` and run `yarn build:flowtypes`
- Check the output for dist/util/types.js.flow to see that multi-line instances of these types are being handled correctly
**dist/util/types.js.flow**
```
export type Item =
| false
| React.Element<typeof ActionItem | typeof OptionItem | typeof SeparatorItem>;
```
> [🔥AUDIT🔥] Handle React.Element<React.ElementProps<...>> spanning multiple lines

- .changeset/dull-trainers-peel.md
- packages/wonder-blocks-testing/src/gql/mock-gql-fetch.ts
The codemod used for the changes in https://github.com/Khan/wonder-blocks/pull/1749 stripped the indentation from this template literal. This fixes that.
Issue: FEI-5042
The snapshot tests in webapp caught this. If they pass without udpate, we know it's fixed.
> [🔥AUDIT🔥] [fixmockgqlfetch] Fix the indentation for outputting GQL operations

- .changeset/pink-terms-fry.md
- packages/wonder-blocks-testing/src/fetch/__tests__/__snapshots__/mock-fetch.test.ts.snap
- packages/wonder-blocks-testing/src/fetch/mock-fetch.ts
This fixes a regression that was introduced via the codemod in https://github.com/Khan/wonder-blocks/pull/1749.
Issue: FEI-5042
`yarn test`
Also will verify that the existing snapshots in webapp pass as-is with this change.
> [🔥AUDIT🔥] [fixfetchmock] Fix formatting of fetch mock errors

- .changeset/metal-carrots-wonder.md
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
Using a named import confuses vite since moment doesn't have true named exports.  It isn't an ES6 module.
Issue: None
- apply this change manually in webapp's node_modules folder
- clear the vite cache by deleting node_modules/.vite
- restart vite
- see that the logged out homepage loads at localhost:8224/
> Fix moment import

- .changeset/dull-zoos-learn.md
- .changeset/metal-worms-heal.md
- __docs__/wonder-blocks-link/link.argtypes.ts
- __docs__/wonder-blocks-link/link.stories.tsx
- packages/wonder-blocks-link/src/components/link.tsx
Add title prop to Link
Issue: WB-1453
- Ran yarn test & yarn typecheck
- Set title prop in control panel and inspected title attribute change in the DOM
- Added WithTitle story that renders link with a title attribute that appears when hovering over the link
> add title to link

- .changeset/small-masks-appear.md
- packages/wonder-blocks-link/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-link/src/components/link-core.tsx
Fixed link to use aphrodite style instead of inline style.
Updated span to StyledSpan
Issue:
Inspect in Storybook to confirm styling is correct.
http://localhost:6061/?path=/story/link--start-and-end-icons&globals=outline:true
> Fix Link inline style

- .changeset/fifty-crabs-develop.md
- packages/wonder-blocks-link/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-link/src/components/link-core.tsx
Initially, the link text/`children` was nested inside a `span` element in order to use `verticalAlign` to center the text with icons.
Nesting `children` in a `span` broke other links that don't have icons (screenshots). 
This change checks first if icon props are present. If true, the text/`children` is nested inside a `span` element.
If the link has no icons, no `span` is needed.
Broken:
From production:
Also removed `textUnderlineOffset` from `sharedStyles` because without the `span` element, the underline sat too low when inline:
Added `textUnderlineOffset` to `sharedStyles.withIcon` and `restingInline` to match the underline when inline:
Issue: n/a
For start and end icon props:
- In Storybook, inspect the Default `Link` story. 
- Confirm the link text is not nested inside a `span` …
> Remove span from links without icons

- .changeset/dirty-waves-remain.md
- package.json
- yarn.lock
Flowgen wasn't converting React.ForwardExoticRefComponent<> or React.ForwardedRef<> and Flow was just ignoring those types in webapp.  This was resulting it issues with incorrect props not being detected in some components.
Issue: None
- check text-field.js.flow and add-style.js.flow in the dist folders of wonder-blocks-form and wonder-blocks-core to see that they contain React.AbstractComponent<> and React.Ref<> instead of the types listed in the summary.
> Update flowgen to convert more React types properly

- .changeset/cool-spiders-yell.md
- package.json
- packages/wonder-blocks-testing/src/harness/make-test-harness.js.flow
- yarn.lock
This PR updates flowgen to include https://github.com/Khan/flowgen/pull/9 which fixes issues with refs not working with HTML elements.  It also adds a .js.flow override for makeTestHarness. Previously I had fixed one issue with the types that flowgen was generating for that file, but this uncovered a new issue that wasn't detected until I updated wonder-blocks in webapp earlier this afternoon.  That file contains pretty complicated types. It's easier to use an override and use the Flow types we used to use for makeTestHarness.
Issue: None
- check that the types for LabeledTextFiela dn TestField and using 'forwardRef: {|current: HTMLInputElement | null|}
- check that the override types for makeTestHarness got copied over into the dist folder
> Fix Flow errors in wonder-blocks-from and wonder-blocks-testing

- .changeset/wise-experts-sell.md
- packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
- packages/wonder-blocks-core/src/util/types.ts
- packages/wonder-blocks-dropdown/src/components/action-menu.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- packages/wonder-blocks-modal/src/components/modal-launcher.tsx
- packages/wonder-blocks-popover/src/components/popover.tsx
- packages/wonder-blocks-timing/src/util/types.ts
- packages/wonder-blocks-tooltip/src/components/tooltip.tsx
The problem is that 'getDerivedStateFromProps' ends up in the .d.ts files we generate and the React lib defs have its 'props' param wrapped in Readonly<>. This is causing type errors in webapp.  We need to make sure all components that make use of 'getDerivedStateFromProps' are also using readonly props for this static method.  I've updated all props and state types to be readonly. This is generally a good practice since neither of those should be mutated directly.
I've created https://khanacademy.atlassian.net/browse/FEI-5164 to track writing a lint rule for this.  Ideally all components should have readonly props and state.
Issue: FEI-5161
- yarn tsc
- let the tests run on CI
> FEI-5161: Update component using getDerivedStateFromProps to have readonly props and state

- .alexrc
- .changeset/strong-geckos-build.md
- packages/wonder-blocks-core/src/components/render-state-context.ts
- packages/wonder-blocks-data/src/components/intercept-context.ts
- packages/wonder-blocks-data/src/hooks/__tests__/use-server-effect.test.ts
- packages/wonder-blocks-data/src/util/gql-router-context.ts
- packages/wonder-blocks-data/src/util/request-tracking.ts
- packages/wonder-blocks-layout/src/components/media-layout-context.ts
- packages/wonder-blocks-modal/src/components/modal-context.ts
- packages/wonder-blocks-popover/src/components/popover-context.ts
I was debugging some context-related changes in webapp and using React Dev Tools as well as the React Context extension for dev tools. I noticed that many of the contexts were given unhelpful generated names, which made it hard to find the context that I was looking for. This diff adds a display name to all of our contexts so that they can be more easily identified in dev tools.
This was found while working on the guide context stabilization work, so I'm tagging with that issue.
Issue: GL-568
`yarn test`
> [namedcontexts] Make sure contexts have a name

- .changeset/fuzzy-sheep-dream.md
- __docs__/wonder-blocks-popover/popover.stories.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover-dialog.test.tsx
- packages/wonder-blocks-popover/src/components/popover-dialog.tsx
- packages/wonder-blocks-popover/src/components/popover.tsx
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-tail.test.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-tail.tsx
This makes it so that the popover tail can be hidden for designs that warrant it. This new prop defaults to true so that existing uses are unchanged.
I made this a minor update for popover since it's a new prop on the primary usage. I made it only patch for tooltip as the primary usage is unchanged (it's only the TooltipTail component that changes).
Here's the default story for the popover that shows the tail:
Here's the new No Tail story that shows the popover without the tail:
Issue: WB-1556
`yarn start` and view the new story (and the old ones) to see that it works.
> [wb1556.1.notail] Make popover tail optional

- .changeset/seven-hairs-bake.md
- __docs__/wonder-blocks-form/text-field.stories.tsx
- __docs__/wonder-blocks-search-field/search-field.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-form/tsconfig-build.json
- packages/wonder-blocks-search-field/src/components/__tests__/search-field.test.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
- packages/wonder-blocks-search-field/tsconfig-build.json
Add autofocus prop to SearchField (and TextField) so that
they can receive focus on page load.
The example I added to storybook makes you press a button
to load the autofocus search field, because I didn't
want the story to autofocus when loading the Storybook site.
Issue: none
`yarn jest`
Storybook
SearchField: https://5e1bf4b385e3fb0020b7073c-uwyyegabqe.chromatic.com/?path=/docs/search-field-searchfield--with-autofocus
TextField: https://5e1bf4b385e3fb0020b7073c-uwyyegabqe.chromatic.com/?path=/docs/form-textfield--with-autofocus
> Add autofocus prop to SearchField

- .changeset/tough-beans-matter.md
- packages/wonder-blocks-core/src/hooks/__tests__/use-force-update.test.tsx
- packages/wonder-blocks-core/src/hooks/use-force-update.ts
This update makes sure that no matter how many times `forceUpdate` is called, it will trigger a re-render. Before this change, the new test case would fail because the boolean value, after multiple calls, would not have actually changed, so React never forced a new render.
With this update, things work as intended.
Issue: FEI-5213
`yarn test`
> [fei5213.1.useforceupdatefix] Fix useForceUpdate

- .changeset/five-dodos-count.md
- packages/wonder-blocks-core/src/hooks/__tests__/use-force-update.test.tsx
- packages/wonder-blocks-core/src/hooks/use-force-update.ts
While the previous "fix" corrected the issue of multiple calls before a render, it broke the situation where a hook that is based off `useForceUpdate` may need to trigger an async update outside of a render.
I discovered the issue when integrating the update into webapp where a hook failed because of the issue resolved by this PR.
This change ensures that every call to force an update will do a change, and thus make sure that calling hooks can trigger updates asynchronously between renders.
I have added an additional test case to capture the scenario where things broke. The original implementation handled it, but the updated one did not. This implementation should handle both situations.
Issue: FEI-5213
`yarn test`
> [forceupdatefix2] Tweak implementation so this works in all scenarios

- .changeset/tidy-islands-juggle.md
- packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx
- packages/wonder-blocks-popover/src/components/focus-manager.tsx
Currently, you can't tab back to the anchor after closing a popover.
It seems to be caused by the line changed in this PR.
For context, the `|| this.nextElementAfterPopover` was added
in order to reduce the number of re-calculations, but it
seems like removing this condition is necessary for correct behavior.
Issue: https://khanacademy.atlassian.net/browse/WB-1559
`yarn jest packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx`
^ I confirmed that the test fails with the old code (`if (!anchorElement || this.nextElementAfterPopover)`) and passes with the new code (`if (!anchorElement)` ) 🎉 
https://github.com/Khan/wonder-blocks/assets/13231763/cf5e3d1e-25ba-410f-896a-7150af22fb15
> Fix the issue where the anchor is no longer shift-tabbable after closing popover

- .changeset/fifty-cycles-juggle.md
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-button/src/components/button-core.tsx
Updated styling for tertiary button focus state to be a border instead of underline so that the states can be differentiated. Also updated some styling for other buttons.
Issue: WB-1420
- Wrote new interaction test/story for tertiary button
- Updated snapshots in unit tests
| Focus state before | Focus state after |
|--------|--------|
| <img width="154" alt="Screen Shot 2023-06-30 at 5 14 46 PM" src="https://github.com/Khan/wonder-blocks/assets/77523470/e648fc41-d6da-4958-97cd-33faf26cd288"> | <img width="196" alt="Screen Shot 2023-07-05 at 10 58 47 AM" src="https://github.com/Khan/wonder-blocks/assets/77523470/80a61809-b8cb-4fa5-a499-08074e34c4c5"> |
> Updating tertiary button focus state to be a border instead of underline

- .changeset/stale-buses-walk.md
- packages/wonder-blocks-link/src/components/link-core.tsx
Removed `StyledSpan` from links with icons because the `verticalAlign: center` and underline offset styles were not being applied correctly on Safari.
Also removed `withIcon` styling to keep link underline offset consistent.
| Before (in Safari) | After (in Safari) |
| --- | --- |
|<img width="313" alt="Screen Shot 2023-07-10 at 2 18 28 PM" src="https://github.com/Khan/wonder-blocks/assets/77523470/9998cbde-c66e-4982-952b-3f47806dd3f0"> | <img width="289" alt="Screen Shot 2023-07-10 at 2 18 56 PM" src="https://github.com/Khan/wonder-blocks/assets/77523470/6606e740-5135-41c3-b1ff-74417ff60503"> |
Issue: WB-1550
- Manual testing by checking storybook Link stories on both Chrome and Safari to ensure no inconsistencies between them
- Run `yarn test`
> Center inline link text with icon by removing styled span and updating vertical align

- .changeset/fuzzy-buses-breathe.md
- __docs__/wonder-blocks-banner/banner.stories.tsx
- packages/wonder-blocks-banner/src/components/banner.tsx
There are a couple of banners where the copy is being cut off because
of the overflow on the Wonder Blocks banner component. Here, I'm updating
it so that the text in WB Banner has `overflowWrap: break-word` so that
the long text line wraps
Issue: https://khanacademy.atlassian.net/browse/FEI-4898
also https://khanacademy.atlassian.net/browse/FEI-4823
Storybook
http://localhost:50875/?path=/docs/banner--long-text
- Resize the page and confirm that the text never goes under the
dismiss button, and that it never gets cut off of to the side.
The text should wrap.
> Fix banner overflow

- .changeset/few-chicken-help.md
- packages/wonder-blocks-core/src/components/__tests__/text.test.tsx
- packages/wonder-blocks-core/src/components/text.tsx
- packages/wonder-blocks-typography/src/components/__tests__/title.test.tsx
- packages/wonder-blocks-typography/src/components/title.tsx
We want to add ref forwarding for Title. This also means we need to
forward refs for Text.
To make this easier, I converted both Title and Text to functional
components.
Issue: https://khanacademy.atlassian.net/browse/WB-424
`yarn jest packages/wonder-blocks-typography/src/components/__tests__/title.test.tsx`
`yarn jest packages/wonder-blocks-core/src/components/__tests__/text.test.tsx`
Check that local storybook typography page matches the prod storybook typography page.
> Forward refs for Title and Text

- .changeset/nervous-knives-carry.md
- consistency-tests/__tests__/ref-forwarded.test.tsx
- packages/wonder-blocks-breadcrumbs/src/components/__tests__/breadcrumbs.test.tsx
- packages/wonder-blocks-breadcrumbs/src/components/breadcrumbs.tsx
Add ref forwarding to Breadcrumbs. To make this easier, I also
changed it to a functional component.
Issue: https://khanacademy.atlassian.net/browse/WB-424
`yarn jest packages/wonder-blocks-breadcrumbs/src/components/__tests__/breadcrumbs.test.tsx`
Confirm that the Breadcrumbs work as expected in storybook
> Add ref forwarding to Breadcrumbs

- .changeset/pink-guests-accept.md
- __docs__/wonder-blocks-tooltip/tooltip.argtypes.ts
- __docs__/wonder-blocks-tooltip/tooltip.stories.tsx
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip.test.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-content.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip.tsx
- packages/wonder-blocks-tooltip/src/util/types.ts
Exposed new `contentStyle` (color and padding) and `backgroundColor` props on `Tooltip` to allow some custom styling.
Issue: WB-1410
- `yarn test packages/wonder-blocks-tooltip`
- Experiment with styles in storybook
> Add style prop to tooltip

- .changeset/ninety-jobs-hammer.md
- __docs__/wonder-blocks-link/link.argtypes.tsx
- __docs__/wonder-blocks-link/link.stories.tsx
- consistency-tests/__tests__/ref-forwarded.test.tsx
- packages/wonder-blocks-icon/src/components/__tests__/icon.test.tsx
- packages/wonder-blocks-icon/src/components/icon.tsx
- packages/wonder-blocks-link/src/components/__tests__/link.test.tsx
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-link/src/components/link.tsx
We want the `startIcon` and `endIcon` props on `Link` to accept `Icon`
instead of `IconAsset`.
In this PR:
- Updated `startIcon` and `endIcon` to use type `Icon`
- Updated Icon so it forwards refs while I was here
- Updated tests for Icon so they use RTL convention
Issue: https://khanacademy.atlassian.net/browse/WB-1542
`yarn jest`
Go to Storybook and confirm that the Links and Icons look
exactly the same as before.
> Use Icon instead of IconAsset in Link

- .changeset/strange-suns-kick.md
- packages/wonder-blocks-clickable/src/util/get-clickable-behavior.ts
- packages/wonder-blocks-core/src/index.ts
- packages/wonder-blocks-core/src/util/types.propsfor.js.flow
- packages/wonder-blocks-core/src/util/types.propsfor.ts
- packages/wonder-blocks-core/src/util/types.ts
- packages/wonder-blocks-typography/src/components/body-monospace.tsx
- packages/wonder-blocks-typography/src/components/body-serif-block.tsx
- packages/wonder-blocks-typography/src/components/body-serif.tsx
- packages/wonder-blocks-typography/src/components/body.tsx
- packages/wonder-blocks-typography/src/components/caption.tsx
- packages/wonder-blocks-typography/src/components/footnote.tsx
- packages/wonder-blocks-typography/src/components/heading-large.tsx
- packages/wonder-blocks-typography/src/components/heading-medium.tsx
- packages/wonder-blocks-typography/src/components/heading-small.tsx
- packages/wonder-blocks-typography/src/components/heading-xsmall.tsx
- packages/wonder-blocks-typography/src/components/label-large.tsx
- packages/wonder-blocks-typography/src/components/label-medium.tsx
- packages/wonder-blocks-typography/src/components/label-small.tsx
- packages/wonder-blocks-typography/src/components/label-xsmall.tsx
- packages/wonder-blocks-typography/src/components/tagline.tsx
- packages/wonder-blocks-typography/src/components/title.tsx
- packages/wonder-blocks-typography/src/util/types.ts
This adds a new type, `PropsFor` that is like `React.ElementConfig` in flow, simplifying the interface of `JSX.LibraryManagedAttributes`.
I updated code that used `JSX.ManagedAttributes` to use `PropsFor` instead, so this change is dog-fooding the type.
I verified the flow equivalent that we output here:
https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602QF92kEdQD0AKgAEAARg0IAdwN6dAHSgUADhDS4rBhgYBK2PAZhoIcgMbEEweEIBuOztcfgcMAwAFAId6AwBeA2AAHzsDd2QDRXJeDDRWO2y1aKhIKHpXAFl+AGFApygFV0yACgcU+kLkiFSASgyAPmCQAAkAUQAZBYB5AEJImtj4pIGAMWcAHgAVQu8eADoAQV4GtB428g6ug6wofinsrx9cc4en0iOcQwLzeEymmTOeHOcxoGEopDasEQxwmUSgMSBOxG9F2AXIw1S+zQGSxhMOWwwEBgBmaf2gXVRNTqDQMnCGezxBJxzhJwDyBQMAGYKlA1Gi7MzXPx2djcYEuUTefysIUQoKQiKxWwQAA3MpM …
> [propsfor] Add PropsFor type

- .changeset/short-apes-flow.md
- .storybook/components/token-table.tsx
- .storybook/preview.js
- __docs__/wonder-blocks-theming/tokens-border.mdx
- __docs__/wonder-blocks-theming/tokens-color.mdx
- __docs__/wonder-blocks-theming/tokens-font.mdx
- __docs__/wonder-blocks-theming/tokens-spacing.mdx
- packages/wonder-blocks-theming/src/index.ts
- packages/wonder-blocks-theming/src/tokens.ts
Adds global tokens to the theming package. This includes border, color,
font, and spacing tokens.
This also adds a token table component to storybook.
1. **WB-1567: Add tokens to theming package [CURRENT]**
2. #1977
3. #1978
4. #1979 
5. #1981
6. #1982
7. Create Storybook example for adding theming support to a custom component (WIP)
Issue: WB-1567
Verify that the new tokens stories are in storybook.
https://5e1bf4b385e3fb0020b7073c-ywcimklozr.chromatic.com/?path=/docs/theming-tokens-border--docs
https://5e1bf4b385e3fb0020b7073c-ywcimklozr.chromatic.com/?path=/docs/theming-tokens-color--docs
https://5e1bf4b385e3fb0020b7073c-ywcimklozr.chromatic.com/?path=/docs/theming-tokens-typography--docs
https://5e1bf4b385e3fb0020b7073c-ywcimklozr.chromatic.com/?path=/docs/theming-tokens-spacing--docs
> WB-1567: Add tokens to theming package

- .changeset/khaki-pianos-brush.md
- packages/wonder-blocks-form/src/components/choice-internal.tsx
After forwarding refs, the snapshots showed that the checkbox and
radio `input` elements had a random `variant` attribute that isn't
supposed to be there. This was an oversight on my part when I updated
these to be functional components and shifted around their props in #1956.
I'm fixing that here by making sure I don't pass in all the props when it should
just be a subset.
Issue: none
Test plan:
- Go to the Checkbox and Radio (Internal) stories in storybook.
- Use the dev tools to confirm that they don't have `variant` in their attributes.
> Fix destructured props in Choice Internal

- .changeset/beige-oranges-call.md
- __docs__/wonder-blocks-form/checkbox-accessibility.stories.mdx
- __docs__/wonder-blocks-switch/switch-best-practices.mdx
- __docs__/wonder-blocks-switch/switch-best-practices.stories.tsx
- __docs__/wonder-blocks-switch/switch.argtypes.tsx
- __docs__/wonder-blocks-switch/switch.stories.tsx
- consistency-tests/__tests__/ref-forwarded.test.tsx
- consistency-tests/tsconfig.json
- packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
- packages/wonder-blocks-switch/package.json
- packages/wonder-blocks-switch/src/components/__tests__/switch.test.tsx
- packages/wonder-blocks-switch/src/components/switch.tsx
- packages/wonder-blocks-switch/src/index.ts
- packages/wonder-blocks-switch/tsconfig-build.json
- Add 'switch' role to ClickableBehavior
- Create new Switch component
- Add unit tests for Switch
- Add stories for Switch
- Add ref forwarding test for Switch
Issue: WB-1581
- Write new unit tests and run `yarn test packages/wonder-blocks-switch`
- Create new stories for use cases
> Create new primitive Switch component based on implementation spec

- .changeset/great-planes-vanish.md
- packages/wonder-blocks-clickable/src/components/__tests__/clickable.typestest.tsx
- packages/wonder-blocks-clickable/src/components/clickable.tsx
Looking at the implementation of ClickableBehavior, 'beforeNav' and 'safeWithNav' can be used without an 'href'.  This change to the types allows us to use 'Clicakble' in accordion-item.tsx in webapp without splitting its existing use in two.
Issue: None
- yarn tsc
- let CI run tests
- copy the types over to webapp and check that we can collapse the uses of `Clickable` in https://github.com/Khan/webapp/pull/16140
> Allow 'beforeNav' and 'safeWithNav' to be used without an 'href'

- .changeset/chilly-steaks-brake.md
- packages/wonder-blocks-core/src/hooks/__tests__/use-is-mounted.test.ts
- packages/wonder-blocks-core/src/hooks/__tests__/use-online.test.tsx
- packages/wonder-blocks-data/src/components/__tests__/data.test.tsx
- packages/wonder-blocks-data/src/components/data.ts
- packages/wonder-blocks-data/src/hooks/__tests__/use-cached-effect.test.tsx
- packages/wonder-blocks-data/src/hooks/__tests__/use-gql-router-context.test.tsx
- packages/wonder-blocks-data/src/hooks/__tests__/use-hydratable-effect.test.ts
- packages/wonder-blocks-data/src/hooks/__tests__/use-request-interception.test.tsx
- packages/wonder-blocks-data/src/hooks/__tests__/use-server-effect.test.ts
- packages/wonder-blocks-data/src/hooks/__tests__/use-shared-cache.test.ts
- packages/wonder-blocks-data/src/hooks/use-cached-effect.ts
- packages/wonder-blocks-data/src/hooks/use-gql.ts
- packages/wonder-blocks-data/src/hooks/use-request-interception.ts
- packages/wonder-blocks-data/src/hooks/use-shared-cache.ts
- packages/wonder-blocks-data/src/util/__tests__/request-api.test.ts
- packages/wonder-blocks-data/src/util/__tests__/request-tracking.test.tsx
- packages/wonder-blocks-data/src/util/__tests__/result-from-cache-response.test.ts
- packages/wonder-blocks-data/src/util/__tests__/serializable-in-memory-cache.test.ts
- packages/wonder-blocks-data/src/util/__tests__/ssr-cache.test.ts
- packages/wonder-blocks-data/src/util/__tests__/to-gql-operation.test.ts
- packages/wonder-blocks-data/src/util/graphql-document-node-parser.ts
- packages/wonder-blocks-data/src/util/merge-gql-context.ts
- packages/wonder-blocks-data/src/util/request-tracking.ts
- packages/wonder-blocks-data/src/util/ssr-cache.ts
- packages/wonder-blocks-data/src/util/status.ts
- packages/wonder-blocks-data/src/util/types.ts
This introduces a new status to the `Result<TData>` type; `no-data`. This new result is returned when the effect is not waiting on a pending fetch, and there is no data in the cache.
I also addressed the suppressed ts errors in WB Data while I was doing this - most of them were very simple.
Issue: FEI-5147
`yarn test`
> [fei5147.1.nodata] Add no-data state to useCachedEffect

- .changeset/blue-ways-cough.md
- .changeset/large-paws-wonder.md
- __docs__/wonder-blocks-testing/exports.harness-adapters.stories.mdx
- __docs__/wonder-blocks-testing/types.test-harness-adapters.stories.mdx
- __docs__/wonder-blocks-testing/types.test-harness-configs.stories.mdx
- package.json
- packages/wonder-blocks-core/src/components/render-state-root.tsx
- packages/wonder-blocks-testing/src/fetch/fetch-request-matches-mock.ts
- packages/wonder-blocks-testing/src/fetch/mock-fetch.ts
- packages/wonder-blocks-testing/src/fixtures/__tests__/fixtures.test.tsx
- packages/wonder-blocks-testing/src/fixtures/fixtures.basic.stories.tsx
- packages/wonder-blocks-testing/src/fixtures/fixtures.tsx
- packages/wonder-blocks-testing/src/gql/mock-gql-fetch.ts
- packages/wonder-blocks-testing/src/harness/__tests__/hook-harness.test.ts
- packages/wonder-blocks-testing/src/harness/__tests__/render-adapters.test.tsx
- packages/wonder-blocks-testing/src/harness/__tests__/test-harness.test.ts
- packages/wonder-blocks-testing/src/harness/__tests__/types.typestest.tsx
- packages/wonder-blocks-testing/src/harness/adapters/__tests__/data.test.tsx
- packages/wonder-blocks-testing/src/harness/adapters/__tests__/ssr.test.tsx
- packages/wonder-blocks-testing/src/harness/adapters/adapters.ts
- packages/wonder-blocks-testing/src/harness/adapters/css.tsx
- packages/wonder-blocks-testing/src/harness/adapters/router.tsx
- packages/wonder-blocks-testing/src/harness/adapters/ssr.tsx
- packages/wonder-blocks-testing/src/harness/make-hook-harness.tsx
- packages/wonder-blocks-testing/src/harness/render-adapters.tsx
- packages/wonder-blocks-testing/src/harness/types.ts
- packages/wonder-blocks-testing/src/mock-requester.ts
- packages/wonder-blocks-testing/src/respond-with.ts
- packages/wonder-blocks-testing/src/settle-controller.ts
This adds a new `ssr` adapter to the Wonder Blocks Testing package. It ensures a `RenderStateRoot` component is rendered around the component under test.
This adapter is default off since it may add the need for additional `act` or `waitFor` calls when using Testing Library due to the state changes that `RenderStateRoot` will perform.
In addition, default off ensures that updating to this new version won't break tests that were rendering their own `RenderStateRoot` component; nested `RenderStateRoot` components throw an error by default.
This change also addresses the TypeScript error suppressions in Wonder Blocks Testing as well as one in Wonder Blocks Core.
I also added a `yarn typewatch` command to package.json. This is a useful command to run in a separate terminal while developing to …
> [fei5235.1.ssradapter] Add SSR adapter for test harness

- .changeset/gorgeous-books-hunt.md
- packages/wonder-blocks-switch/src/components/switch.tsx
I realized that the styles check in switch was checking the wrong object. Corrected the typo
- Add console logs and make sure the styles are not being regenerated every render
> Fix typo in switch style check

- __docs__/wonder-blocks-timing/use-interval.stories.mdx
- __docs__/wonder-blocks-timing/use-scheduled-interval.stories.mdx
- __docs__/wonder-blocks-timing/use-scheduled-timeout.stories.mdx
- __docs__/wonder-blocks-timing/use-timeout.stories.mdx
We were seeing errors in the docs for these examples. It turns out they were trying to use React without importing it.
`yarn start` and view the various timing hooks docs to see they work rather than showing a stacktrace.
> [🔥AUDIT🔥] [fixtimingstories] The examples use React but that isn't a globally available thing, we have to import it

- .changeset/sixty-moons-promise.md
- packages/wonder-blocks-core/src/util/types.ts
There are a number of places where we use 'title' on a View or typography component in webapp.  Our types should allow this.
Issue: None
- let CI run TypeScript
> Allow 'title' to be used on typography components and View

- .changeset/chatty-chicken-listen.md
- packages/wonder-blocks-testing/src/harness/__tests__/adapt.test.tsx
- packages/wonder-blocks-testing/src/harness/adapt.tsx
- packages/wonder-blocks-testing/src/harness/get-named-adapter-component.tsx
My change to add a name to each adapter component broke our testing because it meant that every render of the harness would cause things to remount unnecessarily.
This works around that problem by caching the named components so they can be reused across renders. This works great since only the name changes; everything else is done at render time, allowing even different adapters with the same name to share a cached component.
I also added a test case to capture the non-cached situation to show that things are not remounting in this new implementation (comment out the cache retrieval step in `getNamedAdapterComponent` to see the test fail).
Issue: FEI-5235
`yarn test`
Putting this into my PR for adding the new `ssr` test harness adapter to webapp will show that it works. …
> [fei5235.4.cacheadaptercomponents] Cache adapter components so we reuse the same one rather than causing remounting by auto-generating them

- .changeset/lucky-zoos-heal.md
- packages/wonder-blocks-testing/src/harness/adapters/__tests__/__snapshots__/ssr.test.tsx.snap
- packages/wonder-blocks-testing/src/harness/adapters/__tests__/ssr.test.tsx
- packages/wonder-blocks-testing/src/harness/adapters/ssr.tsx
There are times, like in our storybook stories, where we may nest harnessed components. We should be passive when doing that, which means not throwing just because we're nested.
`yarn test`
> [🔥AUDIT🔥] [ssradaptertweak] Don't throw when the ssr adapter is nested

- .changeset/thick-frogs-warn.md
- packages/wonder-blocks-clickable/src/components/clickable.tsx
We're passing 'title' to Clickable in a number of places in webapp.  When I havemore time I'll fix this in a comprehensive way so that we aren't playing whack-a-mole.
Issue: None
- n/a, yolo
> Allow 'title' as a prop on Clickable

- .changeset/wild-guests-protect.md
- __docs__/wonder-blocks-core/exports.use-latest-ref.stories.mdx
- packages/wonder-blocks-core/src/hooks/__tests__/use-latest-ref.test.ts
- packages/wonder-blocks-core/src/hooks/__tests__/use-latest-ref.typestest.ts
- packages/wonder-blocks-core/src/hooks/use-latest-ref.ts
React defines the RefObject type as:
```
interface RefObject<T> {
readonly current: T | null;
}
```
Previously, the `useLatestRef` hook was typed to return `RefObject<T>`,
but that wasn't really correct. The `current` value returned by
`useLatestRef` cannot be null if `T` is not nullable.
This commit changes the return type to `{readonly current: T}`.
Issue: none
Run `yarn start` to launch Storybook.
View the documentation for `useLatestRef`. The return type should be `React.MutableRefObject<T>`.
`yarn lint`, `yarn test`, and `yarn typecheck` should pass.
> Fix the return type of useLatestRef

- .changeset/flat-sloths-sit.md
- packages/wonder-blocks-core/src/index.ts
This exports the new `usePreHydrationEffect` hook from Wonder Blocks Core, which I forgot to do in the last PR. 🤦🏻‍♂️
Issue: FEI-5275
`yarn build` and check the output.
> [🔥AUDIT🔥] [fei5275.3.actuallyexporthook] Actually export the new hook

- .changeset/thin-feet-shave.md
- .eslintrc.js
- __docs__/wonder-blocks-core/exports.use-pre-hydration-effect.stories.mdx
- packages/wonder-blocks-core/src/hooks/__tests__/use-pre-hydration-effect.test.tsx
- packages/wonder-blocks-core/src/hooks/use-pre-hydration-effect.ts
With the very specific naming and purpose of this hook, we don't want any dependencies, so this removes them.
I made this a minor update to the package; it's a breaking change to typing but not functionality, and nothing should be using this yet outside my code. I could've added some typing to allow an empty deps array only but that seemed pointless.
Issue: FEI-5275
> [fei5275.3.removedepsfromprehydrationeffect] Remove deps arg from usePreHydrationEffect

- .changeset/curly-zoos-guess.md
- packages/wonder-blocks-timing/src/components/with-action-scheduler.tsx
When a component is wrapped with `withActionScheduler`, the React dev tools aren't able to derive a meaningful name for the wrapping component. This PR uses a [trick](https://github.com/remix-run/react-router/blob/7a891467987b164b64f39eaf72415b609ed2d4a7/packages/react-router/modules/withRouter.js) I learned from `react-router` to provide a friendly name for the wrapping component. 
Issue: "none"
Run an app that uses `withActionScheduler`
Inspect a page using the React dev tools and note that the component created by `withActionScheduler` is named `withActionSchedule(SomeComponent)`.
> Provide better debug component name for withActionScheduler HoC

- .storybook/preview.tsx
Adds a new bg option in the background switcher widget include in the Storybook
toolbar.
Verify that the background changes to `eggplant` if you click on `khanmigo` in
the background switcher toolbar option.
> [🔥AUDIT🔥] Include khanmigo background in storybook toolbar

- .changeset/odd-spiders-cry.md
- __docs__/wonder-blocks-icon-button/icon-button.argtypes.ts
- __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
- packages/wonder-blocks-icon-button/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-icon-button/src/__tests__/custom-snapshot.test.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
- packages/wonder-blocks-icon-button/src/util/icon-button-util.test.ts
- packages/wonder-blocks-icon-button/src/util/icon-button-util.ts
- Added new size prop with 3 options based on designs found in Figma
- Created new icon button util file with 2 simple functions
- Refactored icon button stories file by using comments as descriptions
- Factored out icon button stories argtypes
Issue: WB-1528
- New test file was created for icon util functions
- New snapshot generated for sizes
> Add new xsmall, small, and medium size prop to IconButton

- .changeset/fast-jokes-hammer.md
- __docs__/wonder-blocks-switch/switch.stories.tsx
- packages/wonder-blocks-switch/src/components/__tests__/switch.test.tsx
- packages/wonder-blocks-switch/src/components/switch.tsx
We are not currently allowing to focus a disabled switch component. This PR adds
support to that via the `aria-disabled` attribute.
Also made the default story fully interactive so users can play/interact with
it.
Issue: WB-1609
1. Verify that the switch elements in the `Disabled` state can be focused via
keyboard.
/?path=/story/switch--disabled
https://github.com/Khan/wonder-blocks/assets/843075/7f6c4f2f-424b-4fed-8695-33e4399b2c2c
2. Verify that the `Default` story is fully interactive (switch can be
checked/unchecked).
/?path=/story/switch--default
> WB-1609: Add support to disabled + focus state to Switch

- .changeset/hot-bikes-approve.md
- __docs__/wonder-blocks-switch/switch-best-practices.mdx
- packages/wonder-blocks-switch/src/components/switch.tsx
Based on feedback from SarahB:
- Adds a `not-allowed` cursor for disabled + hover state.
- Includes a note in the best practices section about not using `label` + `aria-label` at the same time.
Issue: WB-1609
Verify that the cursor is `not-allowed` when hovering over a disabled switch.
> [🔥AUDIT🔥] WB-1609: Switch - Add `not-allowed` cursor for disabled + hover state

- .changeset/afraid-rings-knock.md
- packages/wonder-blocks-color/src/util/__tests__/utils.test.ts
- packages/wonder-blocks-color/src/util/utils.ts
Previously, if the red, green, or blue component was less than 16, its hex digit would be repeated (e.g. `f` would become `ff`). With this change, we preserve the real value of the number by prepending a `0` instead (e.g. `f` becomes `0f`).
`yarn run jest packages/wonder-blocks-color/src/util/__tests__/utils.test.ts`
> Fix how `mix` from `wonder-blocks-color` formats single-digit color components

- .github/workflows/release.yml
Replicating the changes done in the Perseus repo to able to send an alert to the
#wonder-blocks-dev channel in Slack when the publishing workflow fails.
See https://github.com/Khan/perseus/pull/727 for the original implementation.
If the publishing workflow fails, an alert should be sent to the
#wonder-blocks-dev channel in Slack.
> Add alert for failure in publishing workflow

- .github/workflows/node-ci-pr.yml
Another implementation borrowed from the Perseus repo, that help us to verify
that there's a changeset for every changed package.
Previously, we were using `check-for-changeset` to verify the existence of a
changeset file, but now we switch to `changeset-per-package` to make sure that
there's a changeset for every changed package. This is useful in monorepos like
this one.
See original PR: https://github.com/Khan/perseus/pull/735 (thanks @nedredmond!)
Verify that the CI passes and that in other PRs with actual changes, the
changeset workflow works as expected.
> Verify changeset for every changed package

- .github/workflows/node-ci-pr.yml
Now that we have a better path to release the packages in a safer way (#2070 and
#2071), we can re-enable the snapshots release job. re-enable the snapshots
release job to run on every non-draft PR.
Issue: WB-1606
Verify that the snapshots release job is running on every non-draft PR.
> WB-1606: Re-enable snapshots release job

- .changeset/hot-starfishes-sleep.md
- .github/workflows/node-ci-pr.yml
- package.json
- packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
There’s an issue with wb-cell that was introduced after making some layout/css
changes to the components.
Turns out that Cell states won’t be displayed as expected when the cell top node
is `display: inline`. As cells are meant to use the full-width of it’s parent
container, this PR fixes that by making the top node to always use `display: flex`.
Issue: https://khanacademy.atlassian.net/browse/WB-1623
Verify that cell states are displayed as expected (hover, active change the bg
color).
> WB-1623: Cell states don't work with anchor tags correctly [fix]

- .changeset/strange-spiders-sing.md
- .changeset/tasty-deers-listen.md
- .github/workflows/node-ci-pr.yml
- __docs__/wonder-blocks-icon-button/icon-button.argtypes.ts
- __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
- __docs__/wonder-blocks-icon/phosphor-icon.argtypes.ts
- __docs__/wonder-blocks-icon/phosphor-icon.stories.tsx
- __docs__/wonder-blocks-toolbar/toolbar.argtypes.tsx
- __docs__/wonder-blocks-tooltip/tooltip.stories.tsx
- consistency-tests/__tests__/ref-forwarded.test.tsx
- package.json
- packages/wonder-blocks-banner/package.json
- packages/wonder-blocks-banner/src/components/banner.tsx
- packages/wonder-blocks-icon-button/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-icon-button/src/__tests__/custom-snapshot.test.tsx
- packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
- packages/wonder-blocks-icon-button/src/index.ts
- packages/wonder-blocks-modal/package.json
- packages/wonder-blocks-modal/src/components/close-button.tsx
- packages/wonder-blocks-popover/package.json
- packages/wonder-blocks-popover/src/components/close-button.tsx
- packages/wonder-blocks-search-field/package.json
- packages/wonder-blocks-search-field/src/components/search-field.tsx
- yarn.lock
- Changes the `icon` prop to accept a `PhosphorIcon` instead of an
`IconAsset`.
- Updates the `IconButton` stories and unit tests to verify the new
`PhosphorIcon` support.
- Updates existing WB packages to use the new `IconButton` API (Banner,
Modal, Popover, SearchField).
**NOTE:** The plan is to replace all `IconButton` instances in webapp after this PR is landed.
Issue: WB-1612
Verify that the `IconButton` stories and unit tests are passing. Also verify the
visual changes in Chromatic.
https://github.com/Khan/wonder-blocks/assets/843075/5a5c8ba1-3858-42c0-8791-085cf819ffda
> WB-1612: `IconButton`: Add PhosphorIcon support

- .changeset/dull-jobs-leave.md
- packages/wonder-blocks-layout/src/components/media-layout.tsx
We weren't taking into account custom ones, which was a problem if you wante to use a custom one!
> Handle custom media layout specs.

- .github/workflows/node-ci-pr.yml
By default, filters are inclusive disjunctions (OR). This makes the `packages/` filter useless, since the glob filter will match anything that does not include `__tests__` and `dist` in the path.
This field that I added to the `filter-files` action will ensure that file pathnames match EVERY provided filter. This prevents accidental inclusions of packages outside of `packages/`.
> Fix filters for changeset workflow step

- .changeset/nervous-ladybugs-search.md
- .storybook/components/component-info.tsx
- __docs__/wonder-blocks-button/button.argtypes.ts
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/components/__tests__/button.test.tsx
- packages/wonder-blocks-button/src/components/button-core.tsx
- packages/wonder-blocks-button/src/components/button-icon.tsx
- packages/wonder-blocks-button/src/components/button.tsx
- Changes the `icon` prop to accept a `PhosphorIconAsset` instead of an
`IconAsset`.
- Updates the `Button` stories and unit tests to verify the new `PhosphorIcon` support.
Issue: WB-1613
Verify that the `Button` stories and unit tests are passing. Also verify the
visual changes in Chromatic.
> WB-1613: Add PhosphorIcon support to Button

- .github/workflows/node-ci-pr.yml
Corrects an issue where we unexpectedly match all files except those with both `tests` and `dist` in the path.
> Fix glob match issue in `filter-files` action

- .github/workflows/chromatic-pr.yml
After optimizing our chromatic workflow, we can now re-enable chromatic
snapshots on draft PRs.
Some data collected from the past 3 months:
- July 14 / Aug 13 => 9,524 skipped snapshots (21.4%) - 35,000 snapshots (78.6%)…  :red: reached the quota limit on Aug 2.
- Aug 14 / Sept 13 => 13,193 skipped snapshots  (27.4%) - 35,000 (72.6%) snapshots…  :red: reached the quota limit on Aug 23.
- [Optimized the chromatic workflow at this point]
- Sept 14 / Oct 13 => 17,449 skipped snapshots (46.5%) - 20,104 snapshots (53.5%) :white_check_mark: we still have ~15000 snapshots available.
This data shows that we can re-enable chromatic snapshots on draft PRs without
reaching the quota limit. If that happens, we can always disable them again.
Verify that …
> [🔥AUDIT🔥] Re-enable chromatic snapshots on draft PRs

- .changeset/rich-jars-jog.md
- .changeset/tricky-phones-applaud.md
- .storybook/components/component-info.tsx
- __docs__/wonder-blocks-button/button.argtypes.ts
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/components/__tests__/button.test.tsx
- packages/wonder-blocks-button/src/components/button-core.tsx
- packages/wonder-blocks-button/src/components/button.tsx
- packages/wonder-blocks-button/src/themes/default.ts
Currently, the `icon` prop on WB Button added an icon on the left.
Now, `icon` has been renamed to `startIcon`, and we are adding
an `endIcon` prop so people can add an icon on the other side.
Issue: https://khanacademy.atlassian.net/browse/WB-1630
In storybook, confirm that the icon story has the right
description and that the icons look correct.
`yarn jest packages/wonder-blocks-button/src/components/__tests__/button.test.tsx`
> Add `endIcon` prop and change existing `icon` prop to `startIcon`

- .changeset/beige-kings-train.md
- packages/wonder-blocks-core/src/hooks/use-on-mount-effect.ts
Previously, `useOnMountEffect` accepted functions that either return a cleanup function or explicitly return undefined. This means that functions with no return value (e.g. `() => {}`) result in errors, even though they're accepted by `useEffect`. This PR updates the argument type so that it accepts functions with void returns. Minor version bump because the API changed, but it is non-breaking.
N/A
> Make `useOnMountEffect` accept functions with void return types

- .github/workflows/node-ci-pr.yml
The snapshot releases job only runs when the PR is not a draft. There was an
issue that prevented from creating a snapshot release when a PR was moved from
`draft` to `ready for review`.
This PR fixes that by including the `ready_for_review` activity type in the
workflow.
N/A
> [🔥AUDIT🔥] Run snapshots job when the PR is ready for review

- .changeset/blue-cows-clap.md
- __docs__/wonder-blocks-switch/switch.argtypes.tsx
- __docs__/wonder-blocks-switch/switch.stories.tsx
- packages/wonder-blocks-switch/src/components/__tests__/switch.test.tsx
- packages/wonder-blocks-switch/src/components/switch.tsx
Replaces Icon with the new PhosphorIcon component in `Switch`. Now
Switch only should accept `PhosphorIcon` instances in its `icon` prop.
Issue: WB-1615
In Storybook, verify that the `Switch` icon stories look correct.
Also compare the changes in Chromatic.
> WB-1615: Add PhosphorIcon support to Switch

- .changeset/nine-meals-yell.md
- __docs__/wonder-blocks-theming/adding-a-theme.mdx
- __docs__/wonder-blocks-theming/theme-examples.tsx
- __docs__/wonder-blocks-theming/theme-switcher-context.mdx
- packages/wonder-blocks-button/src/themes/themed-button.tsx
- packages/wonder-blocks-switch/src/themes/themed-switch.tsx
- packages/wonder-blocks-theming/src/components/with-scoped-theme.tsx
- packages/wonder-blocks-theming/src/hooks/use-scoped-theme.ts
- packages/wonder-blocks-theming/src/hooks/use-styles.ts
- packages/wonder-blocks-theming/src/index.ts
- packages/wonder-blocks-theming/src/types.ts
- packages/wonder-blocks-theming/src/utils/__tests__/theme-switcher-context.test.tsx
- packages/wonder-blocks-theming/src/utils/theme-switcher-context.ts
Exports supported themes list to enforce available themes.
This change will allow us to enforce that all themes are supported by the theme
switcher. This will prevent us from accidentally shipping a theme that is not
allowed.
Issue: https://khanacademy.atlassian.net/browse/WB-1634
Verify that the new types are exported and that the theme switcher context
enforces the supported themes list.
> WB-1634: Add supported themes list to wb-theming

- .changeset/shiny-pugs-shout.md
- __docs__/wonder-blocks-link/link.argtypes.tsx
- __docs__/wonder-blocks-link/link.stories.tsx
- packages/wonder-blocks-link/src/components/__tests__/link.test.tsx
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-link/src/components/link.tsx
Replaces `Icon` with the new `PhosphorIcon` component in `Link`. Now `Link` only
should accept PhosphorIcon instances in the `startIcon` and `endIcon` props.
Issue: https://khanacademy.atlassian.net/browse/WB-1614
In Storybook, verify that the `Link` icon stories look correct.
- `startIcon` and `endIcon`: /?path=/story/link--start-and-end-icons
- External link: /?path=/story/link--opens-in-a-new-tab
Also compare the changes in Chromatic.
> WB-1614: Add PhosphorIcon support to Link

- .changeset/honest-shoes-remain.md
- packages/wonder-blocks-testing/src/gql/__tests__/types.typestest.ts
- packages/wonder-blocks-testing/src/respond-with.ts
This change makes sure that the `TData` type parameter of `MockResponse<TData>` has an effect on the generated type.
Before this change, the value of `TData` did not affect the resultant type. For example, `MockResponse<{a: number}>` and `MockResponse<{b: string}>` would both be equivalent to the type looked like `{readonly toPromise: () => Promise<Response>}`. Since they both look the same, TypeScript accepts them as the same.
After this change, we have a hidden property on `MockResponse` that cannot be accessed that expects data of shape `TData`. We never assign it (we use casting to pretend we are honoring that contract), but by having it present, TypeScript now sees the types as different as `MockResponse<{a: number}>` is now a type like `{[inaccessible]: {a: number}; readonly …
> Enforce TData type in MockResponse

- .changeset/many-kids-raise.md
- __docs__/wonder-blocks-accordion/accordion-section.argtypes.tsx
- __docs__/wonder-blocks-accordion/accordion-section.stories.tsx
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion-section-header.test.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion-section.test.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
In the event that an accordion section needs to stay open at all times, the user can now use `collapsible={false}` to keep it open. This also sets the header button's `aria-disabled` to `true`, as outlined in the [accessibility guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/).
Issue: https://khanacademy.atlassian.net/browse/WB-1585
`yarn jest packages/wonder-blocks-accordion/src/components/__tests__/accordion-section.test.tsx`
`yarn jest packages/wonder-blocks-accordion/src/components/__tests__/accordion-section-header.test.tsx`
Storybook
- Go to http://localhost:6061/?path=/docs/accordion-accordionsection--docs
- Check that there is no caret icon 
- Confirm that the header button cannot be clicked
> Add `collapsible` prop to AccordionSection

- .changeset/clever-rice-protect.md
- .changeset/forty-tomatoes-wink.md
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- consistency-tests/__tests__/ref-forwarded.test.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
- packages/wonder-blocks-accordion/src/components/accordion.tsx
- packages/wonder-blocks-clickable/src/components/clickable.tsx
- types/aphrodite.d.ts
As per the [w3 guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/) for accordion, 
it is recommended (but optional... but we're doing it anyway!) to have keyboard nav support for
arrow up, arrow down, home, and end.
I've added that keyboard support here using the `onKeyDown` listener on `ul` and
`onFocus` on AccordionSection. To get this to work, I changed the ref for AccordionSection
from its container View/div to its header button. I also had to update Clickable because its
`onFocus` prop wasn't working on buttons for some reason.
Issue: https://khanacademy.atlassian.net/browse/WB-1585
Manual testing on Accordion stories
- Go to a story with multiple accordions, such as http://localhost:6061/?path=/story/accordion-accordion--caret-positions
- try keyboard nav in all sort of …
> Add keyboard nav support to Accordion (arrow keys, home, end)

- .changeset/lazy-impalas-study.md
- packages/wonder-blocks-birthday-picker/package.json
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
- packages/wonder-blocks-form/src/__tests__/__snapshots__/custom-snapshot.test.tsx.snap
- packages/wonder-blocks-form/src/components/checkbox-core.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
Replaces the `Icon` component with `PhosphorIcon` in the following packages:
- `wonder-blocks-birthday-picker`
- `wonder-blocks-form`
- `wonder-blocks-search-field`
This concludes the migration of all WB packages to `PhosphorIcon`.
Issue: WB-1618, WB-1620, WB-1621
Verify that the icons look correct in the following components:
- `BirthdayPicker`
- `Checkbox`
- `SearchField`
> Add PhosphorIcon support to remaining WB packages

- .changeset/smart-flowers-wave.md
- __docs__/wonder-blocks-accordion/accessibility.stories.mdx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion-section-header.test.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
- packages/wonder-blocks-accordion/src/components/accordion.tsx
This PR includes
- a11y mdx docs
- the addition of `region` as advised by w3
- the addition of `aria-labelledby` as advised by w3
- tests
Issue: https://khanacademy.atlassian.net/browse/WB-1585
`yarn jest packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx`
Go to the storybook page and check the accessibility tool to confirm
that `region` and `aria-labelledby` are set appropriately.
Turn on Voiceover and confirm that the new region(s) are available in the landmarks menu.
https://github.com/Khan/wonder-blocks/assets/13231763/3c66bb8a-9598-4bb4-9fc5-f2c91422fff2
> Make Accordion fully accessible

- .changeset/violet-clocks-switch.md
- __docs__/wonder-blocks-clickable/clickable.stories.tsx
- packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
- packages/wonder-blocks-clickable/src/components/clickable.tsx
Recently, Clickable was updated to include a `onFocus` handler to be able to use
that event in consumers. One of the changes caused clickable from not reporting
the focused state correctly. This PR fixes that, but removing the custom handler
and leaving to `ClickableBehavior` to resolve that directly (via `commonProps`).
Verify that the `focused` state is now correctly displayed.
/?path=/story/clickable-clickable--default
BEFORE:
https://github.com/Khan/wonder-blocks/assets/843075/042128a3-fc72-4521-be22-e8ac7627f5a0
AFTER:
https://github.com/Khan/wonder-blocks/assets/843075/c5dbb8a1-6b00-4bed-b6c6-6254104ec01f
> [🔥AUDIT🔥] Clickable: Fix focused/onFocus handling for buttons

- .changeset/wet-apricots-wait.md
- __docs__/wonder-blocks-accordion/accordion-section.argtypes.tsx
- __docs__/wonder-blocks-accordion/accordion-section.stories.tsx
- __docs__/wonder-blocks-accordion/accordion.argtypes.tsx
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- packages/wonder-blocks-accordion/package.json
- packages/wonder-blocks-accordion/src/components/__tests__/accordion-section.test.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
- packages/wonder-blocks-accordion/src/components/accordion.tsx
All that's left is some polishing, and the Accordion component should be ready for launch!
In this PR:
- Prioritize children's values for overloaded props
- Fix the issue where the bottom border radius was applying to non-last section content when it wasn't supposed to
- Update the Uncontrolled AccordionSection story so it actually says it's uncontrolled
- Add categories to prop tables
- Fixed typo
- Update comments and documentation accordingly
- Make Accordion package.json say that the package is public! 🎉 
Issue: https://khanacademy.atlassian.net/browse/WB-1585
`yarn jest`
Storybook
- Confirm that Accordion's prop table has the props split up into sections now
- Confirm that AccordionSection's prop table has the props split the sections now
- Confirm that all the documentation says …
> Accordion cleanup and release

- .changeset/good-balloons-laugh.md
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
Use static position in AccordionSection to fix the outline overlap issue.
Issue: none
- Go to Storybook at ?path=/story/accordion-accordion--on-dark-background
- Make sure that hovering and tabbing causes the outline to show up.
- Confirm that the outline shows up correctly and isn't clipped anywhere.
> Fix AccordionSection outline overlap issue

- .changeset/dirty-dingos-battle.md
- __docs__/wonder-blocks-popover/popover-content-core.stories.tsx
- __docs__/wonder-blocks-popover/popover-content.stories.tsx
- __docs__/wonder-blocks-popover/popover.accessibility.stories.mdx
- __docs__/wonder-blocks-popover/popover.argtypes.tsx
- __docs__/wonder-blocks-popover/popover.stories.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx
- packages/wonder-blocks-popover/src/components/popover-content-core.tsx
- packages/wonder-blocks-popover/src/components/popover-content.tsx
- packages/wonder-blocks-popover/src/components/popover-dialog.tsx
- packages/wonder-blocks-popover/src/components/popover.tsx
The Popover dialog element is not assigning correctly the `aria-describedby`
value, thus causing Screen Readers not being able to read the popover contents
correctly.
This PR fixes the issue by assigning the `aria-describedby` value to the popover
content, and also associates the popover title with the popover dialog via the
`aria-labelledby` attribute. By implementing this, the popover dialog will be
read correctly by Screen Readers.
Also fixed some issues with the Storybook docs by adding correct descriptions
and fixing some of the Arg types to the Popover component.
Issue: WB-1636
This is better to be tested with Safari + VoiceOver.
1. Open any popover story in Storybook and click on the popover trigger.
2. Verify that the popover dialog is read correctly by VoiceOver. The popover …
> WB-1636: Announce popover contents correctly to screen readers

- .changeset/friendly-taxis-drive.md
- __docs__/wonder-blocks-dropdown/action-menu.argtypes.ts
- __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
- __docs__/wonder-blocks-dropdown/base-select.argtypes.ts
- __docs__/wonder-blocks-dropdown/multi-select.argtypes.ts
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.argtypes.ts
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-popper.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-popper.tsx
- packages/wonder-blocks-dropdown/src/util/dropdown-menu-styles.ts
- packages/wonder-blocks-dropdown/src/util/popper-max-height-modifier.ts
This PR changes the logic to display the listbox based on the viewport size.
Before this, we were calculating a fixed height for the listbox based on the
number of items in the listbox. This was causing the listbox to be displayed
partially and the scrollbar was not visible by default.
I'm changing that logic to display the listbox based on the viewport size. This
is done using a PopperJS modifier so we can detect the viewport size and
calculate the height of the listbox accordingly. By implementing this change, we
no longer display a fixed height and instead we display as many items as we can.
Issue: WB-1607
Navigate to any of the `SingleSelect/MultiSelect` stories and verify that the
listbox is displayed based on the viewport size (resize the screen to see how
the listbox changes its …
> WB-1607: Allow displaying the listbox based on the viewport size

- .changeset/stale-steaks-call.md
- __docs__/wonder-blocks-typography/styles.css
- __docs__/wonder-blocks-typography/typography.stories.tsx
- packages/wonder-blocks-core/src/components/__tests__/text.test.tsx
- packages/wonder-blocks-core/src/components/text.tsx
While working on adding custom option items to Dropdowns, I noticed that the
`className` prop was not being appended to the `Text` component. This PR fixes
that by changing the logic to append the `className` prop to the `Text` if it
includes both a `className` and a `style` prop.
Also updated the typography docs to include an example of using the `style` and
`className` props.
Issue: WB-1645
Verify that the unit tests pass.
Also verify that the following story works as expected:
http://localhost:6061/?path=/docs/typography--docs#with-style
1. Verify that the text is blue (assigned via `style`).
2. Verify that the has a bg color (assigned via `className` + `css()`).
3. Lastly, verify that it includes a black border (assigned via `className` + and external css import).
> WB-1645.pre: Append className value in Text component (fix)

- .changeset/perfect-chefs-lay.md
- __docs__/wonder-blocks-icon/accessibility.stories.mdx
- __docs__/wonder-blocks-icon/phosphor-icon.argtypes.ts
- __docs__/wonder-blocks-icon/phosphor-icon.stories.tsx
- packages/wonder-blocks-banner/src/components/banner.tsx
- packages/wonder-blocks-icon/src/components/__tests__/phosphor-icon.test.tsx
- packages/wonder-blocks-icon/src/components/phosphor-icon.tsx
- Banner: Fix a11y issue that caused that icons were not read by screen readers
properly.
- PhosphorIcon: Improved docs to explain how to use the `role` prop +
added unit tests.
1. Navigate to the Banner component in the docs and verify that the icons are read
by screen readers properly (e.g. includes `info` before reading the message).
http://localhost:6061/?path=/story/banner--default
2. Navigate to the PhosphorIcon component in the docs and verify that the `role`
prop is documented properly.
http://localhost:6061/?path=/docs/icon-phosphoricon--docs#announcing-the-icon-to-assistive-technology
> Banner: Fix a11y issue by adding role=img to icons

- .changeset/warm-hats-walk.md
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
Fixes a regression in `SingleSelect` where the opener is not able to use an
empty string as a label.
In #2139, I changed the logic to use `1 item` for those cases, but turns out
that this "empty" value feature is required by Perseus.
Issue: WB-1645
Verify that the "Two with Text" example in the `SingleSelect` storybook page
shows empty string as the label for both openers:
http://localhost:6061/?path=/story/dropdown-singleselect--two-with-text
> [🔥AUDIT🔥] WB-1645.fix Dropdown: Fix regression in SingleSelect

- .changeset/itchy-penguins-dress.md
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
Currently, there is a 2px added to expanded accordions in order to account for
the outline and stop it from being cut off by the content panel. This is causing
an issue in webapp where these 2px is causing a weird visible gap, so we
want to remove it.
While using z-index here is unfortunate, this is still an appropriate use
for z-index, and it will remove spacing issues.
Example of the gap this 2px margin was causing:
Outline cutoff issue that is making the use of z-index necessary:
Issue: none
- Make sure the outline shows up on hover and via keyboard nav in Accordion storybook
- Specifically this story is a good test:
http://localhost:6061/?path=/story/accordion-accordionsection--react-element-in-header
> Accordion: Use z-index instead of adding a 2px margin to bring the header outline in front of the content panel

- .changeset/tough-waves-juggle.md
- __docs__/wonder-blocks-modal/modal-footer.stories.tsx
- __docs__/wonder-blocks-modal/modal-header.stories.tsx
- __docs__/wonder-blocks-modal/modal-panel.argtypes.tsx
- __docs__/wonder-blocks-modal/modal-panel.stories.tsx
- packages/wonder-blocks-modal/src/components/modal-content.tsx
- packages/wonder-blocks-modal/src/components/modal-footer.tsx
- packages/wonder-blocks-modal/src/components/modal-header.tsx
- packages/wonder-blocks-modal/src/components/modal-panel.tsx
- packages/wonder-blocks-modal/src/themes/default.ts
Following up on #2141, this PR focuses on adding theming support to the
remaining modal building blocks: ModalHeader and ModalFooter.
The main change is to add the "eggplant" bg color to ModalHeader and to refactor
these components to use media queries instead of `MediaLayout`.
Also added better docs for ModalPanel and ModalFooter.
Issue: WB-1652
1. Verify that the `ModalHeader` component is now using the `eggplant` bg color.
2. Verify that the `ModalHeader` and `ModalFooter` docs look correct.
> WB-1652.3: Add theming support to ModalHeader and ModalFooter

- .changeset/eighty-radios-trade.md
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-opener.tsx
There's a bug in the dropdown component where the focus state is not applied to
custom openers. This PR solves that by adding `tabIndex` to the custom opener so
`ClickableBehavior` can apply the focus state as the element can trigger its
`onFocus`/`onBlur` handlers.
Verify that the SingleSelect > Custom opener example displays the focus state
when tabbing to the opener.
https://github.com/Khan/wonder-blocks/assets/843075/f30cfeea-b6b0-427f-a0bd-22a04ff149ef
> Dropdown: Fix focus state for custom openers

- .changeset/red-foxes-thank.md
- __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/action-menu.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-opener.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- packages/wonder-blocks-dropdown/src/util/types.ts
Pass opened state down to custom opener in order to control styles without additional dom manipulation.
Issue: N/A
Verify that custom opener story displays opened state when clicking on the opener.
https://github.com/Khan/wonder-blocks/assets/23404711/0c8e3ff9-3692-4fb3-8dd1-065875641193
> Add `opened` state to Dropdown opener function

- .changeset/wild-kangaroos-impress.md
- __docs__/wonder-blocks-accordion/accordion-section.stories.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
Currently, there is an issue with a particular accordion section in webapp where long titles in the
custom header cause the accordion contents to overflow. This is fixed by adding `minWidth: 0`
to the styles in Wonder Blocks Accordion Header.
I also included a story in this PR that replicates the issue, which is fixed with the new style.
| Before | After |
| --- | --- |
| <img width="651" alt="Screenshot 2023-12-19 at 3 41 54 PM" src="https://github.com/Khan/wonder-blocks/assets/13231763/a4106bef-9cef-4479-953e-6c5ed307d699"> | <img width="654" alt="Screenshot 2023-12-19 at 3 41 37 PM" src="https://github.com/Khan/wonder-blocks/assets/13231763/5e9a55e4-b886-4a21-aba3-ad886d820bee"> |
Issue: none
- Go to the following story: /?path=/story/accordion-accordionsection--react-element-in-header …
> Accordion header overflow fix

- .changeset/tough-rabbits-cough.md
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
After introducing the custom option items, the search/filter logic was broken.
This PR fixes that by using the correct lookup value for the search/filter.
Also added some unit tests and modified some stories to ensure that this
scenario is fully covered for both `SingleSelect` and `MultiSelect`.
Verify that the search/filter logic works as expected in the following stories:
- /?path=/story/dropdown-singleselect--virtualized-filterable
- /?path=/story/dropdown-singleselect--custom-option-items-virtualized
https://github.com/Khan/wonder-blocks/assets/843075/0f8fbed5-aaff-4ce2-b5be-cea449d41248
> Fix search/filter logic on SingleSelect

- .changeset/grumpy-meals-sleep.md
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
- packages/wonder-blocks-accordion/src/components/accordion.tsx
Summary:
Adjusts Accordion element to only handle keydown events when an Accordion header is focused. Previously, an "active header" index would be set, but not unset when the header was blurred. Rather than adding `onBlur` handlers throughout `Clickable`, instead remove active index state and check the `activeElement` from the document at the time a keydown event is fired.
Issue: WB-1656
Test:
Added a story, "With Dropdown" to Accordion docs.
> Accordion only handles keydown when header focused

- .changeset/witty-crabs-clean.md
- __docs__/wonder-blocks-pill/pill.argtypes.tsx
- __docs__/wonder-blocks-pill/pill.stories.tsx
- packages/wonder-blocks-pill/package.json
- packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
- packages/wonder-blocks-pill/tsconfig-build.json
- packages/wonder-blocks-theming/src/tokens.ts
Some updates need to be made to pill so they're more usable
within webapp.
- small size needs 14px font and 24px height
- Banner colors included
- Needs fixed height
- Needs a story for vertically stacked pills
More context for some of these changes can be found in
the following slack thread:
https://khanacademy.slack.com/archives/C8Z9DSKC7/p1693923761646739
Issue: https://khanacademy.atlassian.net/browse/WB-1602
`yarn jest packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx`
Storybook
- All variants
/?path=/story/pill--variants
- Vertically stacked pills
/?path=/story/pill--vertically-stacked
> Pill updates - updated colors, small pills are bigger for a11y

- .changeset/cyan-oranges-wait.md
- __docs__/wonder-blocks-popover/popover.stories.tsx
- packages/wonder-blocks-popover/src/components/__tests__/focus-manager.test.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx
- packages/wonder-blocks-popover/src/components/focus-manager.tsx
There is a bug in the popover where tabbing out of the popover (while it
is still open) will cause the focus order to be incorrect. More
specifically, the focus will be returned to the trigger element, while
it should be returned to the next element in the tab order.
This is because the popover is not properly handling the case where the
trigger element is the last element in the tab order. This PR fixes that
by making all the focusable elements in the popover non-tabbable, and
then make them tabbable again when the popover gains focus.
For more reference on the actual error, see: https://khanacademy.atlassian.net/browse/CL-1259
https://github.com/Khan/wonder-blocks/assets/843075/ca72e266-9091-409e-9065-3754e4c681c9
Issue: WB-1638
- Navigate to …
> WB-1638: Fix tabbing in popover

- .changeset/clever-trees-confess.md
- packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx
- packages/wonder-blocks-popover/src/components/focus-manager.tsx
- packages/wonder-blocks-popover/src/components/popover-event-listener.ts
- packages/wonder-blocks-popover/src/components/popover.tsx
- packages/wonder-blocks-popover/src/util/__tests__/util.test.tsx
- packages/wonder-blocks-popover/src/util/util.ts
As soon as a popover is closed, we return focus to its trigger element (or
element that caused the popover to open). This works fine in most cases, but
there are situations where we don’t want to do that.
For example, when there are multiple Popovers within the same context and the
user opens a separate popover, the previous opened popover closes, but in this
case the focus is being moved from the new popover to the trigger element of the
previous popover.
This PR fixes this by detecting if the element that caused the popover to be
dismissed is an element that can be focused, and if so, we let the focus flow
naturally to that element. If not, we return focus to the trigger element.
Issue: https://khanacademy.atlassian.net/browse/WB-1654
- Open the popover docs page.
- Scroll down to the …
> WB-1654: Popover trigger element is stealing focus from other focusable elements [FIX]

- .changeset/strong-lemons-crash.md
- __docs__/wonder-blocks-popover/popover.argtypes.tsx
- __docs__/wonder-blocks-popover/popover.stories.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx
- packages/wonder-blocks-popover/src/components/popover.tsx
Allows manually redirecting the focus after the popover is closed/hidden. This
feature already exists in the WB Modal package, and this commit adds support to
the popover package.
The `closedFocusId` prop is a string that represents the id of the element that
should receive focus after the popover is closed. If the element is not found,
the focus will be set to the element that triggered the popover.
This feature has been requested by the Perseus team.
Issue: https://khanacademy.atlassian.net/browse/WB-1657
- Navigate to /?path=/docs/popover-popover--docs#with-closedfocusid
- Verify that the popover returns focus to the first button after it is closed.
https://github.com/Khan/wonder-blocks/assets/843075/a6ab6c20-2abe-4eec-b6b0-513c2392cc52
> WB-1657: Add support to `closedFocusId` prop in Popover

- .changeset/fifty-countries-fry.md
- __docs__/wonder-blocks-accordion/accordion-section.stories.tsx
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- packages/wonder-blocks-accordion/src/components/accordion.tsx
Currently, pressing the home, end, and arrow keys causes
scrolling on the page (the default behavior of those keys).
To fix this, I added `preventDefault()` for all the keys.
While I'm updating accordion, I also added a comment to the
`WithAnimation` stories warning people about the performance
impact of using height animations.
Issue: none
- Go to local accordion stories docs tab.
- Click just before the "Default" story accordion.
- Press tab so that the focus shifts to the first section header.
- Press the end key and confirm that the page does not jump
to the bottom. Confirm that it focuses on the last section header.
- Press the home key and confirm that the page does not jump
to the top. Confirm that it focuses on the first section header.
- Press the up arrow key repeatedly. Confirm …
> Accordion keyboard nav: stop nav keys from causing page scroll

- .changeset/smart-terms-own.md
- package.json
- wb-codemod/README.md
- wb-codemod/bin/cli.js
- wb-codemod/package.json
- wb-codemod/src/wb-codemod.ts
- wb-codemod/transforms/__tests__/template.test.ts
- wb-codemod/transforms/template.ts
- yarn.lock
This PR creates a new package `wb-codemod` that will be used to run code
migrations using codemods. The package is a wrapper around `jscodeshift` that
provides a CLI to run WB codemods from different packages/locations.
This will be useful now that Web Wonder Blocks is being actively used in the
main repo and in Perseus as well.
The goal/motivation is for anyone to run a particular codemod without having to
install jscodeshift or the codemod package itself locally.
```
npx @khanacademy/wb-codemod -t <transform-file-name> <path>
```
e.g.
```
npx @khanacademy/wb-codemod -t "template" src/
```
Issue: WB-1660
Verify that unit tests pass and that the package can be used to run codemods.
If you want to run this locally while the package is not published yet, you can
use the following command: …
> WB-1660: Create `wb-codemod` package

- .changeset/clean-carrots-give.md
- wb-codemod/bin/cli.js
- wb-codemod/package.json
- wb-codemod/src/wb-codemod.js
This change updates the wb-codemod package to use JS directly instead of TS.
This simplifies the build process and makes it easier to maintain.
The transform files will still be written in TypeScript, but the package will be
built to JS.
```
npx @khanacademy/wb-codemod -t template -d -p path/to/files/
```
> [🔥AUDIT🔥] Change wb-codemod to use JS directly

- .changeset/eight-timers-sneeze.md
- wb-codemod/bin/cli.js
- wb-codemod/transforms/__tests__/migrate-spacing-to-tokens.test.ts
- wb-codemod/transforms/migrate-spacing-to-tokens.ts
Creates a codemod to migrate the Spacing package to wb-tokens. This will allow
us to have a consistent spacing across the repo(s) and make it easier to change
in the future.
Issue: WB-1643
- Run the codemod on the repo (next PR).
- Run unit tests for the codemod.
> WB-1643.1: Add transform to migrate spacing to tokens

- .changeset/four-melons-breathe.md
- wb-codemod/transforms/__tests__/migrate-color-to-tokens.test.ts
- wb-codemod/transforms/migrate-color-to-tokens.ts
Creates a codemod to migrate the wb-color imports to wb-tokens. This will allow
us to have a consistent spacing across the repo(s) and make it easier to change
in the future.
Issue: WB-1642
- Run the codemod on the repo (next PR).
- Run unit tests for the codemod.
> WB-1642.1: Add transform to migrate color to tokens

- .changeset/pink-islands-grin.md
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
We are currently selecting disabled items when the "Select all" option is
selected. Even that this is not a common use case, it is still a bug in the
sense that it doesn't match how `<select>` works.
In this PR we are trying to match the behavior of `<select>` by not selecting
disabled option items when "Select all" is selected.
Another change is that we are counting the number of available options to
select in the `Select All (n)` label.
Issue: WB-1665
1. Navigate to /?path=/story/dropdown-multiselect--shortcuts.
2. Open the dropdown and select "Select all".
3. Verify that the disabled items are not selected.
https://github.com/Khan/wonder-blocks/assets/843075/199ae0d9-f59e-4ffe-bc15-fc1da44b9555
> WB-1665: MultiSelect: Don't select disabled items when select all is selected

- .changeset/short-numbers-cheer.md
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
There is a visual issue when the `horizontalRule` prop is set to `true` in the
`OptionItem` component. The `OptionItem` component is not vertically centered
as causes to include a padding after the horizontal rule.
This PR fixes that by applying the correct padding to the `OptionItem` component
to make it vertically centered when the `horizontalRule` prop is set.
Issue: WB-1666
1. Navigate to /?path=/story/dropdown-singleselect--custom-option-items.
2. Focus on different option items by pressing `Tab`.
2. Verify that the `OptionItem` component is vertically centered and the
horizontal rule is correctly aligned to the bottom of the component.
Alternatively, navigate to /?path=/story/dropdown-optionitem--horizontal-rule and verify the alignment.
| BEFORE | AFTER |
|--------|--------|
| …
> WB-1666: OptionItem not vertically centered when horizontalRule is set (fix)

- .changeset/rotten-cheetahs-guess.md
- packages/wonder-blocks-tokens/src/tokens/color.ts
- Add some new color tokens to existing primary colors. These new tokens are 24%
lighter than the original ones, and will be used for some cards in the WHAM
project.
- Also fixed a very small issue with the existing faded colors, which were not
including a mix with white. The change is minimal, but still worth as it allows
to convert the shade from an alpha value to a solid color.
Issue: https://khanacademy.atlassian.net/browse/WB-1668
Verify that the new colors are included and that the snapshots look correct.
> WB-1668: Tokens: Add 24% color shades

- .changeset/giant-tigers-shout.md
- __docs__/wonder-blocks-pill/pill.argtypes.tsx
- __docs__/wonder-blocks-pill/pill.stories.tsx
- packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
Adds a transparent variant to the Pill component. This variant is useful for
when the Pill is used as a filter, and the user wants to see the background
behind the Pill.
e.g.
Issue: https://khanacademy.atlassian.net/browse/WB-1669
Verify that the `transparent` variant works as expected.
- It's transparent in its resting state.
- It uses `offBlack32` in its pressed/active state.
https://github.com/Khan/wonder-blocks/assets/843075/18af2d1e-1db1-41cc-bb6d-776d91388c4d
> WB-1669: Pill - Add transparent variant

- .changeset/four-readers-rush.md
- packages/wonder-blocks-layout/src/components/__tests__/media-layout-context.test.tsx
- packages/wonder-blocks-layout/src/components/__tests__/media-layout.test.tsx
- packages/wonder-blocks-layout/src/components/media-layout.tsx
I was working on addressing the source of some hydration issues in webapp and discovered the `MediaLayout` component was using a heuristic to determine SSR that meant it was not doing the SSR behavior in our route tests.
I addressed this from the webapp side by deleting the `matchMedia` function when doing our route testing, but I also wanted to fix the core issue here by ensuring the `MediaLayout` component utilizes our central `Server.isServerSide()` function from Wonder Blocks Core.
This PR does that and also modifies the tests acccordingly. I also did some tweaks to the testing to make use of `describe.each` and reduce some nesting.
NOTE: I am not convinced the `MediaLayout` component hydrates properly since I don't see how it guarantees the initial client-side render will match the …
> [fei5384.1.medialayout] Make sure MediaLayout respects Server.isServerSide()

- .changeset/thick-spiders-wave.md
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
Fixes the width of the year dropdown to prevent the text from being truncated
when the user zooms in. This happened in Firefox, so we are setting a min-width
to the dropdown (listbox) to prevent this from happening.
Issue: WB-1673
/?path=/story/birthdaypicker--birthday-picker-default
1. Open the year dropdown in the BirthdayPicker component.
2. Zoom in the browser (to at least 30%).
3. Verify that the text is not truncated.
https://github.com/Khan/wonder-blocks/assets/843075/a6362f54-b906-4894-989f-cfb9f5c5fa4a
> WB-1673: Fix year dropdown width to avoid truncating the text when the user zooms in

- .changeset/ten-pumas-tap.md
- __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
- __docs__/wonder-blocks-form/text-field.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
Currently, `TextField` accepts a `validate` prop, which updates an internal error
state. We don’t update `aria-invalid` if the validation fails, and that might
mislead folks as they would expect this value to be changed internally.
This PR fixes that by setting `aria-invalid` directly in `TextField` to inform
the user when the validation fails and there's an error in the input field.
Also removed the `aria-invalid` from `LabeledTextField` as it's not necessary
since the error state is already being handled in `TextField`.
Issue: WB-1679
1. Navigate to the `TextField > Error` story in Storybook.
2. Verify that the `aria-invalid` attribute is set to `true` when the validation
fails.
3. Verify that the `aria-invalid` attribute is set to `false` when the validation
passes.
Do the same for the …
> WB-1679: Set aria-invalid inside TextField when validation fails

- .changeset/weak-melons-destroy.md
- __docs__/wonder-blocks-modal/modal-dialog.stories.tsx
- __docs__/wonder-blocks-modal/modal-panel.stories.tsx
- packages/wonder-blocks-modal/src/components/__tests__/modal-dialog.test.tsx
- packages/wonder-blocks-modal/src/components/modal-dialog.tsx
Requires `aria-labelledby` to comply with A-level WCAG success criterion 4.1.2
> Require `aria-labelledby` in ModalDialog (WCAG 2.1 4.1.2)

- .changeset/quick-chicken-remain.md
- __docs__/wonder-blocks-tooltip/tooltip.argtypes.ts
- __docs__/wonder-blocks-tooltip/tooltip.stories.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip.tsx
- packages/wonder-blocks-tooltip/src/index.ts
- packages/wonder-blocks-tooltip/src/util/types.ts
Adds a new `autoUpdate` prop to update the tooltip position when the trigger element changes.
This is useful for cases where the trigger element changes its position after
the tooltip is shown, like when the trigger element is a draggable element.
PopperJS does not update the tooltip position when the trigger element changes
by default, so we need to force the update.
After different approaches, I decided to use `MutationObserver` to listen to
changes in the trigger element and update the tooltip position when needed.
**NOTE:** The newer version of PopperJS (floating-ui) have an `autoUpdate`
middleware that does the same thing, but it's not available in the version we
are using. This prop uses the same naming to be consistent with the newer
version (if we decide to upgrade in the future). …
> WB-1681: Tooltip: Add `autoUpdate` prop to force updating the tooltip position

- .changeset/smooth-lies-build.md
- packages/wonder-blocks-tokens/src/tokens/color.ts
Based on previous discussions with Design, we are going to add faded versions of
the existing `offBlack` and white `color` tokens.
Currently, our "offBlack" versions are using the `rgba` format, and sometimes we just need the solid version of it, so we are adding those versions to the color tokens.
https://khanacademy.slack.com/archives/C8Z9DSKC7/p1713907216050369?thread_ts=1713907205.849639&cid=C8Z9DSKC7
Issue: https://khanacademy.atlassian.net/browse/WB-1682
Verify that the new colors are available in the `Tokens > Color` page.
> WB-1682: Add faded versions of offBlack

- .changeset/gold-jeans-repeat.md
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.tsx
- packages/wonder-blocks-tooltip/src/util/types.ts
The `Placement` type looked to be copy-pasted from the `react-popper` code which had many variations, but WB limits valid placements to `top | bottom | left | right`. Anything else will throw an error.
This change limits the allowed values to the valid values.
> Remove strings from Popover placement prop that throw errors

- .changeset/tender-frogs-appear.md
- packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
- packages/wonder-blocks-popover/src/components/popover-content.tsx
Previously, aria attributes were accepted as props, but nothing was done with them. I have passed the aria attributes to the `clickable` and the `view` so that they can be used.
> Pass aria attributes to pill

- .changeset/pink-tables-attack.md
- packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
Exposes tabIndex and passes to Clickable wrapper. Adds test.
> Allow consumers to set tabindex on pill when clickable

- .changeset/famous-birds-compare.md
- packages/wonder-blocks-core/src/util/__tests__/__snapshots__/unique-id-factory.test.ts.snap
- packages/wonder-blocks-core/src/util/__tests__/unique-id-factory.test.ts
- packages/wonder-blocks-core/src/util/unique-id-factory.ts
This came up with the Perseus team, where they had some Unicode characters in an ID and that was throwing errors. I did some more research and learned that only whitespace is considered to be invalid, so I updated our logic around this.
Issue: WB-1704
I ran the tests and they passed.
> Allow all special characters in IDs, except whitespace.

- .changeset/swift-days-refuse.md
- __docs__/wonder-blocks-form/labeled-text-field.argtypes.ts
- __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
- __docs__/wonder-blocks-form/text-field.argtypes.ts
- __docs__/wonder-blocks-form/text-field.stories.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-form/src/util/types.ts
HTML `<input>` elements have `min`, `max`, and `step` props.
Adding them here to TextField to better align with HTML props.
Issue: none
Storybook
http://localhost:6061/?path=/story/packages-form-textfield--number
> Allow TextField number input to use min, max, and step props

- .changeset/ten-forks-repair.md
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
Fixes an issue where the `onValidate` prop was not being called when the
callback was provided in the call site. This caused a weird behavior where
the `handleValidate` function inside `LabeledTextField` never got called.
See https://github.com/Khan/webapp/actions/runs/9273558563/job/25513924364?pr=22121
for more context in the failure.
Verify that unit tests pass.
> LabeledTextField: Fix `onValidate` prop to be called properly

- .changeset/afraid-coats-call.md
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
Requirement: When enableTypeAhead is set to false, Single Select component should not auto focus on a dropdown item when the search text changes.
This PR prvents the dropdown item from from focus when the search text changes the first time. 
Issue: DIST-4569
> Prevent dropdown item focus when enableTypeAhead is false

- .changeset/long-zoos-think.md
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
While working on #2235, I missed a few extra props from being passed to the
underlying `TextField` component. This PR fixes that.
Verify that unit tests work here and in webapp.
> [🔥AUDIT🔥] LabeledTextField: Fix onValidate prop to be called properlyLabeledTextField: Fix onBlur and onFocus props to be called properly

- .changeset/chatty-crews-visit.md
- __docs__/wonder-blocks-form/text-field.argtypes.ts
- __docs__/wonder-blocks-form/text-field.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-search-field/src/components/__tests__/search-field.test.tsx
- Changed `id` prop to be optional.
- Use `IDProvider` to automatically generate the `id` if it’s not provided by
the caller.
Issue: WB-1092
1. In Storybook, verify that the Default story auto-generates the `id` for the
input field: `?path=/story/packages-form-textfield--default`.
2. Modify the Default story to provide an `id` prop and verify that the `id` is
now used in the input field: `?path=/story/packages-form-textfield--default&args=id:some-custom-id`.
> WB-1092: Make id prop optional in TextField

- .changeset/few-mugs-speak.md
- packages/wonder-blocks-layout/src/components/__tests__/media-layout-context.test.tsx
- packages/wonder-blocks-layout/src/components/__tests__/media-layout.test.tsx
- packages/wonder-blocks-layout/src/components/media-layout.tsx
In working with React 18, I identified some hydration issues in our main website. One of these is in how the `MediaLayout` component renders. Previous to this change, it would render one way on the server and then another locally. Now we use the `WithSSRPlaceholder` to ensure we retain the same structure on initial render, whether on the server or on the client.
It's a reasonable simple change - I've done my best to leave the original code intact to minimize the change.
I have also updated the tests:
- to remove promise use (when we update the Testing Library and React in Wonder Blocks, the promise approach won't work right)
- to fix the tests that were failing after updating things to properly hydrate
Issue: FEI-5498
`yarn test`
Integrating this into webapp, and verifying that the …
> Fix hydration error in MediaLayout component

- .changeset/rotten-actors-flow.md
- __docs__/wonder-blocks-birthday-picker/birthday-picker.stories.tsx
- __docs__/wonder-blocks-dropdown/multi-select-variants.stories.tsx
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select-variants.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
- Use `aria-disabled` instead of `disabled` for SelectOpener so that the disabled state can be focusable. This makes it consistent with disabled buttons
- Add focus styling for disabled SelectOpener for both light and non-light types
- Add single/multiselect variant stories with states. When creating the new stories to show all the variants, I noticed two things (I will address these in a separate pull request!):
- The error state styling needs to be updated when the `light` prop is `true` 
- The state styling (focus, hover, active) can be moved from JS to CSS pseudoclasses (ie. `:focus-visible`, `:hover`, `:active`). By doing this, we can simplify logic and also utilize the Storybook pseudostates addon for visual regression tests (I'll add stories for the different states once this is …
> Allow SingleSelect and MultiSelect to be focusable when disabled

- .changeset/thin-pants-double.md
- __docs__/wonder-blocks-banner/banner.argtypes.ts
- __docs__/wonder-blocks-banner/banner.stories.tsx
- packages/wonder-blocks-banner/src/components/__tests__/banner.test.tsx
- packages/wonder-blocks-banner/src/components/__tests__/custom-icon-mock.svg
- packages/wonder-blocks-banner/src/components/banner.tsx
Adds support for an icon (phosphor or custom) to the Banner component. This overrides the default icon used to represent the kind of Banner
Issue: WB-1447
- Review Banner documentation (`?path=/docs/packages-banner--docs`)
- new `icon` prop documentation
- the example story descriptions for `With Phosphor Icon` and `With Custom Icon` 
- Verify that the Banner works with a PhosphorIcon (`?path=/story/packages-banner--with-phosphor-icon`)
- Verify that the Banner works with a custom icon (`?path=/story/packages-banner--with-custom-icon`)
- Verify that the aria-label of the icon matches the `kind` prop ("info", "success", "warning", "critical")
- Note: I created WB-1713 since the aria label for the icon doesn't support translations at the moment
Banner with Phosphor Icon
Banner with Custom …
> Add support for an icon in the Banner component

- .changeset/curvy-frogs-listen.md
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/select-opener.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- Remove storybook controls for SingleSelect disabled story. Because the storybook args included opened:false, the select was always closed, which was hiding a bug where the disabled select could still be opened using keyboard arrows
- Add disabled prop to DropdownCore so that it's interactions can be disabled if it is true. This is needed now that the SelectOpener does not have the disabled attribute set (since we use aria-disabled now so that it can be focusable)
- Add tests to make sure event handlers aren't called when a component is disabled
- Prevent Single and Multi Select from being in an open state when the `opened` prop and `disabled` prop are both true
Issue: WB-1238
- Confirm that the SingleSelect and MultiSelect cannot be opened when disabled, especially by using the down …
> Disable keyboard interactions for DropdownCore if component is disabled

- .changeset/moody-dragons-turn.md
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- Fixing bug where the SingleSelect and MultiSelect components can be opened via keyboard when it is disabled because it has 0 items. The select components should not be able to be opened when the select opener is disabled
- Update SingleSelect to have the same behaviour as MultiSelect: if all option items are disabled, the select should be disabled
Issue: WB-1238
- Confirm when there are no items, the select components should not be able to be opened using the keyboard
- `?path=/story/packages-dropdown-singleselect--disabled`
- `?path=/story/packages-dropdown-multiselect--disabled`
> Fixing edge case for opening the Single/MultiSelect when there are no items

- .changeset/four-donuts-chew.md
- __docs__/wonder-blocks-icon-button/icon-button-variants.stories.tsx
- __docs__/wonder-blocks-icon-button/icon-button.argtypes.ts
- __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
- packages/wonder-blocks-icon-button/src/util/icon-button-util.test.ts
- packages/wonder-blocks-icon-button/src/util/icon-button-util.ts
- IconButton: Add option for `large` value for `size` prop (24x24 icon size with target area of 48x48)
Issue: WB-1694
- New large size for the IconButton meets specifications
- `?path=/story/packages-iconbutton--sizes`
- `?path=/docs/packages-iconbutton-all-variants--docs`
- IconButton stories have 0 warnings in the Storybook a11y addon
> Adds large IconButton size

- .changeset/small-avocados-complain.md
- __docs__/wonder-blocks-cell/compact-cell.argtypes.tsx
- __docs__/wonder-blocks-clickable/clickable.argtypes.ts
- packages/wonder-blocks-cell/src/components/internal/__tests__/cell-core.test.tsx
- packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
- packages/wonder-blocks-cell/src/util/types.ts
- packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
- packages/wonder-blocks-dropdown/src/components/__tests__/action-menu.test.tsx
- packages/wonder-blocks-dropdown/src/components/action-menu.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
When OptionItems are used within an ActionMenu, they should have role="menuitemcheckbox" and use aria-checked instead of aria-selected
Issue: WB-1659
- Confirm that an ActionMenu with OptionItems communicates when an option item is selected (`?path=/story/packages-dropdown-actionmenu--with-option-items`)
- rendered option items should have role="menuitemcheckbox" and aria-checked="true"
- screenreaders communicate the checked status
In the before videos, the selected option item in the menu is not communicated to the user using a screen reader. In the after videos, it is communicated (safari reads out "Checkmark", Chrome reads out "checked")
https://github.com/Khan/wonder-blocks/assets/14334617/114ac914-0ece-4e65-a886-987e8ba2f163 …
> Communicate checked status to screenreaders when OptionItems are used in ActionMenu

- .changeset/light-swans-thank.md
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/components/button-core.tsx
Use the same theme token for the height of the underline on the active state of the tertiary button so that the hover and active styling are consistent
Issue: WB-1025
- Confirm that the hover and active state of the tertiary button have a consistent underline thickness
Before & After
https://github.com/Khan/wonder-blocks/assets/14334617/2ce3725e-48f1-49f8-a111-761d1ce48944
> Fix active state styling for tertiary button

- .changeset/new-rice-punch.md
- __docs__/wonder-blocks-banner/banner.stories.tsx
- packages/wonder-blocks-banner/src/components/banner.tsx
Fixing styling issue where non-tertiary buttons get cropped when used as a custom action in the banner component.
Issue: WB-1716
- Confirm buttons look as expected in the banner (`?path=/story/packages-banner--with-custom-action-primary`)
- Confirm a mix of actions and custom actions look as expected in the banner (`?path=/story/packages-banner--with-mixed-actions`)
Mixed actions (before & after changes)
Primary button for custom action (before & after changes)
> Fix Banner styling for custom action buttons

- .github/workflows/node-ci-pr.yml
This means we can edit tsx test files without being asked to add per package changesets.
Edit a tsx test file and push to a branch, raise a PR and see that changeset check does not ask for a changeset.
> [🔥AUDIT🔥] [ignoretsxtestfiles] Ignore tsx test files in changeset check

- .changeset/gentle-houses-listen.md
- build-settings/rollup.config.mjs
- package.json
- yarn.lock
Turns out that the rollup plugin, autoexternals, doesn't handle sub-package improts, like `react-dom/server`. However, reading the issue report on that package, [I saw a link to another](https://github.com/stevenbenisek/rollup-plugin-auto-external/issues/16#issuecomment-557172792), more up-to-date package, that does handle this. So I switched to that package, and now everything works as expected.
I did have to explicitly use the `mjs` extension for the rollup config, but that's a small price to pay for the benefits of the new package.
`yarn build` to see that the build works.
I'll also verify the packages in webapp to check everything else is fine, though the storybook should also check out.
> [fixexternals] Fix how react-dom/server is imported

- .changeset/dull-stingrays-mate.md
- .vscode/settings.json
- .vscode/tasks.json
- packages/wonder-blocks-form/src/components/__tests__/field-heading.test.tsx
- packages/wonder-blocks-i18n/src/functions/__tests__/i18n-store.test.ts
- packages/wonder-blocks-i18n/src/functions/__tests__/i18n.test.ts
- packages/wonder-blocks-i18n/src/functions/i18n-store.ts
- packages/wonder-blocks-i18n/src/functions/i18n.ts
- packages/wonder-blocks-i18n/src/functions/types.ts
- packages/wonder-blocks-i18n/src/index.ts
This is adding in functionality that's similar to LinguiJS, to the wonder-blocks-i18n package, so that we can have a store of translated strings and use them for our translations instead of assuming that the strings will already be translated for us.
Issue: FEI-5682
Tests should pass! I'll be wiring this up in Webapp in a separate PR, once this lands.
> Add in loadTranslations/clearTranslations to i18n, use stored messages if they exist.

- .changeset/plenty-rockets-breathe.md
- __docs__/wonder-blocks-popover/popover.stories.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover.test.tsx
- packages/wonder-blocks-popover/src/components/popover.tsx
Adds conditional logic to allow aria-describedby to be:
- defined by the user (overrides default)
- available in addition to `aria-label` or `aria-labelledby`
Issue: LEMS-2225
1. `yarn start` in branch or [chromatic link](https://5e1bf4b385e3fb0020b7073c-lzlzfekdzl.chromatic.com/?path=/docs/overview--docs)
2. Navigate to Popover stories
3. Choose `With custom aria described by` story 
4. Story includes hidden element that should be read out by the screen reader 
https://github.com/user-attachments/assets/a46ca21a-71ac-442a-891b-98dc675701fb
> fix(LEMS-2225): add conditional aria-describedby logic

- .changeset/orange-peaches-sit.md
- __docs__/wonder-blocks-birthday-picker/birthday-picker.argtypes.ts
- __docs__/wonder-blocks-birthday-picker/birthday-picker.stories.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
To allow the BirthdayPicker to be rendered in a wider variety of locations, such as narrow modals or mobile views, two new props have been added. "style" which allows the caller to add styles to the root element of the BirthdayPicker, and "dropdownStyle" which applies styles to the individual dropdowns. As opposed to a more narrow approach of specifying a "vertical" prop, this broad approach relieves the component of having to know when to render horizontally or vertically. This logic is placed in the callers hands, which can easily be determined via media query.
Issue: None
- View http://localhost:6061/?path=/story/packages-birthdaypicker--birthday-picker-vertical
- ensure component displays in a top to bottom manner
- View http://localhost:6061/?path=/story/packages-birthdaypicker--birth …
> Add style and dropdownStyle props to BirthdayPicker

- .changeset/breezy-moons-dress.md
- .changeset/hungry-planes-push.md
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- __docs__/wonder-blocks-banner/banner.stories.tsx
- __docs__/wonder-blocks-cell/compact-cell.stories.tsx
- __docs__/wonder-blocks-cell/detail-cell.stories.tsx
- __docs__/wonder-blocks-clickable/accessibility.stories.tsx
- __docs__/wonder-blocks-clickable/clickable-behavior.stories.tsx
- __docs__/wonder-blocks-clickable/clickable.stories.tsx
- __docs__/wonder-blocks-core/view.stories.tsx
- __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- __docs__/wonder-blocks-layout/media-layout.stories.tsx
- __docs__/wonder-blocks-link/link.stories.tsx
- __docs__/wonder-blocks-popover/popover.stories.tsx
- __docs__/wonder-blocks-theming/adding-a-theme.mdx
- __docs__/wonder-blocks-theming/merge-theme.mdx
- __docs__/wonder-blocks-theming/theme-examples.tsx
- __docs__/wonder-blocks-theming/with-scoped-theme.mdx
- __docs__/wonder-blocks-tooltip/tooltip.stories.tsx
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-tokens/src/tokens/color.ts
- static/sb-styles/vars.css
Follow up to #2291. This PR removes the pink and lightBlue colors from the
tokens package, as requested by the design team.
Issue: https://khanacademy.atlassian.net/browse/WB-1732
Verify that the snapshots switch to different colors.
> Remove pink and lightBlue colors

- .changeset/soft-seas-sparkle.md
- packages/wonder-blocks-button/src/components/button-core.tsx
Fixes a UI issue where secondary buttons weren't displaying the focus ring when
disabled + focused.
Issue: WB-1741
Navigate to the Button variants story in Storybook and verify that the focus
ring is displayed when a secondary button is disabled and focused.
/?path=/story/packages-button--variants
> WB-1741: Button is missing focus styles when secondary and disabled

- .changeset/small-walls-destroy.md
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/themes/default.ts
While working on some other changes, I noticed that the icon color on secondary
and tertiary buttons was not being set correctly. This PR fixes that issue by
setting the icon color to the same color as the text.
Navigate to /?path=/story/packages-button--icon
Hover over the secondary and tertiary buttons
Verify that the icon color on secondary and tertiary buttons is the same as the
text color
https://github.com/user-attachments/assets/1902a543-463c-443d-824b-6b6d1263fc0d
https://github.com/user-attachments/assets/5b9929a9-3082-4d2b-b439-1a4b2e0222c7
> Fix icon color on secondary and tertiary buttons (hover)

- .changeset/sharp-maps-leave.md
- __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
- packages/wonder-blocks-form/src/components/field-heading.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
- Use the `LabeledTextField`'s `light` prop in `FieldHeading` to apply light styling for the label, required indicator, description, and the error message. This improves the color contrast of the elements in `LabelledTextField` when used on a dark background. This aligns with the specs in [Figma](https://www.figma.com/design/VbVu3h2BpBhH80niq101MHHE/%F0%9F%92%A0-Main-Components?node-id=13840-8635&t=sq9ZCuTcvzXGme48-4)
- Updated documentation for the `Light` and `Error Light` stories
Issue: WB-1744
1. Review the LabelledTextField Light and ErrorLight documentation (`?path=/docs/packages-form-labeledtextfield--docs`)
2. Review the Light and ErrorLight stories
- `?path=/story/packages-form-labeledtextfield--light` 
- `?path=/story/packages-form-labeledtextfield--error-light`
> LabeledTextField: Adjust styling for light prop for improved color contrast

- .changeset/famous-walls-scream.md
- __docs__/wonder-blocks-form/text-field-variants.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- Update `TextField` state styling so it is consistent with other components like `TextArea`, `SingleSelect`, `MultiSelect` (especially the focus styling)
- The styling changes use CSS pseudo-classes now so that we can have visual regression tests for the UI states using Storybook's pseudo-states add on.
- These styles align with the [Figma TextField component](https://www.figma.com/design/VbVu3h2BpBhH80niq101MHHE/%F0%9F%92%A0-Main-Components?node-id=13497-10015&t=QZlu8ecGmGU3QceA-4)
- Removed unneeded focused state since we use pseudo classes now
- Added variant stories for Chromatic tests
Note: These styles are based on how TextArea was styled!
Issue: WB-1746
1. Confirm the focus styling for TextField when (`?path=/docs/packages-form-textfield--docs`):
- it is focused
- it is focused on …
> Update TextField styling for consistency with other components (focus styling)

- .changeset/wicked-carrots-hope.md
- __docs__/wonder-blocks-core/initial-fallback.stories.tsx
- packages/wonder-blocks-core/src/components/__tests__/initial-fallback.test.tsx
- packages/wonder-blocks-core/src/components/__tests__/unique-id-provider.test.tsx
- packages/wonder-blocks-core/src/components/initial-fallback.tsx
- packages/wonder-blocks-core/src/components/unique-id-provider.tsx
- packages/wonder-blocks-core/src/index.ts
- packages/wonder-blocks-layout/src/components/media-layout.tsx
This renames `WithSSRPlaceholder` to more accurately reflect its purpose. This includes changing the `placeholder` prop to `fallback` so that we more closely match the `React.Suspense` API.
1. Find/replace `WithSSRPlaceholder placeholder=` in files using that component to `InitialFallback fallback=`
2. Find/replace `WithSSRPlaceholder` to `InitialFallback`
`yarn test`
`yarn start:storybook` and view the docs for the `InitialFallback` component
> [initialfallback] Rename WithSSRPlaceholder to InitialFallback

- .changeset/thin-gorillas-visit.md
- __docs__/wonder-blocks-dropdown/combobox.argtypes.ts
- __docs__/wonder-blocks-dropdown/combobox.stories.tsx
- packages/wonder-blocks-dropdown/src/components/combobox.tsx
- Changed  the border color from `offBlack16` to `offBlack50` to be consistent with the rest of form fields.
- Also applied a few Storybook fixes:
- Refactored arg types to use categories
- Fixed interactive story to support switching `selectionType` values without breaking the story.
Issue: WB-1677
Navigate to the Combobox docs in Storybook and verify the following:
1. The border color is now `offBlack50`.
2. The arg types are now categorized.
3. The interactive story should now support switching `selectionType` values
without breaking the story. This means that the story should try to preserve the
`value` when switching between `single` and `multi` selection types.
https://github.com/user-attachments/assets/0d8481d8-5fcf-4c0e-b665-0798c22f3e0c
> WB-1677.2: Combobox misc fixes

- config/jest/test-setup.js
React 18 requires these things but JSDOM doesn't include them, so we shim them
`yarn test` before React 18 update and after.
> [encoderpatch] Patch TextEncoder/TextDecoder for tests

- .changeset/tame-mice-lick.md
- __docs__/wonder-blocks-toolbar/toolbar.argtypes.tsx
- __docs__/wonder-blocks-toolbar/toolbar.stories.tsx
- packages/wonder-blocks-toolbar/src/components/toolbar.tsx
There’s a valid use case where a toolbar needs to use a progress bar in the
center area. Right now, that part of the layout only accepts a title as a
string.
See design screenshot for reference:
This change allows the title to also accept React nodes, which will allow
engineers to use more complex components in that part of the layout.
Issue: https://khanacademy.atlassian.net/browse/WB-1755
Navigate to the new story in the toolbar documentation and verify that the
progress bar is displayed in the center area.
/?path=/docs/packages-toolbar--docs#custom%20toolbar
> WB-1755: Toolbar - Allow title to also support React nodes

- .changeset/real-taxis-develop.md
- __docs__/wonder-blocks-dropdown/combobox.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/combobox.test.tsx
- packages/wonder-blocks-dropdown/src/components/combobox.tsx
- packages/wonder-blocks-dropdown/src/hooks/use-listbox.tsx
Currently, the Combobox component uses useEffect to determine when the selected
value changes.
This is causing some sync issues between the hook (`useListbox`) and its caller
(`Combobox`), as we rely on side effects to verify when the value changes.
For example, there was a case where the combobox was not closing when the same
option was selected twice in a row.
This PR takes a different approach to let the consumer component know when an
option is selected via a handler exposed from the hook.
Also took the opportunity to reorganize/cleanup the code in the Combobox
component.
Issue: https://khanacademy.atlassian.net/browse/WB-1754
Navigate to the Combobox story in Storybook and verify that the component
behaves as expected.
Also open the combobox, select an option, verify that the …
> WB-1754: Refactor Combobox to consume handleChange from useListbox instead of relying on useEffect

- .changeset/cuddly-chefs-care.md
- __docs__/wonder-blocks-popover/popover.argtypes.tsx
- __docs__/wonder-blocks-popover/popover.stories.tsx
- __docs__/wonder-blocks-tooltip/tooltip.argtypes.ts
- __docs__/wonder-blocks-tooltip/tooltip.stories.tsx
- packages/wonder-blocks-popover/src/components/popover.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip.tsx
This new `viewportPadding` prop provides spacing between the popper and the viewport edges in the `Tooltip` and `Popover` components. If this prop is not provided, default spacing is applied so that the popper contents are not too close to the edge by default. This can be overridden to support different use cases.
Note: `viewportPadding` is only applied if the `rootBoundary` prop is set to `viewport`. `Tooltip` will always use `viewport` for the `rootBoundary`, however, this prop is exposed in the `Popover` component
Issue: WB-1756
- Tooltip
- Confirm that default spacing is applied to the Tooltip contents when it is in the corners (`?path=/story/packages-tooltip-tooltip--in-corners`)
- Confirm that changing the `viewportPadding` control in Storybook updates the spacing between the …
> Add `viewportPadding` prop to `Tooltip` and `Popover` components

- .changeset/modern-bats-crash.md
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip.integration.test.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-popper.tsx
There have been some instances in `webapp` where Tooltip or Popover components are initially rendered in the top left corner and then is moved to the correct position in the next render. This causes the Tooltip/Popover to flicker briefly before it is shown in the correct place. In this video, we are able to see the Tooltip in the top left corner if we go through a video frame by frame:
https://github.com/user-attachments/assets/029e75b4-fc98-4033-b2c2-46ec30326603
When we log the style props from `popper-js`, we see that it passes us a `transform` property when it is rendered in the correct position. 
| Styles when popper is in the corner | Styles when positioned properly |
| --- | --- |
| ![tooltip-log-incorrect](https://github.com/user-attachments/assets/4e49afa2-6e7d-4962-b3a0-42837c1e8 …
> Fix initial Tooltip/Popover flicker in wrong position

- .changeset/two-toys-raise.md
- __docs__/wonder-blocks-form/text-area-variants.stories.tsx
- __docs__/wonder-blocks-form/text-field-variants.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
Work was initially done in https://github.com/Khan/wonder-blocks/pull/2302 to update the TextField state styling so it was consistent with other components like SingleSelect, MultiSelect, and TextArea. The new styling had some issues in webapp where the focus outline would get cropped off if an ancestor element had `overflow: hidden`. The new styles were reverted in https://github.com/Khan/wonder-blocks/pull/2309 to unblock other WB changes at the time. This PR re-applies those styles and addresses the focus outline issue in both the TextField and TextArea components.
The cropped focus outline issue is resolved by making sure the outlines are within the component. This makes it so the outline is never cropped off if a parent or ancestor element has `overflow: hidden`. The changes that …
> Updated TextField & TextArea styling (for consistency and addresses cropped outline)

- .changeset/curly-bats-cover.md
- __docs__/wonder-blocks-search-field/search-field.argtypes.ts
- packages/wonder-blocks-search-field/src/components/__tests__/search-field.test.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
The SearchField component now accepts an `onKeyUp` prop that will be called when
the user releases a key while the input is focused.
This is to bring consistency with the other input components in the library and
also to allow for more flexibility when using the SearchField component.
Also took the opportunity to clear some of the SB argtype descriptions, as we no
longer need to duplicate them as of SB 8.0.
NOTE: This will be used as part of the Search page refactor.
Issue: FEI-5728
Verify that the unit tests pass.
> SearchField: Add onKeyUp prop

- .changeset/three-keys-add.md
- __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
- packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
This PR adds a new prop `type` to the `IconButton` component that allows the
button to submit a form when clicked or pressed. This is useful when we want to
use an IconButton to submit a form, for example, a search form.
This is done as I noticed that the IconButton component is missing the `type`
and was needed in the search page. The prop is currently set, but the type
definition is missing.
Issue: FEI-5728
Docs:
- Navigate to /?path=/docs/packages-iconbutton--docs#submitting%20forms
- Verify that the docs make sense.
Interactive example:
- Navigate to /?path=/story/packages-iconbutton--submitting-forms
- Verify that the submit action is recorded in the SB `Actions` tab.
> IconButton: Add type=submit prop to allow submitting forms using the button

- .changeset/thick-maps-provide.md
- packages/wonder-blocks-i18n/src/functions/__tests__/i18n.test.ts
- packages/wonder-blocks-i18n/src/functions/plural-forms.ts
It only has "other", but was configured "like english", resulting in a crash
on km.khanacademy.org for pages with plural form platform strings.
Further details can be seen on Slack: https://khanacademy.slack.com/archives/C3SLM30AW/p1727281143856849
Issue: https://khanacademy.atlassian.net/browse/CP-8661
Test Plan:
- After making a release of `wonder-blocks-i18n` package and deploying webapp
- Verify https://km.khanacademy.org/math/early-math/cc-early-math-counting-topic doesn't crash
> Fix plural forms configiration for Khmer locale

- .changeset/friendly-moose-type.md
- packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
Following up on #2325, this PR fixes an issue that I introduced in the
IconButton component, which was that the type prop was not being set to 'button'
by default.
This PR fixes that issue and also adds an optional `id` prop to the
IconButton component.
NOTE: We set `button` as the default type because it is the most common use case
of how browsers interpret the type attribute of a button element. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type
Verify that the IconButton component works as expected with the new changes.
Also verify that that the tests pass.
/iframe.html?args=id:some-identifier&id=packages-iconbutton--default&viewMode=story
> IconButton: Add id prop, fix type to set 'button' as default

- .changeset/old-islands-relax.md
- packages/wonder-blocks-testing/src/gql/__tests__/gql-request-matches-mock.test.ts
- packages/wonder-blocks-testing/src/gql/gql-request-matches-mock.ts
Before this change, these two variables objects are considered different:
```ts
{
a: undefined,
b: 1
}
```
```ts
{
b: 1
}
```
This can be annoying when writing tests, because you have to explicitly set the variable to `undefined` in the expectation if the actual request ends up fetching with an explicit `undefined` value.
To make GraphQL mocks easier, we now consider a missing key to be equivalent to an explicit key with an `undefined` value. This brings this approach to GraphQL mocking inline with Apollo mocks that already do this.
Note that with this implementation, there's no way to assert that an explicit `undefined` variable is included in the request. We could add that if it turns out to be something we really need though I suspect that it is not.
Issue: FEI-5850
`yarn test`
> [fei5850.1.friendlyobjectmatching] Support undefined variable comparison

- .changeset/great-paws-ring.md
- __docs__/wonder-blocks-testing/exports.mock-fetch.mdx
- __docs__/wonder-blocks-testing/exports.mock-gql-fetch.mdx
- packages/wonder-blocks-testing-core/src/__tests__/mock-requester.test.ts
- packages/wonder-blocks-testing-core/src/fetch/mock-fetch.ts
- packages/wonder-blocks-testing-core/src/fetch/types.ts
- packages/wonder-blocks-testing-core/src/index.ts
- packages/wonder-blocks-testing-core/src/mock-requester.ts
- packages/wonder-blocks-testing-core/src/types.ts
- packages/wonder-blocks-testing/src/gql/__tests__/mock-gql-fetch.test.tsx
- packages/wonder-blocks-testing/src/gql/mock-gql-fetch.ts
- packages/wonder-blocks-testing/src/gql/types.ts
An oft annoying but sometimes useful feature of Apollo's `MockLink` is that it will hard fail if a request is made that has not been mocked. This is annoying because it forces folks to provide a mock for every request, even if they don't care about that request. However, it is useful when debugging tests to see why a mock isn't matching as expected or what requests are happening (the KA_LOG_FETCHES is useful for seeing this info too, but less accessible).
This change adds the ability to turn on hard fails for our request mocking system. I have added this using a fluent API so that it is more easily worked into existing uses of this mocking system.
I've also added tests to verify the new functionality, and added some additional commentary to the types for the mocking framework.
Issue: …
> [fei5850.2.hardfail] Add hard fail support to request mocking

- .changeset/empty-wasps-beg.md
- __docs__/wonder-blocks-form/labeled-text-field.argtypes.ts
- packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
- Adds `name` prop for `LabeledTextField` so that it can be set on the `TextField` component.
This is useful for setting the `name` attribute with the `autocomplete` attribute on input fields. This will help address a [LevelAccess issue](https://khanacademy.hub.essentia11y.com/short-link/C9J-QKFwoBnaiDMD) on the login page for FEI-5839: `Ensure that common input fields allow autocomplete and use standard autocomplete values`
Issue: WB-1762
- Confirm that setting the `name` prop sets the `name` attribute on the input field in LabeledTextField (`?path=/story/packages-form-labeledtextfield--default&args=testId:;name:test-123`)
> Adding name prop in LabeledTextField for the TextField component

- .changeset/rare-islands-pretend.md
- __docs__/wonder-blocks-dropdown/combobox.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/combobox.test.tsx
- packages/wonder-blocks-dropdown/src/components/combobox-live-region.tsx
- packages/wonder-blocks-dropdown/src/components/combobox.tsx
- packages/wonder-blocks-dropdown/src/util/constants.ts
- packages/wonder-blocks-dropdown/src/util/types.ts
- packages/wonder-blocks-form/src/components/text-field.tsx
- Added `error` prop to the `Combobox` component to handle the error state.
- Included an X icon to clear the combobox selection in single-selection mode. This is useful for the user to quickly reset the value when needed. 
- Textbox: Modifies the order in which the `aria-invalid` attribute is applied
to the input element.
Issue: WB-1757
1. Navigate to the `Error` story: /?path=/story/packages-dropdown-combobox--error
2. Verify that the error state is displayed and `aria-invalid` is set `true`.
3. Open the listbox and select one option.
4. Verify that the error is gone and `aria-invalid=false`.
5. Verify that the "Clear selection" button (X) is now visible.
6. Click on the X button.
7. Verify that the error is visible again and `aria-invalid=true`. …
> WB-1757.1: Combobox - Add error prop

- .changeset/fresh-onions-peel.md
- __docs__/wonder-blocks-form/checkbox-group.stories.tsx
- __docs__/wonder-blocks-form/radio-group.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/checkbox-group.test.tsx
- packages/wonder-blocks-form/src/components/__tests__/radio-group.test.tsx
- packages/wonder-blocks-form/src/components/checkbox-group.tsx
- packages/wonder-blocks-form/src/components/group-styles.ts
- packages/wonder-blocks-form/src/components/radio-group.tsx
`RadioGroup` and `ChoiceGroup` components are not associating correctly their
labels with their `fieldset` elements. The underlying issue is that these
components are appending a `View` element as the only child of the `fieldset`
element, which is causing the `fieldset` element to not associate correctly the
`legend` value as its label.
This PR fixes that issue by removing the `View` element and using the `legend`
element directly as the first child of the `fieldset` element.
Navigate to:
- CheckboxGroup: /?path=/docs/packages-form-checkboxgroup--docs
- RadioGroup: /?path=/docs/packages-form-radiogroup--docs
Verify that the first example associates the `label` value with the `fieldset`
element correctly.
| BEFORE | AFTER |
|--------|--------|
| <img width="1122" …
> Form: Fix a11y issue on RadioGroup and ChoiceGroup

- .changeset/pink-turtles-sleep.md
- __docs__/wonder-blocks-labeled-field/accessibility.mdx
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- packages/wonder-blocks-labeled-field/src/components/__tests__/labeled-field.test.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
- Use an auto-generated unique id if the `id` prop is not provided
- Wire up elements within the component
- the `label` element's `for` attribute is the field `id`
-  `aria-describedby` on the field has the ids of the description and/or error message elements
- Apply attributes to the field element:
- `id`
- `aria-describedby`
- `required` if the `required` prop is set to `true`
- `testId`
Issue: WB-1503
- Tests are passing
- Updated documentation makes sense:
- `?path=/docs/packages-labeledfield-labeledfield--docs`
- `?path=/docs/packages-labeledfield-labeledfield-accessibility--docs`
- There are no a11y warnings in the Storybook Accessibility add on for the LabeledField stories
- Note: There are warnings for the LabeledField stories with the different field examples. They are related …
> LabeledField(part3): Wire up attributes

- .changeset/fluffy-forks-check.md
- __docs__/wonder-blocks-birthday-picker/birthday-picker.stories.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
The BirthdayPicker gets cut off at small viewport widths: https://khanacademy.atlassian.net/browse/WB-1739
In this PR, I opted for a hard-coded breakpoint in CSS to change the flexDirection.
- This will be updated with https://khanacademy.atlassian.net/browse/WB-1655 for media query tokens in a separate PR!
I also preserved the somewhat recent change of allowing style and dropdownStyle props in https://github.com/Khan/wonder-blocks/pull/2288.
> Improve responsiveness of BirthdayPicker

- .changeset/dirty-dragons-fix.md
- packages/wonder-blocks-icon/src/components/__tests__/phosphor-icon.test.tsx
- packages/wonder-blocks-icon/src/components/phosphor-icon.tsx
When an `aria-label` is provided, there should be a `role` applied to the element to give it meaning to browsers and screenreaders. This PR defaults the `role` to `"img"` in `PhosphorIcon` when an `aria-label` is provided.
I'm not sure what our definitions are for "major", "minor", and "patch" releases. _I_ would consider this a `minor` release since we are changing the behavior (even if it is slight), but it is backwards compatible so `patch` might be fine.
Issue: WB-1795
- Tests pass
- Axe is happy
> PhosphorIcon: default role to img when aria-label is provided

- .changeset/cold-cows-sit.md
- __docs__/wonder-blocks-form/text-area-variants.stories.tsx
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field-variants.stories.tsx
- __docs__/wonder-blocks-form/text-field.argtypes.ts
- __docs__/wonder-blocks-form/text-field.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-area.test.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
Adds an `error` prop to TextField and TextArea components so they can be put in an error state declaratively. This is useful for validation that happens after a form submission.
Related to the LabeledField work:
- By having an error prop, the LabeledField component will set the `error` prop to `true` if it is provided with an error message (will do this in a separate PR for LabeledField work)
- The error prop is consistent with other fields such as the SingleSelect, MultiSelect, and Combobox components. I'll be updating SearchField in another PR (with other updates)!
- These changes can be released separately from the LabeledField changes since they are incremental changes to existing components
Issue: WB-1777
- Setting the `error` prop puts the component in an error state (`aria-invalid` …
> TextField and TextArea: add `error` prop

- .changeset/chatty-moles-brush.md
- __docs__/wonder-blocks-form/text-area.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-area.test.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- Adds instantValidation prop so there is an option to validate on blur. If instantValidation is false, the error is also cleared on change
- If textarea is required and instantValidation is false, validate whenever the user tabs away from the field
Issue: WB-1781
Next: I'll work on refactoring TextField to a function component first and then will add the same `instantValidation` prop to TextField
- Instant Validation docs are reviewed (`/?path=/docs/packages-form-textarea--docs#instant%20validation`)
- Instant Validation works as expected (see docs for expected behaviour) (`/?path=/story/packages-form-textarea--instant-validation`)
> Add `instantValidation` prop for TextArea

- .changeset/large-rockets-wonder.md
- packages/wonder-blocks-form/src/components/text-field.tsx
Refactor TextField to be a function component. 
This will make it easier to share validation logic from the TextArea instantValidation PR https://github.com/Khan/wonder-blocks/pull/2355 so that TextField will also have the `instantValidation` prop functionality (I'll be working on this next)!
Issue: WB-1781
Tests pass and TextField looks and functions the same way (`/?path=/docs/packages-form-textfield--docs`)
> Refactor TextField to be a function component

- .changeset/old-ghosts-yell.md
- __docs__/wonder-blocks-form/form-utilities.ts
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field.argtypes.ts
- __docs__/wonder-blocks-form/text-field.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-area.test.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-field.test.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-form/src/hooks/__tests__/use-field-validation.test.ts
- packages/wonder-blocks-form/src/hooks/use-field-validation.ts
- Adds `instantValidation` prop to `TextField` component
- Create `useFieldValidation` hook to share validation logic between `TextField` and `TextArea`
- `TextArea` is updated to use `useFieldValidation` hook.
- Both `TextArea` and `TextField` will now validate on initialization if `value` is not empty and it is not disabled
- Stories: Use utility functions for validate functions
Issue: WB-1781
- TextField
- Instant Validation docs are reviewed (`/?path=/docs/packages-form-textfield--docs#instant%20validation`)
- Instant Validation works as expected (see docs for expected behaviour) (`/?path=/story/packages-form-textfield--instant-validation`)
- TextArea
- Instant Validation docs are reviewed (`/?path=/docs/packages-form-textarea--docs#instant%20validation`)
- Instant Validation works as …
> Add `instantValidation` prop for TextField & share logic with TextArea

- .changeset/old-pears-fix.md
- __docs__/wonder-blocks-dropdown/combobox.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/combobox.test.tsx
- packages/wonder-blocks-dropdown/src/components/combobox.tsx
Adds a new `startIcon` prop (optional) to the Combobox component. This prop
will allow to optinally add an icon to the left of the input field.
This use case will be helpful for the AI tools case where we want to use a
search icon.
Issue: https://khanacademy.atlassian.net/browse/WB-1779
Verify that the `Start icon` docs make sense and that the example works as
expected.
/?path=/docs/packages-dropdown-combobox--docs#start%20icon
> WB-1779: Add startIcon prop to Combobox

- .changeset/fresh-vans-love.md
- packages/wonder-blocks-i18n/src/functions/__tests__/i18n.test.ts
- packages/wonder-blocks-i18n/src/functions/i18n.ts
This bug is in prod right now, unfortunately. Some strings are appearing untranslated.
Issue: FEI-6007
This was actually wrong in the tests!! So I fixed the test in the process.
> [🔥AUDIT🔥] Fix ngettext not returning plural translations.

- .changeset/dry-kangaroos-boil.md
- packages/wonder-blocks-i18n/src/functions/__tests__/i18n-store.test.ts
- packages/wonder-blocks-i18n/src/functions/__tests__/i18n.test.ts
- packages/wonder-blocks-i18n/src/functions/i18n-store.ts
- packages/wonder-blocks-i18n/src/functions/i18n.ts
- packages/wonder-blocks-i18n/src/index.ts
I may have introduced this in my last fix, actually - but this now helps us ensure that we don't accidentally use the other language pluralization rules when we are falling back to English strings.
Issue: FEI-6007
The tests pass!
> [🔥AUDIT🔥] Fix up plural form fallback when no translation is present.

- .changeset/breezy-bears-teach.md
- __docs__/wonder-blocks-search-field/search-field-variants.stories.tsx
- __docs__/wonder-blocks-search-field/search-field.stories.tsx
- packages/wonder-blocks-search-field/src/components/__tests__/search-field.test.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
To make the SearchField component more consistent with other form field components like TextField and TextArea, we add validation related props to the component. See [LabeledField Implementation Spec](https://khanacademy.atlassian.net/wiki/spaces/WB/pages/2261352551/LabeledField+Implementation+Spec) for more details!
The changes include:
- Add error, instantValidation, validate, onValidate props to SearchField
- Minor tweaks
- Hide clear icon button if the field is disabled
- Refine magnifying glass icon styling to make it [match Figma component](https://www.figma.com/design/VbVu3h2BpBhH80niq101MHHE/%F0%9F%92%A0-Main-Components?node-id=13840-8605&t=83MBW2IFJ6nx42vp-4) more (smaller, bold icon, spacing, update disabled state)
- Storybook:
- Add error and validation stories for SearchField …
> SearchField: Add validation props and refine states

- .changeset/cuddly-fireants-cheat.md
- packages/wonder-blocks-search-field/src/components/__tests__/search-field.test.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
Previously, the SearchField component was appending "-field" to the end of a provided id prop. We remove this post-fix and now use the `id` prop as is
This change is needed so when SearchField is used with LabeledField, LabeledField will set the id of the field element and wire it up with the label element. Since LabeledField works with a variety of components, the id shouldn't be modified by the field.
Issue: WB-1771
- Confirm that the id on the search field is the same value as the id prop (`/?path=/story/packages-searchfield--default&args=id:test123`)
- Verify with the npm snapshot if there will be any breaking unit/e2e tests in webapp due to the internal id change
> SearchField: Remove -field postfix from id

- .changeset/mean-ligers-relax.md
- .changeset/smooth-poems-buy.md
- __docs__/wonder-blocks-dropdown/base-select.argtypes.ts
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/select-opener.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-opener.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- packages/wonder-blocks-dropdown/src/util/constants.ts
- Adding validation related props to SingleSelect: `validate`, `onValidate`, `required`. (`error` prop was already supported)
- DropdownOpener and SelectOpener: Add optional `onBlur` prop and set `aria-invalid` based on `error` prop
- DropdownCore: When checking keyboard events, check what key is pressed using [event.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) instead of [event.which](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) or [event.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) which are now deprecated. Testing keyboard interactions in tests weren't triggering the correct logic since we were using deprecated fields that [user-event doesn't support …
> SingleSelect validation props

- .changeset/thin-gifts-tickle.md
- __docs__/wonder-blocks-dropdown/multi-select.argtypes.ts
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- packages/wonder-blocks-dropdown/src/hooks/__tests__/use-select-validation.test.ts
- packages/wonder-blocks-dropdown/src/hooks/use-select-validation.tsx
- packages/wonder-blocks-dropdown/src/util/helpers.ts
- Refactor SingleSelect validation logic to useSelectValidation hook
- Adding validation related props to MultiSelect: validate, onValidate, required. (error prop was already supported)
- Make sure aria-invalid is set if it is in an error state
Issue: WB-1782
- MultiSelect docs are reviewed `?path=/docs/packages-dropdown-multiselect--docs`
- Validation works as expected in MultiSelect (see docs for more details on validation behaviour):
- Error (`?path=/story/packages-dropdown-multiselect--error`)
- Required (`?path=/story/packages-dropdown-multiselect--required`)
- Error from Validation (`?path=/story/packages-dropdown-multiselect--error-from-validation`)
- MultiSelect continues to work as expected (including keyboard interactions)
- SingleSelect continues to work as expected (including …
> Add validation props to MultiSelect and share logic with SingleSelect

- .changeset/kind-buckets-poke.md
- .changeset/perfect-cameras-protect.md
- __docs__/wonder-blocks-modal/modal-launcher.argtypes.ts
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-modal/src/components/__tests__/modal-backdrop.test.tsx
- packages/wonder-blocks-modal/src/components/__tests__/modal-launcher.test.tsx
- packages/wonder-blocks-modal/src/components/modal-backdrop.tsx
- packages/wonder-blocks-modal/src/components/modal-launcher.tsx
- packages/wonder-blocks-modal/src/components/modal-panel.tsx
- packages/wonder-blocks-modal/src/themes/default.ts
- packages/wonder-blocks-modal/src/util/find-focusable-nodes.ts
Today, the default for a modal is to focus the first focusable element, but we
exclude the top close button. What this often means is that the first button in
the footer area of the modal is focused.
This PR changes the default focus to be the top close button. This is a more
consistent experience as it allows to focus in the first focusable element in
the dialog content area.
Also had to modify the `IconButton` styles to make sure the focus ring in close
button is visible when the focus is applied programmatically.
Note that we could use `node.focus({focusVisible: true})` to make the focus
visible, but this is not supported in all browsers. So, we are using the
`:focus` pseudo-class to style the focus ring in these cases.
Issue: https://khanacademy.atlassian.net/browse/WB-1796
Navigate …
> WB-1796: Change modal default focus to be the Close (X) button

- .changeset/bright-apes-sparkle.md
- __docs__/wonder-blocks-core/exports.use-render-state.mdx
- packages/wonder-blocks-core/src/components/initial-fallback.tsx
- packages/wonder-blocks-core/src/components/render-state-context.ts
- packages/wonder-blocks-core/src/components/render-state-root.tsx
- packages/wonder-blocks-core/src/hooks/__tests__/use-unique-id.test.tsx
- packages/wonder-blocks-core/src/hooks/use-render-state.ts
- packages/wonder-blocks-core/src/hooks/use-unique-id.ts
This addresses an issue where `useRenderState` would return `RenderState.Root` during initial render to components nested inside our `RenderStateRoot` component, when they should only ever see `Initial` or `Standard`.
I suspect this was happening due to hook execution order and render order. React component render functions are executed from the inside out, and I suspect that because of this, the initial call to `useRenderState` is using the default context value, because the root component hasn't rendered it's value yet - a general flaw in hook-based context access.
However, for everything but `RenderStateRoot` and `InitialFallback` components, code doesn't need to know if it's the root render or not. It's an easier API if they just always see `Initial` or `Standard`. This change makes …
> [wb1812.0.fixrenderstate] Make sure RenderState.Root is an internal concept only

- .changeset/thirty-jars-grow.md
- __docs__/wonder-blocks-core/id.stories.tsx
- packages/wonder-blocks-core/src/components/__tests__/id.test.tsx
- packages/wonder-blocks-core/src/components/id.tsx
- packages/wonder-blocks-core/src/index.ts
This adds a simple CaaF (children-as-a-function) component to generate unique IDs as a stand-in for the `useId` hook. This is useful for cases where one needs to generate unique IDs for a component, but cannot use the hook without a larger refactor.
Issue: WB-1812
`yarn test`
`yarn start:storybook` to check for the added docs
> [wb1812.2.idcomponent] Add the Id component

- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- __docs__/wonder-blocks-form/text-area-variants.stories.tsx
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field-variants.stories.tsx
- __docs__/wonder-blocks-form/text-field.stories.tsx
- __docs__/wonder-blocks-search-field/search-field-variants.stories.tsx
- __docs__/wonder-blocks-search-field/search-field.stories.tsx
Use LabeledField in other component stories
Issue: WB-1783
Verify stories for the following components:
- SingleSelect (`?path=/docs/packages-dropdown-singleselect--docs`)
- MultiSelect (`?path=/docs/packages-dropdown-multiselect--docs`)
- TextArea (`?path=/docs/packages-form-textarea--docs`)
- TextArea Variants (`?path=/docs/packages-form-textarea-all-variants--docs`)
- TextField (`?path=/docs/packages-form-textfield--docs`)
- TextField Variants (`?path=/docs/packages-form-textfield-all-variants--docs`)
- SearchField (`?path=/docs/packages-searchfield--docs`)
- SearchField Variants (`?path=/docs/packages-searchfield-all-variants--docs`)
Note: This addresses Storybook a11y issues related to form fields and labels. There are some stories that focus on the form field without the label so …
> Use LabeledField in other component stories

- .changeset/cold-rocks-notice.md
- __docs__/wonder-blocks-form/radio-group.stories.tsx
- packages/wonder-blocks-form/src/components/group-styles.ts
Adds `width: 100%` to `legend` element to allow expanding it to fill the
available space.
Note that this applies to both `RadioGroup` and `CheckboxGroup`.
Navigate to `/?path=/docs/packages-form-radiogroup--docs#custom%20label`.
Verify that the legend element is now full-bleed.
> RadioGroup: Add flexible width to legend element to fill available space

- .changeset/config.json
I recently updated our Changesets config to auto-commit the `.md` file when using `yarn changset` to describe a set of changes. This broke our releases as the default behaviour is that Changesets adds `[skip ci]` to the commit created when running `yarn changesets version`. No CI on that PR/commit, meant that none of our release Github Actions ran!
So this PR fixes the config so that Changesets no longer adds `[skip ci]` to any commits, but still auto-commits them. 
Issue: "none"
Land this PR
Merge `main` into an open Version Packages PR
Land that PR and ensure the release goes out
> Update changesets' auto-commit feature to not suppress CI on commits

- .changeset/ten-pandas-decide.md
- .github/workflows/node-ci-pr.yml
For some reason, merging Version Packages didn't do a squash merge and that meant we got the change
Issue: FEI-6062
> [fei6062.3.releasing] Catch the RELEASING commit issueprotections

- __docs__/wonder-blocks-labeled-field/accessibility.mdx
Documenting the different browser + screen reader behaviours for reference since there are some browser/screen reader inconsistencies!
Issue: WB-1842
- Review new LabeledField Accessibility docs (`?path=/docs/packages-labeledfield-accessibility--docs`)
- Review the LabeledField stories with different screen readers/browsers, especially around errors (would appreciate any feedback around this!)
Safari + VoiceOver
https://github.com/user-attachments/assets/4913f5e6-6af5-42fb-996c-c2bed380b37a 
Chrome + NVDA
https://github.com/user-attachments/assets/230aa0ec-07b7-47e5-bb3e-98e1e65a5908
Firefox + NVDA
https://github.com/user-attachments/assets/1a9a4b9d-7c97-455b-a830-63f9e90a852d
Safari + VoiceOver
https://github.com/user-attachments/assets/37cbf220-52b8-4078-8872-d431379659d5
Chrome + NVDA …
> Add more docs around different browser + screen reader behaviours for LabeledField

- __docs__/wonder-blocks-cell/detail-cell-variants.stories.tsx
- __docs__/wonder-blocks-cell/detail-cell.stories.tsx
Add scenario and variant stories for DetailCell. This will help us confirm styling for different states with visual regression tests.
For now, the color contrast issues haven't been addressed yet. Coordinating with design on what styling updates we want long term (see WB-1797 comments for more details!). Including these stories for now so we can have visual regression tests ready when we address the color issues!
Issue: WB-1797
- Review stories for:
- All Variants (`?path=/docs/packages-cell-detailcell-all-variants--docs`)
- Scenarios (`?path=/story/packages-cell-detailcell--scenarios`)
> DetailCell: Add variant stories

- .changeset/serious-cherries-wonder.md
- packages/wonder-blocks-labeled-field/src/components/__tests__/labeled-field.test.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
Makes sure custom required messages passed into `LabeledField` or the `field` prop are displayed
Issue: WB-1848
Confirm in `?path=/story/packages-labeledfield--required` that the error message shows the custom required message
> LabeledField: Make sure custom required message is shown

- __docs__/wonder-blocks-labeled-field/labeled-field.argtypes.ts
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
The LabeledField accepts a ReactNode for the `label`, `description`, and `errorMessage` props already. This adds a story and documentation for this functionality!
Issue: WB-1785
Review Custom story docs in `?path=/docs/packages-labeledfield--docs#custom`
> LabeledField: Add a story for custom jsx for props

- .changeset/mean-cherries-press.md
- __docs__/wonder-blocks-dropdown/single-select.accessibility.stories.tsx
- packages/wonder-blocks-clickable/src/components/__tests__/clickable-behavior.test.tsx
- packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
- packages/wonder-blocks-core/src/index.ts
- packages/wonder-blocks-core/src/util/keys.ts
- packages/wonder-blocks-dropdown/src/components/__tests__/action-menu.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/combobox.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/dropdown-core.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/select-opener.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
- packages/wonder-blocks-dropdown/src/util/constants.ts
In working on [WB-1799](https://khanacademy.atlassian.net/browse/WB-1799) for SingleSelect, I found a bunch of [disabled tests](https://khanacademy.atlassian.net/browse/FEI-5533) that I started fixing to ensure keyboard interactions work. Fixing these tests required changes to Clickable, which is used in WB Dropdowns.
Issue: https://khanacademy.atlassian.net/browse/FEI-6114
PR highlights:
1. Re-enables some keyboard tests that were disabled with `userEvent@14`
2. Exposes a centralized `keys` object in `wonder-blocks-core` for use in `wonder-blocks-clickable`, `wonder-blocks-dropdown`, and any other modules that need it.
1. Note: userEvent passes the literal key code string back, i.e. `Space` or `space`. I lower-cased the key names to make sure they match in the code. We could use linting …
> FEI-5533: Re-enable select keyboard tests for Dropdown and Clickable

- .changeset/hot-panthers-kneel.md
- __docs__/components/color.tsx
- __docs__/foundations-color.mdx
- packages/wonder-blocks-tokens/src/tokens/semantic-color.ts
Reworked `semanticColor` actions to use a new structure. Every `action` now
includes `default`, `hover` and `press` states, and each state includes
`border`, `background` and `foreground` tokens.
By doing this change, we'll offer a more consistent and predictable styling
direction for our interactive components.
Issue: https://khanacademy.atlassian.net/browse/WB-1849
Navigate to `/?path=/docs/foundations-using-color--docs` and check that the
`Action` section includes all the new tokens and the structure is readable and
makes sense.
> [WB-1849] Rework action semantic color tokens

- .changeset/cold-rivers-travel.md
- .changeset/curly-poems-sin.md
- .changeset/wet-pigs-end.md
- __docs__/wonder-blocks-form/labeled-text-field.argtypes.ts
- __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
- __docs__/wonder-blocks-form/text-area-variants.stories.tsx
- __docs__/wonder-blocks-form/text-area.argtypes.ts
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field-variants.stories.tsx
- __docs__/wonder-blocks-form/text-field.argtypes.ts
- __docs__/wonder-blocks-form/text-field.stories.tsx
- __docs__/wonder-blocks-labeled-field/labeled-field.argtypes.ts
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- __docs__/wonder-blocks-search-field/search-field-variants.stories.tsx
- __docs__/wonder-blocks-search-field/search-field.argtypes.ts
- __docs__/wonder-blocks-search-field/search-field.stories.tsx
- packages/wonder-blocks-form/src/components/field-heading.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
Following up on #2430.
This PR removes the `light` variant from the remaining form fields:
- `LabeledTextField`
- `TextField`
- `TextArea`
- `LabeledField`
- `SearchField`
This is based on the discussion with the design team where we decided to
remove the light prop from Wonder Blocks due to its low usage and to prepare
for the upcoming design changes.
Issue: WB-1851
Verify that the light prop is removed from the components mentioned in the summary.
> [WB-1851.2] Form: Remove light prop on remaining form fields

- .changeset/rude-mice-serve.md
- packages/wonder-blocks-popover/src/components/__tests__/focus-manager.test.tsx
- packages/wonder-blocks-popover/src/components/focus-manager.tsx
`focus-manager.tsx` is overriding tabindex settings on all of its children. Anything that needs to implement roving focus and restrict tabbing, like a `radiogroup`, is not possible since tabindex is always reset to 0 when focus is inside of the popover.
This fixes that issue by allowing the original tabindex to remain when internal focus is not disabled.
> Fix bug in popover child tab indices

- .changeset/ninety-radios-reflect.md
- .changeset/spicy-grapes-invite.md
- __docs__/wonder-blocks-form/text-area-variants.stories.tsx
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field.stories.tsx
- __docs__/wonder-blocks-search-field/search-field-variants.stories.tsx
- packages/wonder-blocks-form/src/components/field-heading.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-tokens/src/tokens/semantic-color.ts
- Form: Migrated `color` instances to use `semanticColor` internally in
TextField and TextArea.
- Tokens: Added `border.focus` semantic color token to use for the focus outline
Issue: WB-1814
Navigate to the Storybook for `TextField` and `TextArea` components and verify
that the colors are looking as expected.
- /?path=/docs/packages-form-textarea--docs
- /?path=/docs/packages-form-textfield--docs
> [WB-1814.2] Refactor TextField and TextArea to use semantic colors

- .storybook/main.ts
- package.json
- yarn.lock
After the Storybook v8 upgrade, we lost the ability to use GFM in MDX files.
This PR adds the `remark-gfm` plugin to the MDX loader to re-enable GFM support.
For more context, GFM (GitHub Flavored Markdown) is a superset of the original
Markdown specification that adds additional features like tables, task lists,
and strikethrough text.
https://storybook.js.org/docs/writing-docs/mdx#markdown-tables-arent-rendering-correctly
Issue: WB-XXXX
Navigate to any docs page that renders markdown tables and verify that they are
rendered correctly.
/?path=/docs/packages-clickable-clickable-accessibility--docs
BEFORE | AFTER
> [🔥AUDIT🔥] Storybook: Add remark-gfm plugin to add GFM MDX support

- .changeset/gorgeous-adults-lay.md
- __docs__/wonder-blocks-accordion/accordion.stories.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section.tsx
- packages/wonder-blocks-banner/src/components/banner.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
Next step is to refactor the `Accordion`, `Banner`, and `BirthdayPicker`
components to use semantic colors.
1. #2439
2. #2440
3. #2441
4. Accordion, Banner, BirthdayPicker (current PR)
5. IconButton
6. Clickable, Link
7. Modal
8. Popover, Tooltip
9. Pill, Toolbar
Issue: WB-1814
Verify that the Chromatic snapshots are unchanged.
> [WB-1814.4] Refactor Accordion, Banner, BirthdayPicker to use semantic colors

- .changeset/mighty-mangos-hammer.md
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
Updating Birthday Picker to use aria-labels for accessible names. The label placeholders were not applied in this way after WB Dropdowns were changed to use `role="combobox"`.
Issue: https://khanacademy.atlassian.net/browse/WB-1872
> [birthday-picker-combobox] Add labels to birthday picker

- .changeset/cool-months-travel.md
- __docs__/wonder-blocks-timing/use-interval.stories.tsx
- __docs__/wonder-blocks-timing/use-timeout.mdx
- __docs__/wonder-blocks-timing/use-timeout.stories.tsx
- packages/wonder-blocks-timing/src/hooks/__tests__/use-interval.test.ts
- packages/wonder-blocks-timing/src/hooks/__tests__/use-timeout.test.ts
- packages/wonder-blocks-timing/src/hooks/use-interval.ts
- packages/wonder-blocks-timing/src/hooks/use-timeout.ts
This fixes a bug I found in the API returned by the `useTimeout` and `useInterval` hooks. The `clear` function returned by these hooks was not properly honouring the clear policy explicitly passed to the hook options. This PR fixes that issue.
`yarn test`
`yarn start:storybook` and visit the `useTimeout` and `useInterval` stories. Go to the OnDemandAndResolveOnClear story and see that clicking the Clear button will invoke the corresponding action as it should - this was not the case, previously.
> [timeouthooks.bugfix] Fix clear function on useTimeout and useInterval

- .changeset/hungry-papayas-grin.md
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
[dropdown-refresh-fix] Restore type=button to prevent refreshes
Issue: https://khanacademy.atlassian.net/browse/WB-1875
- Run unit tests - removing `type="button"` in `select-opener.tsx` will cause the new tests in this PR to fail.
- Integrate in webapp to fix test failures there: https://github.com/Khan/webapp/pull/28147
> [dropdown-refresh-fix] Re-exposes type=button on dropdown openers to prevent form submits and page refreshes.

- .changeset/mighty-goats-look.md
- __docs__/wonder-blocks-link/link-variants.stories.tsx
- __docs__/wonder-blocks-link/link.stories.tsx
- packages/wonder-blocks-link/src/components/link-core.tsx
Next step is to refactor the `Link` component to use semantic colors.
Besides the migration, this PR also includes the following changes:
- Reworked the theme structure to make it closer to the semanticColor structure.
- Updated stories to use the new semantic colors.
1. #2439
2. #2440
3. #2441
4. #2446
5. #2449
6. Link (current PR)
7. Modal
8. Popover, Tooltip
9. Pill
10. Clickable, Toolbar
Issue: WB-1814
Verify that the Chromatic snapshots are unchanged.
URL: `/?path=/story/packages-link-link-all-variants--default`
> [WB-1814.6] Refactor Link to use semantic colors

- .changeset/friendly-weeks-drum.md
- .changeset/shaggy-windows-rescue.md
- __docs__/wonder-blocks-clickable/accessibility.stories.tsx
- __docs__/wonder-blocks-clickable/clickable-behavior.stories.tsx
- __docs__/wonder-blocks-clickable/clickable.stories.tsx
- __docs__/wonder-blocks-pill/pill-variants.stories.tsx
- __docs__/wonder-blocks-pill/pill.stories.tsx
- packages/wonder-blocks-clickable/src/components/clickable.tsx
- packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
- Migrate Clickable and Pill to use semantic colors
- Add `All Variants` story to Pill
1. #2439
2. #2440
3. #2441
4. #2446
5. #2449
6. #2464
7. #2468
8. #2470
9. Clickable, Pill (current PR)
10. Dropdown
Issue: WB-1814
Navigate to the `Clickable` and `Pill` stories in Storybook and verify that the
colors are correct.
> [WB-1814.9] Refactor Clickable and Pill to use semantic colors

- .changeset/new-donuts-melt.md
- .changeset/witty-wolves-fry.md
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- __docs__/wonder-blocks-form/_overview_.mdx
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field.stories.tsx
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- __docs__/wonder-blocks-search-field/search-field.stories.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
- packages/wonder-blocks-form/src/components/labeled-text-field.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-search-field/src/components/search-field.tsx
- Update component docs for TextField, TextArea, SearchField, SingleSelect and MultiSelect with guidelines for labelling, including using LabeledField. These suggestions will be shown with Intellisense
- Add stories for these fields to show it being used with LabeledField
- Add the `@deprecated` tag for the LabeledTextField component. The component docs for it were also updated to suggest using LabeledField + TextField instead
- Updated LabeledField form example to use form element with onSubmit prop. Also added docs for form guidelines around this behaviour. This shows how to avoid using event handlers on non-interactive elements (form elements)
Issue: FEI-6161
- Review LabeledField section in docs for:
- TextField (`?path=/docs/packages-form-textfield--docs#with%20labeled%20field`)
- …
> [FEI-6161] Update docs and examples to suggest LabeledField

- .changeset/rude-bobcats-tap.md
- __docs__/wonder-blocks-link/link-variants.stories.tsx
- __docs__/wonder-blocks-link/link.argtypes.tsx
- __docs__/wonder-blocks-link/link.stories.tsx
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-link/src/components/link.tsx
Removed the `visitable` prop as it is not used in `webapp` (only 1 call site).
Also removed as per design recommendation for privacy purposes.
Confluence: https://khanacademy.atlassian.net/wiki/spaces/WB/pages/3769925723/Token+usage+in+Wonder+Blocks+components?focusedCommentId=3782017071
Issue: WB-1890
Verify that the `Visitable` example in the `Link` storybook is no longer available.
> [WB-1890] Link: Remove `visitable` prop

- .changeset/smooth-kiwis-reflect.md
- packages/wonder-blocks-button/src/components/button-core.tsx
- packages/wonder-blocks-button/src/themes/default.ts
This PR aligns with the new Design aproach in Figma, were we want to define
separate styles for focus and hover states. From now on, the focus state will be
a global style, and the hover state will be a local style (replicating what we
currently have).
Figma: https://www.figma.com/design/VbVu3h2BpBhH80niq101MHHE/%F0%9F%92%A0-Main-Components?node-id=19724-1290&t=7yCkqQqjqnJeqCVc-4
Issue: WB-1844
Navigate to the Button docs and check the button styles for hover and focus
states look as expected.
- hover: the button should have a different outline color based on the color
(destructive vs default).
- focus: the button should always have a blue outline (destructive, default,
disabled).
> [WB-1844] Button: Create separate styles for hover and focus

- .changeset/chilled-otters-hang.md
- .changeset/funny-rocks-smoke.md
- __docs__/components/gallery/component-tile.tsx
- __docs__/foundations-color.mdx
- __docs__/wonder-blocks-clickable/accessibility.stories.tsx
- __docs__/wonder-blocks-clickable/clickable-behavior.stories.tsx
- __docs__/wonder-blocks-clickable/clickable.stories.tsx
- __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-button/src/components/button-core.tsx
- packages/wonder-blocks-button/src/themes/default.ts
- packages/wonder-blocks-clickable/src/components/clickable.tsx
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
- packages/wonder-blocks-dropdown/src/components/combobox-multiple-selection.tsx
- packages/wonder-blocks-dropdown/src/components/combobox.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
- packages/wonder-blocks-form/src/components/checkbox-core.tsx
- packages/wonder-blocks-form/src/components/radio-core.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
- packages/wonder-blocks-form/src/components/text-field.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/themes/default.ts
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-modal/src/themes/default.ts
- packages/wonder-blocks-pill/src/components/pill.tsx
- packages/wonder-blocks-switch/src/themes/default.ts
- packages/wonder-blocks-tokens/src/tokens/semantic-color.ts
- Tokens: Renamed `border.focus` to `focus.outer` and added a new `focus.inner` token.
- Switch all components to use a new `focus.outer` semanticColor token.
- Consolidated all the interactive elements to use the same global semantic focus token. This means that `error` and `disabled` states now use the blue outline when focused.
Issue: WB-1856
Verify that all components have the correct focus indicator color.
> [WB-1856] Focus: Define general pattern for focus indicators in all components

- .changeset/gorgeous-wolves-vanish.md
- .changeset/silent-jobs-itch.md
- __docs__/foundations-color.mdx
- __docs__/wonder-blocks-clickable/accessibility.stories.tsx
- __docs__/wonder-blocks-clickable/clickable-behavior.stories.tsx
- __docs__/wonder-blocks-clickable/clickable.stories.tsx
- packages/wonder-blocks-accordion/src/components/accordion-section-header.tsx
- packages/wonder-blocks-button/src/components/button-core.tsx
- packages/wonder-blocks-button/src/themes/default.ts
- packages/wonder-blocks-button/src/themes/khanmigo.ts
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
- packages/wonder-blocks-dropdown/src/components/action-menu-opener-core.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
- packages/wonder-blocks-form/src/components/checkbox-core.tsx
- packages/wonder-blocks-form/src/components/radio-core.tsx
- packages/wonder-blocks-icon-button/src/themes/default.ts
- packages/wonder-blocks-icon-button/src/themes/khanmigo.ts
- packages/wonder-blocks-link/src/components/link-core.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
- packages/wonder-blocks-switch/src/themes/default.ts
- packages/wonder-blocks-tokens/src/tokens/semantic-color.ts
This is so we can have a more consistent naming convention for our action tokens
(also defined in Figma). This change is backwards compatible, as we are just
renaming the tokens.
Issue: "none"
Navigate to the `foundations > Using color` section in the docs and verify that
the action tokens are now named `primary` and `secondary` instead of `filled`
and `outlined`.
> [🔥AUDIT🔥] Tokens: Rename action tokens: `filled` -> `primary`, `outlined` -> `secondary`.

- .changeset/unlucky-cups-notice.md
- __docs__/wonder-blocks-birthday-picker/birthday-picker.stories.tsx
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
BirthdayPicker currently use the first day of the month for the date if `monthYearOnly` prop is set to `true`. But for most use-cases developers want to use the last day of the month so that a user who is still 17, for example, is not considered 18, if their birthday is anything after the 1st of the month.
This update modifies the behavior of the component to pass the last day of the month to `onChange` if `monthYearOnly` is set to `true`.
Issue: PG-5959
- Modified unit tests to prove last day of month is returned when the prop is set
> Update monthYearOnly to use last day of month

- .changeset/good-ladybugs-add.md
- packages/wonder-blocks-testing-core/src/harness/adapters/__tests__/__snapshots__/router.test.tsx.snap
- packages/wonder-blocks-testing-core/src/harness/adapters/router.tsx
This update is intended to make the error case when using path matching be more informative, and less confusing. The intention is to give a clearer signal to the developer about why things didn't work as they expected.
Made this a minor update because:
- Though it could potentially be considered a breaking change, it is only changing the error message thrown in the fail condition, which folks shouldn't be relying on anyway.
- It's a bit more than a patch fix, imho.
Issue: WB-XXXX
`pnpm jest packages/wonder-blocks-testing-core`
> [routeradapterupdate] Rework the catch all path error

- .changeset/little-ways-rush.md
- .changeset/unlucky-cups-notice.md
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
Reverts this PR: #2486
The reason for reverting is to keep the current behavior of the BirthdayPicker
component, which is to default to the first day of the month when no day is
selected. This is to release other WB packages separately, and let this change
be released separately.
Issue: "none"
N/A
> Revert recent BirthdayPicker picker changes

- .changeset/sharp-pens-pull.md
- .storybook/preview.tsx
- __docs__/wonder-blocks-tokens/__overview__.mdx
- __docs__/wonder-blocks-tokens/tokens-sizing.mdx
- packages/wonder-blocks-tokens/src/index.ts
- packages/wonder-blocks-tokens/src/tokens/sizing.ts
- packages/wonder-blocks-tokens/src/tokens/spacing.ts
- static/sb-styles/preview.css
- static/sb-styles/vars.css
Add sizing primitive tokens to support the new tokens with rem units that will
be used by the thunderblocks/classroom theme.
This is done to offer a more flexible way to define sizes in the components
that use these tokens by setting the size in rem units.
Also modified the Storybook styles to use 50%/8px as the base font size to
better match the rem units.
The tokens were defined here: https://khanacademy.atlassian.net/wiki/spaces/WB/pages/3683483678/REMs
Issue: https://khanacademy.atlassian.net/browse/WB-1887
Navigate to the docs and see that the new sizing tokens are available.
/?path=/docs/packages-tokens-sizing--docs
Also verify that the font sizes in the storybook are preserved.
> [WB-1887] Add new sizing tokens for ThunderBlocks

- .changeset/unlucky-ladybugs-talk.md
- packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx
- packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
BirthdayPicker currently use the first day of the month for the date if monthYearOnly prop is set to true. But for most use-cases developers want to use the last day of the month so that a user who is still 17, for example, is not considered 18, if their birthday is anything after the 1st of the month.
This update modifies the behavior of the component to pass the last day of the month to onChange if monthYearOnly is set to true.
Issue: PG-5959
- Modified unit tests to prove last day of month is returned when the prop is set
> [dmcalpin/birthday-picker-update] Update monthYearOnly to use last day of month

- .changeset/new-seas-sin.md
- packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
Use semantic tokens for cell-core.
Issue: WB-1797
- Review use of semantic tokens in code to make sure the intent makes sense.
- Review stories + Chromatic diff to make sure visual updates are intended
> Use semantic tokens for CellCore

- .changeset/breezy-pandas-knock.md
- __docs__/wonder-blocks-dropdown/action-item.stories.tsx
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
Addressing the styling issue where ActionItem contents can get cropped with the new Cell changes (found in https://github.com/Khan/webapp/pull/29021#pullrequestreview-2675406111). This was happening because we set [`overflow: hidden` now in CellCore](https://github.com/Khan/wonder-blocks/pull/2435/files#diff-0b4c2beea72229dd5e2a29d5053ba87703ec2c51882604d29f36995815a299d5R248-R250) to prevent the left bar indicator from overflowing when the border radius is set on a cell. 
Remove explicitly setting the height of action items so the contents don't overflow. We can inspect the current implementation and see the cell contents are overflowing the inner wrapper container
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/89410914-1805-43e0-a0d3-c626a427ab70) …
> WB-1797 Fix ActionItem height

- .changeset/gorgeous-beans-rescue.md
- .changeset/selfish-goats-protect.md
- __docs__/wonder-blocks-labeled-field/labeled-field.argtypes.ts
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- packages/wonder-blocks-labeled-field/src/components/__tests__/labeled-field.test.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
- Add `styles` prop to support custom stying for the label, description, and error elements
- Use CSS padding instead of `<Strut>` for spacing
- Migrated to `sizing` tokens instead of `spacing`
Issue: WB-1900
- Review new Custom Styles story (`?path=/story/packages-labeledfield--custom-styles`)
- Existing styling should not be changed (no visual changes for existing stories should be detected in Chromatic, especially for `?path=/story/packages-labeledfield--scenarios`)
> Add `styles` prop to `LabeledField` and switch to sizing tokens

- .changeset/hot-days-cross.md
- __docs__/wonder-blocks-icon-button/icon-button-variants.stories.tsx
- __docs__/wonder-blocks-icon-button/icon-button.argtypes.ts
- __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
We are trying to get more alignment with design, and part of that is that icon
buttons will use an `actionType` prop, which supports `progressive` and
`destructive`.
This PR includes the following API changes:
- `color` => `actionType`.
- `color=default` => `actionType=progressive`.
NOTE: `progressive` is now the default value.
Issue: https://khanacademy.atlassian.net/browse/WB-1871
Navigate to the IconButton docs and verify that the prop is now `actionType`
instead of `color`.
/?path=/docs/packages-iconbutton--docs#actiontype
> [WB-1871] IconButton: Rename `color` prop to `actionType`

- .changeset/pretty-candles-pretend.md
- __docs__/wonder-blocks-popover/popover-content-core.stories.tsx
- __docs__/wonder-blocks-popover/popover-content.argtypes.tsx
- __docs__/wonder-blocks-popover/popover-content.stories.tsx
- __docs__/wonder-blocks-popover/popover.argtypes.tsx
- __docs__/wonder-blocks-popover/popover.stories.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover-content.typestest.tsx
- packages/wonder-blocks-popover/src/components/__tests__/popover-dialog.test.tsx
- packages/wonder-blocks-popover/src/components/popover-content-core.tsx
- packages/wonder-blocks-popover/src/components/popover-content.tsx
- packages/wonder-blocks-popover/src/components/popover-dialog.tsx
Removed the `emphasized` props from `PopoverContent` and `color` prop from
`PopoverContentCore` as these are not currently used and no longer recommended.
Issue: https://khanacademy.atlassian.net/browse/WB-1911
Navigate to the Popover docs and verify that the `emphasized` and `dark` stories
are no longer present.
`/?path=/docs/packages-popover-popovercontentcore--docs`
`/?path=/docs/packages-popover-popovercontent--docs`
> [WB-1911] Popover: Remove "emphasized" and "color" variants

- __docs__/wonder-blocks-tabs/navigation-tab-item-variants.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tabs-variants.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
Minor updates to the NavigationTabs stories:
- Circling back to wrap NavigationTabItem with a `<ul>` element instead of disabling expected a11y rules ([discussed in the a11y fixes PR](https://github.com/Khan/wonder-blocks/pull/2509#discussion_r2008067305)). It was expected because the NavigationTabs component provides the `<ul>` element for it
- Use the logo with text image instead for header example (the logo asset can't be found in the deployed version, but the logo with text image should be available since we use that for the logo in Storybook)
- Update comments
Issue: WB-XXXX
- Confirm the NavigationTabItem stories don't have a11y warnings using the Storybook a11y add on
> NavigationTabs stories updates

- .changeset/slow-cycles-visit.md
- packages/wonder-blocks-icon-button/package.json
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/themes/default.ts
- packages/wonder-blocks-icon-button/tsconfig-build.json
- packages/wonder-blocks-modal/package.json
- packages/wonder-blocks-modal/src/components/modal-panel.tsx
- packages/wonder-blocks-modal/src/themes/default.ts
- packages/wonder-blocks-modal/tsconfig-build.json
- pnpm-lock.yaml
In #2524, we updated the IconButton focus state to use a box-shadow instead of
an outline. This change was made to improve accessibility and provide a more
modern look to the component.
Turns out that the box-shadow is not 100% accessible for all users, as it
doesn't work well on Windows High Contrast mode. This PR modifies the focus
style to use the `focus` style from `wonder-blocks-styles`, which is a
combination of a box-shadow and an outline. This should provide a more
consistent experience across different platforms and improve accessibility.
Issue: WB-1902
Navigate to the IconButton component in Storybook and verify that the focus
state looks correct.
`/?path=/story/packages-iconbutton-all-variants--focus&globals=viewport:desktop;pseudo.focusVisible:!true`
Also verify that the close …
> [WB-1902.2] IconButton: Update IconButton focus state to use box-shadow + outline for better a11y

- .changeset/beige-fireants-divide.md
- .changeset/long-cougars-enjoy.md
- .changeset/twenty-shoes-sleep.md
- __docs__/wonder-blocks-icon-button/icon-button-variants.stories.tsx
- __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
- __docs__/wonder-blocks-styles/action-styles-variants.stories.tsx
- __docs__/wonder-blocks-styles/action-styles.stories.tsx
- __docs__/wonder-blocks-toolbar/toolbar.argtypes.tsx
- packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
- packages/wonder-blocks-icon-button/src/themes/default.ts
- packages/wonder-blocks-icon-button/src/themes/khanmigo.ts
- packages/wonder-blocks-modal/src/components/close-button.tsx
- packages/wonder-blocks-modal/src/components/modal-panel.tsx
- packages/wonder-blocks-popover/package.json
- packages/wonder-blocks-popover/src/components/close-button.tsx
- packages/wonder-blocks-popover/src/components/popover-content-core.tsx
- packages/wonder-blocks-popover/tsconfig-build.json
- packages/wonder-blocks-styles/src/index.ts
- packages/wonder-blocks-styles/src/styles/action-styles.ts
- pnpm-lock.yaml
This PR removes the `light` variant from the IconButton component and replaces
it with a new `actionStyles.inverse` style. This change is part of a larger
effort to standardize the styling of interactive elements across WB. The `light`
variant was previously used in the `Popover` and `Moda`l components. The new
`actionStyles.inverse` style provides a way to apply almost the same styling as
the `light` variant, but allow us to avoid having to maintain a separate `light`
variant in the IconButton component (which won't be supported in Thunder
Blocks and new styles).
Key changes:
- Styles: Added a new `actionStyles.inverse` style to apply to interactive
(action) components.
- IconButton: Removed the `light` variant and replaced it with
`actionStyles.inverse`.
- Modal and Popover: Updated …
> [WB-1852.1] IconButton: Remove `light` variant

- .changeset/twelve-pillows-lay.md
- __docs__/wonder-blocks-tabs/tabs.accessibility.mdx
- __docs__/wonder-blocks-tabs/tabs.argtypes.ts
- __docs__/wonder-blocks-tabs/tabs.stories.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tab-panel.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tab.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tablist.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
- packages/wonder-blocks-tabs/src/components/tab-panel.tsx
- packages/wonder-blocks-tabs/src/components/tab.tsx
- packages/wonder-blocks-tabs/src/components/tablist.tsx
- packages/wonder-blocks-tabs/src/components/tabs.tsx
- packages/wonder-blocks-tabs/src/index.ts
Set up the base Tabs component semantics and structure
Issue: WB-1073
- Semantics of the Tabs component follows the [ARIA APG Tabs pattern]( https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) (uses elements with tab, tablist, and tabpanel roles)
- Review Tabs prop and a11y docs
- Set up base component
- Keyboard interactions
- Remaining props
- Styles
> Set up Tabs component

- .changeset/proud-elephants-wave.md
- .changeset/tricky-rice-promise.md
- __docs__/components/all-variants.tsx
- __docs__/components/scenarios-layout.tsx
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tab-item-variants.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tabs-variants.stories.tsx
- __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
- __docs__/wonder-blocks-tokens/tokens-sizing.mdx
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
- packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
- packages/wonder-blocks-tabs/src/components/navigation-tabs.tsx
- packages/wonder-blocks-tokens/src/tokens/sizing.ts
- static/sb-styles/preview.css
- static/sb-styles/vars.css
This change updates the sizing tokens in wonder-blocks-tokens to use Base 10 rather than Base 8. We decided on this change as a team to work around some minimum issues in browsers where JavaScript returned the incorrect font-size on a page.
Issue: WB-1914
1. Reference Base 10 scale in https://khanacademy.atlassian.net/wiki/spaces/WB/pages/3683483678/Sizing
2. Double-check math of values used
3. Ensure there are no lint errors with tokens used in WB
4. To-do: update usage in webapp (FEI-6229)
> [WB-1914] Update wonder-blocks-tokens to use Base 10

- .changeset/breezy-bulldogs-yawn.md
- .changeset/little-laws-flash.md
- .changeset/loud-lamps-deny.md
- __docs__/wonder-blocks-tabs/tabs.accessibility.mdx
- __docs__/wonder-blocks-tabs/tabs.argtypes.ts
- __docs__/wonder-blocks-tabs/tabs.stories.tsx
- packages/wonder-blocks-core/src/util/__tests__/focus.test.tsx
- packages/wonder-blocks-core/src/util/focus.ts
- packages/wonder-blocks-core/src/util/keys.ts
- packages/wonder-blocks-tabs/src/components/__tests__/tab-panel.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tab.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tablist.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
- packages/wonder-blocks-tabs/src/components/tab-panel.tsx
- packages/wonder-blocks-tabs/src/components/tab.tsx
- packages/wonder-blocks-tabs/src/components/tablist.tsx
- packages/wonder-blocks-tabs/src/components/tabs.tsx
Implement the focus management and keyboard interactions from the [ARIA APG Tabs Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)
- Add keyboard support for Tabs (left arrow, right arrow, home, and end keys)
- Add `activationMode` prop to choose between manual and automatic activation (defaults to `manual`)
- Make the tabpanel focusable if there are no focusable elements in it
- Make only the active tab focusable
- Copy focus utilities to core so more components can use them
- Add more key constants for keyboard events
Issue: WB-1909
- Test the keyboard interactions and focus management in the following stories:
- `?path=/story/packages-tabs-tabs-tabs--manual-activation`
- `?path=/story/packages-tabs-tabs-tabs--automatic-activation`
- …
> Tabs: Set up keyboard navigation and activationMode prop

- .changeset/twenty-pans-film.md
- __docs__/wonder-blocks-tabs/tabs.argtypes.ts
- __docs__/wonder-blocks-tabs/tabs.stories.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tab-panel.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tab.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tablist.test.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
- packages/wonder-blocks-tabs/src/components/tab-panel.tsx
- packages/wonder-blocks-tabs/src/components/tab.tsx
- packages/wonder-blocks-tabs/src/components/tablist.tsx
- packages/wonder-blocks-tabs/src/components/tabs.tsx
- packages/wonder-blocks-tabs/src/index.ts
- Implement remaining props (id, testId, aria props for Tab component)
- Support render function for the tab label
- Cache tab panel contents so it is only mounted once a tab is selected. Revisiting a tab panel doesn't cause it to re-mount
Issue: WB-1907
- Props work as expected
- Tab Label Render Function renders properly (`?path=/story/packages-tabs-tabs-tabs--tab-label-render-function`)
- Note: This story shows how the render function can be used for the tab label. WB-1901 is for investigating tabs more with popover/tooltip components and a11y considerations
- Panel Caching story behaves as expected (see docs for this story for more details) (`?path=/story/packages-tabs-tabs-tabs--panel-caching`)
- Set up base component https://github.com/Khan/wonder-blocks/pull/2528
- Keyboard …
> Tabs: Implement props and features

- .changeset/dirty-pens-share.md
- __docs__/components/placeholder.tsx
- __docs__/wonder-blocks-tabs/tab-variants.stories.tsx
- __docs__/wonder-blocks-tabs/tabs-variants.stories.tsx
- __docs__/wonder-blocks-tabs/tabs.accessibility.mdx
- __docs__/wonder-blocks-tabs/tabs.stories.tsx
- packages/wonder-blocks-tabs/src/components/navigation-tabs.tsx
- packages/wonder-blocks-tabs/src/components/tab-panel.tsx
- packages/wonder-blocks-tabs/src/components/tab.tsx
- packages/wonder-blocks-tabs/src/components/tablist.tsx
- packages/wonder-blocks-tabs/src/components/tabs.tsx
- packages/wonder-blocks-tabs/src/hooks/use-tab-indicator.ts
- packages/wonder-blocks-tabs/tsconfig-build.json
- Implement styling for the Tabs component
- Add support for `styles` prop
- Implement the selected tab indicator animation with `animated` prop
- Refactored NavigationTabs tab indicator logic into a hook so it can be shared
Issue: WB-1908
- styles look as expected
- Scenarios (including scrolling behaviour) (`?path=/story/packages-tabs-tabs--scenarios`)
- Tab All Variants (`?path=/story/packages-tabs-tabs-subcomponents-tab-all-variants--default`)
- Tabs All Variants (states + zoom) (`?path=/story/packages-tabs-tabs-tabs-all-variants--default`)
- `animated` prop works as expected (`?path=/story/packages-tabs-tabs--animated`)
- `styles` prop works as expected (`?path=/story/packages-tabs-tabs--custom-styles`)
- NavigationTabs animations continues to work as expected
- Set up base component …
> Tabs: Styling

- .changeset/odd-turkeys-train.md
- packages/wonder-blocks-tokens/package.json
This change updates the `package.json` file in the `wonder-blocks-tokens`
package to ensure that TypeScript types are exported correctly. This allows
consumers of the package to use the types without any issues.
I noticed this issue when trying to use a snapshot release in Webapp. The cause
is that the `package.json`'s `field` setting was modified to support exporting
CSS files, and the change was not including the type definitions for this
package.
Issue: "none"
Verify that checks pass.
In the Snapshot release, verify that the types are correctly exported and can be
used in the site properly.
> [🔥AUDIT🔥] Tokens: Export TS types correctly in package.json so consumers can use them correctly

- .changeset/clever-kids-talk.md
- packages/wonder-blocks-testing-core/src/fixtures/fixtures.basic.stories.tsx
- packages/wonder-blocks-testing-core/src/fixtures/fixtures.defaultwrapper.stories.tsx
- packages/wonder-blocks-testing-core/src/fixtures/fixtures.tsx
- packages/wonder-blocks-testing-core/src/fixtures/types.ts
This marks the fixtures framework as deprecated. The fixtures framework is not
intended to be used for new code, but that is happening in Webapp.
I am hoping that showing the deprecated strikethrough will discourage folks from more new use so we can move towards removing this and not maintaining it anymore.
I do not believe webapp currently lints against deprecated code use, so this should not create any new errors in webapp when it gets updated.
Issue: FEI-5273
`pnpm typecheck`
`pnpm lint`
> Deprecate fixtures framework

- .changeset/fair-ants-hunt.md
- __docs__/wonder-blocks-tabs/tabs.stories.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
- packages/wonder-blocks-tabs/src/components/tabs.tsx
- Add `mountAllPanels` prop to `Tabs`. It defaults to `false`
- When it is false, panels are only mounted the first time it is visited. It stays mounted so it doesn't need to be remounted when it is visited again.
- When it is true, all panels are mounted when the Tabs first render. This is useful for SEO purposes if we want the unvisited tab panels to be crawlable (context: https://github.com/Khan/wonder-blocks/pull/2542#discussion_r2033952892)
Issue: WB-1923
- Confirm the PanelCaching story behaves the same way as before (`[?path=/docs/packages-tabs-tabs--docs](http://localhost:6061/?path=/docs/packages-tabs-tabs--docs#panel%20caching)`)
- Confirm the new MountAllPanels story includes all tab panels in the DOM (even if they aren't visited yet) …
> Tabs: Add `mountAllPanels` prop.

- .changeset/moody-stingrays-jog.md
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-anchor.test.tsx
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip.test.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-anchor.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip.tsx
When I migrated from the old ID generation to the new `useId`-based generation, I broke the `aria-describedby` attribute on the anchor. This caused screen readers to not read out the tooltip content when the anchor was focused.
This change updates things so that the tooltip bubble ID and the ID used in the `aria-describedby` attribute are the same.
I have also added test cases to ensure that we detect regressions.
Issue: WB-1932
`pnpm test`
`pnpm typecheck`
> Make sure that the tooltip bubble is using the same ID as the aria-describedby attribute on the anchor

- .changeset/sweet-pianos-end.md
- __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
- __docs__/wonder-blocks-icon/phosphor-icon.argtypes.ts
- packages/wonder-blocks-dropdown/src/components/__tests__/action-menu.test.tsx
- packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
- packages/wonder-blocks-icon-button/src/components/icon-button.tsx
- Fixes an issue with the IconButton component not triggering `onClick` when the
`Space` key is pressed.
- Adds a story to demonstrate the issue and the fix.
Issue: https://khanacademy.atlassian.net/browse/WB-1937
Navigate to `?path=/story/packages-dropdown-actionmenu--opening-modal&globals=viewport:desktop`
- Open the ActionMenu using the `Space` key.
- Verify that the ActionMenu opens as expected.
- Navigate to the "Open modal" action item by using the arrow keys.
- Press the `Space` key to open the modal.
- Verify that the modal opens as expected.
- Tab through the Modal dialog and verify that the focus is trapped within the modal.
- Press the `Escape` key to close the modal.
> [WB-1937] IconButton not opening with the `Space` key (fix)

- .changeset/late-carpets-jam.md
- __docs__/wonder-blocks-tabs/tabs.stories.tsx
- packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
- packages/wonder-blocks-tabs/src/components/tab.tsx
- packages/wonder-blocks-tabs/src/components/tabs.tsx
We now check if an ancestor element has `dir=rtl` to determine what the left and right arrow keys do within the Tabs component. In RTL mode:
- The right arrow will move the focus to the tab on the right (which is the previous tab)
- The left arrow will move the focus to the tab on the left (which is the next tab)
- The `Home` and `End` keys continue to move the focus to the first and last tabs
Issue: WB-1933
Confirm that the keyboard behaviour in RTL and LTR work as expected (`?path=/story/packages-tabs-tabs--right-to-left`)
> Tabs: Fix keyboard navigation for right-to-left

- .changeset/gentle-games-study.md
- __docs__/wonder-blocks-dropdown/action-item.argtypes.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/action-item.test.tsx
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
Adds "active" prop to ActionItem so that the underlying link or button can get an `aria-current` value
> Add "active" prop to ActionItem

- .changeset/mighty-chairs-roll.md
- packages/wonder-blocks-banner/src/components/banner.tsx
- packages/wonder-blocks-banner/src/index.ts
Typescript doesn't seem to infer action types correctly when passing a memoized array to the Banner component.
Exporting the ActionTrigger type should allow us to properly define the type.
> Export ActionTrigger type for Banner

- .changeset/early-worms-relate.md
- __docs__/wonder-blocks-badge/_overview_.mdx
- __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-badge/badge.stories.tsx
- __docs__/wonder-blocks-badge/status-badge.stories.tsx
- packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
- packages/wonder-blocks-badge/src/components/__tests__/status-badge.test.tsx
- packages/wonder-blocks-badge/src/components/status-badge.tsx
- packages/wonder-blocks-badge/src/index.ts
- Adds `StatusBadge` component with `kind` prop. Supports `info`, `success`, `warning`, and `critical` kinds
Issue: WB-1944
- Review stories and docs for `StatusBadge` (`?path=/docs/packages-badge-statusbadge--docs`)
- Review Badge package overview docs (`?path=/docs/packages-badge-overview--docs`)
> Add `StatusBadge` component

- .changeset/famous-hotels-fly.md
- build-settings/rollup.config.mjs
- tsconfig-common.json
This PR upgrades the TypeScript `target` to ES2021. The current minimum browser list at Khan Academy is: 
* Chrome v128
* Safari v15.6
* Latest Edge
* Latest Firefox 
All of these browsers fully support ES2021 (verified by looking through the linked features of https://caniuse.com/?search=ES2021). By bumping to ES2021 we give ourselves access to all ES2021 features without risking shipping code that is incompatible with our supported browser list.
This also cleans up the 'external' flag in our Rollup build (it referenced `@babel/preset-env which we no longer use and `core-js` is no longer a dependency of the project, further we don't use core-js because we don't need any polyfills for ES2021 support).
Related: https://github.com/Khan/perseus/pull/2511
Issue: "none"
I ran `pnpm build; pnpm …
> Bump TypeScript target to ES2021

- .changeset/kind-cherries-report.md
- .changeset/pink-pandas-tap.md
- .storybook/preview.tsx
- __docs__/foundations-color.mdx
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
- packages/wonder-blocks-form/src/components/radio-core.tsx
- packages/wonder-blocks-pill/src/components/pill.tsx
- packages/wonder-blocks-switch/src/themes/default.ts
- packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
- Replaced some `action` call sites with `core.background` tokens.
- Added `core.background` and `core.foreground` tokens in `OG` and `TB`.
- Updated `press` action states to use `core.subtle` (`fadedBlue8`) instead of `fadedBlue`.
1. #2613
**2. Add `core.background` and `core.foreground` semantic color tokens (CURRENT)**
Issue: WB-1941
Verify that the Chromatic snapshots look as expected.
Note that `Button`, `IconButton`, `Action/OptionItem` and `Checkbox`/`Radio` will change as we changed the press background color.
https://khanacademy.slack.com/archives/C07CA2YR0BZ/p1747931528405019
> [WB-1941.2] Add core.background and core.foreground semantic color tokens

- .changeset/khaki-actors-bow.md
- .changeset/serious-jeans-thank.md
- .changeset/silly-cooks-smash.md
- __docs__/wonder-blocks-badge/_overview_.mdx
- __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-badge/badge.argtypes.ts
- __docs__/wonder-blocks-badge/badge.stories.tsx
- __docs__/wonder-blocks-badge/gem-badge.stories.tsx
- __docs__/wonder-blocks-badge/status-badge.stories.tsx
- __docs__/wonder-blocks-icon/custom-icon-components.stories.tsx
- __docs__/wonder-blocks-icon/icon.stories.tsx
- packages/wonder-blocks-badge/package.json
- packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
- packages/wonder-blocks-badge/src/components/__tests__/gem-badge.test.tsx
- packages/wonder-blocks-badge/src/components/badge.tsx
- packages/wonder-blocks-badge/src/components/gem-badge.tsx
- packages/wonder-blocks-badge/src/components/status-badge.tsx
- packages/wonder-blocks-badge/src/index.ts
- packages/wonder-blocks-badge/src/types.ts
- packages/wonder-blocks-badge/tsconfig-build.json
- packages/wonder-blocks-icon/src/components/__tests__/custom-icon-components.test.tsx
- packages/wonder-blocks-icon/src/components/custom-icon-components/gem-icon.tsx
- packages/wonder-blocks-icon/src/hooks/__tests__/use-svg-attributes.test.ts
- packages/wonder-blocks-icon/src/hooks/use-svg-attributes.ts
- packages/wonder-blocks-icon/src/index.ts
- packages/wonder-blocks-icon/src/types.ts
- pnpm-lock.yaml
- Adds `GemBadge` component. It uses the `Badge` component with a pre-defined style and icon using the new `Icon` component
- Since the icon is pre-defined, it accepts a `showIcon` prop instead of an `icon` prop like the `Badge` and `StatusBadge` components
- Will be updating it to semantic color tokens in an upcoming PR
- Adds `GemIcon` custom icon component. It can be used with the `Icon` component and renders an inline svg so that we can use semantic color tokens for the fill so that the multi-colored svg is themable
GemBadge:
GemIcon:
Issue: WB-1943
- Review docs and components
- Badge Overview (`?path=/docs/packages-badge-overview--docs`) 
- GemBadge (`?path=/docs/packages-badge-gembadge--docs`)
- Custom Icon Components (includes GemIcon) …
> Add GemBadge and GemIcon components

- .changeset/cold-apes-yawn.md
- __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-badge/badge.stories.tsx
- packages/wonder-blocks-badge/package.json
- packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
- packages/wonder-blocks-badge/src/components/badge.tsx
- packages/wonder-blocks-badge/tsconfig-build.json
- pnpm-lock.yaml
- Document and add examples for using Badge with Tooltips. 
- `role` needs to be set on `Badge` in order for the tooltip content to be read out by screen readers (since Tooltip sets aria-describedby on the anchor)
- Sincle the Badge would be interactive when used with a Tooltip, we use the global focus styles 
Issue: WB-1952
`?path=/story/packages-badge-badge--badge-with-tooltip`
- The Badge should be focusable when used with a Tooltip
- The tooltip content should be read out by screen readers when the Badge is focused
- Tested with NVDA+Chrome, NVDA+Firefox, VO+Safari. When the tooltip is open, the tooltip content is read out with the Badge label
- Note: Created WB-1967 for broader tooltip SR improvements so that it works by default with any component without consumers having to set the …
> Supporting Badge with Tooltip

- .changeset/nasty-impalas-sparkle.md
- __docs__/wonder-blocks-icon-button/activity-icon-button-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-icon-button/activity-icon-button.stories.tsx
- packages/wonder-blocks-icon-button/package.json
- packages/wonder-blocks-icon-button/src/components/__tests__/activity-icon-button.test.tsx
- packages/wonder-blocks-icon-button/src/components/__tests__/activity-icon-button.typestest.tsx
- packages/wonder-blocks-icon-button/src/components/__tests__/icon-button-types.test.tsx
- packages/wonder-blocks-icon-button/src/components/activity-icon-button.tsx
- packages/wonder-blocks-icon-button/tsconfig-build.json
- pnpm-lock.yaml
- Adds a `label` prop to `ActivityIconButton` to be able to use visible icon descriptions.
- Modifies the types to expect one of `aria-label` or `label`.
- Adds new docs and snapshots to cover this variant.
Issue: WB-1915
- Verify that the new Label docs look correct: `/?path=/docs/packages-iconbutton-activityiconbutton--docs#with-label`
- Verify that the `label` prop is rendered correctly in the snapshots: `/?path=/story/packages-iconbutton-testing-snapshots-activityiconbutton--state-sheet-visible-label-story&globals=theme:thunderblocks`
- Verify that the Scenarios story renders the `label` prop correctly: `/?path=/story/packages-iconbutton-testing-snapshots-activityiconbutton--scenarios&globals=;theme:thunderblocks`
> [WB-1915.2] ActivityIconbutton: Add `label` prop

- .changeset/lazy-rice-cheat.md
- packages/wonder-blocks-banner/src/components/banner.tsx
- Set up banner tokens structure and define layout, sizing, color values (will set up the thunderblocks theming in the next PR)
- Updated styles
- replace `LabelSmall` with `BodyText`
- use `sizing` tokens instead of `spacing`
- refactor styling for the background color so we can use semantic color tokens instead of also relying on opacity
Issue: WB-1865
- Review Banner stories and snapshots
- The component should look the same in Classic theme. 
- Layout is now using rem values instead of px (since we use `sizing` tokens now)
> Set up banner tokens structure and update styles

- .changeset/cool-parents-grow.md
- .changeset/late-days-join.md
- packages/wonder-blocks-cell/package.json
- packages/wonder-blocks-cell/src/components/__tests__/compact-cell.test.tsx
- packages/wonder-blocks-cell/src/components/__tests__/detail-cell.test.tsx
- packages/wonder-blocks-cell/src/components/compact-cell.tsx
- packages/wonder-blocks-cell/src/components/detail-cell.tsx
- packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
- packages/wonder-blocks-cell/src/components/internal/common.ts
- packages/wonder-blocks-cell/src/theme/default.ts
- packages/wonder-blocks-cell/src/theme/index.ts
- packages/wonder-blocks-cell/src/util/types.ts
- packages/wonder-blocks-cell/tsconfig-build.json
- pnpm-lock.yaml
- Refactors Cell structure by removing Strut in favor of CSS's gap property
- Moves the Cell tokens to a separate `theme` file and converts these component-level tokens to CSS variables (this is required here as the Cell styles differ in TB).
- Change old typography components with new ones (`Heading`, `BodyText`).
Issue: https://khanacademy.atlassian.net/browse/WB-1958
Navigate to the Cell docs and verify that there are no noticeable visual
changes. The Cell should still render correctly with the same spacing and
alignment as before.
- `/?path=/story/packages-cell-testing-snapshots-compactcell--state-sheet-story`
- `/?path=/story/packages-cell-testing-snapshots-detailcell--state-sheet-story`
> [WB-1958.2] Add theming support to Cell

- .changeset/green-grapes-call.md
- __docs__/wonder-blocks-banner/banner.stories.tsx
- packages/wonder-blocks-banner/src/components/banner.tsx
- Allows the `root` element of the `Banner` component to be styled using a `styles` prop
- This supports the use case where consumers may need to apply layout properties to the banner so it works with existing layouts (for example, setting `flex-shrink: 0` on the banner so it doesn't shrink)
- Currently, we only support custom styling for the `root` element. This may change later on if we decide to support the customization of other elements in the component
- Stories:
- stories clean up: remove use of color tokens, spacing tokens, and strut usage
- set up story that needs to have custom styles supported
Issue: WB-1980
- Confirm that the custom styles story renders as expected (banner does not shrink) (`/?path=/docs/packages-banner--docs#with-custom-styles`)
- Review prop docs and Custom …
> Add `styles` prop to `Banner` so that the `root` element can be styled

- .changeset/chatty-bees-explain.md
- __docs__/wonder-blocks-typography/body-text.stories.tsx
- __docs__/wonder-blocks-typography/heading.stories.tsx
- packages/wonder-blocks-typography/src/components/body-text.tsx
- packages/wonder-blocks-typography/src/components/heading.tsx
- packages/wonder-blocks-typography/src/util/styles.ts
The BodyText and Heading components used dynamic styles to match the fontSize, fontWeight, and lineHeight via component props. But the way the styles were inlined meant they couldn't be overridden.
This PR puts all of the style combinations into a styles.ts file but still matches them via props. There are also stories showing the styles being overridden (specifically the lineHeight).
Issue: WB-1978
1. Review stories for style combinations and custom styles
- BodyText: /?path=/docs/packages-typography-bodytext-new--docs&globals=theme:thunderblocks
- Heading: /?path=/docs/packages-typography-heading-new--docs&globals=theme:thunderblocks
> Update styling of BodyText and Heading components to allow overrides

- .changeset/large-avocados-thank.md
- __docs__/wonder-blocks-modal/modal-dialog.stories.tsx
- __docs__/wonder-blocks-modal/modal-footer.stories.tsx
- __docs__/wonder-blocks-modal/modal-header.argtypes.tsx
- __docs__/wonder-blocks-modal/modal-header.stories.tsx
- __docs__/wonder-blocks-modal/modal-panel.argtypes.tsx
- __docs__/wonder-blocks-modal/modal-panel.stories.tsx
- __docs__/wonder-blocks-modal/one-pane-dialog.stories.tsx
- packages/wonder-blocks-modal/src/components/modal-header.tsx
- packages/wonder-blocks-modal/src/components/modal-panel.tsx
- packages/wonder-blocks-modal/src/theme/default.ts
Removes the `light` prop from modal as it is no longer needed.
1. #2676
2. #2677
3. #2678
Issue: https://khanacademy.atlassian.net/browse/WB-1867
Navigate to the Modal stories in Storybook and ensure that the modals render
correctly.
Verify that the "Dark" stories are no longer present in the docs.
> [WB-1867.2] Remove `light` prop from Modal package.

- .changeset/shaggy-trees-drive.md
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
I missed exporting the modal css vars in the last PR. This PR adds that to the
release.
Issue: "none"
N/A
> [🔥AUDIT🔥] Export modal css vars from the tokens package.

- .changeset/dull-experts-deny.md
- .changeset/nice-toys-sparkle.md
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-form/checkbox-accessibility.stories.tsx
- __docs__/wonder-blocks-form/checkbox-group.stories.tsx
- __docs__/wonder-blocks-form/checkbox.stories.tsx
- __docs__/wonder-blocks-form/choice.stories.tsx
- __docs__/wonder-blocks-form/radio-group.stories.tsx
- __docs__/wonder-blocks-form/radio.stories.tsx
- packages/wonder-blocks-dropdown/package.json
- packages/wonder-blocks-form/package.json
- packages/wonder-blocks-form/src/components/__tests__/checkbox.test.tsx
- packages/wonder-blocks-form/src/components/checkbox-core.tsx
- packages/wonder-blocks-form/src/components/checkbox-group.tsx
- packages/wonder-blocks-form/src/components/choice-internal.tsx
- packages/wonder-blocks-form/src/components/radio-core.tsx
- packages/wonder-blocks-form/src/components/radio-group.tsx
- packages/wonder-blocks-form/src/theme/default.ts
- packages/wonder-blocks-form/src/theme/index.ts
- packages/wonder-blocks-form/src/theme/thunderblocks.ts
- packages/wonder-blocks-form/src/util/styles.ts
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
- pnpm-lock.yaml
Adds theming support to Checkbox and Radio, including the Thunderblocks theme.
Notable differences in TB include:
- Increased hover and target click areas (4px)
- 4px border-radius instead of 3px
- Semantic colors: Component/Input/Selected blue
Issue: WB-1972, WB-1974
1. Review Test sheets for Checkbox and Radio
2. Test clicking of padded wrapper around both component types
3. Compare to Figma designs
- TB: https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=2048-52&t=B2xxLXv7GkDySMja-0
- OG: https://www.figma.com/design/VbVu3h2BpBhH80niq101MHHE/%F0%9F%92%A0-Main-Components?node-id=15197-6798&t=zmIZ176DtJ5rmwyU-0
> Add theming to Checkbox/Radio

- .changeset/heavy-dolphins-lie.md
- .changeset/short-spoons-approve.md
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
- packages/wonder-blocks-labeled-field/src/theme/default.ts
- packages/wonder-blocks-labeled-field/src/theme/thunderblocks.ts
We now show the error icon in the `LabeledField` error message in the Thunderblocks theme too.
We were going to move the error icon and add a readonly icon inside the field in TB in PR https://github.com/Khan/wonder-blocks/pull/2689, however, this would require a change in the TextField DOM structure so that we can place icons in the field (we would need to wrap the underlying `input` element). This is a more involved change since this would mean testing and updating many instances of TextField in the other repos, to make sure layouts and custom styles don't break. 
Design has agreed with keeping the error icon with the message! Adding to the LabeledField component is more flexible, and will also be more consistent with the different form fields (for example, we wouldn't also need to add …
> LabeledField: Show the error icon for TB theme

- .changeset/ninety-feet-guess.md
- packages/wonder-blocks-dropdown/src/components/action-item.tsx
- packages/wonder-blocks-dropdown/src/components/option-item.tsx
- packages/wonder-blocks-dropdown/src/components/select-opener.tsx
Updates dropdown option item labels to use div/span instead of p to avoid
nesting issues
Issue: "none"
Verify that the dropdown still works as expected, and that the labels
are rendered correctly without any nesting issues.
> [🔥AUDIT🔥] Dropdown: Fix dropdown labels to use div/span

- .changeset/metal-pans-call.md
- .changeset/popular-bats-fly.md
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
- Updating core background success strong token value to match updated Figma token value for TB. 
- Also updating learning.foreground.progress.complete strong to green 10
Issue: WB-2010
- Confirm green 20 is used for the core background success strong token
- Note: in the docs `?path=/docs/foundations-using-color--docs`, there is a bug with the hex code for the colors. If the color swatch is inspected, it should be using the correct color (`#3C6D4A`)
> Change core background success strong to green 20

- .changeset/neat-news-chew.md
- __docs__/wonder-blocks-badge/_overview_.mdx
- __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-badge/badge.argtypes.ts
- __docs__/wonder-blocks-badge/due-badge.stories.tsx
- packages/wonder-blocks-badge/package.json
- packages/wonder-blocks-badge/src/components/__tests__/badge.typestest.tsx
- packages/wonder-blocks-badge/src/components/__tests__/due-badge.test.tsx
- packages/wonder-blocks-badge/src/components/due-badge.tsx
- pnpm-lock.yaml
- DueBadge: Adds support for a `kind` prop that can be `due` (default) or `overdue`
- The icon is now provided by the component. There is now a `showIcon` and `iconAriaLabel` prop instead of an `icon` prop that supports any icon
Issue: WB-2009
Figma design: https://www.figma.com/design/e9qdyiDUBZ3rDabP9S7ulO/%E2%9A%A1%EF%B8%8F-Handshake?node-id=4033-12008&m=dev
Confirm the styling and docs for the DueBadge with `kind="overdue"`
- `?path=/docs/packages-badge-duebadge--docs`
- `?path=/docs/packages-badge-testing-snapshots--docs`
- `?path=/docs/packages-badge-overview--docs`
> Add `overdue` kind for `DueBadge` and include icons

- .changeset/small-cats-kick.md
- __docs__/foundations-color.mdx
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
There are some shared feedback tokens for Toasts to add to semanticColor. This PR introduces those colors for use in Toast components.
Issue: WB-1986
1, Review foundations-color to see how colors are structured
2. Review naming and structure to ensure it aligns with Figma
> Add shared feedback tokens to semanticColor

- .changeset/fifty-bananas-explode.md
- .changeset/strange-squids-try.md
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
- __docs__/wonder-blocks-form/text-area.stories.tsx
- __docs__/wonder-blocks-form/text-field.stories.tsx
- __docs__/wonder-blocks-labeled-field/accessibility.mdx
- __docs__/wonder-blocks-labeled-field/labeled-field-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-labeled-field/labeled-field.argtypes.ts
- __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- __docs__/wonder-blocks-search-field/search-field.stories.tsx
- packages/wonder-blocks-labeled-field/src/components/__tests__/labeled-field.test.tsx
- packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
- packages/wonder-blocks-labeled-field/src/theme/default.ts
- packages/wonder-blocks-labeled-field/src/theme/thunderblocks.ts
Removing the `required` prop from `LabeledField` in favour of the new upcoming `contextLabel` prop. The asterisk that marks a field as required will be replaced with a context label (either "required" or "optional"). Consumers can pass in the `required` prop to the underlying field component used with the LabeledField
Issue: WB-2017
- Confirm there is no `required` prop on the `LabeledField` anymore
- Confirm the LabeledField docs don't include references to the `required` prop for `LabeledField` (Note: The form field components will still support a `required` prop)
- Confirm the LabeledField Required story continues to work as expected (pressing "Submit" while all the fields are empty shows the custom error message provided to the field) `?path=/story/packages-labeledfield--required`
- …
> LabeledField: Remove `required` prop

- .changeset/flat-rivers-reflect.md
- __docs__/wonder-blocks-modal/modal-launcher.stories.tsx
- packages/wonder-blocks-modal/src/components/__tests__/focus-trap.test.tsx
- packages/wonder-blocks-modal/src/components/focus-trap.tsx
This prevents issues when the last element in a modal is hidden. Without this PR, we would try to focus it when shift+tabbing back from the close button, and focus would exit the trap.
Ideally, we'd use [`checkVisibility`](https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility), but Safari 15.6 doesn't support it per [caniuse](https://caniuse.com/mdn-api_element_checkvisibility).
- Run the new test
- Check out the reverted commit in this PR, which includes a story which can be used for manually testing (I don't think it's worth keeping this story around, but I wanted to see it working firsthand)
> Do not try to focus hidden elements in `FocusTrap`

- .changeset/healthy-crabs-refuse.md
- packages/wonder-blocks-button/src/components/button-core.tsx
The recent button changes in https://github.com/Khan/wonder-blocks/pull/2734/files#diff-ede6855e27a1ecfe88d6f2e68ba1979e36ea896776f7e023078b353df3b84b94L36-L37 would cause tests to fail in `frontend` due to unexpected `console.error` calls.
This was because `hovered` and `focused` props were being included with `restProps`, which is applied to the underlying button element. These aren't valid html attributes so an error was logged.
To fix this, we go back to pulling out the `focused` and `hovered` props from `restProps`. Since they are unused, we disable the unused variable lint rules for these lines
Note: We continue to have `focused` and `hovered` props because `Button` still uses `ClickableBehaviour` and it passes in state information. Long term we want to move away from using …
> ButtonCore: Fix passing in invalid attributes

- .changeset/busy-seals-strive.md
- __docs__/wonder-blocks-button/activity-button.stories.tsx
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/components/button-core.tsx
[WB-2038] Add programmatic focus to Button
Issue: WB-2038
1. Review story for programmatic focus: /?path=/story/packages-button-button--receiving-focus-programmatically&globals=viewport:desktop;
2. Compare to ActivityButton: /?path=/story/packages-button-activitybutton--receiving-focus-programmatically&globals=viewport:desktop;
[WB-2038]: https://khanacademy.atlassian.net/browse/WB-2038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add programmatic focus to Button

- .changeset/thin-candles-nail.md
- __docs__/wonder-blocks-modal/drawer-dialog.argtypes.ts
- __docs__/wonder-blocks-modal/drawer-dialog.stories.tsx
- __docs__/wonder-blocks-modal/drawer-launcher-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-modal/drawer-launcher.stories.tsx
- __docs__/wonder-blocks-modal/flexible-dialog.argtypes.ts
- __docs__/wonder-blocks-modal/flexible-dialog.stories.tsx
- packages/wonder-blocks-modal/src/components/drawer-dialog.tsx
- packages/wonder-blocks-modal/src/components/flexible-dialog.tsx
- packages/wonder-blocks-modal/src/components/flexible-panel.tsx
- packages/wonder-blocks-modal/src/components/modal-content.tsx
The DrawerDialog needs an update to support zeroed-out padding where borders and content go all the way to the edge. There is padding set in the `ModalContent` component, a nested child deep in the structure. In this PR, plumbing is created to allow a `styles.content` object to override the padding in `ModalContent`.
Issue: WB-2079
1. Review stories for DrawerDialog, FlexibleDialog, and Modal Testing snapshot stories
2. Ensure ModalContent has no unexpected layout shifts in OG modals
3. Determine whether media query usage in ModalContent can be deferred until later (WB-2080)
> DrawerDialog: Add support for zeroed out padding

- .changeset/smart-ants-clap.md
- __docs__/wonder-blocks-button/activity-button-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-button/activity-button.stories.tsx
- __docs__/wonder-blocks-button/button-shared.argtypes.ts
- __docs__/wonder-blocks-button/button.stories.tsx
- packages/wonder-blocks-button/src/components/__tests__/activity-button.test.tsx
- packages/wonder-blocks-button/src/components/__tests__/button-with-icon.test.tsx
- packages/wonder-blocks-button/src/components/activity-button.tsx
- packages/wonder-blocks-button/src/components/button-icon.tsx
- packages/wonder-blocks-button/src/util/button.types.ts
Adds support for custom non-Phosphor icons in Button and ActivityButton components. The `startIcon` and `endIcon` props can now accept either a `PhosphorIconAsset` or a `ReactElement`. In the docs, we recommend using the Wonder Blocks Icon component for custom icons.
For context, this implementation is similar to the one in PR: https://github.com/Khan/wonder-blocks/pull/2762 . Various teams have asked about custom icons like Khanmigo or gem icons in WB components. I've created other tickets for supporting custom icons in IconButton and Banner components as well!
Issue: WB-1954
Confirm a custom icon can be used in Button and ActivityButton components:
- `?path=/story/packages-button-button--with-icon`
- `?path=/story/packages-button-activitybutton--with-custom-icons`
> Button and ActivityButton: Support custom icons

- .changeset/wicked-rabbits-buy.md
- __docs__/wonder-blocks-banner/banner-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-banner/banner.stories.tsx
- packages/wonder-blocks-banner/src/components/banner.tsx
Adds support for custom non-Phosphor icons in the Banner component. It can now also accept a `ReactElement` for the `icon` prop. In the docs, we recommend using the Wonder Blocks Icon component for custom icons.
Issue: WB-2081
1. Confirm that the Banner component supports custom icons: `?path=/story/packages-banner--with-custom-icon`
> Banner: Support custom icons

- .changeset/chilly-rockets-know.md
- .changeset/mighty-countries-vanish.md
- .changeset/ninety-poets-rest.md
- packages/wonder-blocks-dropdown/src/theme/default.ts
- packages/wonder-blocks-dropdown/src/theme/thunderblocks.ts
- packages/wonder-blocks-modal/src/theme/thunderblocks.ts
- packages/wonder-blocks-popover/src/components/popover-content-core.tsx
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
- packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
- packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-tail.test.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
- packages/wonder-blocks-tooltip/src/components/tooltip-tail.tsx
- Tokens:
- Updated `core.shadow.transparent` to include `low`, `mid` and `high` tokens. Renames `shadow.chonky.progressive` to `shadow.chonky.instructive`.
- Updated `core.shadow.chonky.progressive` with `*.instructive`
- Dropdown and Modal: Updates boxShadow to use `core.shadow.transparent.{low, high}` instead of the previous `core.shadow.transparent` token.
- Popover and Tooltip: Updates boxShadow to use `core.shadow.transparent.low` instead of a primitive `color` token.
Issue: https://khanacademy.atlassian.net/browse/WB-2059
Navigate to the Popover and Tooltip examples and verify that the box shadow now uses the updated shadow color token.
In OG, the new value should be `offBlack16` instead of `offBlack8`.
> [WB-2059] Sync shadow color tokens with Figma tokens

- .changeset/hungry-carrots-leave.md
- __docs__/wonder-blocks-dropdown/action-menu.argtypes.ts
- __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
- packages/wonder-blocks-dropdown/src/components/action-menu.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
- packages/wonder-blocks-dropdown/src/components/dropdown-popper.tsx
In some niche scenarios, we may want to position an ActionMenu somewhere other than below the opener. To support this, we can update the `alignment` prop to allow any valid popper placement as a value.
- Ensure tests pass
- View storybook and make sure the ActionMenu stories are rendering correctly
> Allow ActionMenu to support any valid popper placement

- .changeset/rare-cheetahs-scream.md
- packages/wonder-blocks-tabs/src/components/__tests__/tab.test.tsx
- packages/wonder-blocks-tabs/src/components/tab.tsx
Set `type=button` in the Tab component to prevent form submission when Tabs are used within a form element
Issue: WB-2089
1. Confirm that tabs have type="button" set `?path=/story/packages-tabs-tabs--default`
> Tabs: Set type on tabs to prevent form submission

- .changeset/spotty-balloons-swim.md
- __docs__/components/text-for-testing.ts
- __docs__/wonder-blocks-form/text-area-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-form/text-area.argtypes.ts
- __docs__/wonder-blocks-form/text-area.stories.tsx
- packages/wonder-blocks-form/src/components/__tests__/text-area.test.tsx
- packages/wonder-blocks-form/src/components/text-area.tsx
Implements the following changes to the TextArea component:
- `autoResize (defaults to false)` (new) - enables the textarea element to grow/shrink based on the content 
- `maxRows` (new) - limits the number of rows shown before becoming scrollable. This prevents the textarea from infinitely expanding
- `resizeType` (deprecated) - we mark this prop as deprecated in favour of the `autoResize` prop. We don't remove this prop yet so that this change isn't a breaking change. It'll be removed in a future version
Context around decisions made for this implementation: 
- Using JS to calculate the needed content height when the content changes or a resize observer is triggered
- Explored using [field-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/field-sizing) for dynamic content sizing. …
> TextArea: Support dynamic content sizing

- .changeset/fluffy-glasses-rest.md
- __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
- packages/wonder-blocks-dropdown/src/components/multi-select.tsx
- packages/wonder-blocks-dropdown/src/components/single-select.tsx
To work around combobox bugs in Safari and VoiceOver, SingleSelect and MultiSelect were augmented with an Announcer integration. In practice, when a default value is set (such as "All Students" in a filter), an announcement is made on page load. The announcement is pretty random and confusing when a user isn't interacting with a dropdown. It also runs the risk of conflicting with other announcements on the page, such as client-side routing announcements or skeleton loader techniques.
In this PR, I add a flag for initial rendering that prevents the initial announcement on page load. There should still be announcements when the dropdown is opened, items filtered, and item(s) selected.
Issue: WB-2067
1. Review "initial render" stories with VoiceOver turned on, listening for no announcement …
> WB-2067: Prevent premature announcements in SingleSelect and MultiSelect

- .changeset/brave-books-attend.md
- packages/wonder-blocks-modal/src/components/flexible-dialog.tsx
Removes a media query breakpoint that was causing positioning to be lost at in-between sizes
Before:
After:
Issue: WB-2105
1. Review FlexibleDialog at various screen widths
2. Ensure dialog is positioned in the middle of the screen
3. Ensure DrawerLauncher / DrawerDialog aren't affected, since they are built on top of FlexibleDialog
> FlexibleDialog: Fix positioning at middle breakpoint size

- .changeset/fifty-bottles-happen.md
- .changeset/happy-trains-swim.md
- __docs__/components/scenarios-layout.tsx
- __docs__/wonder-blocks-cell/compact-cell-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-cell/detail-cell-testing-snapshots.stories.tsx
- __docs__/wonder-blocks-dropdown/single-select.stories.tsx
- packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
- Cell: Updates styles to support RTL.
- Tooling: Adds a `decorator` field to ScenariosLayout.
- Docs: adds RTL stories for Cell and SingleSelect.
Issue: https://khanacademy.atlassian.net/browse/WB-2101
Navigate to the docs and verify that the new RTL stories render correctly.
- `/?path=/story/packages-dropdown-singleselect--right-to-left&globals=backgrounds.value:baseDefault;backgrounds.grid:!undefined;;direction:rtl`
> [WB-2101] Fix left-aligned dropdown components to be right-aligned
