Khan/wonder-blocks

__snapshots__/story-shots.test.js.snap, packages/wonder-blocks-color/index.js, packages/wonder-blocks-color/index.stories.js
Summary:
Related task: https://khanacademy.atlassian.net/browse/CLASS-1340
Mockup: zpl://screen?sid=5a6226d4ba218e7607ff5661&pid=5a622684dd6d876f24a8cb20
Test Plan:
Run `npm run storybook`
Go to http://localhost:9001/?selectedKind=Color&selectedStory=All%20colors&full=0&addons=1&stories=1&panelRight=0&addonPanel=kadira%2Fjsx%2Fpanel
See all new colors
=> Add new colors to match the color spec

__snapshots__/story-shots.test.js.snap, packages/wonder-blocks-color/index.js
Summary:
The color offBlack50 was missing.
TestPlan:
Check colors in packages/wonder-blocks-color/index.js
Run `npm run storybook`
Go to http://localhost:9001/?selectedKind=Color&selectedStory=All%20colors&full=0&addons=1&stories=1&panelRight=0&addonPanel=kadira%2Fjsx%2Fpanel
Check offBlack50
=> Missed one color

.eslintignore, .eslintrc, eslint/README.md, eslint/eslintrc, eslint/eslintrc.browser, eslint/eslintrc.flow, eslint/eslintrc.node, eslint/eslintrc.prettier, eslint/eslintrc.react, eslint/eslintrc.shared, package-lock.json, package.json, packages/wonder-blocks-button/components/button-core.js, packages/wonder-blocks-core/components/text.js, packages/wonder-blocks-grid/components/cell.js, packages/wonder-blocks-grid/components/grid.js, packages/wonder-blocks-modal/components/focus-trap.js, packages/wonder-blocks-modal/components/modal-backdrop.js, packages/wonder-blocks-modal/components/modal-backdrop.test.js, packages/wonder-blocks-modal/components/modal-launcher-portal.js, packages/wonder-blocks-modal/components/modal-launcher-portal.test.js, packages/wonder-blocks-modal/components/modal-launcher.test.js, packages/wonder-blocks-modal/components/standard-modal.js, packages/wonder-blocks-modal/components/two-column-modal.js
I've copied the eslintrc files from khan-linter and added a top level .eslintrc file that inherits from them.  This will allow us to add additional rules such as https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md in the future.  The PR also fixes all existing lint of which there was not very much thankfully.
=> Setup eslint

.eslintignore, packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-button/components/button-core.js, packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-core/components/view.js, packages/wonder-blocks-core/docs.md, packages/wonder-blocks-core/generated-snapshot.test.js, packages/wonder-blocks-core/index.js, packages/wonder-blocks-core/util/add-style.js
This allows us to easily add the same `style` prop to any component we want.
=> create addStyles HOC and use it in button-core.js and view.js

packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-button/components/button-core.js
(Sorry there's more!)
Remove so that we don't define in both `Button` and `ButtonCore`.
If we don't want to remove it, we should update `disable` to `disabled`!
=> [Button v1] Remove DefaultProps from ButtonCore

demo/package-lock.json, packages/wonder-blocks-spacing/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-spacing/components/spring.js, packages/wonder-blocks-spacing/components/strut.js, packages/wonder-blocks-spacing/docs.md, packages/wonder-blocks-spacing/generated-snapshot.test.js, packages/wonder-blocks-spacing/index.js, packages/wonder-blocks-spacing/package.json
These components are useful for creating certain layouts, especially things like toolbars where you have some components on the left and some on the right separated by compressible space in the middle.
=> Add Spring and Strut components

demo/README.md
I should've done this as part of https://github.com/Khan/wonder-blocks/pull/107.
=> Update demo/README.md to use watch:all instead of build:all

packages/wonder-blocks-button/__snapshots__/index.test.js.snap, packages/wonder-blocks-button/index.test.js, packages/wonder-blocks-icon-button/__snapshots__/index.test.js.snap, packages/wonder-blocks-icon-button/index.test.js, packages/wonder-blocks-link/__snapshots__/index.test.js.snap, packages/wonder-blocks-link/index.test.js, packages/wonder-blocks-spacing/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-spacing/docs.md, packages/wonder-blocks-spacing/generated-snapshot.test.js
Not sure how these got through, though!
=> Fix some Flow errors that slipped through.

.vscode/extensions.json
This adds the awesome Jest extension that I've been using.
With this, you'll get inline test results and the tests will auto-run. This has made my testing loop really good.
=> Add jest extension to recommendations

packages/wonder-blocks-dropdown/components/select-box.md, packages/wonder-blocks-dropdown/generated-snapshot.test.js
This fixes the select-box.md so that the snapshots generate correct code.
=> Fix select box docs

packages/wonder-blocks-tooltip/components/tooltip-portal-mounter.js, packages/wonder-blocks-tooltip/components/tooltip-portal-mounter.test.js, packages/wonder-blocks-tooltip/components/tooltip-tail.js
After recent reworking, some of the tests were no longer testing what they used to, and they were far too complicated. This fixes all that and ups the coverage about 20% points.
=> Updating the portal tests

package.json, packages/wonder-blocks-color/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-core/package.json, packages/wonder-blocks-core/util/util.js, packages/wonder-blocks-grid/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-layout/package.json, packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-modal/components/modal-backdrop.test.js, packages/wonder-blocks-typography/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-typography/package.json, test-setup.js, yarn.lock
There are three failing errors that I wasn't able to resolve...yet.  Two of them stem from our use of `findDOMNode` and the third is `Enzyme Internal Error: unknown node with tag 12`.  We'll to disable that test until https://github.com/airbnb/enzyme/issues/1620 is fixed.
=> try upgrading to React 16 to suss out the issues

packages/wonder-blocks-icon/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-icon/docs.md, packages/wonder-blocks-icon/generated-snapshot.test.js
The error was showing up in the dev server. Added a `<tbody>` under the `table` to fix the error.
=> Fix console error about missing tbody element

packages/wonder-blocks-button/__snapshots__/custom-snapshot.test.js.snap, packages/wonder-blocks-button/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-button/components/button.js, packages/wonder-blocks-button/components/button.md, packages/wonder-blocks-button/custom-snapshot.test.js, packages/wonder-blocks-button/generated-snapshot.test.js
The key changes:
- there's more regularity between the main examples (each focuses on a particular prop)
- the best practices section covers issues that people might run into an common solutions as well as best practices
- I also changed the `size` prop to take `"small" | "medium" (default)` instead of `"small" | "default" (default)` so that it would mesh better with our other `size` props.
=> rework Button docs to include a Best Practices section

packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-form/components/choice-internal.js, packages/wonder-blocks-form/package.json
I found some more missing deps.  We'll want to have a lint for this as well as directly including files from other packages before the next round of development begins in earnest.
=> exclude more deps from being packaged

packages/wonder-blocks-form/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-form/components/checkbox-group.js, packages/wonder-blocks-form/components/checkbox-group.md, packages/wonder-blocks-form/components/choice-internal.js, packages/wonder-blocks-form/components/radio-core.js, packages/wonder-blocks-form/components/radio-group.js, packages/wonder-blocks-form/components/radio-group.md, packages/wonder-blocks-form/generated-snapshot.test.js
* Align the checkbox / radio button with the first line of the label (it was being centered with the entire label before)
* Remove leading spacing of 8 for a group when is no group label, description, or error message
* Remove padding of 1 from `legend` element
* Add an example how to use CheckboxGroup in an existing context that has a different style than the spec
=> Fix visual bugs in Choice

package.json, packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-form/package.json, utils/pre-publish-check.js, yarn.lock
Also add a new `dry-run-publish` command so that we can test the publishing process.
Here is what the command is link and the kinds of warnings that you now get:
```
$ npm run dry-run-publish
> wonder-blocks@0.0.1 dry-run-publish /Users/jeresig/khan/wonder-blocks
> yarn run publish --no-npm --no-git
yarn run v1.7.0
$ node utils/pre-publish-check.js && git diff --stat --exit-code HEAD && yarn build:all && lerna publish --no-npm --no-git
@khanacademy/wonder-blocks-dropdown is private and won't be published to NPM.
@khanacademy/wonder-blocks-form is private and won't be published to NPM.
@khanacademy/wonder-blocks-grid is private and won't be published to NPM.
@khanacademy/wonder-blocks-toolbar is private and won't be published to NPM.
@khanacademy/wonder-blocks-tooltip is private and won't …
```
=> Add a pre-publish check to publish.

packages/wonder-blocks-form/package.json, packages/wonder-blocks-toolbar/package.json, packages/wonder-blocks-tooltip/package.json
We want to publish these packages so we need to make them public first!
=> Make form, toolbar, and tooltip packages public.

packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-form/package.json
This was causing problems when we tried to include them in webapp. I'm going to integrate a check for this into the pre-publish-check.js.
=> Ensure that all of the mains point to the right index.js file.

packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-modal/components/one-column-modal.js
=> Fix layout of OneColumnModal. Fixes WB-352.

packages/wonder-blocks-core/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-form/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-layout/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-layout/components/strut.js, packages/wonder-blocks-layout/components/strut.md, packages/wonder-blocks-layout/generated-snapshot.test.js, packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap
=> WB-355: make Strut truly incompressible

packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-dropdown/components/action-item.js, packages/wonder-blocks-dropdown/components/action-menu.js, packages/wonder-blocks-dropdown/components/action-menu.md, packages/wonder-blocks-dropdown/components/dropdown.js, packages/wonder-blocks-dropdown/components/multi-select.js, packages/wonder-blocks-dropdown/components/multi-select.md, packages/wonder-blocks-dropdown/components/option-item.js, packages/wonder-blocks-dropdown/components/select-opener.js, packages/wonder-blocks-dropdown/components/single-select.js, packages/wonder-blocks-dropdown/components/single-select.md, packages/wonder-blocks-dropdown/docs.md, packages/wonder-blocks-dropdown/generated-snapshot.test.js
* Change `dropdownStyle` and `openerStyle` back to `style`
* Size widths correctly
* Remove redundant variables from option-related stuff
=> Extract API change and styling fixes from #268

packages/wonder-blocks-form/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-form/components/checkbox-core.js, packages/wonder-blocks-form/components/checkbox-group.md, packages/wonder-blocks-form/components/checkbox.md, packages/wonder-blocks-form/components/choice-internal.js, packages/wonder-blocks-form/components/choice.js, packages/wonder-blocks-form/components/radio-core.js, packages/wonder-blocks-form/components/radio-group.js, packages/wonder-blocks-form/components/radio-group.md, packages/wonder-blocks-form/components/radio.md, packages/wonder-blocks-form/generated-snapshot.test.js
* Pre-bind callbacks
* Remove unnecessary lists from styles
* Manually fix weird prettier autoformatting
=> Clean up form package

packages/wonder-blocks-icon/components/icon.js
=> WB-367 Add IconAsset type to Icon documentation

packages/wonder-blocks-color/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-color/index.js
=> Update WB teal

README.md
Followed these steps: https://circleci.com/docs/2.0/status-badges/
=> Update the Circle CI Badge

packages/wonder-blocks-tooltip/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-tooltip/components/tooltip.md, packages/wonder-blocks-tooltip/generated-snapshot.test.js
A quick docs update to get the tooltip docs using Wonder Blocks button
=> Use Button in tooltip docs

flow-typed/npm/jest_v23.x.x.js
When I updated us to Jest v23, I didn't update the flow-typed definition. This does that.
=> Update jest flow-typed definition

flow-typed/npm/jest_v23.x.x.js, packages/wonder-blocks-icon/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-icon/components/icon.md, packages/wonder-blocks-icon/components/icon.test.js, packages/wonder-blocks-icon/generated-snapshot.test.js, packages/wonder-blocks-icon/index.test.js, packages/wonder-blocks-icon/util/icon-assets.test.js, packages/wonder-blocks-icon/util/icon-util.test.js
Add some more testing and realign so that the test files map to the things they're testing
=> Increase icon package test coverage

packages/wonder-blocks-link/__snapshots__/custom-snapshot.test.js.snap, packages/wonder-blocks-link/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-link/components/link-core.js, packages/wonder-blocks-link/components/link.js, packages/wonder-blocks-link/components/link.md, packages/wonder-blocks-link/custom-snapshot.test.js, packages/wonder-blocks-link/generated-snapshot.test.js, packages/wonder-blocks-toolbar/__snapshots__/generated-snapshot.test.js.snap
https://khanacademy.atlassian.net/browse/WB-391
In this commit, I add a new prop called `visitable` which will default
to `false`. Since only primary links have a visited state we shouldn't
allow it on other link types.
=> Add `visitable` prop on Link

packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-modal/components/modal-launcher.js, packages/wonder-blocks-modal/components/modal-launcher.md, packages/wonder-blocks-modal/components/modal-launcher.test.js, packages/wonder-blocks-modal/docs.md, packages/wonder-blocks-modal/generated-snapshot.test.js
Reverts Khan/wonder-blocks#326
=> Revert "Fixes WB-449: Allow modals to be launched programmatically"

packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-dropdown/components/action-menu.js, packages/wonder-blocks-dropdown/components/action-menu.md, packages/wonder-blocks-dropdown/generated-snapshot.test.js
This commit adds optional dropdownStyle to ActionMenu like SingleSelect has.
=> Add optional dropdownStyle to ActionMenu for consistency

packages/wonder-blocks-button/components/button.js, packages/wonder-blocks-button/index.js, packages/wonder-blocks-dropdown/components/dropdown.js, packages/wonder-blocks-tooltip/components/tooltip-popper.js
Following up from the last PR, a couple more issues that we need to resolve to get it working in Webapp!
=> Fix a few more Flow issues.

packages/wonder-blocks-modal/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-modal/components/__snapshots__/standard-modal.test.js.snap, packages/wonder-blocks-modal/components/one-column-modal/__snapshots__/one-column.modal.test.js.snap, packages/wonder-blocks-modal/components/one-column-modal/large-one-column-modal.js, packages/wonder-blocks-modal/components/one-column-modal/one-column-modal.js, packages/wonder-blocks-modal/components/one-column-modal/one-column.modal.test.js, packages/wonder-blocks-modal/components/one-column-modal/small-one-column-modal.js, packages/wonder-blocks-modal/components/standard-modal.js, packages/wonder-blocks-modal/components/standard-modal.test.js, packages/wonder-blocks-modal/components/two-column-modal/__snapshots__/two-column-modal.test.js.snap, packages/wonder-blocks-modal/components/two-column-modal/large-two-column-modal.js, packages/wonder-blocks-modal/components/two-column-modal/small-two-column-modal.js, packages/wonder-blocks-modal/components/two-column-modal/two-column-modal.js, packages/wonder-blocks-modal/components/two-column-modal/two-column-modal.test.js, packages/wonder-blocks-modal/docs.md, packages/wonder-blocks-modal/generated-snapshot.test.js
….  This allows users to customize the style of the modal's ModalDialog
=> [feature-modal]: Added style prop to modals

packages/wonder-blocks-grid/package.json
This is ready to go we just haven't made it public and published it to npm.  The publish will happen in a separate commit.
=> make wonder-blocks-grid public

CODEOWNERS
Adding myself as code owner for Wonder Blocks (initially for Modal and Breadcrumbs)
=> Add @jandrade as code owner

.vimrc
Previously this was flat-out incorrect and broken.
=> Update .vimrc to actually work with ALE

packages/wonder-blocks-timing/index.js, packages/wonder-blocks-timing/util/interval.js, packages/wonder-blocks-timing/util/interval.test.js, packages/wonder-blocks-timing/util/timeout.js, packages/wonder-blocks-timing/util/types.js
This adds the internal `Interval` type to the new `wonder-blocks-timing` package as we continue to implement ADR-77.
=> WB-570: Implement Interval class

packages/wonder-blocks-timing/index.js, packages/wonder-blocks-timing/util/animation-frame.js, packages/wonder-blocks-timing/util/animation-frame.test.js, packages/wonder-blocks-timing/util/types.js
More implementation for ADR-77.
=> WEB-571: Added AnimationFrame, IAnimationFrame

packages/wonder-blocks-timing/index.js, packages/wonder-blocks-timing/util/action-scheduler.js, packages/wonder-blocks-timing/util/action-scheduler.test.js, packages/wonder-blocks-timing/util/animation-frame.js, packages/wonder-blocks-timing/util/animation-frame.test.js, packages/wonder-blocks-timing/util/interval.js, packages/wonder-blocks-timing/util/interval.test.js, packages/wonder-blocks-timing/util/timeout.js, packages/wonder-blocks-timing/util/timeout.test.js, packages/wonder-blocks-timing/util/types.js
- Added error cases for the timeout, interval, and animation frame types
- Implemented `ActionScheduler` class that provides the API we'll expose via the `ActionSchedulerComponent` (to be implemented as part of WB-573)
- Added unit tests for functionality
=> [WB-572] ActionScheduler implementation completion

.flowconfig, package.json, packages/wonder-blocks-grid/components/row.test.js, packages/wonder-blocks-timing/util/animation-frame.test.js, packages/wonder-blocks-timing/util/interval.test.js, packages/wonder-blocks-timing/util/timeout.test.js, packages/wonder-blocks-tooltip/components/tooltip-anchor.test.js, yarn.lock
- Add flow-bin 0.100.0
- Update `.flowconfig` to match
- Add flow suppressions now that flow is spotting we're using mocks off things that it doesn't know we have mocks of
=> [tooling] Update to flow 0.100.0

.flowconfig, package.json, packages/wonder-blocks-core/util/util.js, yarn.lock
This is necessary before we upgrade webapp to flow 0.101.0 or this fixed flow error will show up there
=> Update to flow 0.101.0

packages/wonder-blocks-dropdown/components/action-menu.js, packages/wonder-blocks-dropdown/components/dropdown-core.js, packages/wonder-blocks-dropdown/components/dropdown-core.test.js, packages/wonder-blocks-dropdown/components/multi-select.js, packages/wonder-blocks-dropdown/components/single-select.js, packages/wonder-blocks-dropdown/generated-snapshot.test.js, styleguide.config.js
I've refactored the Dropdown component to DropdownCore in order to accommodate the new Dropdown with custom openers.
=> Refactor Dropdown to DropdownCore

packages/wonder-blocks-dropdown/index.js, packages/wonder-blocks-dropdown/index.test.js
just added Dropdown to the export
=> Export Dropdown

packages/wonder-blocks-button/components/button-core.js, packages/wonder-blocks-core/components/clickable-behavior.js, packages/wonder-blocks-core/index.js, packages/wonder-blocks-dropdown/components/action-menu-opener-core.js, packages/wonder-blocks-dropdown/components/dropdown.js, packages/wonder-blocks-icon-button/components/icon-button-core.js, packages/wonder-blocks-link/components/link-core.js
I've implemented a new exported type `ClickableState` which can be used in props.
=> [core:feature] Implement ClickableState type

packages/wonder-blocks-form/__snapshots__/custom-snapshot.test.js.snap, packages/wonder-blocks-form/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-form/components/checkbox-core.js, packages/wonder-blocks-form/components/radio-core.js
Added aria-invalid to Checkboxes and Radio buttons, also removed aria-checked from Checkboxes as per WB-584.
=> WB-409: add aria-invalid, remove aria-checked

packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-dropdown/components/multi-select.js, packages/wonder-blocks-dropdown/components/multi-select.md, packages/wonder-blocks-dropdown/components/multi-select.test.js, packages/wonder-blocks-dropdown/generated-snapshot.test.js
Add ‘implicitAllEnabled’ prop to MultiSelect that only changes the
menu text when there's no item selected.
=> [feature:dropdown] WB-625: New(MultiSelect) - Added ‘implicitAllEnabled’ prop

packages/wonder-blocks-breadcrumbs/components/breadcrumbs-item.js, packages/wonder-blocks-breadcrumbs/components/breadcrumbs.js, packages/wonder-blocks-modal/components/modal-header.js, packages/wonder-blocks-modal/components/one-pane-dialog/one-pane-dialog.js, packages/wonder-blocks-popover/components/popover-dialog.js, packages/wonder-blocks-popover/components/popover.js, packages/wonder-blocks-tooltip/components/tooltip-bubble.js, packages/wonder-blocks-tooltip/components/tooltip-bubble.test.js, packages/wonder-blocks-tooltip/components/tooltip-popper.test.js
I think this is something we might want to promote as a best practice to avoid unnecessary dependencies.
=> Use typeof imports whenever possible

.flowconfig
I ran `yarn flow check --profile` to get the following data about startup times:
- before
- total: 12.7s
- parsing: 6.7s
- after
- total: 6.7s
- parsing: 2.1s
Full timing reports:
**BEFORE**
```
==========================================Init Timings=========================================
WALL TIME            CPU TIME         RUN/READ/SEND/IDLE/DONE/GC m/GC M      SECTION
-----------------------------------------------------------------------------------------------
12.672 (100.0%)      47.415 (100.0%)    59%   0%   0%  10%  18%   4%   5%    <Total>
0.000 (  0.0%)       0.000 (  0.0%)     0%   0%   0%   0%   0%   0%   0%      FetchSavedState
6.746 ( 53.2%)      28.470 ( 60.0%)    59%   0%   0%   3%  22%   5%   7%      Parsing
0.246 (  1.9%)       0.242 (  0.5%)     0%   0%   0%   0%   0% …
```
=> update .flowconfig to parse fewer files

.flowconfig, packages/wonder-blocks-dropdown/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-dropdown/components/dropdown-core.js, packages/wonder-blocks-dropdown/components/dropdown-core.test.js, packages/wonder-blocks-dropdown/components/multi-select.js, packages/wonder-blocks-dropdown/components/multi-select.md, packages/wonder-blocks-dropdown/components/multi-select.test.js, packages/wonder-blocks-dropdown/components/search-text-input.js, packages/wonder-blocks-dropdown/generated-snapshot.test.js, packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-dropdown/util/constants.js
Mockup link: https://www.figma.com/file/4l5Y4zG14xaj2d8wqjCCA8/Admin-Reports-(1.3-Release)?node-id=5234%3A1850&viewport=1160%2C306%2C0.6481390595436096
**Context**
We want to have a search field text input within the MultiSelect
component's dropdown body that allows filtering the option items by the
"label" of the options.
**This PR has the following changes**
In MultiSelect:
- Fix a bug related to the item count in MultiSelect (when the children has `false`, it was counted as an item and led incorrect menu text, selected count) 
- Add `searchText` in state to filter the option items by
- Add `lastSelectedValues` in state to obtain the selectedValues when the dropdown is opened to maintain the order of previously selected items at the top.
- Add an optional `isFilterable` in prop
- If …
=> WB-642: MultiSelect with search filter

packages/wonder-blocks-timing/util/action-scheduler.js, packages/wonder-blocks-timing/util/animation-frame.js, packages/wonder-blocks-timing/util/animation-frame.test.js, packages/wonder-blocks-timing/util/types.js
Fixes https://khanacademy.atlassian.net/browse/WB-809
=> [WB-809] Pass the timestamp through to action in AnimationFrame

.codecov.yml, config/jest/test.config.js
Spotted this issue while working on my feature branch. We don't want coverage for flowtest files.
=> Remove flowtest from coverage results

packages/wonder-blocks-data/components/data.test.js, packages/wonder-blocks-data/components/internal-data.js, packages/wonder-blocks-data/components/internal-data.test.js, packages/wonder-blocks-data/util/request-tracking.js, packages/wonder-blocks-data/util/request-tracking.test.js
For WB-833.
This adds some test gap filling and a couple of related code tweaks.
=> Part 2: Fill some testing gaps

packages/wonder-blocks-data/components/data.js, packages/wonder-blocks-data/components/data.md, packages/wonder-blocks-data/components/data.test.js, packages/wonder-blocks-data/components/intercept-cache.js, packages/wonder-blocks-data/components/intercept-cache.test.js, packages/wonder-blocks-data/components/intercept-data.js, packages/wonder-blocks-data/components/intercept-data.test.js, packages/wonder-blocks-data/components/internal-data.js, packages/wonder-blocks-data/components/internal-data.test.js, packages/wonder-blocks-data/docs.md, packages/wonder-blocks-data/generated-snapshot.test.js, packages/wonder-blocks-data/index.js, packages/wonder-blocks-data/index.test.js, packages/wonder-blocks-data/util/memory-cache.js, packages/wonder-blocks-data/util/memory-cache.test.js, packages/wonder-blocks-data/util/no-cache.js, packages/wonder-blocks-data/util/no-cache.test.js, packages/wonder-blocks-data/util/request-fulfillment.js, packages/wonder-blocks-data/util/request-fulfillment.test.js, packages/wonder-blocks-data/util/request-handler.js, packages/wonder-blocks-data/util/request-handler.md, packages/wonder-blocks-data/util/request-tracking.js, packages/wonder-blocks-data/util/request-tracking.test.js, packages/wonder-blocks-data/util/response-cache.js, packages/wonder-blocks-data/util/response-cache.test.js, packages/wonder-blocks-data/util/types.js, styleguide.config.js
This is a PR for merging the feature. The code has already been reviewed in separate PRs, so no reviews required. :)
=> [WB-833, WB-832] Custom caching and cache purging

packages/wonder-blocks-data/components/data.js, packages/wonder-blocks-data/components/data.md, packages/wonder-blocks-data/index.js, packages/wonder-blocks-data/util/no-cache.js, packages/wonder-blocks-data/util/no-cache.md, packages/wonder-blocks-data/util/request-handler.md
This relates to WB-832 and WB-833.
I forgot to export the `ICache` type and also the docs needed some changes.
=> Fix docs and export ICache type

.flowconfig, package.json, packages/wonder-blocks-clickable/components/clickable.js, packages/wonder-blocks-core/components/view.js, packages/wonder-blocks-data/util/__tests__/memory-cache.test.js, packages/wonder-blocks-data/util/__tests__/no-cache.test.js, packages/wonder-blocks-dropdown/components/action-menu.js, packages/wonder-blocks-form/components/choice.js, yarn.lock
This will help us upgrade flow in webapp.
=> Upgrade to flow 0.115

packages/wonder-blocks-button/__tests__/__snapshots__/custom-snapshot.test.js.snap, packages/wonder-blocks-button/__tests__/custom-snapshot.test.js, packages/wonder-blocks-button/components/button.js, packages/wonder-blocks-icon-button/components/icon-button.js, packages/wonder-blocks-link/__tests__/__snapshots__/custom-snapshot.test.js.snap, packages/wonder-blocks-link/__tests__/custom-snapshot.test.js, packages/wonder-blocks-link/components/link-core.js, packages/wonder-blocks-link/components/link.js
- remove 'caret' since we don't use this design pattern in webapp anymore
- add 'tabIndex' and snapshot tests to make sure it's working
Issue: none
- check the new snapshots to see that 'tabindex' was set correctly
=> Fix Link props

consistency-tests/__tests__/clickables.test.js, packages/wonder-blocks-button/components/button.js, packages/wonder-blocks-clickable/components/clickable.js, packages/wonder-blocks-icon-button/components/icon-button.js, packages/wonder-blocks-link/components/link.js
=> Set target on underlying element

.flowconfig, package.json, packages/wonder-blocks-button/components/__tests__/button.flowtest.js, packages/wonder-blocks-clickable/components/clickable-behavior.js, packages/wonder-blocks-core/util/__tests__/enumerate-scroll-ancestors.test.js, packages/wonder-blocks-core/util/__tests__/get-element-intersection.test.js, packages/wonder-blocks-core/util/enumerate-scroll-ancestors.js, packages/wonder-blocks-link/components/__tests__/link.flowtest.js, packages/wonder-blocks-timing/util/__tests__/animation-frame.test.js, packages/wonder-blocks-timing/util/__tests__/interval.test.js, packages/wonder-blocks-timing/util/__tests__/timeout.test.js, packages/wonder-blocks-tooltip/components/__tests__/tooltip-anchor.test.js, packages/wonder-blocks-tooltip/components/__tests__/tooltip.test.js, shared-unpackaged/__tests__/is-obscured.test.js, shared-unpackaged/__tests__/visibility-modifier.test.js, yarn.lock
=> [FEI-3327].1 Upgrade to Flow 0.127.0

.flowconfig, flow-typed/ka-types.js, flow-typed/npm/jest_v24.x.x.js, flow-typed/storybook.flow.js, package.json, packages/wonder-blocks-button/components/button.stories.js, packages/wonder-blocks-clickable/components/clickable.stories.js, packages/wonder-blocks-data/components/data.js, packages/wonder-blocks-data/index.js, packages/wonder-blocks-data/util/response-cache.js, packages/wonder-blocks-data/util/types.js, packages/wonder-blocks-dropdown/components/action-menu.js, packages/wonder-blocks-dropdown/components/multi-select.js, packages/wonder-blocks-dropdown/components/multi-select.stories.js, packages/wonder-blocks-dropdown/components/single-select.js, packages/wonder-blocks-dropdown/components/single-select.stories.js, packages/wonder-blocks-modal/components/one-pane-dialog.stories.js, yarn.lock
The were a few different points where changes were made, but they
seemed small enough to keep it all bundled into one review.
Issue: FEI-3327
`yarn flow`
`yarn test`
=> [FEI-3327].2 Update to Flow 0.145.0

utils/pre-publish-check.js
In #1099 I moved the source code in each package into 'src', but forgot to update the pre-publish script.  Now the script looks for index.js in the right place.
Issue: none
- After landing this I'll do a publish.
=> Fix pre-publish-check script

packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js, packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.js, packages/wonder-blocks-form/src/components/labeled-text-field.js, packages/wonder-blocks-form/src/components/labeled-text-field.md, packages/wonder-blocks-form/src/components/labeled-text-field.stories.js
Added all props dealing with Validation and Event Handling to `LabeledTextField`.
The following were the props added:
* validation
* onValidation
* onChange
* onKeyDown
* onFocus
* onBlur
Added unit tests to ensure the new props work as expected.
Issue: https://khanacademy.atlassian.net/browse/WB-1068
1. Open Styleguidist or React Storybook (see generated links).
2. View the `LabeledTextField` examples under "Form / LabeledTextField".
3. View at all the new examples that show validation and events in action.
4. View the examples that provide error message on validation errors.
5. Test all examples by pressing "Enter" and notice how the TextField blurs.
---
=> WB-1068 - Add Validation and Event Props to LabeledTextField

package.json, packages/wonder-blocks-data/src/components/__tests__/data.test.js, packages/wonder-blocks-data/src/components/__tests__/internal-data.test.js, packages/wonder-blocks-data/src/components/data.js, packages/wonder-blocks-data/src/util/__tests__/request-tracking.test.js, packages/wonder-blocks-dropdown/src/components/dropdown-core.js, packages/wonder-blocks-layout/src/components/media-layout.js, packages/wonder-blocks-timing/src/components/__tests__/action-scheduler-provider.test.js, packages/wonder-blocks-timing/src/util/__tests__/action-scheduler.test.js, packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-anchor.test.js, shared-unpackaged/__tests__/is-obscured.test.js, yarn.lock
=> Update to Flow 0.154.0

packages/wonder-blocks-form/src/__tests__/__snapshots__/generated-snapshot.test.js.snap, packages/wonder-blocks-form/src/__tests__/generated-snapshot.test.js, packages/wonder-blocks-form/src/components/field-heading.js, packages/wonder-blocks-form/src/components/field-heading.md, styleguide.config.js
Adding the private `FieldHeading` component on Styleguidist's private
internal component section under "Form". This will allow other KA devs
to know that FieldHeading exists.
Issue: https://khanacademy.atlassian.net/browse/WB-1084
2. Check the Styleguidist Netlify preview for the FieldHeading example that was added under "Internal Components" in the "Form" section.
=> WB-1084 - Add FieldHeading on Styleguidist (as an Internal Component)

.github/workflows/node-ci.yml
- Refactored the `node-ci` workflow to include linting and testing.
- Integrated ESLint + Flow + test + coverate into the workflow.
Issue: https://khanacademy.atlassian.net/browse/WB-1097
Verify that the actions pass.
=> WB-1097: Add lint and test Github actions

.github/workflows/node-ci.yml
Adding some Github actions to experiment with file sizes in our WB bundles.
Verify the PR results in the PR!
=> [Experiment] Add filesize actions

.github/workflows/node-ci-push.yml
Fixes some of the changes introduced in #1224
1. Adds `yarn build:all` to the Chromatic step.
2. Reuses the coverage action steps used in the `pr` event (see `node-ci-pr.yml`)/
Merge into master and verify that this workflow works!
=> [🔥AUDIT🔥] Fix Node CI workflow on push to main

.github/workflows/node-ci-push.yml, package.json
This makes a few tweaks to try and get the main push workflow working again.
Land the audit and see!
=> [🔥AUDIT🔥] Try to fix main push workflow

package.json, yarn.lock
We run the checks using GitHub Actions anyways so having to wait for checks to run locally, on every commit, is a bit of a pain.  This was discussed on Slack, see https://khanacademy.slack.com/archives/C4PE1QM5Y/p1639511103074300 for details.
Issue: none
n/a
=> Stop using husky pre-commit hook

.github/workflows/node-ci-push.yml
Adding the `node-ci-push` workflow to the changesets PR (Release PR), to see if
it automatically detects these checks and run it against that branch.
Merge this into the Release PR and verify if the checks run.
=> [🔥AUDIT🔥] Add changeset-release/* to the branches list

.changeset/fei-4126.1.md, .eslintignore, CODEOWNERS, build-settings/webpack.config.js, packages/wonder-blocks-testing/docs.md, packages/wonder-blocks-testing/package.json, packages/wonder-blocks-testing/src/index.js, styleguide.config.js
This introduces a new package for our test tooling and components.
It does absolutely nothing in this PR.
Issue: FEI-4126
`yarn test`
=> Add skeleton wonder-blocks-testing package

packages/wonder-blocks-popover/src/components/popover.stories.js, packages/wonder-blocks-tooltip/src/components/tooltip.stories.js
Chromatic is still detecting changes on the Tooltip and Popover stories. So I'm
incrementing the delay a bit to help with that in the meantime.
Verify if Chromatic flakyness is temporarily reduced for tooltips and popovers
in subsequent PRs.
=> [🔥AUDIT🔥] Increment chromatic delay for flaky visual tests (tooltip, popover)

.changeset/poor-glasses-grab.md, packages/wonder-blocks-cell/package.json
Adding wonder-blocks-layout as a direct dependency
N/A
=> [🔥AUDIT🔥] Add layout as a cell dependency

.changeset/brown-monkeys-confess.md, packages/wonder-blocks-data/src/hooks/__tests__/use-data.test.js, packages/wonder-blocks-data/src/hooks/use-data.js
Discovered this bug while trying to integrate WB Data v3 into webapp.
Issue: FEI-4219
`yarn test`
I've also integrated a build of this in webapp to confirm it works.
=> [fixssrdata] Ensure we track the intercepted request

.github/workflows/release.yml
Run the release workflow and see!
=> [🔥AUDIT🔥] [fixworkflow] Fix env var reference

.github/workflows/release.yml
Run the release workflow and see what happens
=> [🔥AUDIT🔥] [fixreleaseworkflow.2] Fix typo in release workflow

.github/workflows/release.yml
I ran this locally:
```
echo "UPDATED_PACKAGES=$(jq '[group_by(.name) | .[] | " - "+.[].name+"@"+.[].version] | join("\n")' <<< '[{"name":"@khanacademy/wonder-blocks-data","version":"3.1.0"}]')"
```
And got this output:
```
UPDATED_PACKAGES=" - @khanacademy/wonder-blocks-data@3.1.0"
```
So, I think we're good now.
=> [🔥AUDIT🔥] Fix up the jq stuff

.github/workflows/release.yml
This was done before and should've been in the last audit (it's how I generated the test plan results).
For some reason, VSCode rejected the save and I didn't notice. :facepalm:
See the previous update to this file.
=> [🔥AUDIT🔥] [reallyfix] Add the printf bit to release workflow

.changeset/fuzzy-seahorses-remember.md
Update changeset for wonder-blocks-clickable so that buttons can have right behavior pick ca3c4bb6fde Migrate simple analytics functions
Issue: https://khanacademy.atlassian.net/browse/WB-393
Verify that the version gets bumped in the release PR
=> Update changeset for wonder-blocks-clickable

.changeset/heavy-stingrays-change.md
I missed adding the changeset on this PR: #1330
This PR exclusively adds the MD file to include the changes in the Release PR.
N/A
=> [🔥AUDIT🔥] Add disabled prop

.changeset/happy-dots-drive.md, packages/wonder-blocks-data/src/index.js
This just adds an export for code that already exists.
Issue: FEI-4261
`yarn test`
`yarn flow`
=> [🔥AUDIT🔥] [fei4261.resultsnotcachedresponses] Export resultFromCachedResponse

.github/REVIEWERS, CODEOWNERS
Previously we were tagging individuals, which doesn't feel right. Instead let's use the Wonder Blocks team for this!
=> Update CODEOWNERS and REVIEWERS to use the Wonder Blocks team.

.changeset/slimy-eyes-fold.md
Changeset for https://github.com/Khan/wonder-blocks/pull/1343
Issue: https://khanacademy.atlassian.net/browse/WB-1090
N/A
=> Add changeset for added prop closedFocusId to modal

.changeset/cell-target-prop.md
I forgot to add a .md for changesets.
Issue: None
- n/a, wait for the GitHub Action to create a publish PR
=> [🔥AUDIT🔥] Add changeset .md file for changes from #1380

package.json, yarn.lock
Fixes crashes and LSP issues
Issue: FEI-4424
`yarn flow check`
=> [🔥AUDIT🔥] [flow176.3] Update to Flow 0.176.3

.github/workflows/node-ci-pr.yml
The existing Node CI (PR) workflow is taking around 5-7 minutes to run.
Replicating the CI workflow defined in `wonder-stuff` to be able to parallelize
some job steps that take ~2 minutes.
Verify that this workflow takes less time than the actual one. Expecting to save
around 2 minutes per run.
=> Optimize GH Node CI worflow on PRs to run in parallel

yarn.lock
Thought I'd try `yarn-deduplicate` on Wonder Blocks before I started the rest of my changes. Don't know if it helped much, but the cache has to be a little smaller.
I ran:
`npx yarn-deduplicate yarn.lock`
Issue: FEI-4370
`yarn`
`yarn test`
=> [fei4370.1.dedupe] Dedupe yarn.lock

.github/workflows/chromatic-build.yml, .github/workflows/node-ci-push.yml
I missed these two when doing the initial update.
Merge to `main` and check things work as expected.
=> [🔥AUDIT🔥] [fixpushworkflow] Update shared cache action in all workflows

packages/wonder-blocks-dropdown/src/components/__docs__/action-menu.stories.js, packages/wonder-blocks-dropdown/src/components/__docs__/multi-select.stories.js, packages/wonder-blocks-dropdown/src/components/__docs__/single-select.stories.js
Prep work for moving dropdown-related SB stories to the `__docs__` folder. After
this, we'll start with the Dropdown migration to Storybook.
Verify that the all the checks pass and there are no changes in Chromatic.
=> [🔥AUDIT🔥] Move dropdown stories to __docs__ folder

.changeset/weak-bugs-attend.md, packages/wonder-blocks-data/src/hooks/use-cached-effect.js
I didn't add any new test cases here. If folks feel strongly that there should be test cases to verify this, then I can work on adding some.
Issue: FEI-4677
`yarn test`
=> [fei4677.1] Make sure that if there is a cached response, we don't fetch

.github/workflows/release.yml
=> [🔥AUDIT🔥] [fei4139.audit.releaseworkflow] Release workflow should be using Node 16

.changeset/slow-knives-live.md, packages/wonder-blocks-banner/package.json, packages/wonder-blocks-banner/src/index.js
This PR introduces a new package for Banner: `wonder-blocks-banner`
Issue: https://khanacademy.atlassian.net/browse/WB-1383
`yarn test`
=> Add wonder-blocks-banner package

.changeset/wicked-eagles-end.md, packages/wonder-blocks-banner/src/components/__tests__/banner.test.js, packages/wonder-blocks-banner/src/components/banner.js
Banner is complete!
If anyone thinks of any tweaks or last minute
changes, I can put them here. Otherwise, let's
ship it!
banner.js:
https://github.com/Khan/wonder-blocks/blob/feature/banner/packages/wonder-blocks-banner/src/components/banner.js
Full wonder-blocks-banner directory:
https://github.com/Khan/wonder-blocks/tree/feature/banner/packages/wonder-blocks-banner
Issue: https://khanacademy.atlassian.net/browse/WB-1385
`yarn jest`
https://5e1bf4b385e3fb0020b7073c-bygfuctxdv.chromatic.com/?path=/docs/banner--default
=> Banner v1.0.0 changeset

.changeset/slimy-sheep-tie.md, packages/wonder-blocks-core/src/index.js
=> [🔥AUDIT🔥] Export useOnMountEffect hook

.changeset/fuzzy-trains-film.md, packages/wonder-blocks-data/package.json, packages/wonder-blocks-icon/package.json, packages/wonder-blocks-testing/package.json, yarn.lock
There were some issues with the flow types being included in some of the wonder-stuff packages.  This PR updates to versions were that issues has been resolved.
Issue: None
- let CI do its thing
=> Update wonder-stuff dependencies

.changeset/rude-cherries-hear.md, packages/wonder-blocks-button/src/components/button-core.tsx, packages/wonder-blocks-cell/src/components/internal/cell-core.tsx, packages/wonder-blocks-clickable/src/components/clickable.tsx, packages/wonder-blocks-core/src/util/add-style.tsx, packages/wonder-blocks-dropdown/src/components/__mocks__/dropdown-core-virtualized.tsx, packages/wonder-blocks-dropdown/src/components/dropdown-core-virtualized.tsx, packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx, packages/wonder-blocks-form/src/components/__docs__/labeled-text-field.stories.tsx, packages/wonder-blocks-form/src/components/__tests__/labeled-text-field.test.tsx, packages/wonder-blocks-icon-button/src/__tests__/custom-snapshot.test.tsx, packages/wonder-blocks-modal/src/components/__docs__/modal-dialog.stories.tsx, packages/wonder-blocks-modal/src/components/__docs__/modal-launcher.stories.tsx, packages/wonder-blocks-modal/src/components/__docs__/one-pane-dialog.stories.tsx, packages/wonder-blocks-modal/src/components/modal-launcher.tsx, packages/wonder-blocks-modal/src/util/types.ts, packages/wonder-blocks-modal/tsconfig.json, packages/wonder-blocks-progress-spinner/src/components/circular-spinner.tsx, packages/wonder-blocks-testing/src/harness/__tests__/types.flowtest.tsx, packages/wonder-blocks-testing/src/harness/adapters/css.tsx, packages/wonder-blocks-testing/src/harness/make-test-harness.tsx, packages/wonder-blocks-testing/src/harness/test-harness.ts, packages/wonder-blocks-timing/src/components/__docs__/with-action-scheduler-examples.tsx, packages/wonder-blocks-timing/src/components/with-action-scheduler.tsx, packages/wonder-blocks-timing/src/util/types.ts, packages/wonder-blocks-timing/tsconfig.json, packages/wonder-blocks-tooltip/src/components/tooltip-tail.tsx, types/aphrodite.d.ts, types/utility.d.ts
The HOCs seem to be working for the most part.  I'm sure that we'll be able to improve these types in the future, but this is good enough for now.
- yarn typecheck, see everything passing (the language service is complaining about missing imports in a couple of files though, I'll work on fixing the config for paths in a future PR)
=> FEI-4966.7: Fix HOCs and other reamaining TS errors

.changeset/stale-lions-switch.md, .github/workflows/node-ci-pr.yml, build-scripts/gen-flow-types.ts, build-scripts/remove-test-types-from-dist.ts, build-settings/rollup.config.js, package.json, packages/wonder-blocks-modal/src/components/one-pane-dialog.tsx, packages/wonder-blocks-testing/src/settle-controller.ts, packages/wonder-blocks-testing/src/settle-signal.ts, packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx, utils/testing/expect-render-error.d.ts, utils/testing/mock-request-animation-frame.d.ts, yarn.lock
This is the last step before we can publish.  I had copied the scripts over from wonder-stuff in a previous PR, but forgot to update the paths.  This PR fixes the paths and adds a step to the PR workflow file.
- yarn clean
=> FEI-4966.14: Build Flow types

.changeset/eighty-bananas-flow.md, __docs__/wonder-blocks-clickable/clickable.argtypes.ts, __docs__/wonder-blocks-clickable/clickable.stories.tsx, packages/wonder-blocks-clickable/src/components/__tests__/clickable.test.tsx, packages/wonder-blocks-clickable/src/components/clickable.tsx
Add tabIndex and ref props to Clickable
Issue: WB-1549
- Write new unit tests for both props
- Add new story for ref prop
- Test on storybook
=> Added tabIndex and ref props to Clickable component

.changeset/mean-books-wash.md, consistency-tests/__tests__/ref-forwarded.test.tsx, consistency-tests/tsconfig.json, packages/wonder-blocks-core/src/components/view.tsx
Added ref forwarding prop to View
Issue: WB-1578
`yarn test consistency-tests`
=> Add ref forwarding to View

.changeset/great-cherries-compete.md, consistency-tests/__tests__/ref-forwarded.test.tsx, consistency-tests/tsconfig.json, packages/wonder-blocks-button/src/components/button-core.tsx, packages/wonder-blocks-button/src/components/button.tsx, packages/wonder-blocks-clickable/src/components/__tests__/clickable.test.tsx, packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx, packages/wonder-blocks-icon-button/src/components/icon-button.tsx
- Added ref forwarding to Button
- Added ref forwarding to IconButton
- Removed duplicate Clickable test
- Wrote new tests for ref forwarding
Issue: WB-1579
`yarn test consistency_tests`
=> Add ref forwarding for Button and IconButton

__docs__/wonder-blocks-core/unique-id-provider.stories.tsx, __docs__/wonder-blocks-form/checkbox-group.stories.tsx, __docs__/wonder-blocks-form/radio-group.stories.tsx, packages/wonder-blocks-timing/src/util/__tests__/animation-frame.test.ts, packages/wonder-blocks-timing/src/util/interval.ts, packages/wonder-blocks-timing/src/util/timeout.ts, packages/wonder-blocks-tooltip/src/util/active-tracker.ts, packages/wonder-blocks-tooltip/src/util/ref-tracker.ts
Fixed a few error suppressions that I happened to know how to fix. Functionally no changes so I didn't add a changeset here.
Issue: FEI-5019
=> [🔥AUDIT🔥] [fixsomeerrorsuppressions] Fix a few error suppressions

.changeset/wet-bees-move.md, __docs__/wonder-blocks-switch/switch.stories.tsx, consistency-tests/__tests__/ref-forwarded.test.tsx, packages/wonder-blocks-switch/package.json, packages/wonder-blocks-switch/src/components/__tests__/switch.test.tsx, packages/wonder-blocks-switch/src/components/switch.tsx, packages/wonder-blocks-switch/src/themes/default.ts, packages/wonder-blocks-switch/src/themes/khanmigo.ts, packages/wonder-blocks-switch/src/themes/themed-switch.tsx, packages/wonder-blocks-switch/tsconfig-build.json, packages/wonder-blocks-theming/src/tokens.ts
- Fix typo and refactor parts of Switch
- Added new color tokens for khanmigo
- Add theme files and theming to switch
Issue: WB-1600
- Create new story for switch style and update snapshots
=> Add Khanmigo theme to Switch

.changeset/silent-clouds-fetch.md, __docs__/wonder-blocks-dropdown/base-select.argtypes.ts, __docs__/wonder-blocks-dropdown/multi-select.stories.tsx, __docs__/wonder-blocks-dropdown/single-select.stories.tsx, packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx, packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx, packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx, packages/wonder-blocks-dropdown/src/components/multi-select.tsx, packages/wonder-blocks-dropdown/src/components/select-opener.tsx, packages/wonder-blocks-dropdown/src/components/single-select.tsx, packages/wonder-blocks-dropdown/src/util/constants.ts, packages/wonder-blocks-dropdown/src/util/types.ts, packages/wonder-blocks-dropdown/tsconfig-build.json
- Added `isInvalid` prop to single and multi select with styling to match
- Added new stories
Issue: WB-1501
- Check new storybook story to ensure styles are being rendered correctly
=> Add invalid state to single and multi select

.github/workflows/chromatic-build.yml, .github/workflows/chromatic-pr.yml, .github/workflows/chromatic-push.yml, .storybook/preview.tsx, __docs__/wonder-blocks-banner/banner.stories.tsx
- Update Banner stories to CSF v3
- Skip chromatic builds on Release PR
- Skip chromatic builds on draft PRs
Issue: WB-1593
Verify that the stories are still working as expected.
Also verify that the chromatic build was skipped when this PR was a draft: https://github.com/Khan/wonder-blocks/actions/runs/6251415412/job/16972487374?pr=2058
=> WB-1593.3: More chromatic workflow optimizations and optimize Banner stories

.changeset/big-numbers-begin.md, packages/wonder-blocks-pill/src/components/pill.tsx
There's a network issue with Cloudfare (that is used by NPM). This is causing
some packages to fail to install. This PR bumps the version of Pill to match the
existing version of Pill publised in NPM.
N/A
=> [🔥AUDIT🔥] Bump Pill version to avoid changeset error in next release

.changeset/mean-toes-think.md, packages/wonder-blocks-theming/src/tokens.ts
There was an issue with the `font.family.sans` token.
- Good question
=> Fix font.family.sans token

.changeset/forty-cats-rescue.md, packages/wonder-blocks-switch/src/themes/khanmigo.ts
Updates the khanmigo theme for the Switch component to match the latest design.
Figma: https://www.figma.com/file/SmYQXeL3Qu1qO1eo7yPqNV/Khanmigo-Library?type=design&node-id=1582-2145&mode=design&t=pGmmd2rUMVJMK61m-4
Issue: WB-1627
Verify that the new variants are available and that they match the design.
/?path=/story/switch--khanmigo-theme
=> WB-1627: Update Khanmigo-themed Switch with latest styling

__docs__/wonder-blocks-search-field/search-field.argtypes.ts, __docs__/wonder-blocks-search-field/search-field.stories.tsx
Updating the SearchField docs to include the component description, usage, and
improving the examples.
Verify that the search docs are updated and the examples are working as
expected.
=> [🔥AUDIT🔥] Storybook: Update `SearchField` docs

.changeset/big-starfishes-worry.md, packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
Refactoring the LabeledField component to a function component.
The LabeledField is based on the FieldHeading component and will be updated in more PRs to meet the implementation spec
Issue: WB-1503
Confirm tests still pass and component looks and functions the same way
=> LabeledField(part2): refactor to a function component

.changeset/young-pumpkins-compete.md, packages/wonder-blocks-form/src/components/group-styles.ts
This PR is meant to bump the version of the form package to test changesets.
We are seeing if a change being applied in #2409 will fix the issue we are
seeing with changesets not being triggering PR checks at all.
This is causing that packages are not being published to NPM.
Land this PR and see if the changesets checks are triggered once the Release PR
is created.
=> Changesets: Bump form package to test release process

__docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
- Fix import to ComponentInfo for feature branch now that it is up to date with main. This fixes the lint and type errors in the feature branch
- For context, ComponentInfo was moved to a new location after the initial set up of the LabeledField work
Issue: WB-XXXX
- Checks pass on the PR
=> LabeledField: fix import

.changeset/unlucky-moles-report.md, packages/wonder-blocks-labeled-field/package.json
[labeled-field-pkg] fix labeled-field package.json config so we can publish it
Issue: WB-XXXX
=> Update labeled-field package.json config

.changeset/rare-balloons-beam.md, .changeset/small-dryers-judge.md, __docs__/foundations-color.mdx, packages/wonder-blocks-button/src/themes/default.ts, packages/wonder-blocks-clickable/src/components/clickable.tsx, packages/wonder-blocks-dropdown/src/components/action-menu-opener-core.tsx, packages/wonder-blocks-dropdown/src/components/checkbox.tsx, packages/wonder-blocks-dropdown/src/components/combobox.tsx, packages/wonder-blocks-dropdown/src/components/listbox.tsx, packages/wonder-blocks-dropdown/src/components/option-item.tsx, packages/wonder-blocks-dropdown/src/components/select-opener.tsx, packages/wonder-blocks-form/src/components/checkbox-core.tsx, packages/wonder-blocks-form/src/components/choice-internal.tsx, packages/wonder-blocks-form/src/components/radio-core.tsx, packages/wonder-blocks-form/src/components/text-area.tsx, packages/wonder-blocks-form/src/components/text-field.tsx, packages/wonder-blocks-icon-button/src/themes/default.ts, packages/wonder-blocks-search-field/src/components/search-field.tsx, packages/wonder-blocks-switch/src/themes/default.ts, packages/wonder-blocks-tokens/src/tokens/semantic-color.ts
- Modified the `semanticColor` structure to include `disabled` tokens on
every `action` variant (`primary` and `secondary`).
- Updated the codebase to to make use of the new `disabled` tokens.
Issue: WB-1889
Verify that the disabled state of the components is consistent with the
design system.
=> WB-1889: Rework action.disabled tokens

.changeset/green-tomatoes-build.md, __docs__/wonder-blocks-tabs/accessibility.mdx, __docs__/wonder-blocks-tabs/navigation-tab-item.argtypes.tsx, __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx, __docs__/wonder-blocks-tabs/navigation-tabs-variants.stories.tsx, __docs__/wonder-blocks-tabs/navigation-tabs.argtypes.tsx, __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx, packages/wonder-blocks-tabs/src/components/__tests__/navigation-tab-item.test.tsx, packages/wonder-blocks-tabs/src/components/__tests__/navigation-tabs.test.tsx, packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx, packages/wonder-blocks-tabs/src/components/navigation-tabs.tsx
- Adding props for NavigationTabs and NavigationTabItem
- Adding docs for accessibility
Issue: WB-1898
Confirm props are working as expected (Note: styling for the current NavigationTabItem will be added in the next PR)
=> Add NavigationTabs and NavigationTabItem props

.changeset/tricky-lizards-lie.md, .github/workflows/chromatic-build.yml, package.json, packages/wonder-blocks-birthday-picker/package.json, packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx, packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
This update changes birthday-picker.tsx to use Temporal for working with dates and removes the moment.js library.
Issue: None
- updated unit tests
- manual testing via storybook
=> Replaced moment.js with Temporal polyfill

.changeset/thirty-toes-do.md, __docs__/wonder-blocks-typography/body-text.stories.tsx, __docs__/wonder-blocks-typography/heading.stories.tsx, packages/wonder-blocks-typography/src/components/__tests__/heading.test.tsx, packages/wonder-blocks-typography/src/components/body-text.tsx, packages/wonder-blocks-typography/src/components/heading.tsx
While integrating the new WB Typography components into webapp, I found a few things needing updates for a smooth transition.
Issue: WB-1966
1. Ensure tests pass
2. Test integration into webapp
=> Adjust BodyText and Heading docs and defaults

.changeset/twelve-tomatoes-serve.md
The Switch PR added component-level tokens but lacked a changeset to bump WB Tokens. This PR adds the needed version bump.
Issue: WB-XXXX
:
=> docs(changeset): Add tokens for themable Switch component

.changeset/chatty-moons-press.md, .changeset/neat-lizards-teach.md, .changeset/tame-eels-allow.md, .changeset/twenty-eagles-cough.md, __docs__/wonder-blocks-cell/compact-cell.argtypes.tsx, __docs__/wonder-blocks-cell/detail-cell.stories.tsx, packages/wonder-blocks-cell/package.json, packages/wonder-blocks-cell/src/components/internal/__tests__/cell-core.test.tsx, packages/wonder-blocks-cell/src/components/internal/cell-core.tsx, packages/wonder-blocks-cell/src/theme/default.ts, packages/wonder-blocks-cell/src/theme/thunderblocks.ts, packages/wonder-blocks-cell/src/util/types.ts, packages/wonder-blocks-cell/tsconfig-build.json, packages/wonder-blocks-dropdown/src/components/action-item.tsx, packages/wonder-blocks-dropdown/src/components/option-item.tsx, pnpm-lock.yaml
Following up with the Cell theming support, this PR simplifies the layout and structure of the cell component.
Issue: https://khanacademy.atlassian.net/browse/WB-1959
Navigate to the Cell docs and verify that the layout looks correct.
Also check the option items in dropdown examples.
=> [WB-1959.3] Cell layout refactor

.changeset/flat-feet-taste.md, .changeset/new-zoos-retire.md, __docs__/wonder-blocks-dropdown/combobox.stories.tsx, packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-dropdown/src/components/action-item.tsx, packages/wonder-blocks-dropdown/src/components/action-menu-opener-core.tsx, packages/wonder-blocks-dropdown/src/components/check.tsx, packages/wonder-blocks-dropdown/src/components/checkbox.tsx, packages/wonder-blocks-dropdown/src/components/combobox.tsx, packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx, packages/wonder-blocks-dropdown/src/components/listbox.tsx, packages/wonder-blocks-dropdown/src/components/option-item.tsx, packages/wonder-blocks-dropdown/src/components/select-opener.tsx, packages/wonder-blocks-dropdown/src/components/separator-item.tsx, packages/wonder-blocks-dropdown/src/theme/default.ts, packages/wonder-blocks-dropdown/src/theme/index.ts, packages/wonder-blocks-dropdown/src/theme/thunderblocks.ts, packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts, packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Adds the `ThunderBlocks` theme to the `wonder-blocks-dropdown` package.
Issue: WB-1868
- Navigate to the Dropdown docs and verify that the stories look correct.
- Ensure that all the dropdown snapshots look correct.
=> [WB-1868.3] Add ThunderBlocks theme to dropdown

.changeset/dull-experts-deny.md, .changeset/nice-toys-sparkle.md, __docs__/wonder-blocks-dropdown/multi-select.stories.tsx, __docs__/wonder-blocks-form/checkbox-accessibility.stories.tsx, __docs__/wonder-blocks-form/checkbox-group.stories.tsx, __docs__/wonder-blocks-form/checkbox.stories.tsx, __docs__/wonder-blocks-form/choice.stories.tsx, __docs__/wonder-blocks-form/radio-group.stories.tsx, __docs__/wonder-blocks-form/radio.stories.tsx, packages/wonder-blocks-dropdown/package.json, packages/wonder-blocks-form/package.json, packages/wonder-blocks-form/src/components/__tests__/checkbox.test.tsx, packages/wonder-blocks-form/src/components/checkbox-core.tsx, packages/wonder-blocks-form/src/components/checkbox-group.tsx, packages/wonder-blocks-form/src/components/choice-internal.tsx, packages/wonder-blocks-form/src/components/radio-core.tsx, packages/wonder-blocks-form/src/components/radio-group.tsx, packages/wonder-blocks-form/src/theme/default.ts, packages/wonder-blocks-form/src/theme/index.ts, packages/wonder-blocks-form/src/theme/thunderblocks.ts, packages/wonder-blocks-form/src/util/styles.ts, packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts, pnpm-lock.yaml
This PR includes the following commits:
- Add theming to Checkbox/Radio (#2662)
Issue: WB-1972
=> Feature branch pull-request from `reintroduce-checkradio` to `main`

.changeset/tender-items-move.md, __docs__/wonder-blocks-tabs/navigation-tab-item-testing-snapshots.stories.tsx, __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx, packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx, packages/wonder-blocks-tabs/src/components/tab.tsx
Update font color for Tabs and NavigationTabs so that it matches the designs 
Figma: https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=2156-77&m=dev
Issue: WB-2026
Confirm font color in Tabs and NavigationTabs matches the designs
- `?path=/docs/packages-tabs-navigationtabs--docs`
- `?path=/docs/packages-tabs-tabs--docs`
=> Update Tab and NavigationTabItem font color
